import { writeFileSync, readdir, lstatSync, mkdirSync } from 'fs';
import { compileFromFile } from 'json-schema-to-typescript';

const SCHEMA_DIR = '../generated/schemas';
const TYPES_DIR = '../generated/ts';

let out: string = `
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
`;

async function generate(rootDir: string) {
  readdir(rootDir, async (_err, files) => {
    for (const fileName of files) {
      const file = `${rootDir}/${fileName}`;
      console.log(`found schema ${file}`);

      if (lstatSync(file).isDirectory()) {
        await generate(`${file}`);
      } else if (file.endsWith('.json')) {
        await generateType(rootDir, file, fileName);
      }
    }

    writeFileSync(`${TYPES_DIR}/api-types.d.ts`, out);
  });
  return out;
}

async function generateType(dir: string, path: string, name: string) {
  // can be customized further here: https://github.com/bcherny/json-schema-to-typescript#options
  const typeDef = await compileFromFile(path, {
    additionalProperties: false,
    declareExternallyReferenced: false,
    bannerComment: '',
    cwd: SCHEMA_DIR,
  });

  mkdirSync(TYPES_DIR, { recursive: true });
  let newPath = name.replace('.json', '.d.ts');
  newPath = `${TYPES_DIR}/${newPath}`;

  out = out.concat('\n', typeDef);
}

async function main() {
  await generate(SCHEMA_DIR);
}

main();
