import {
  CollectedDataEventData,
  TimelineEvent,
  TimelineEventKind,
} from '@onefootprint/types';
import { TimelineItemTimeData } from 'src/components/timeline';

export type AuditTrailTimelineEvent = Omit<TimelineEvent, 'timestamp'> & {
  time: TimelineItemTimeData;
};

const mergeAuditTrailTimelineEvents = (
  events: TimelineEvent[],
): AuditTrailTimelineEvent[] => {
  // Do a first pass to merge consecutive data collected events generated by other tenants
  const mergedTimeline: AuditTrailTimelineEvent[] = [];

  events.forEach((event: TimelineEvent) => {
    const isEventKycDataCollection =
      event.event.kind === TimelineEventKind.dataCollected;
    const lastEvent = mergedTimeline[mergedTimeline.length - 1];
    const isLastEventKycDataCollection =
      lastEvent?.event.kind === TimelineEventKind.dataCollected;
    if (
      // If the event is not from another tenant, or is not a kyc data collection event, add it as is
      !event.isFromOtherOrg ||
      !isEventKycDataCollection ||
      // If this is the first event, add it as is
      !mergedTimeline.length ||
      // If the previously added event is not a kyc data collection event, add the current event as is
      !lastEvent?.isFromOtherOrg ||
      !isLastEventKycDataCollection
    ) {
      mergedTimeline.push({
        event: event.event,
        isFromOtherOrg: event.isFromOtherOrg,
        time: {
          timestamp: event.timestamp,
        },
      });
      return;
    }

    // Merge times
    if ('timestamp' in lastEvent.time) {
      // Use the last event time as the start time to create a range
      lastEvent.time = {
        start: lastEvent.time.timestamp,
        end: event.timestamp,
      };
    } else {
      // Just update the end rage
      lastEvent.time.end = event.timestamp;
    }

    // Merge kyc data (id doc/selfie are not portable for now) & dedupe just in case
    const eventData = event.event.data as CollectedDataEventData;
    const lastEventData = lastEvent.event.data as CollectedDataEventData;
    const mergedAttributes = Array.from(
      new Set([...lastEventData.attributes, ...eventData.attributes]),
    );
    lastEventData.attributes = mergedAttributes;
  });

  return mergedTimeline;
};

export default mergeAuditTrailTimelineEvents;
