CI:
  - .github/**/*

Backend:
  - backend/**/*

DB:
  - backend/components/db/**/*

Migrations:
  - backend/components/db/migrations/**/*

API:
  - backend/components/api/**/*

Enclave:
  - backend/components/enclave/**/*

ephemeral:
  - 'backend/infra/**/*'
  - 'backend/infra/*'

Mobile:
  - mobile/**/*
  
Frontend:
  - frontend/**/*

Dashboard:
  - frontend/apps/dashboard/**/*

Bifrost:
  - frontend/apps/bifrost/**/*

Developer Docs:
  - frontend/apps/docs/**/*

Frontpage:
  - frontend/apps/frontpage/**/*

Tooling:
  - frontend/packages/**/*