CI:
  - .github/**/*

Backend:
  - backend/**/*

DB:
  - backend/components/db/**/*

Migrations:
  - backend/components/db/migrations/**/*

API:
  - backend/components/api/**/*

Enclave:
  - backend/components/enclave/**/*

FastEphemeral:
  - 'backend/infra/**/*'
  - 'backend/infra/*'
  - '.github/workflows/backend_build_and_deploy.yml'

FullEphemeral:
  - 'backend/infra/src/db.ts'

Mobile:
  - mobile/**/*

Frontend:
  - frontend/**/*

Dashboard:
  - frontend/apps/dashboard/**/*

Bifrost:
  - frontend/apps/bifrost/**/*

Developer Docs:
  - frontend/apps/docs/**/*

Frontpage:
  - frontend/apps/frontpage/**/*
