DROP INDEX incode_verification_session_identity_document_id;
CREATE UNIQUE INDEX incode_verification_session_unique_identity_document_id ON incode_verification_session(identity_document_id);
ALTER TABLE incode_verification_session
    DROP COLUMN scoped_vault_id;