ALTER TABLE task ALTER created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE task ALTER _created_at TYPE TIMESTAMPTZ USING _created_at AT TIME ZONE 'UTC';
ALTER TABLE task ALTER _updated_at TYPE TIMESTAMPTZ USING _updated_at AT TIME ZONE 'UTC';
ALTER TABLE task ALTER scheduled_for TYPE TIMESTAMPTZ USING scheduled_for AT TIME ZONE 'UTC';