# Docker dev environment
# ----------------------
#
# To run locally, you could use Docker Desktop, but colima is often a better experience.
#
# Install colima:
#   brew install colima docker docker-buildx
#   mkdir -p ~/.docker/cli-plugins
#   ln -sfn $HOMEBREW_PREFIX/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
#
# Start colima with enough resources for Rust builds:
#   colima start --cpu 8 --memory 16 --disk 256
#
# You may eventually need to clear your disk if the Rust build cache grows too large.
#   docker buildx prune
#
# Note that we disable the Docker Compose .env file loading since that is
# handled by the applications. Leaving off the `--env-file /dev/null` flags may
# work, but you may see warnings if the .env file isn't compatible with
# Docker's own .env syntax.
#
# Some useful commands
# --------------------
# Build and run all services locally:
#   make set-dot-env
#   docker compose --env-file /dev/null build
#   docker compose --env-file /dev/null up
# Run python integration tests:
#   docker compose --env-file /dev/null run integration_tests pytest ci/tests

networks:
  footprint:

services:
  api:
    # Optional image that may be set in CI.
    image: ${CI_IMAGE_API:-}
    # Build definition for local development.
    build:
      context: .
      dockerfile: ./images/api/Dockerfile
      args:
        GIT_HASH: dummy-version
        BUILD_PROFILE: debug
    networks:
      - footprint
    ports:
      - "8000:8000"
    volumes:
      - .env:/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
      ENCLAVE_PROXY_ENDPOINT: http://enclave_proxy:3668
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/health
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      enclave_proxy:
        condition: service_healthy

  enclave_proxy:
    # Optional image that may be set in CI.
    image: ${CI_IMAGE_ENCLAVE_PROXY:-}
    # Build definition for local development.
    build:
      context: .
      dockerfile: ./images/enclave-proxy/Dockerfile
      args:
        GIT_HASH: dummy-version
        CARGO_FEATURES: ""
        BUILD_PROFILE: debug
    networks:
      - footprint
    ports:
      - "3668:3668"
    volumes:
      - .env:/.env
    environment:
      ENCLAVE_TCP_HOST: enclave
    depends_on:
      - enclave
    healthcheck:
      test: curl --fail http://127.0.0.1:3668/health
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

  enclave:
    # Optional image that may be set in CI.
    image: ${CI_IMAGE_ENCLAVE:-}
    # Build definition for local development.
    build:
      context: .
      dockerfile: ./images/enclave-dev/Dockerfile
    networks:
      - footprint
    ports:
      - "5001:5001"
    volumes:
      - .env:/.env

  postgres:
    image: postgres:16.3@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
    networks:
      - footprint
    ports:
      - "5432:5432"
      # Add another port to distinguish from a postgres instance running on a
      # laptop host for integration tests.
      - "9432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: pg_isready --username=postgres
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

  integration_tests:
    # Optional image that may be set in CI.
    image: ${CI_IMAGE_INTEGRATION_TESTS:-}
    # Build definition for local development.
    build:
      context: .
      dockerfile: ./images/integration-tests/Dockerfile
    # Running this on the host network makes the API accessible at localhost,
    # which seems to be necessary for WebAuthn, even with RELYING_PARTY_ID=api.
    network_mode: host
    environment:
      EXPECTED_SERVER_VERSION: ${EXPECTED_SERVER_VERSION:-}
      TEST_URL: ${TEST_URL:-http://localhost:8000}
      IT_TWILIO_ACCOUNT_SID: ${IT_TWILIO_ACCOUNT_SID}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${IT_TWILIO_SECRET_AUTH_TOKEN}
      DITTO_URL: ${DITTO_URL:-https://ditto.footprint.dev}
      IT_SVIX_API_KEY: ${IT_SVIX_API_KEY}
      ENVIRONMENT: ${ENVIRONMENT}
      # Used by diesel migration tests.
      DATABASE_URL: "postgresql://postgres:postgres@localhost:9432/postgres"
    volumes:
      - .:/backend
    profiles:
      # Don't run by default.
      - test
