# Docker dev environment

networks:
  footprint:

services:
  api:
    build:
      context: .
      dockerfile: ./images/api/Dockerfile
      args:
        GIT_HASH: dummy-version
        BUILD_PROFILE: debug
    networks:
      - footprint
    ports:
      - "8000:8000"
    volumes:
      - .env:/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
      ENCLAVE_PROXY_ENDPOINT: http://enclave_proxy:3668
    depends_on:
      postgres:
        condition: service_healthy
      enclave_proxy:
        condition: service_healthy

  enclave_proxy:
    build:
      context: .
      dockerfile: ./images/enclave-proxy-dev/Dockerfile
    networks:
      - footprint
    ports:
      - "3668:3668"
    volumes:
      - .env:/.env
    environment:
      ENCLAVE_TCP_HOST: enclave
    depends_on:
      - enclave
    healthcheck:
      test: curl --fail http://127.0.0.1:3668/health
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

  enclave:
    build:
      context: .
      dockerfile: ./images/enclave-dev/Dockerfile
    networks:
      - footprint
    ports:
      - "5000:5000"
    volumes:
      - .env:/.env

  postgres:
    image: postgres
    networks:
      - footprint
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: pg_isready --username=postgres
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

