export type Author = {
  bio: string | null;
  cover_image: string | null;
  facebook: string | null;
  id: string;
  location: string | null;
  meta_description: string | null;
  meta_title: string | null;
  name: string;
  profile_image: string;
  slug: string;
  twitter: string | null;
  url: string;
  website: string | null;
};

export type Tag = {
  accent_color: string | null;
  canonical_url: string | null;
  codeinjection_foot: string | null;
  codeinjection_head: string | null;
  description: string | null;
  feature_image: string | null;
  id: string;
  meta_description: string | null;
  meta_title: string | null;
  name: string;
  og_description: string | null;
  og_image: string | null;
  og_title: string | null;
  slug: string;
  twitter_description: string | null;
  twitter_image: string | null;
  twitter_title: string | null;
  url: string;
  visibility: string;
};

export type Post = {
  authors: Author[];
  created_at: string;
  excerpt: string;
  feature_image_alt?: string;
  feature_image: string;
  featured: boolean | undefined;
  html: string | undefined;
  id: string;
  primary_author: Author;
  primary_tag: Tag;
  published_at: string;
  reading_time: number;
  slug: string;
  tags: Tag[];
  title: string;
  url: string;
  uuid: string;
};

export type PostDetails = {
  authors: Author[];
  canonical_url: string;
  created_at: string;
  custom_excerpt: string;
  excerpt: string;
  feature_image_alt?: string;
  feature_image: string;
  featured: boolean;
  html: string;
  meta_description: string;
  meta_title: string;
  og_description: string;
  og_image: string;
  og_title: string;
  primary_author: Author;
  primary_tag: Tag;
  published_at: string;
  reading_time: number;
  slug: string;
  tags: Tag[];
  title: string;
  twitter_description: string;
  twitter_image: string;
  twitter_title: string;
  updated_at: string;
  url: string;
  uuid: string;
};
