AWSTemplateFormatVersion: 2010-09-09
Description: Airplane ECS agentv2 stack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Airplane Settings
        Parameters:
          - TeamID
          - APIToken
          - APITokenSecretARN
          - APITokenSecretKMSKeyARN
      - Label:
          default: Agent Configuration
        Parameters:
          - ClusterARN
          - SubnetIDs
          - VpcID
          - SecurityGroupID
          - ServiceName
      - Label:
          default: Task Settings
        Parameters:
          - DefaultTaskCPU
          - DefaultTaskMemory
          - MaxTaskCPU
          - MaxTaskMemory
      - Label:
          default: Other Settings
        Parameters:
          - APIHost
          - AgentLabels
          - EnvSlug
          - AllowedIAMRoles
          - AllowTaskDefinitionCleanup
          - TemporalHost
          - ProjectID
    ParameterLabels:
      APIToken: { 'default': 'Airplane API Token' }
      APITokenSecretARN: { 'default': 'Airplane API Token Secret' }
      APITokenSecretKMSKeyARN: { 'default': 'KMS Key for API Token Secret' }
      DefaultTaskCPU: { 'default': 'Default task CPU' }
      DefaultTaskMemory: { 'default': 'Default task memory' }
      MaxTaskCPU: { 'default': 'Max task CPU' }
      MaxTaskMemory: { 'default': 'Max task memory' }
      TeamID: { 'default': 'Airplane Team ID' }
      SubnetIDs: { 'default': 'Subnet IDs' }
      VpcID: { 'default': 'VPC ID' }
      SecurityGroupID: { 'default': 'SecurityGroup ID' }

Parameters:
  AgentLabels:
    Description: Space-separated key-value pairs to use as labels for the agent
    Type: String
    Default: 'ecs:true'
  AllowedIAMRoles:
    Description: Space-separated list of additional IAM roles that tasks are allowed to assume
    Type: String
    Default: ''
  AllowTaskDefinitionCleanup:
    Description: Whether the agent is allowed to deregister old task definitions.
    AllowedValues: [true, false]
    Type: String
    Default: true
  APIHost:
    Description: Airplane API host - do not change this
    Type: String
    Default: 'https://api.airplane.dev'
  APIToken:
    Description: Your Airplane API token - generate one via `airplane apikeys create`. Either this or API Token Secret must be set.
    Type: String
    NoEcho: true
    Default: ''
  APITokenSecretARN:
    Description: ARN of API Token stored in AWS secret. Either this or API Token must be set.
    Type: String
    Default: ''
  APITokenSecretKMSKeyARN:
    Description: ARN of customer-managed KMS key, if any, used to encrypt API Token Secret.
    Type: String
    Default: ''
  ClusterARN:
    Type: String
    Description: Your ECS cluster ARN. Leave blank to create a new cluster.
    Default: ''
  DefaultTaskCPU:
    Type: String
    Description: Default CPU for tasks (in milliCPUs, e.g. 500m).
    Default: '1000m'
  DefaultTaskMemory:
    Type: String
    Description: Default memory for tasks (e.g. 500Mi or 1Gi).
    Default: '1Gi'
  EnvSlug:
    Type: String
    Description: Set an environment's slug to have agent only execute tasks from that environment. Leave blank to allow all environments.
    Default: ''
  MaxTaskCPU:
    Type: String
    Description: Max CPU for tasks (in milliCPUs, e.g. 500m).
    Default: '2000m'
  MaxTaskMemory:
    Type: String
    Description: Max memory for tasks (e.g. 500Mi or 1Gi).
    Default: '4Gi'
  ProjectID:
    Description: Airplane project ID - do not change this
    Type: String
    Default: 'airplane-prod'
  TeamID:
    Description: Your Airplane team ID - get it via `airplane auth info`
    Type: String
  TemporalHost:
    Description: Airplane Temporal host - do not change this
    Type: String
    Default: 'temporal-api.airplane.dev:443'
  ServiceName:
    Description: Name to assign to ECS service
    Type: String
    Default: 'airplane-agent'
  SubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for ECS service
  VpcID:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy to, should match subnet IDs
  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: SecurityGroup to attach

Conditions:
  ShouldCreateCluster: !Equals [!Ref ClusterARN, '']
  UsingTokenSecret: !Not [!Equals [!Ref APITokenSecretARN, '']]
  CustomerManagedKMS: !Not [!Equals [!Ref APITokenSecretKMSKeyARN, '']]
  NoAllowedIAMRoles: !Equals [!Ref AllowedIAMRoles, '']

Resources:
  Cluster:
    Condition: ShouldCreateCluster
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
  AgentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Airplane agents'
      VpcId: !Ref 'VpcID'
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: 'Allow all egress'
          IpProtocol: '-1'
  DefaultRunPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'secretsmanager:GetSecretValue'
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:airplane/*'
            Effect: Allow
          - !If
            - UsingTokenSecret
            - Action:
                - 'secretsmanager:GetSecretValue'
              Resource: !Ref APITokenSecretARN
              Effect: Allow
            - !Ref AWS::NoValue
          - !If
            - CustomerManagedKMS
            - Action:
                - 'kms:Decrypt'
              Resource: !Ref APITokenSecretKMSKeyARN
              Effect: Allow
            - !Ref AWS::NoValue
  RunExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ecs-tasks.amazonaws.com
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - !Ref DefaultRunPolicy
  DefaultRunRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ecs-tasks.amazonaws.com
            Effect: Allow
      ManagedPolicyArns:
        - !Ref DefaultRunPolicy
  AgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ecs-tasks.amazonaws.com
            Effect: Allow
      Policies:
        - PolicyName: airplane-agent-policy
          PolicyDocument:
            Statement:
              - Action:
                  - 'ecs:ListTaskDefinitions'
                  - 'ecs:RegisterTaskDefinition'
                  - 'secretsmanager:ListSecrets'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'ecs:DeregisterTaskDefinition'
                Resource: '*'
                Effect: Allow
                Condition:
                  StringEquals:
                    'true': !Ref AllowTaskDefinitionCleanup
              - Action:
                  - 'iam:PassRole'
                Resource: !Split
                  - ' '
                  - !If
                    - NoAllowedIAMRoles
                    - !Join
                      - ' '
                      - - !GetAtt RunExecutionRole.Arn
                        - !GetAtt DefaultRunRole.Arn
                    - !Join
                      - ' '
                      - - !GetAtt RunExecutionRole.Arn
                        - !GetAtt DefaultRunRole.Arn
                        - !Ref AllowedIAMRoles
                Effect: Allow
              - Action:
                  - 'ecs:RunTask'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/airplane-agentv2-*'
                Effect: Allow
              - Action:
                  - 'ecs:ListTasks'
                  - 'ecs:DescribeTasks'
                Condition:
                  ArnEquals:
                    ecs:cluster: !If
                      - ShouldCreateCluster
                      - !GetAtt Cluster.Arn
                      - !Ref ClusterARN
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'logs:GetLogEvents'
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${RunLogGroup}:log-stream:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${AgentLogGroup}:log-stream:*'
                Effect: Allow
              - Action:
                  - 'secretsmanager:CreateSecret'
                  - 'secretsmanager:DeleteSecret'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:PutSecretValue'
                  - 'secretsmanager:TagResource'
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:airplane/*'
                Effect: Allow
              - !If
                - UsingTokenSecret
                - Action:
                    - 'secretsmanager:GetSecretValue'
                  Resource: !Ref APITokenSecretARN
                  Effect: Allow
                - !Ref AWS::NoValue
              - !If
                - CustomerManagedKMS
                - Action:
                    - 'kms:Decrypt'
                  Resource: !Ref APITokenSecretKMSKeyARN
                  Effect: Allow
                - !Ref AWS::NoValue
  AgentExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ecs-tasks.amazonaws.com
            Effect: Allow
      Policies:
        - PolicyName: airplane-agent-policy
          PolicyDocument:
            Statement:
              - Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${AgentLogGroup}:*'
                Effect: Allow

  AgentTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: airplane-agent
          Image: us-docker.pkg.dev/airplane-prod/public/agentv2:1
          Environment:
            - Name: AP_API_HOST
              Value: !Ref APIHost
            - Name: AP_API_TOKEN
              Value: !Ref APIToken
            - Name: AP_API_TOKEN_SECRET_ARN
              Value: !Ref APITokenSecretARN
            - Name: AP_AUTO_UPGRADE
              Value: true
            - Name: AP_AGENT_IMAGE
              Value: us-docker.pkg.dev/airplane-prod/public/agentv2:1
            - Name: AP_DEFAULT_CPU
              Value: !Ref DefaultTaskCPU
            - Name: AP_DEFAULT_MEMORY
              Value: !Ref DefaultTaskMemory
            - Name: AP_DRIVER
              Value: ecs
            - Name: AP_ECS_REGION
              Value: !Ref AWS::Region
            - Name: AP_ECS_CLUSTER
              Value: !If
                - ShouldCreateCluster
                - !Ref Cluster
                - !Ref ClusterARN
            - Name: AP_ECS_EXECUTION_ROLE
              Value: !Ref RunExecutionRole
            - Name: AP_ECS_TASK_ROLE
              Value: !Ref DefaultRunRole
            - Name: AP_ECS_DEREGISTER_TASK_DEFINITIONS
              Value: !Ref AllowTaskDefinitionCleanup
            - Name: AP_ECS_LOG_GROUP
              Value: !Ref RunLogGroup
            - Name: AP_ECS_SUBNETS
              Value: !Join
                - ','
                - !Ref SubnetIDs
            - Name: AP_ECS_SECURITY_GROUPS
              Value: !Join
                - ','
                - - !Ref SecurityGroupID
                  - !Ref AgentSecurityGroup
            - Name: AP_ENV_SLUG
              Value: !Ref EnvSlug
            - Name: AP_LABELS
              Value: !Join
                - ' '
                - - 'airplane_installer:cloudformation_ecs'
                  - !Ref AgentLabels
            - Name: AP_MAX_CPU
              Value: !Ref MaxTaskCPU
            - Name: AP_MAX_MEMORY
              Value: !Ref MaxTaskMemory
            - Name: AP_TEAM_ID
              Value: !Ref TeamID
            - Name: AP_LOCK_KEY
              Value: !Join
                - '-'
                - - 'fargate'
                  - !Select [2, !Split ['/', !Ref AWS::StackId]]
                  - !Ref TeamID
            - Name: AP_RUNNER_TEMPORAL_HOST
              Value: !Ref TemporalHost
            - Name: AP_GCP_PROJECT_ID
              Value: !Ref ProjectID
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref AgentLogGroup
              awslogs-stream-prefix: agentv2
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      TaskRoleArn: !Ref AgentRole
      ExecutionRoleArn: !Ref AgentExecutionRole
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      RequiresCompatibilities:
        - FARGATE
  AgentService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !If
        - ShouldCreateCluster
        - !Ref Cluster
        - !Ref ClusterARN
      DesiredCount: 3
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref SubnetIDs
          SecurityGroups:
            - !Ref AgentSecurityGroup
            - !Ref SecurityGroupID
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref AgentTaskDef
  AgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - '-'
        - - /airplane/agents
          - !Select [2, !Split ['/', !Ref AWS::StackId]]
  RunLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - '-'
        - - /airplane/runs
          - !Select [2, !Split ['/', !Ref AWS::StackId]]
