extensions:
  health_check:

receivers:
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

  awsecscontainermetrics:
  prometheus:
    config:
      scrape_configs:
        - job_name: "prometheus-metrics"
          scrape_interval: 60s
          metrics_path: "/${API_SERVER_METRICS_ENDPOINT_PATH}"
          static_configs:
            - targets: ["${API_SERVER_TARGET}"]

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 33
    spike_limit_percentage: 20

  batch/honeycomb:

  batch/traces:

  batch/metrics:
    timeout: 30s

  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.reserved
          - ecs.task.memory.utilized
          - ecs.task.cpu.reserved
          - ecs.task.cpu.utilized
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
          - container.duration

  attributes/remove_honeycomb_service_name:
    # In Honeycomb, we use fpc-api as the service name even for workers and crons.
    # In Datadog, we want to use the actual service name.
    actions:
      - key: service.name
        action: upsert
        value: "${DD_SERVICE}"

exporters:
  otlp/honeycomb:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "fpc-otel"

  otlp/honeycombprom:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "fpc-prometheus"

  otlp/honeycombaws:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "fpc-aws-otel"

  otlp/datadog:
    # Exporting to the Datdog agent's OTLP receiver. This makes it easier to
    # switch to the Datadog agent directly.
    endpoint: "http://127.0.0.1:${DD_OTEL_PORT}"
    tls:
      # Connecting to local agent.
      insecure: true

service:
  pipelines:
    metrics/application:
      receivers: [otlp, prometheus]
      processors: [memory_limiter]
      exporters: [otlp/honeycombprom]
    metrics/performance:
      receivers: [awsecscontainermetrics]
      processors: [memory_limiter, filter]
      exporters: [otlp/honeycombaws]
    traces/honeycomb:
      receivers: [otlp]
      processors: [memory_limiter, batch/honeycomb]
      exporters: [otlp/honeycomb]
    logs/honeycomb:
      receivers: [otlp]
      processors: [memory_limiter, batch/honeycomb]
      exporters: [otlp/honeycomb]
    metrics/honeycomb:
      receivers: [otlp]
      processors: [memory_limiter, batch/honeycomb]
      exporters: [otlp/honeycomb]
    traces/datadog:
      receivers: [otlp]
      processors: [memory_limiter, attributes/remove_honeycomb_service_name]
      exporters: [otlp/datadog]
    logs/datadog:
      receivers: [otlp]
      processors: [memory_limiter, attributes/remove_honeycomb_service_name]
      exporters: [otlp/datadog]
    metrics/datadog:
      receivers: [otlp]
      processors: [memory_limiter, attributes/remove_honeycomb_service_name]
      exporters: [otlp/datadog]

  extensions: [health_check]
