extensions:
  health_check:

receivers:
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

  awsecscontainermetrics:
  prometheus:
    config:
      scrape_configs:
        - job_name: "prometheus-metrics"
          scrape_interval: 60s
          metrics_path: "/${API_SERVER_METRICS_ENDPOINT_PATH}"
          static_configs:
            - targets: ["${API_SERVER_TARGET}"]

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 33
    spike_limit_percentage: 20

  batch/traces:

  batch/metrics:
    timeout: 30s

  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.reserved
          - ecs.task.memory.utilized
          - ecs.task.cpu.reserved
          - ecs.task.cpu.utilized
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
          - container.duration

exporters:
  otlp/datadog:
    # Exporting to the Datdog agent's OTLP receiver. This makes it easier to
    # switch to the Datadog agent directly.
    endpoint: "http://127.0.0.1:${DD_OTEL_PORT}"
    tls:
      # Connecting to local agent.
      insecure: true

service:
  pipelines:
    traces/datadog:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlp/datadog]
    logs/datadog:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlp/datadog]
    metrics/datadog:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlp/datadog]

  extensions: [health_check]
