ALTER TABLE onboardings RENAME TO onboarding_links;

-- Rename indexes
ALTER INDEX onboardings_pkey RENAME TO onboarding_links_pkey;
ALTER INDEX onboardings_ob_configuration_id RENAME TO fk_onboarding_links_ob_configuration_id;
ALTER INDEX onboardings_onboarding_id RENAME TO fk_onboarding_links_onboarding_id;
ALTER INDEX onboardings_insight_event_id RENAME TO onboarding_links_insight_event_id;
ALTER INDEX onboardings_onboarding_id_ob_configuration_id RENAME TO onboarding_links_onboarding_id_ob_configuration_id;

-- Rename FK constraints
ALTER TABLE onboarding_links RENAME CONSTRAINT fk_onboardings_insight_event_id TO fk_onboarding_links_insight_event_id;
ALTER TABLE onboarding_links RENAME CONSTRAINT fk_onboardings_ob_configuration_id TO fk_onboarding_links_ob_configuration_id;
ALTER TABLE onboarding_links RENAME CONSTRAINT fk_onboardings_scoped_user_id TO fk_onboarding_links_scoped_user_id;