export {
  hasAuthMethodUnverifiedEmail,
  hasEmailAndPhoneNumber,
  isAuth,
  isBiometric,
  isEmail,
  isEmailIdentifier,
  isEmailOrPhoneIdentifier,
  isError,
  isFunction,
  isObject,
  isPhone,
  isPhoneIdentifier,
  isSms,
  isString,
  isStringValid,
  isUndefined,
} from './type-guards';
