import { DocumentDI } from '@onefootprint/types';
import { useTranslation } from 'react-i18next';

const useDocumentFields = () => {
  const { t } = useTranslation('common', { keyPrefix: 'di' });

  const fields = [
    {
      main: DocumentDI.latestIdCardFront,
      label: t(DocumentDI.latestIdCardFront),
      dis: [
        DocumentDI.latestIdCardFront,
        DocumentDI.latestIdCardBack,
        DocumentDI.latestIdCardSelfie,
        DocumentDI.idCardFullName,
        DocumentDI.idCardDOB,
        DocumentDI.idCardGender,
        DocumentDI.idCardFullAddress,
        DocumentDI.idCardDocumentNumber,
        DocumentDI.idCardIssuedAt,
        DocumentDI.idCardExpiresAt,
        DocumentDI.idCardIssuingState,
        DocumentDI.idCardIssuingCountry,
        DocumentDI.idCardRefNumber,
        DocumentDI.idCardNationality,
        DocumentDI.idCardClassifiedDocumentType,
        DocumentDI.idCardCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestDriversLicenseFront,
      label: t(DocumentDI.latestDriversLicenseFront),
      dis: [
        DocumentDI.latestDriversLicenseFront,
        DocumentDI.latestDriversLicenseBack,
        DocumentDI.latestDriversLicenseSelfie,
        DocumentDI.driversLicenseFullName,
        DocumentDI.driversLicenseDOB,
        DocumentDI.driversLicenseGender,
        DocumentDI.driversLicenseFullAddress,
        DocumentDI.driversLicenseDocumentNumber,
        DocumentDI.driversLicenseIssuedAt,
        DocumentDI.driversLicenseExpiresAt,
        DocumentDI.driversLicenseIssuingState,
        DocumentDI.driversLicenseIssuingCountry,
        DocumentDI.driversLicenseRefNumber,
        DocumentDI.driversLicenseNationality,
        DocumentDI.driversLicenseClassifiedDocumentType,
        DocumentDI.driversLicenseCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestPassport,
      label: t(DocumentDI.latestPassport),
      dis: [
        DocumentDI.latestPassport,
        DocumentDI.latestPassportSelfie,
        DocumentDI.passportFullName,
        DocumentDI.passportDOB,
        DocumentDI.passportGender,
        DocumentDI.passportFullAddress,
        DocumentDI.passportDocumentNumber,
        DocumentDI.passportIssuedAt,
        DocumentDI.passportExpiresAt,
        DocumentDI.passportIssuingState,
        DocumentDI.passportIssuingCountry,
        DocumentDI.passportRefNumber,
        DocumentDI.passportNationality,
        DocumentDI.passportClassifiedDocumentType,
        DocumentDI.passportCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestVisa,
      label: t(DocumentDI.latestVisa),
      dis: [
        DocumentDI.latestVisa,
        DocumentDI.latestVisaSelfie,
        DocumentDI.visaFullName,
        DocumentDI.visaDOB,
        DocumentDI.visaGender,
        DocumentDI.visaFullAddress,
        DocumentDI.visaDocumentNumber,
        DocumentDI.visaIssuedAt,
        DocumentDI.visaExpiresAt,
        DocumentDI.visaIssuingState,
        DocumentDI.visaIssuingCountry,
        DocumentDI.visaRefNumber,
        DocumentDI.visaNationality,
        DocumentDI.visaClassifiedDocumentType,
        DocumentDI.visaCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestResidenceDocumentFront,
      label: t(DocumentDI.latestResidenceDocumentFront),
      dis: [
        DocumentDI.latestResidenceDocumentFront,
        DocumentDI.latestResidenceDocumentBack,
        DocumentDI.latestResidenceDocumentSelfie,
        DocumentDI.residenceDocumentFullName,
        DocumentDI.residenceDocumentDOB,
        DocumentDI.residenceDocumentGender,
        DocumentDI.residenceDocumentFullAddress,
        DocumentDI.residenceDocumentDocumentNumber,
        DocumentDI.residenceDocumentIssuedAt,
        DocumentDI.residenceDocumentExpiresAt,
        DocumentDI.residenceDocumentIssuingState,
        DocumentDI.residenceDocumentIssuingCountry,
        DocumentDI.residenceDocumentRefNumber,
        DocumentDI.residenceDocumentNationality,
        DocumentDI.residenceDocumentClassifiedDocumentType,
        DocumentDI.residenceDocumentCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestWorkPermitFront,
      label: t(DocumentDI.latestWorkPermitFront),
      dis: [
        DocumentDI.latestWorkPermitFront,
        DocumentDI.latestWorkPermitBack,
        DocumentDI.latestWorkPermitSelfie,
        DocumentDI.workPermitFullName,
        DocumentDI.workPermitDOB,
        DocumentDI.workPermitGender,
        DocumentDI.workPermitFullAddress,
        DocumentDI.workPermitDocumentNumber,
        DocumentDI.workPermitIssuedAt,
        DocumentDI.workPermitExpiresAt,
        DocumentDI.workPermitIssuingState,
        DocumentDI.workPermitIssuingCountry,
        DocumentDI.workPermitRefNumber,
        DocumentDI.workPermitNationality,
        DocumentDI.workPermitClassifiedDocumentType,
        DocumentDI.workPermitCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestVoterIdentificationFront,
      label: t(DocumentDI.latestVoterIdentificationFront),
      dis: [
        DocumentDI.latestVoterIdentificationFront,
        DocumentDI.latestVoterIdentificationBack,
        DocumentDI.latestVoterIdentificationSelfie,
        DocumentDI.voterIdentificationFullName,
        DocumentDI.voterIdentificationDOB,
        DocumentDI.voterIdentificationGender,
        DocumentDI.voterIdentificationFullAddress,
        DocumentDI.voterIdentificationDocumentNumber,
        DocumentDI.voterIdentificationIssuedAt,
        DocumentDI.voterIdentificationExpiresAt,
        DocumentDI.voterIdentificationIssuingState,
        DocumentDI.voterIdentificationIssuingCountry,
        DocumentDI.voterIdentificationRefNumber,
        DocumentDI.voterIdentificationNationality,
        DocumentDI.voterIdentificationClassifiedDocumentType,
        DocumentDI.voterIdentificationCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.latestPassportCardFront,
      label: t(DocumentDI.latestPassportCardFront),
      dis: [
        DocumentDI.latestPassportCardFront,
        DocumentDI.latestPassportCardBack,
        DocumentDI.latestPassportCardSelfie,
        DocumentDI.passportCardFullName,
        DocumentDI.passportCardDOB,
        DocumentDI.passportCardGender,
        DocumentDI.passportCardFullAddress,
        DocumentDI.passportCardDocumentNumber,
        DocumentDI.passportCardIssuedAt,
        DocumentDI.passportCardExpiresAt,
        DocumentDI.passportCardIssuingState,
        DocumentDI.passportCardIssuingCountry,
        DocumentDI.passportCardRefNumber,
        DocumentDI.passportCardNationality,
        DocumentDI.passportCardClassifiedDocumentType,
        DocumentDI.passportCardCurpValidationResponse,
      ],
    },
    {
      main: DocumentDI.ssnCard,
      label: t(DocumentDI.ssnCard),
      dis: [DocumentDI.ssnCard],
    },
    {
      main: DocumentDI.latestLeaseFront,
      label: t(DocumentDI.latestLeaseFront),
      dis: [DocumentDI.latestLeaseFront],
    },
    {
      main: DocumentDI.latestBankStatementFront,
      label: t(DocumentDI.latestBankStatementFront),
      dis: [DocumentDI.latestBankStatementFront],
    },
    {
      main: DocumentDI.latestUtilityBillFront,
      label: t(DocumentDI.latestUtilityBillFront),
      dis: [DocumentDI.latestUtilityBillFront],
    },
    {
      main: DocumentDI.proofOfAddress,
      label: t(DocumentDI.proofOfAddress),
      dis: [DocumentDI.proofOfAddress],
    },
  ];

  return fields;
};

export default useDocumentFields;
