name: Run backend locally

inputs:
  commit_hash:
    required: true
  image_tag:
    required: true

  run_api_only:
    required: false
    default: false

  aws_region:
    required: true

  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  img_cache_aws_access_key_id:
    required: true
  img_cache_aws_secret_access_key:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      with:
        ref: ${{ inputs.commit_hash }}

    - name: Configure AWS Credentials (Dev)
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-region: ${{ inputs.aws_region }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}

    - name: Set dot env
      working-directory: ./backend
      shell: bash
      run: make set-dot-env

    - name: Configure AWS Credentials (Image Cache)
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        aws-access-key-id: ${{ inputs.img_cache_aws_access_key_id }}
        aws-region: ${{ inputs.aws_region }}
        aws-secret-access-key: ${{ inputs.img_cache_aws_secret_access_key }}

    - name: Login to Amazon ECR (Image Cache)
      id: login-ecr-image-cache
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

    - name: Set overrides for images that may have already been built
      shell: bash
      env:
        REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
        TAG: ${{ inputs.image_tag }}
      run: |
        set -euxo pipefail

        echo "CI_IMAGE_API=${REGISTRY}/api:${TAG}" >> "$GITHUB_ENV"
        echo "CI_IMAGE_ENCLAVE_PROXY=${REGISTRY}/enclave-proxy-dev:${TAG}" >> "$GITHUB_ENV"
        echo "CI_IMAGE_ENCLAVE=${REGISTRY}/enclave-dev:${TAG}" >> "$GITHUB_ENV"
        echo "CI_IMAGE_INTEGRATION_TESTS=${REGISTRY}/integration-tests:${TAG}" >> "$GITHUB_ENV"
        echo "CI_IMAGE_CACHE_REGISTRY=${REGISTRY}" >> "$GITHUB_ENV"

    # These will build any images that are missing.
    - name: Run API in background
      if: ${{ inputs.api_only }}
      shell: bash
      working-directory: ./backend
      run: docker compose --env-file /dev/null up -d --wait --quiet-pull --no-deps postgres api

    - name: Run backend stack in background
      if: ${{ ! inputs.api_only }}
      shell: bash
      working-directory: ./backend
      run: docker compose --env-file /dev/null up -d --wait --quiet-pull
