slug: query_review
name: query_review
parameters:
  - name: fp_id
    slug: fp_id
    type: shorttext
    description: fp_id
sql:
  resource: 'prod_ro_db'
  entrypoint: query_review.sql
  queryArgs:
    fp_id: '{{params.fp_id}}'
