slug: query_user
name: query_user
parameters:
  - name: fp_id
    slug: fp_id
    type: shorttext
    description: fp_id
sql:
  resource: 'prod_ro_db'
  entrypoint: query_user.sql
  queryArgs:
    q: ?
    fp_id: '{{params.fp_id}}'
