slug: query_incode_session
name: query_incode_session
parameters:
  - name: fp_id
    slug: fp_id
    type: shorttext
    description: fp_id
sql:
  resource: 'prod_ro_db'
  entrypoint: query_incode_session.sql
  queryArgs:
    fp_id: '{{params.fp_id}}'
