name: 'Build: bifrost, handoff, demos'
description: 'Builds and cache these 3 apps'
inputs:
  node-version:
    description: 'NodeJS version'
    required: false
    default: ${{ matrix.node-version }}
outputs:
  cache-hit:
    description: The output of cache-dependencies step
    value: ${{ steps.cache-dependencies.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Fetching "frontend/node_modules"
      uses: actions/cache@v3
      id: cache-dependencies
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        path: frontend/node_modules
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Build and cache "bifrost,handoff,demos" apps
      uses: actions/cache@v3
      id: cache-build-bhd
      with:
        key: ${{ runner.os }}-bhd-${{ hashFiles('**/yarn.lock') }}
        path: |
          frontend/apps/bifrost/.next
          frontend/apps/handoff/.next
          frontend/apps/demos/.next
        restore-keys: |
          ${{ runner.os }}-bhd-

    - name: Build "bifrost,handoff,demos" apps if not cached
      working-directory: ./frontend
      if: steps.cache-build-bhd.outputs.cache-hit != 'true'
      shell: bash
      run: yarn build --filter=bifrost... --filter=handoff... --filter=demos...
