export type Content = {
  description?: string;
  content: {
    'application/json': {
      // TODO these always have a "$ref", not a normal ContentSchema
      schema: ContentSchema;
    };
  };
  required?: boolean;
};

export type PathProps = {
  url: string;
  type: string;
};

export enum SecurityTypes {
  apiKey = 'Secret API Key',
  clientToken = 'Client Token',
}

export type ParameterProps = {
  description?: string;
  in: 'query' | 'header' | 'path' | 'cookie';
  name: string;
  required?: boolean;
  schema: ContentSchemaNoRef;
  // biome-ignore lint/suspicious/noExplicitAny: <explanation>
  example?: any;
  style: string;
};

export type HttpMethod = 'get' | 'put' | 'post' | 'delete' | 'options' | 'head' | 'patch' | 'trace';

/***
 * Information from the open API spec about a single backend API: its method, path, and request / response types.
 */
export type ApiArticle<TContent = Content> = {
  description?: string;
  parameters?: ParameterProps[];
  responses?: Record<string, TContent>;
  requestBody?: TContent;
  security?: Record<SecurityTypes, string[]>[];
  tags?: string[];
  // These are added on top of the open API spec
  id: string;
  method: HttpMethod;
  path: string;
  section: string;
};

export type ParametersProps = {
  parameters: ParameterProps[];
};

// TODO consolidate some of these types even more?
export type ContentSchema = {
  description?: string;
  enum?: string[];
  example?: Object;
  items?: ContentSchema;
  properties?: Record<string, ContentSchemaNoRef>;
  required?: string[];
  type: 'string' | 'number' | 'boolean' | 'array' | 'object' | 'integer';
  format?: string;
  $ref?: string;
};

// Same as above, omitting "$ref". Can definitely be cleaned up
export type ContentSchemaNoRef = {
  description?: string;
  enum?: string[];
  example?: Object;
  items?: ContentSchemaNoRef;
  properties?: Record<string, ContentSchemaNoRef>;
  required?: string[];
  type: 'string' | 'number' | 'boolean' | 'array' | 'object' | 'integer';
  format?: string;

  // This isn't an open API field - this is autogenerated for parameters and for requests. Should probably
  // just use a separate wrapper struct around this
  isRequired?: boolean;
};
