export type Content = {
  description?: string;
  content: {
    'application/json': {
      schema: ContentSchema;
    };
  };
  required?: boolean;
};

export type PathProps = {
  url: string;
  type: string;
};

export type SecurityTypes =
  | 'Secret API Key'
  | 'Client Token'
  | 'Dashboard Token';

export type SecurityProps = {
  type: SecurityTypes;
};

export type ParameterProps = {
  description?: string;
  in: string;
  name: string;
  required?: boolean;
  schema: {
    type: 'string' | 'number' | 'boolean' | 'array' | 'object';
    items: ContentSchema;
    enum?: string[];
  };
  style: string;
};

export type ArticleProps = {
  id: string;
  description?: string;
  method?: string;
  parameters?: ParameterProps[];
  path?: string;
  responses?: Record<string, Content>;
  requestBody?: Content;
  security?: SecurityTypes[];
  tags?: string[];
};

export type ParametersProps = {
  parameters: ParameterProps[];
};

export type ArticlesProps = {
  staticArticles: ArticleProps[];
  staticPreviewArticles: ArticleProps[];
};

// TODO consolidate some of these types even more?
export type ContentSchema = {
  description?: string;
  enum?: string[];
  example?: Object;
  items?: ContentSchema;
  properties?: Record<string, ContentSchema>;
  required?: string[];
  type: 'string' | 'number' | 'boolean' | 'array' | 'object' | 'integer';
  format?: string;
  $ref?: string;
  // This isn't an open API field - this is autogenerated in some contexts. Can clean up
  isRequired?: boolean;
};
