/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OnboardingRequirement

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param isMet 
 * @param requirement 
 */
@Serializable

data class ApiOnboardingRequirement (

    @SerialName(value = "is_met") @Required val isMet: kotlin.Boolean,

    @SerialName(value = "requirement") 
    @Serializable(with = OnboardingRequirementSerializer::class)
    @Required val requirement: OnboardingRequirement

) {


}

