/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CollectedDataOption

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param canAccessData 
 * @param orgName 
 * @param logoUrl 
 */
@Serializable

data class AuthorizedOrg (

    @SerialName(value = "can_access_data") @Required val canAccessData: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "org_name") @Required val orgName: kotlin.String,

    @SerialName(value = "logo_url") val logoUrl: kotlin.String? = null

) {


}

