/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param authToken 
 * @param isNewBusiness 
 */
@Serializable

data class BusinessOnboardingResponse (

    @SerialName(value = "auth_token") @Required val authToken: kotlin.String,

    @SerialName(value = "is_new_business") @Required val isNewBusiness: kotlin.Boolean

) {


}

