/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CollectDocumentConfigCustom
import org.openapitools.client.models.CollectDocumentConfigIdentity
import org.openapitools.client.models.CollectDocumentConfigProofOfAddress
import org.openapitools.client.models.CollectDocumentConfigProofOfSsn
import org.openapitools.client.models.DataIdentifier
import org.openapitools.client.models.DocumentUploadSettings

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param kind 
 * @param shouldCollectConsent 
 * @param shouldCollectSelfie 
 * @param supportedCountryAndDocTypes 
 * @param identifier 
 * @param name The human-readable name of the document to display to the user
 * @param requiresHumanReview 
 * @param uploadSettings 
 * @param description Optional human-readable description of the document that will be displayed to the user
 */
@Serializable

data class CollectDocumentConfig (

    @SerialName(value = "kind") @Required val kind: CollectDocumentConfig.Kind,

    @SerialName(value = "should_collect_consent") @Required val shouldCollectConsent: kotlin.Boolean,

    @SerialName(value = "should_collect_selfie") @Required val shouldCollectSelfie: kotlin.Boolean,

    @SerialName(value = "supported_country_and_doc_types") @Required val supportedCountryAndDocTypes: kotlin.String,

    @SerialName(value = "identifier") @Required val identifier: DataIdentifier,

    /* The human-readable name of the document to display to the user */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "requires_human_review") @Required val requiresHumanReview: kotlin.Boolean,

    @SerialName(value = "upload_settings") @Required val uploadSettings: DocumentUploadSettings,

    /* Optional human-readable description of the document that will be displayed to the user */
    @SerialName(value = "description") val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: custom
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "custom") custom("custom");
    }

}

