/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attestationChallenge attestation challenge to use
 * @param state state token to send back along with attestation
 */
@Serializable

data class DeviceAttestationChallengeResponse (

    /* attestation challenge to use */
    @SerialName(value = "attestation_challenge") @Required val attestationChallenge: kotlin.String,

    /* state token to send back along with attestation */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

