/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DocumentImageError
import org.openapitools.client.models.DocumentSide

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for a identity document request. Errors are non-optional if the identity vendor.  Requires additional images be collected.
 *
 * @param errors 
 * @param isRetryLimitExceeded 
 * @param nextSideToCollect 
 */
@Serializable

data class DocumentResponse (

    @SerialName(value = "errors") @Required val errors: kotlin.collections.List<DocumentImageError>,

    @SerialName(value = "is_retry_limit_exceeded") @Required val isRetryLimitExceeded: kotlin.Boolean,

    @SerialName(value = "next_side_to_collect") val nextSideToCollect: DocumentSide? = null

) {


}

