/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DocumentAndCountryConfiguration

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param collectSelfie 
 * @param documentTypesAndCountries 
 */
@Serializable

data class DocumentRequestConfigAnyOfData (

    @SerialName(value = "collect_selfie") @Required val collectSelfie: kotlin.Boolean,

    @SerialName(value = "document_types_and_countries") val documentTypesAndCountries: DocumentAndCountryConfiguration? = null

) {


}

