/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CustomDocumentConfig
import org.openapitools.client.models.DocumentRequestConfigAnyOf
import org.openapitools.client.models.DocumentRequestConfigAnyOf1
import org.openapitools.client.models.DocumentRequestConfigAnyOf2
import org.openapitools.client.models.DocumentRequestConfigAnyOf3

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class DocumentRequestConfig (

    @SerialName(value = "data") @Required val `data`: CustomDocumentConfig,

    @SerialName(value = "kind") @Required val kind: DocumentRequestConfig.Kind

) {

    /**
     * 
     *
     * Values: custom
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "custom") custom("custom");
    }

}

