/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param path 
 * @param requestId 
 * @param visitorId 
 */
@Serializable

data class FingerprintVisitRequest (

    @SerialName(value = "path") @Required val path: kotlin.String,

    @SerialName(value = "request_id") @Required val requestId: kotlin.String,

    @SerialName(value = "visitor_id") @Required val visitorId: kotlin.String

) {


}

