/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FormV1Options
import org.openapitools.client.models.L10nV1

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param authToken 
 * @param l10n 
 * @param options 
 * @param title 
 */
@Serializable

data class FormV1SdkArgs (

    @SerialName(value = "auth_token") val authToken: kotlin.String? = null,

    @SerialName(value = "l10n") val l10n: L10nV1? = null,

    @SerialName(value = "options") val options: FormV1Options? = null,

    @SerialName(value = "title") val title: kotlin.String? = null

) {


}

