/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Inviter
import org.openapitools.client.models.VaultData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param invitedData 
 * @param inviter 
 * @param name 
 */
@Serializable

data class HostedBusinessDetail (

    @SerialName(value = "invited_data") @Required val invitedData: VaultData,

    @SerialName(value = "inviter") @Required val inviter: Inviter,

    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

