/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DataIdentifier
import org.openapitools.client.models.ModernRawUserDataRequest

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param decryptedData 
 * @param hasLinkedUser True if a user has already started onboarding as this beneficial owner. In this case, the  data below comes directly from that user's vault.
 * @param isAuthedUser True if this beneficial owner represents the currently authed user.
 * @param isMutable True if this beneficial owner is editable by the currently authed user.
 * @param linkId 
 * @param populatedData 
 * @param uuid 
 * @param ownershipStake 
 */
@Serializable

data class HostedBusinessOwner (

    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "decrypted_data") @Required val decryptedData: ModernRawUserDataRequest,

    /* True if a user has already started onboarding as this beneficial owner. In this case, the  data below comes directly from that user's vault. */
    @SerialName(value = "has_linked_user") @Required val hasLinkedUser: kotlin.Boolean,

    /* True if this beneficial owner represents the currently authed user. */
    @SerialName(value = "is_authed_user") @Required val isAuthedUser: kotlin.Boolean,

    /* True if this beneficial owner is editable by the currently authed user. */
    @SerialName(value = "is_mutable") @Required val isMutable: kotlin.Boolean,

    @SerialName(value = "link_id") @Required val linkId: kotlin.String,

    @SerialName(value = "populated_data") @Required val populatedData: kotlin.collections.List<DataIdentifier>,

    @SerialName(value = "uuid") @Required val uuid: kotlin.String,

    @SerialName(value = "ownership_stake") val ownershipStake: kotlin.Int? = null

) {


}

