/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IdentifyScope

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeResponse 
 * @param challengeToken Opaque challenge state token
 * @param scope 
 */
@Serializable

data class IdentifyVerifyRequest (

    @SerialName(value = "challenge_response") @Required val challengeResponse: kotlin.String,

    /* Opaque challenge state token */
    @SerialName(value = "challenge_token") @Required val challengeToken: kotlin.String,

    @SerialName(value = "scope") @Required val scope: IdentifyScope

) {


}

