/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthMethodKind
import org.openapitools.client.models.ChallengeKind
import org.openapitools.client.models.CollectedDataOption
import org.openapitools.client.models.IdentifiedUser
import org.openapitools.client.models.IdentifyRequirementChallenge
import org.openapitools.client.models.IdentifyRequirementCollectData
import org.openapitools.client.models.IdentifyRequirementLogin

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cdo 
 * @param kind 
 * @param user 
 * @param authMethod 
 * @param challengeKinds 
 */
@Serializable

data class IdentifyRequirement (

    @SerialName(value = "cdo") @Required val cdo: CollectedDataOption,

    @SerialName(value = "kind") @Required val kind: IdentifyRequirement.Kind,

    @SerialName(value = "user") @Required val user: IdentifiedUser,

    @SerialName(value = "auth_method") @Required val authMethod: AuthMethodKind,

    @SerialName(value = "challenge_kinds") @Required val challengeKinds: kotlin.collections.List<ChallengeKind>

) {

    /**
     * 
     *
     * Values: challenge
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "challenge") challenge("challenge");
    }

}

