/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserChallengeData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeData 
 * @param error 
 */
@Serializable

data class IdentifyChallengeResponse (

    @SerialName(value = "challenge_data") @Required val challengeData: UserChallengeData,

    @SerialName(value = "error") val error: kotlin.String? = null

) {


}

