/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChallengeKind
import org.openapitools.client.models.DataIdentifier
import org.openapitools.client.models.IdentifyAuthMethod
import org.openapitools.client.models.UserAuthScope

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * All of the context on the identified user, if found
 *
 * @param authMethods 
 * @param availableChallengeKinds 
 * @param canInitiateSignupChallenge When true, allowed to create a new user via a signup challenge even when there's already an  existing user with this contact info. Generally, a user can make a new vault IF they're not  in a context logging into a tenant that they've already onboarded onto
 * @param hasSyncablePasskey Signals that one or more biometric credentials support syncing and may be available to use  on desktop/other devices
 * @param isUnverified 
 * @param matchingFps The list of DataIdentifiers whose fingerprints matched on the vault
 * @param token 
 * @param tokenScopes The scopes of the returned token
 * @param scrubbedEmail Populated only when identifying a user via auth token that was created by the tenant
 * @param scrubbedPhone 
 */
@Serializable

data class IdentifiedUser (

    @SerialName(value = "auth_methods") @Required val authMethods: kotlin.collections.List<IdentifyAuthMethod>,

    @SerialName(value = "available_challenge_kinds") @Required val availableChallengeKinds: kotlin.collections.List<ChallengeKind>,

    /* When true, allowed to create a new user via a signup challenge even when there's already an  existing user with this contact info. Generally, a user can make a new vault IF they're not  in a context logging into a tenant that they've already onboarded onto */
    @SerialName(value = "can_initiate_signup_challenge") @Required val canInitiateSignupChallenge: kotlin.Boolean,

    /* Signals that one or more biometric credentials support syncing and may be available to use  on desktop/other devices */
    @SerialName(value = "has_syncable_passkey") @Required val hasSyncablePasskey: kotlin.Boolean,

    @SerialName(value = "is_unverified") @Required val isUnverified: kotlin.Boolean,

    /* The list of DataIdentifiers whose fingerprints matched on the vault */
    @SerialName(value = "matching_fps") @Required val matchingFps: kotlin.collections.List<DataIdentifier>,

    @SerialName(value = "token") @Required val token: kotlin.String,

    /* The scopes of the returned token */
    @SerialName(value = "token_scopes") @Required val tokenScopes: kotlin.collections.List<UserAuthScope>,

    /* Populated only when identifying a user via auth token that was created by the tenant */
    @SerialName(value = "scrubbed_email") val scrubbedEmail: kotlin.String? = null,

    @SerialName(value = "scrubbed_phone") val scrubbedPhone: kotlin.String? = null

) {


}

