/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IdentifyScope
import org.openapitools.client.models.ModernRawUserDataRequest

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param scope 
 */
@Serializable

data class IdentifySessionRequest (

    @SerialName(value = "data") @Required val `data`: ModernRawUserDataRequest,

    @SerialName(value = "scope") @Required val scope: IdentifyScope

) {


}

