/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IdentifyIdAnyOf
import org.openapitools.client.models.IdentifyIdAnyOf1

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An identifier for the identify flow that will uniquely identify a user
 *
 * @param email 
 * @param phoneNumber 
 */
@Serializable

data class IdentifyId (

    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "phone_number") @Required val phoneNumber: kotlin.String

) {


}

