/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IdentifyId
import org.openapitools.client.models.IdentifyScope

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param scope 
 * @param email 
 * @param identifier 
 * @param phoneNumber 
 */
@Serializable

data class IdentifyRequest (

    @SerialName(value = "scope") @Required val scope: IdentifyScope,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "identifier") val identifier: IdentifyId? = null,

    @SerialName(value = "phone_number") val phoneNumber: kotlin.String? = null

) {


}

