/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bankStarAccountType 
 * @param bankStarAchAccountId 
 * @param bankStarAchAccountNumber 
 * @param bankStarAchRoutingNumber 
 * @param bankStarFingerprint 
 * @param bankStarName 
 * @param cardStarBillingAddressCountry 
 * @param cardStarBillingAddressZip 
 * @param cardStarCvc 
 * @param cardStarExpiration 
 * @param cardStarExpirationMonth 
 * @param cardStarExpirationYear 
 * @param cardStarFingerprint 
 * @param cardStarIssuer 
 * @param cardStarName 
 * @param cardStarNumber 
 * @param cardStarNumberLast4 
 * @param customStar 
 * @param documentCustomStar 
 * @param documentDriversLicenseAddressLine1 
 * @param documentDriversLicenseBackImage 
 * @param documentDriversLicenseBackMimeType 
 * @param documentDriversLicenseCity 
 * @param documentDriversLicenseClassifiedDocumentType 
 * @param documentDriversLicenseClaveDeElector 
 * @param documentDriversLicenseCurp 
 * @param documentDriversLicenseCurpValidationResponse 
 * @param documentDriversLicenseDob 
 * @param documentDriversLicenseDocumentNumber 
 * @param documentDriversLicenseExpiresAt 
 * @param documentDriversLicenseFirstName 
 * @param documentDriversLicenseFrontImage 
 * @param documentDriversLicenseFrontMimeType 
 * @param documentDriversLicenseFullAddress 
 * @param documentDriversLicenseFullName 
 * @param documentDriversLicenseGender 
 * @param documentDriversLicenseIssuedAt 
 * @param documentDriversLicenseIssuingCountry 
 * @param documentDriversLicenseIssuingState 
 * @param documentDriversLicenseLastName 
 * @param documentDriversLicenseNationality 
 * @param documentDriversLicensePostalCode 
 * @param documentDriversLicenseRefNumber 
 * @param documentDriversLicenseSambaActivityHistoryResponse 
 * @param documentDriversLicenseSelfieImage 
 * @param documentDriversLicenseSelfieMimeType 
 * @param documentDriversLicenseState 
 * @param documentDriversLicenseUsIssuingState 
 * @param documentFinraComplianceLetter 
 * @param documentIdCardAddressLine1 
 * @param documentIdCardBackImage 
 * @param documentIdCardBackMimeType 
 * @param documentIdCardCity 
 * @param documentIdCardClassifiedDocumentType 
 * @param documentIdCardClaveDeElector 
 * @param documentIdCardCurp 
 * @param documentIdCardCurpValidationResponse 
 * @param documentIdCardDob 
 * @param documentIdCardDocumentNumber 
 * @param documentIdCardExpiresAt 
 * @param documentIdCardFirstName 
 * @param documentIdCardFrontImage 
 * @param documentIdCardFrontMimeType 
 * @param documentIdCardFullAddress 
 * @param documentIdCardFullName 
 * @param documentIdCardGender 
 * @param documentIdCardIssuedAt 
 * @param documentIdCardIssuingCountry 
 * @param documentIdCardIssuingState 
 * @param documentIdCardLastName 
 * @param documentIdCardNationality 
 * @param documentIdCardPostalCode 
 * @param documentIdCardRefNumber 
 * @param documentIdCardSambaActivityHistoryResponse 
 * @param documentIdCardSelfieImage 
 * @param documentIdCardSelfieMimeType 
 * @param documentIdCardState 
 * @param documentIdCardUsIssuingState 
 * @param documentPassportAddressLine1 
 * @param documentPassportBackImage 
 * @param documentPassportBackMimeType 
 * @param documentPassportCity 
 * @param documentPassportClassifiedDocumentType 
 * @param documentPassportClaveDeElector 
 * @param documentPassportCurp 
 * @param documentPassportCurpValidationResponse 
 * @param documentPassportDob 
 * @param documentPassportDocumentNumber 
 * @param documentPassportExpiresAt 
 * @param documentPassportFirstName 
 * @param documentPassportFrontImage 
 * @param documentPassportFrontMimeType 
 * @param documentPassportFullAddress 
 * @param documentPassportFullName 
 * @param documentPassportGender 
 * @param documentPassportIssuedAt 
 * @param documentPassportIssuingCountry 
 * @param documentPassportIssuingState 
 * @param documentPassportLastName 
 * @param documentPassportNationality 
 * @param documentPassportPostalCode 
 * @param documentPassportRefNumber 
 * @param documentPassportSambaActivityHistoryResponse 
 * @param documentPassportSelfieImage 
 * @param documentPassportSelfieMimeType 
 * @param documentPassportState 
 * @param documentPassportUsIssuingState 
 * @param documentPassportCardAddressLine1 
 * @param documentPassportCardBackImage 
 * @param documentPassportCardBackMimeType 
 * @param documentPassportCardCity 
 * @param documentPassportCardClassifiedDocumentType 
 * @param documentPassportCardClaveDeElector 
 * @param documentPassportCardCurp 
 * @param documentPassportCardCurpValidationResponse 
 * @param documentPassportCardDob 
 * @param documentPassportCardDocumentNumber 
 * @param documentPassportCardExpiresAt 
 * @param documentPassportCardFirstName 
 * @param documentPassportCardFrontImage 
 * @param documentPassportCardFrontMimeType 
 * @param documentPassportCardFullAddress 
 * @param documentPassportCardFullName 
 * @param documentPassportCardGender 
 * @param documentPassportCardIssuedAt 
 * @param documentPassportCardIssuingCountry 
 * @param documentPassportCardIssuingState 
 * @param documentPassportCardLastName 
 * @param documentPassportCardNationality 
 * @param documentPassportCardPostalCode 
 * @param documentPassportCardRefNumber 
 * @param documentPassportCardSambaActivityHistoryResponse 
 * @param documentPassportCardSelfieImage 
 * @param documentPassportCardSelfieMimeType 
 * @param documentPassportCardState 
 * @param documentPassportCardUsIssuingState 
 * @param documentPermitAddressLine1 
 * @param documentPermitBackImage 
 * @param documentPermitBackMimeType 
 * @param documentPermitCity 
 * @param documentPermitClassifiedDocumentType 
 * @param documentPermitClaveDeElector 
 * @param documentPermitCurp 
 * @param documentPermitCurpValidationResponse 
 * @param documentPermitDob 
 * @param documentPermitDocumentNumber 
 * @param documentPermitExpiresAt 
 * @param documentPermitFirstName 
 * @param documentPermitFrontImage 
 * @param documentPermitFrontMimeType 
 * @param documentPermitFullAddress 
 * @param documentPermitFullName 
 * @param documentPermitGender 
 * @param documentPermitIssuedAt 
 * @param documentPermitIssuingCountry 
 * @param documentPermitIssuingState 
 * @param documentPermitLastName 
 * @param documentPermitNationality 
 * @param documentPermitPostalCode 
 * @param documentPermitRefNumber 
 * @param documentPermitSambaActivityHistoryResponse 
 * @param documentPermitSelfieImage 
 * @param documentPermitSelfieMimeType 
 * @param documentPermitState 
 * @param documentPermitUsIssuingState 
 * @param documentProofOfAddressImage 
 * @param documentResidenceDocumentAddressLine1 
 * @param documentResidenceDocumentBackImage 
 * @param documentResidenceDocumentBackMimeType 
 * @param documentResidenceDocumentCity 
 * @param documentResidenceDocumentClassifiedDocumentType 
 * @param documentResidenceDocumentClaveDeElector 
 * @param documentResidenceDocumentCurp 
 * @param documentResidenceDocumentCurpValidationResponse 
 * @param documentResidenceDocumentDob 
 * @param documentResidenceDocumentDocumentNumber 
 * @param documentResidenceDocumentExpiresAt 
 * @param documentResidenceDocumentFirstName 
 * @param documentResidenceDocumentFrontImage 
 * @param documentResidenceDocumentFrontMimeType 
 * @param documentResidenceDocumentFullAddress 
 * @param documentResidenceDocumentFullName 
 * @param documentResidenceDocumentGender 
 * @param documentResidenceDocumentIssuedAt 
 * @param documentResidenceDocumentIssuingCountry 
 * @param documentResidenceDocumentIssuingState 
 * @param documentResidenceDocumentLastName 
 * @param documentResidenceDocumentNationality 
 * @param documentResidenceDocumentPostalCode 
 * @param documentResidenceDocumentRefNumber 
 * @param documentResidenceDocumentSambaActivityHistoryResponse 
 * @param documentResidenceDocumentSelfieImage 
 * @param documentResidenceDocumentSelfieMimeType 
 * @param documentResidenceDocumentState 
 * @param documentResidenceDocumentUsIssuingState 
 * @param documentSsnCardImage 
 * @param documentVisaAddressLine1 
 * @param documentVisaBackImage 
 * @param documentVisaBackMimeType 
 * @param documentVisaCity 
 * @param documentVisaClassifiedDocumentType 
 * @param documentVisaClaveDeElector 
 * @param documentVisaCurp 
 * @param documentVisaCurpValidationResponse 
 * @param documentVisaDob 
 * @param documentVisaDocumentNumber 
 * @param documentVisaExpiresAt 
 * @param documentVisaFirstName 
 * @param documentVisaFrontImage 
 * @param documentVisaFrontMimeType 
 * @param documentVisaFullAddress 
 * @param documentVisaFullName 
 * @param documentVisaGender 
 * @param documentVisaIssuedAt 
 * @param documentVisaIssuingCountry 
 * @param documentVisaIssuingState 
 * @param documentVisaLastName 
 * @param documentVisaNationality 
 * @param documentVisaPostalCode 
 * @param documentVisaRefNumber 
 * @param documentVisaSambaActivityHistoryResponse 
 * @param documentVisaSelfieImage 
 * @param documentVisaSelfieMimeType 
 * @param documentVisaState 
 * @param documentVisaUsIssuingState 
 * @param documentVoterIdentificationAddressLine1 
 * @param documentVoterIdentificationBackImage 
 * @param documentVoterIdentificationBackMimeType 
 * @param documentVoterIdentificationCity 
 * @param documentVoterIdentificationClassifiedDocumentType 
 * @param documentVoterIdentificationClaveDeElector 
 * @param documentVoterIdentificationCurp 
 * @param documentVoterIdentificationCurpValidationResponse 
 * @param documentVoterIdentificationDob 
 * @param documentVoterIdentificationDocumentNumber 
 * @param documentVoterIdentificationExpiresAt 
 * @param documentVoterIdentificationFirstName 
 * @param documentVoterIdentificationFrontImage 
 * @param documentVoterIdentificationFrontMimeType 
 * @param documentVoterIdentificationFullAddress 
 * @param documentVoterIdentificationFullName 
 * @param documentVoterIdentificationGender 
 * @param documentVoterIdentificationIssuedAt 
 * @param documentVoterIdentificationIssuingCountry 
 * @param documentVoterIdentificationIssuingState 
 * @param documentVoterIdentificationLastName 
 * @param documentVoterIdentificationNationality 
 * @param documentVoterIdentificationPostalCode 
 * @param documentVoterIdentificationRefNumber 
 * @param documentVoterIdentificationSambaActivityHistoryResponse 
 * @param documentVoterIdentificationSelfieImage 
 * @param documentVoterIdentificationSelfieMimeType 
 * @param documentVoterIdentificationState 
 * @param documentVoterIdentificationUsIssuingState 
 * @param idAddressLine1 
 * @param idAddressLine2 
 * @param idCitizenships 
 * @param idCity 
 * @param idCountry 
 * @param idDob 
 * @param idDriversLicenseNumber 
 * @param idDriversLicenseState 
 * @param idEmail 
 * @param idFirstName 
 * @param idItin 
 * @param idLastName 
 * @param idMiddleName 
 * @param idNationality 
 * @param idPhoneNumber 
 * @param idSsn4 
 * @param idSsn9 
 * @param idState 
 * @param idUsLegalStatus 
 * @param idUsTaxId 
 * @param idVisaExpirationDate 
 * @param idVisaKind 
 * @param idZip 
 * @param investorProfileAnnualIncome 
 * @param investorProfileBrokerageFirmEmployer 
 * @param investorProfileDeclarations 
 * @param investorProfileEmployer 
 * @param investorProfileEmploymentStatus 
 * @param investorProfileFamilyMemberNames 
 * @param investorProfileFundingSources 
 * @param investorProfileInvestmentGoals 
 * @param investorProfileNetWorth 
 * @param investorProfileOccupation 
 * @param investorProfilePoliticalOrganization 
 * @param investorProfileRiskTolerance 
 * @param investorProfileSeniorExecutiveSymbols 
 */
@Serializable

data class ModernUserDecryptResponse (

    @SerialName(value = "bank.*.account_type") val bankStarAccountType: kotlin.String? = null,

    @SerialName(value = "bank.*.ach_account_id") val bankStarAchAccountId: kotlin.String? = null,

    @SerialName(value = "bank.*.ach_account_number") val bankStarAchAccountNumber: kotlin.String? = null,

    @SerialName(value = "bank.*.ach_routing_number") val bankStarAchRoutingNumber: kotlin.String? = null,

    @SerialName(value = "bank.*.fingerprint") val bankStarFingerprint: kotlin.String? = null,

    @SerialName(value = "bank.*.name") val bankStarName: kotlin.String? = null,

    @SerialName(value = "card.*.billing_address.country") val cardStarBillingAddressCountry: kotlin.String? = null,

    @SerialName(value = "card.*.billing_address.zip") val cardStarBillingAddressZip: kotlin.String? = null,

    @SerialName(value = "card.*.cvc") val cardStarCvc: kotlin.String? = null,

    @SerialName(value = "card.*.expiration") val cardStarExpiration: kotlin.String? = null,

    @SerialName(value = "card.*.expiration_month") val cardStarExpirationMonth: kotlin.String? = null,

    @SerialName(value = "card.*.expiration_year") val cardStarExpirationYear: kotlin.String? = null,

    @SerialName(value = "card.*.fingerprint") val cardStarFingerprint: kotlin.String? = null,

    @SerialName(value = "card.*.issuer") val cardStarIssuer: kotlin.String? = null,

    @SerialName(value = "card.*.name") val cardStarName: kotlin.String? = null,

    @SerialName(value = "card.*.number") val cardStarNumber: kotlin.String? = null,

    @SerialName(value = "card.*.number_last4") val cardStarNumberLast4: kotlin.String? = null,

    @SerialName(value = "custom.*") val customStar: kotlin.String? = null,

    @SerialName(value = "document.custom.*") val documentCustomStar: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.address_line1") val documentDriversLicenseAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.back.image") val documentDriversLicenseBackImage: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.back.mime_type") val documentDriversLicenseBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.city") val documentDriversLicenseCity: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.classified_document_type") val documentDriversLicenseClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.clave_de_elector") val documentDriversLicenseClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.curp") val documentDriversLicenseCurp: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.curp_validation_response") val documentDriversLicenseCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.dob") val documentDriversLicenseDob: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.document_number") val documentDriversLicenseDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.expires_at") val documentDriversLicenseExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.first_name") val documentDriversLicenseFirstName: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.front.image") val documentDriversLicenseFrontImage: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.front.mime_type") val documentDriversLicenseFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.full_address") val documentDriversLicenseFullAddress: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.full_name") val documentDriversLicenseFullName: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.gender") val documentDriversLicenseGender: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.issued_at") val documentDriversLicenseIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.issuing_country") val documentDriversLicenseIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.issuing_state") val documentDriversLicenseIssuingState: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.last_name") val documentDriversLicenseLastName: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.nationality") val documentDriversLicenseNationality: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.postal_code") val documentDriversLicensePostalCode: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.ref_number") val documentDriversLicenseRefNumber: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.samba_activity_history_response") val documentDriversLicenseSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.selfie.image") val documentDriversLicenseSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.selfie.mime_type") val documentDriversLicenseSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.state") val documentDriversLicenseState: kotlin.String? = null,

    @SerialName(value = "document.drivers_license.us_issuing_state") val documentDriversLicenseUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.finra_compliance_letter") val documentFinraComplianceLetter: kotlin.String? = null,

    @SerialName(value = "document.id_card.address_line1") val documentIdCardAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.id_card.back.image") val documentIdCardBackImage: kotlin.String? = null,

    @SerialName(value = "document.id_card.back.mime_type") val documentIdCardBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.id_card.city") val documentIdCardCity: kotlin.String? = null,

    @SerialName(value = "document.id_card.classified_document_type") val documentIdCardClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.id_card.clave_de_elector") val documentIdCardClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.id_card.curp") val documentIdCardCurp: kotlin.String? = null,

    @SerialName(value = "document.id_card.curp_validation_response") val documentIdCardCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.id_card.dob") val documentIdCardDob: kotlin.String? = null,

    @SerialName(value = "document.id_card.document_number") val documentIdCardDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.id_card.expires_at") val documentIdCardExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.id_card.first_name") val documentIdCardFirstName: kotlin.String? = null,

    @SerialName(value = "document.id_card.front.image") val documentIdCardFrontImage: kotlin.String? = null,

    @SerialName(value = "document.id_card.front.mime_type") val documentIdCardFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.id_card.full_address") val documentIdCardFullAddress: kotlin.String? = null,

    @SerialName(value = "document.id_card.full_name") val documentIdCardFullName: kotlin.String? = null,

    @SerialName(value = "document.id_card.gender") val documentIdCardGender: kotlin.String? = null,

    @SerialName(value = "document.id_card.issued_at") val documentIdCardIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.id_card.issuing_country") val documentIdCardIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.id_card.issuing_state") val documentIdCardIssuingState: kotlin.String? = null,

    @SerialName(value = "document.id_card.last_name") val documentIdCardLastName: kotlin.String? = null,

    @SerialName(value = "document.id_card.nationality") val documentIdCardNationality: kotlin.String? = null,

    @SerialName(value = "document.id_card.postal_code") val documentIdCardPostalCode: kotlin.String? = null,

    @SerialName(value = "document.id_card.ref_number") val documentIdCardRefNumber: kotlin.String? = null,

    @SerialName(value = "document.id_card.samba_activity_history_response") val documentIdCardSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.id_card.selfie.image") val documentIdCardSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.id_card.selfie.mime_type") val documentIdCardSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.id_card.state") val documentIdCardState: kotlin.String? = null,

    @SerialName(value = "document.id_card.us_issuing_state") val documentIdCardUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.passport.address_line1") val documentPassportAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.passport.back.image") val documentPassportBackImage: kotlin.String? = null,

    @SerialName(value = "document.passport.back.mime_type") val documentPassportBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.passport.city") val documentPassportCity: kotlin.String? = null,

    @SerialName(value = "document.passport.classified_document_type") val documentPassportClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.passport.clave_de_elector") val documentPassportClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.passport.curp") val documentPassportCurp: kotlin.String? = null,

    @SerialName(value = "document.passport.curp_validation_response") val documentPassportCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.passport.dob") val documentPassportDob: kotlin.String? = null,

    @SerialName(value = "document.passport.document_number") val documentPassportDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.passport.expires_at") val documentPassportExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.passport.first_name") val documentPassportFirstName: kotlin.String? = null,

    @SerialName(value = "document.passport.front.image") val documentPassportFrontImage: kotlin.String? = null,

    @SerialName(value = "document.passport.front.mime_type") val documentPassportFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.passport.full_address") val documentPassportFullAddress: kotlin.String? = null,

    @SerialName(value = "document.passport.full_name") val documentPassportFullName: kotlin.String? = null,

    @SerialName(value = "document.passport.gender") val documentPassportGender: kotlin.String? = null,

    @SerialName(value = "document.passport.issued_at") val documentPassportIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.passport.issuing_country") val documentPassportIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.passport.issuing_state") val documentPassportIssuingState: kotlin.String? = null,

    @SerialName(value = "document.passport.last_name") val documentPassportLastName: kotlin.String? = null,

    @SerialName(value = "document.passport.nationality") val documentPassportNationality: kotlin.String? = null,

    @SerialName(value = "document.passport.postal_code") val documentPassportPostalCode: kotlin.String? = null,

    @SerialName(value = "document.passport.ref_number") val documentPassportRefNumber: kotlin.String? = null,

    @SerialName(value = "document.passport.samba_activity_history_response") val documentPassportSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.passport.selfie.image") val documentPassportSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.passport.selfie.mime_type") val documentPassportSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.passport.state") val documentPassportState: kotlin.String? = null,

    @SerialName(value = "document.passport.us_issuing_state") val documentPassportUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.passport_card.address_line1") val documentPassportCardAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.passport_card.back.image") val documentPassportCardBackImage: kotlin.String? = null,

    @SerialName(value = "document.passport_card.back.mime_type") val documentPassportCardBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.passport_card.city") val documentPassportCardCity: kotlin.String? = null,

    @SerialName(value = "document.passport_card.classified_document_type") val documentPassportCardClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.passport_card.clave_de_elector") val documentPassportCardClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.passport_card.curp") val documentPassportCardCurp: kotlin.String? = null,

    @SerialName(value = "document.passport_card.curp_validation_response") val documentPassportCardCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.passport_card.dob") val documentPassportCardDob: kotlin.String? = null,

    @SerialName(value = "document.passport_card.document_number") val documentPassportCardDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.passport_card.expires_at") val documentPassportCardExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.passport_card.first_name") val documentPassportCardFirstName: kotlin.String? = null,

    @SerialName(value = "document.passport_card.front.image") val documentPassportCardFrontImage: kotlin.String? = null,

    @SerialName(value = "document.passport_card.front.mime_type") val documentPassportCardFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.passport_card.full_address") val documentPassportCardFullAddress: kotlin.String? = null,

    @SerialName(value = "document.passport_card.full_name") val documentPassportCardFullName: kotlin.String? = null,

    @SerialName(value = "document.passport_card.gender") val documentPassportCardGender: kotlin.String? = null,

    @SerialName(value = "document.passport_card.issued_at") val documentPassportCardIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.passport_card.issuing_country") val documentPassportCardIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.passport_card.issuing_state") val documentPassportCardIssuingState: kotlin.String? = null,

    @SerialName(value = "document.passport_card.last_name") val documentPassportCardLastName: kotlin.String? = null,

    @SerialName(value = "document.passport_card.nationality") val documentPassportCardNationality: kotlin.String? = null,

    @SerialName(value = "document.passport_card.postal_code") val documentPassportCardPostalCode: kotlin.String? = null,

    @SerialName(value = "document.passport_card.ref_number") val documentPassportCardRefNumber: kotlin.String? = null,

    @SerialName(value = "document.passport_card.samba_activity_history_response") val documentPassportCardSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.passport_card.selfie.image") val documentPassportCardSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.passport_card.selfie.mime_type") val documentPassportCardSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.passport_card.state") val documentPassportCardState: kotlin.String? = null,

    @SerialName(value = "document.passport_card.us_issuing_state") val documentPassportCardUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.permit.address_line1") val documentPermitAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.permit.back.image") val documentPermitBackImage: kotlin.String? = null,

    @SerialName(value = "document.permit.back.mime_type") val documentPermitBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.permit.city") val documentPermitCity: kotlin.String? = null,

    @SerialName(value = "document.permit.classified_document_type") val documentPermitClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.permit.clave_de_elector") val documentPermitClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.permit.curp") val documentPermitCurp: kotlin.String? = null,

    @SerialName(value = "document.permit.curp_validation_response") val documentPermitCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.permit.dob") val documentPermitDob: kotlin.String? = null,

    @SerialName(value = "document.permit.document_number") val documentPermitDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.permit.expires_at") val documentPermitExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.permit.first_name") val documentPermitFirstName: kotlin.String? = null,

    @SerialName(value = "document.permit.front.image") val documentPermitFrontImage: kotlin.String? = null,

    @SerialName(value = "document.permit.front.mime_type") val documentPermitFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.permit.full_address") val documentPermitFullAddress: kotlin.String? = null,

    @SerialName(value = "document.permit.full_name") val documentPermitFullName: kotlin.String? = null,

    @SerialName(value = "document.permit.gender") val documentPermitGender: kotlin.String? = null,

    @SerialName(value = "document.permit.issued_at") val documentPermitIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.permit.issuing_country") val documentPermitIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.permit.issuing_state") val documentPermitIssuingState: kotlin.String? = null,

    @SerialName(value = "document.permit.last_name") val documentPermitLastName: kotlin.String? = null,

    @SerialName(value = "document.permit.nationality") val documentPermitNationality: kotlin.String? = null,

    @SerialName(value = "document.permit.postal_code") val documentPermitPostalCode: kotlin.String? = null,

    @SerialName(value = "document.permit.ref_number") val documentPermitRefNumber: kotlin.String? = null,

    @SerialName(value = "document.permit.samba_activity_history_response") val documentPermitSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.permit.selfie.image") val documentPermitSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.permit.selfie.mime_type") val documentPermitSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.permit.state") val documentPermitState: kotlin.String? = null,

    @SerialName(value = "document.permit.us_issuing_state") val documentPermitUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.proof_of_address.image") val documentProofOfAddressImage: kotlin.String? = null,

    @SerialName(value = "document.residence_document.address_line1") val documentResidenceDocumentAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.residence_document.back.image") val documentResidenceDocumentBackImage: kotlin.String? = null,

    @SerialName(value = "document.residence_document.back.mime_type") val documentResidenceDocumentBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.residence_document.city") val documentResidenceDocumentCity: kotlin.String? = null,

    @SerialName(value = "document.residence_document.classified_document_type") val documentResidenceDocumentClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.residence_document.clave_de_elector") val documentResidenceDocumentClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.residence_document.curp") val documentResidenceDocumentCurp: kotlin.String? = null,

    @SerialName(value = "document.residence_document.curp_validation_response") val documentResidenceDocumentCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.residence_document.dob") val documentResidenceDocumentDob: kotlin.String? = null,

    @SerialName(value = "document.residence_document.document_number") val documentResidenceDocumentDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.residence_document.expires_at") val documentResidenceDocumentExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.residence_document.first_name") val documentResidenceDocumentFirstName: kotlin.String? = null,

    @SerialName(value = "document.residence_document.front.image") val documentResidenceDocumentFrontImage: kotlin.String? = null,

    @SerialName(value = "document.residence_document.front.mime_type") val documentResidenceDocumentFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.residence_document.full_address") val documentResidenceDocumentFullAddress: kotlin.String? = null,

    @SerialName(value = "document.residence_document.full_name") val documentResidenceDocumentFullName: kotlin.String? = null,

    @SerialName(value = "document.residence_document.gender") val documentResidenceDocumentGender: kotlin.String? = null,

    @SerialName(value = "document.residence_document.issued_at") val documentResidenceDocumentIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.residence_document.issuing_country") val documentResidenceDocumentIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.residence_document.issuing_state") val documentResidenceDocumentIssuingState: kotlin.String? = null,

    @SerialName(value = "document.residence_document.last_name") val documentResidenceDocumentLastName: kotlin.String? = null,

    @SerialName(value = "document.residence_document.nationality") val documentResidenceDocumentNationality: kotlin.String? = null,

    @SerialName(value = "document.residence_document.postal_code") val documentResidenceDocumentPostalCode: kotlin.String? = null,

    @SerialName(value = "document.residence_document.ref_number") val documentResidenceDocumentRefNumber: kotlin.String? = null,

    @SerialName(value = "document.residence_document.samba_activity_history_response") val documentResidenceDocumentSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.residence_document.selfie.image") val documentResidenceDocumentSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.residence_document.selfie.mime_type") val documentResidenceDocumentSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.residence_document.state") val documentResidenceDocumentState: kotlin.String? = null,

    @SerialName(value = "document.residence_document.us_issuing_state") val documentResidenceDocumentUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.ssn_card.image") val documentSsnCardImage: kotlin.String? = null,

    @SerialName(value = "document.visa.address_line1") val documentVisaAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.visa.back.image") val documentVisaBackImage: kotlin.String? = null,

    @SerialName(value = "document.visa.back.mime_type") val documentVisaBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.visa.city") val documentVisaCity: kotlin.String? = null,

    @SerialName(value = "document.visa.classified_document_type") val documentVisaClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.visa.clave_de_elector") val documentVisaClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.visa.curp") val documentVisaCurp: kotlin.String? = null,

    @SerialName(value = "document.visa.curp_validation_response") val documentVisaCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.visa.dob") val documentVisaDob: kotlin.String? = null,

    @SerialName(value = "document.visa.document_number") val documentVisaDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.visa.expires_at") val documentVisaExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.visa.first_name") val documentVisaFirstName: kotlin.String? = null,

    @SerialName(value = "document.visa.front.image") val documentVisaFrontImage: kotlin.String? = null,

    @SerialName(value = "document.visa.front.mime_type") val documentVisaFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.visa.full_address") val documentVisaFullAddress: kotlin.String? = null,

    @SerialName(value = "document.visa.full_name") val documentVisaFullName: kotlin.String? = null,

    @SerialName(value = "document.visa.gender") val documentVisaGender: kotlin.String? = null,

    @SerialName(value = "document.visa.issued_at") val documentVisaIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.visa.issuing_country") val documentVisaIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.visa.issuing_state") val documentVisaIssuingState: kotlin.String? = null,

    @SerialName(value = "document.visa.last_name") val documentVisaLastName: kotlin.String? = null,

    @SerialName(value = "document.visa.nationality") val documentVisaNationality: kotlin.String? = null,

    @SerialName(value = "document.visa.postal_code") val documentVisaPostalCode: kotlin.String? = null,

    @SerialName(value = "document.visa.ref_number") val documentVisaRefNumber: kotlin.String? = null,

    @SerialName(value = "document.visa.samba_activity_history_response") val documentVisaSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.visa.selfie.image") val documentVisaSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.visa.selfie.mime_type") val documentVisaSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.visa.state") val documentVisaState: kotlin.String? = null,

    @SerialName(value = "document.visa.us_issuing_state") val documentVisaUsIssuingState: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.address_line1") val documentVoterIdentificationAddressLine1: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.back.image") val documentVoterIdentificationBackImage: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.back.mime_type") val documentVoterIdentificationBackMimeType: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.city") val documentVoterIdentificationCity: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.classified_document_type") val documentVoterIdentificationClassifiedDocumentType: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.clave_de_elector") val documentVoterIdentificationClaveDeElector: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.curp") val documentVoterIdentificationCurp: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.curp_validation_response") val documentVoterIdentificationCurpValidationResponse: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.dob") val documentVoterIdentificationDob: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.document_number") val documentVoterIdentificationDocumentNumber: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.expires_at") val documentVoterIdentificationExpiresAt: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.first_name") val documentVoterIdentificationFirstName: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.front.image") val documentVoterIdentificationFrontImage: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.front.mime_type") val documentVoterIdentificationFrontMimeType: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.full_address") val documentVoterIdentificationFullAddress: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.full_name") val documentVoterIdentificationFullName: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.gender") val documentVoterIdentificationGender: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.issued_at") val documentVoterIdentificationIssuedAt: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.issuing_country") val documentVoterIdentificationIssuingCountry: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.issuing_state") val documentVoterIdentificationIssuingState: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.last_name") val documentVoterIdentificationLastName: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.nationality") val documentVoterIdentificationNationality: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.postal_code") val documentVoterIdentificationPostalCode: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.ref_number") val documentVoterIdentificationRefNumber: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.samba_activity_history_response") val documentVoterIdentificationSambaActivityHistoryResponse: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.selfie.image") val documentVoterIdentificationSelfieImage: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.selfie.mime_type") val documentVoterIdentificationSelfieMimeType: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.state") val documentVoterIdentificationState: kotlin.String? = null,

    @SerialName(value = "document.voter_identification.us_issuing_state") val documentVoterIdentificationUsIssuingState: kotlin.String? = null,

    @SerialName(value = "id.address_line1") val idAddressLine1: kotlin.String? = null,

    @SerialName(value = "id.address_line2") val idAddressLine2: kotlin.String? = null,

    @SerialName(value = "id.citizenships") val idCitizenships: kotlin.String? = null,

    @SerialName(value = "id.city") val idCity: kotlin.String? = null,

    @SerialName(value = "id.country") val idCountry: kotlin.String? = null,

    @SerialName(value = "id.dob") val idDob: kotlin.String? = null,

    @SerialName(value = "id.drivers_license_number") val idDriversLicenseNumber: kotlin.String? = null,

    @SerialName(value = "id.drivers_license_state") val idDriversLicenseState: kotlin.String? = null,

    @SerialName(value = "id.email") val idEmail: kotlin.String? = null,

    @SerialName(value = "id.first_name") val idFirstName: kotlin.String? = null,

    @SerialName(value = "id.itin") val idItin: kotlin.String? = null,

    @SerialName(value = "id.last_name") val idLastName: kotlin.String? = null,

    @SerialName(value = "id.middle_name") val idMiddleName: kotlin.String? = null,

    @SerialName(value = "id.nationality") val idNationality: kotlin.String? = null,

    @SerialName(value = "id.phone_number") val idPhoneNumber: kotlin.String? = null,

    @SerialName(value = "id.ssn4") val idSsn4: kotlin.String? = null,

    @SerialName(value = "id.ssn9") val idSsn9: kotlin.String? = null,

    @SerialName(value = "id.state") val idState: kotlin.String? = null,

    @SerialName(value = "id.us_legal_status") val idUsLegalStatus: kotlin.String? = null,

    @SerialName(value = "id.us_tax_id") val idUsTaxId: kotlin.String? = null,

    @SerialName(value = "id.visa_expiration_date") val idVisaExpirationDate: kotlin.String? = null,

    @SerialName(value = "id.visa_kind") val idVisaKind: kotlin.String? = null,

    @SerialName(value = "id.zip") val idZip: kotlin.String? = null,

    @SerialName(value = "investor_profile.annual_income") val investorProfileAnnualIncome: kotlin.String? = null,

    @SerialName(value = "investor_profile.brokerage_firm_employer") val investorProfileBrokerageFirmEmployer: kotlin.String? = null,

    @SerialName(value = "investor_profile.declarations") val investorProfileDeclarations: kotlin.String? = null,

    @SerialName(value = "investor_profile.employer") val investorProfileEmployer: kotlin.String? = null,

    @SerialName(value = "investor_profile.employment_status") val investorProfileEmploymentStatus: kotlin.String? = null,

    @SerialName(value = "investor_profile.family_member_names") val investorProfileFamilyMemberNames: kotlin.String? = null,

    @SerialName(value = "investor_profile.funding_sources") val investorProfileFundingSources: kotlin.String? = null,

    @SerialName(value = "investor_profile.investment_goals") val investorProfileInvestmentGoals: kotlin.String? = null,

    @SerialName(value = "investor_profile.net_worth") val investorProfileNetWorth: kotlin.String? = null,

    @SerialName(value = "investor_profile.occupation") val investorProfileOccupation: kotlin.String? = null,

    @SerialName(value = "investor_profile.political_organization") val investorProfilePoliticalOrganization: kotlin.String? = null,

    @SerialName(value = "investor_profile.risk_tolerance") val investorProfileRiskTolerance: kotlin.String? = null,

    @SerialName(value = "investor_profile.senior_executive_symbols") val investorProfileSeniorExecutiveSymbols: kotlin.String? = null

) {


}

