/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: kyc,kyb,auth,document
 */
@Serializable
enum class ObConfigurationKind(val value: kotlin.String) {

    @SerialName(value = "kyc")
    kyc("kyc"),

    @SerialName(value = "kyb")
    kyb("kyb"),

    @SerialName(value = "auth")
    auth("auth"),

    @SerialName(value = "document")
    document("document");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ObConfigurationKind) "$data" else null

        /**
         * Returns a valid [ObConfigurationKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ObConfigurationKind? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

