/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The client needs to tell us when user input is done in order for us to continue processing
 *
 * @param kind 
 */
@Serializable

data class OnboardingRequirementProcess (

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementProcess.Kind

): OnboardingRequirement() {

    /**
     * 
     *
     * Values: process
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "process") process("process");
    }

}

