/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthMethodKind
import org.openapitools.client.models.AuthorizeFields
import org.openapitools.client.models.CollectDocumentConfig
import org.openapitools.client.models.CollectedDataOption
import org.openapitools.client.models.DocumentUploadSettings
import org.openapitools.client.models.OnboardingRequirementAuthorize
import org.openapitools.client.models.OnboardingRequirementCollectBusinessData
import org.openapitools.client.models.OnboardingRequirementCollectData
import org.openapitools.client.models.OnboardingRequirementCollectDocument
import org.openapitools.client.models.OnboardingRequirementCollectInvestorProfile
import org.openapitools.client.models.OnboardingRequirementCreateBusinessOnboarding
import org.openapitools.client.models.OnboardingRequirementProcess
import org.openapitools.client.models.OnboardingRequirementRegisterAuthMethod
import org.openapitools.client.models.OnboardingRequirementRegisterPasskey

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param authMethodKind 
 * @param kind 
 * @param missingAttributes 
 * @param optionalAttributes 
 * @param populatedAttributes 
 * @param recollectAttributes 
 * @param missingDocument 
 * @param requiresBusinessSelection When true, requires either selecting an existing business, or will create a new one upon  `POST /hosted/business/onboarding`.  When false, there's already a business associated with this session, so we can  immediately call `POST /hosted/business/onboarding`.
 * @param config 
 * @param documentRequestId 
 * @param uploadSettings 
 * @param fieldsToAuthorize 
 * @param authorizedAt 
 */
@Serializable

data class OnboardingRequirement (

    @SerialName(value = "auth_method_kind") @Required val authMethodKind: AuthMethodKind,

    @SerialName(value = "kind") @Required val kind: OnboardingRequirement.Kind,

    @SerialName(value = "missing_attributes") @Required val missingAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "optional_attributes") @Required val optionalAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "populated_attributes") @Required val populatedAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "recollect_attributes") @Required val recollectAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "missing_document") @Required val missingDocument: kotlin.Boolean,

    /* When true, requires either selecting an existing business, or will create a new one upon  `POST /hosted/business/onboarding`.  When false, there's already a business associated with this session, so we can  immediately call `POST /hosted/business/onboarding`. */
    @SerialName(value = "requires_business_selection") @Required val requiresBusinessSelection: kotlin.Boolean,

    @SerialName(value = "config") @Required val config: CollectDocumentConfig,

    @SerialName(value = "document_request_id") @Required val documentRequestId: kotlin.String,

    @SerialName(value = "upload_settings") @Required val uploadSettings: DocumentUploadSettings,

    @SerialName(value = "fields_to_authorize") @Required val fieldsToAuthorize: AuthorizeFields,

    @SerialName(value = "authorized_at") val authorizedAt: kotlinx.datetime.Instant? = null

) {

    /**
     * 
     *
     * Values: process
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "process") process("process");
    }

}

