/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthMethodKind

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param authMethodKind 
 * @param kind 
 */
@Serializable

data class OnboardingRequirementRegisterAuthMethod (

    @SerialName(value = "auth_method_kind") @Required val authMethodKind: AuthMethodKind,

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementRegisterAuthMethod.Kind

) {

    /**
     * 
     *
     * Values: register_auth_method
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "register_auth_method") register_auth_method("register_auth_method");
    }

}

