/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CollectedDataOption

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * There is missing business data that must be collected
 *
 * @param kind 
 * @param missingAttributes 
 * @param populatedAttributes 
 * @param recollectAttributes 
 */
@Serializable

data class OnboardingRequirementCollectBusinessData (

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementCollectBusinessData.Kind,

    @SerialName(value = "missing_attributes") @Required val missingAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "populated_attributes") @Required val populatedAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "recollect_attributes") @Required val recollectAttributes: kotlin.collections.List<CollectedDataOption>

): OnboardingRequirement() {

    /**
     * 
     *
     * Values: collect_business_data
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "collect_business_data") collect_business_data("collect_business_data");
    }

}

