/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthorizeFields

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The client needs to display the authorization consent page and confirm the user authorizes  access
 *
 * @param fieldsToAuthorize 
 * @param kind 
 * @param authorizedAt 
 */
@Serializable

data class OnboardingRequirementAuthorize (

    @SerialName(value = "fields_to_authorize") @Required val fieldsToAuthorize: AuthorizeFields,

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementAuthorize.Kind,

    @SerialName(value = "authorized_at") val authorizedAt: kotlinx.datetime.Instant? = null

): OnboardingRequirement() {

    /**
     * 
     *
     * Values: authorize
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "authorize") authorize("authorize");
    }

}

