/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Register a passkey
 *
 * @param kind 
 */
@Serializable

data class OnboardingRequirementRegisterPasskey (

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementRegisterPasskey.Kind

) {

    /**
     * 
     *
     * Values: liveness
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "liveness") liveness("liveness");
    }

}

