/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ApiKeyStatus
import org.openapitools.client.models.AuthMethodKind
import org.openapitools.client.models.HostedWorkflowRequest
import org.openapitools.client.models.Iso3166TwoDigitCountryCode
import org.openapitools.client.models.ObConfigurationKind

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The public onboarding configuration
 *
 * @param allowInternationalResidents 
 * @param appClipExperienceId 
 * @param canMakeRealDocScanCallsInSandbox 
 * @param isAppClipEnabled 
 * @param isInstantAppEnabled 
 * @param isKyb 
 * @param isLive 
 * @param isNoPhoneFlow 
 * @param isStepupEnabled 
 * @param key 
 * @param kind 
 * @param name 
 * @param orgId 
 * @param orgName 
 * @param requiresIdDoc 
 * @param skipConfirm 
 * @param status 
 * @param supportedCountries 
 * @param allowedOrigins allow list of origins permitted to host the embedded flow
 * @param appearance 
 * @param logoUrl 
 * @param nidEnabled 
 * @param privacyPolicyUrl 
 * @param requiredAuthMethods When non-null, the provided auth methods are required to be verified by the playbook. Null  does not mean that no auth is required - it just means the playbook doesn't care which  method is used.
 * @param supportEmail 
 * @param supportPhone 
 * @param supportWebsite 
 * @param workflowRequest 
 */
@Serializable

data class PublicOnboardingConfiguration (

    @SerialName(value = "allow_international_residents") @Required val allowInternationalResidents: kotlin.Boolean,

    @SerialName(value = "app_clip_experience_id") @Required val appClipExperienceId: kotlin.String,

    @SerialName(value = "can_make_real_doc_scan_calls_in_sandbox") @Required val canMakeRealDocScanCallsInSandbox: kotlin.Boolean,

    @SerialName(value = "is_app_clip_enabled") @Required val isAppClipEnabled: kotlin.Boolean,

    @SerialName(value = "is_instant_app_enabled") @Required val isInstantAppEnabled: kotlin.Boolean,

    @SerialName(value = "is_kyb") @Required val isKyb: kotlin.Boolean,

    @SerialName(value = "is_live") @Required val isLive: kotlin.Boolean,

    @SerialName(value = "is_no_phone_flow") @Required val isNoPhoneFlow: kotlin.Boolean,

    @SerialName(value = "is_stepup_enabled") @Required val isStepupEnabled: kotlin.Boolean,

    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "kind") @Required val kind: ObConfigurationKind,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "org_id") @Required val orgId: kotlin.String,

    @SerialName(value = "org_name") @Required val orgName: kotlin.String,

    @SerialName(value = "requires_id_doc") @Required val requiresIdDoc: kotlin.Boolean,

    @SerialName(value = "skip_confirm") @Required val skipConfirm: kotlin.Boolean,

    @SerialName(value = "status") @Required val status: ApiKeyStatus,

    @SerialName(value = "supported_countries") @Required val supportedCountries: kotlin.collections.List<Iso3166TwoDigitCountryCode>,

    /* allow list of origins permitted to host the embedded flow */
    @SerialName(value = "allowed_origins") val allowedOrigins: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "appearance") val appearance: kotlin.String? = null,

    @SerialName(value = "logo_url") val logoUrl: kotlin.String? = null,

    @SerialName(value = "nid_enabled") val nidEnabled: kotlin.Boolean? = null,

    @SerialName(value = "privacy_policy_url") val privacyPolicyUrl: kotlin.String? = null,

    /* When non-null, the provided auth methods are required to be verified by the playbook. Null  does not mean that no auth is required - it just means the playbook doesn't care which  method is used. */
    @SerialName(value = "required_auth_methods") val requiredAuthMethods: kotlin.collections.List<AuthMethodKind>? = null,

    @SerialName(value = "support_email") val supportEmail: kotlin.String? = null,

    @SerialName(value = "support_phone") val supportPhone: kotlin.String? = null,

    @SerialName(value = "support_website") val supportWebsite: kotlin.String? = null,

    @SerialName(value = "workflow_request") val workflowRequest: HostedWorkflowRequest? = null

) {


}

