/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param errorMessage 
 * @param elapsedTimeInOsPromptMs 
 */
@Serializable

data class RegisterPasskeyAttemptContext (

    @SerialName(value = "error_message") @Required val errorMessage: kotlin.String,

    @SerialName(value = "elapsed_time_in_os_prompt_ms") val elapsedTimeInOsPromptMs: kotlin.Long? = null

) {


}

