/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RenderV1SdkArgs
import org.openapitools.client.models.SdkArgsAnyOf
import org.openapitools.client.models.SdkArgsAnyOf1
import org.openapitools.client.models.SdkArgsAnyOf2
import org.openapitools.client.models.SdkArgsAnyOf3
import org.openapitools.client.models.SdkArgsAnyOf4
import org.openapitools.client.models.SdkArgsAnyOf5

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * BE VERY CAREFUL CHANGING THESE.  Old versions of Footprint.js may be sending old versions of this struct.  When making a breaking change to the struct, you should add a new version of the struct to this  enum variant.
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class SdkArgs (

    @SerialName(value = "data") @Required val `data`: RenderV1SdkArgs,

    @SerialName(value = "kind") @Required val kind: SdkArgs.Kind

) {

    /**
     * 
     *
     * Values: render_v1
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "render_v1") render_v1("render_v1");
    }

}

