/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FormV1SdkArgs

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class SdkArgsAnyOf2 (

    @SerialName(value = "data") @Required val `data`: FormV1SdkArgs,

    @SerialName(value = "kind") @Required val kind: SdkArgsAnyOf2.Kind

) {

    /**
     * 
     *
     * Values: form_v1
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "form_v1") form_v1("form_v1");
    }

}

