/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RegisterPasskeyAttemptContext
import org.openapitools.client.models.SkipLivenessClientType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attempts 
 * @param clientType 
 * @param numAttempts 
 * @param reason 
 */
@Serializable

data class SkipLivenessContext (

    @SerialName(value = "attempts") @Required val attempts: kotlin.collections.List<RegisterPasskeyAttemptContext>,

    @SerialName(value = "client_type") @Required val clientType: SkipLivenessClientType,

    @SerialName(value = "num_attempts") @Required val numAttempts: kotlin.Long,

    @SerialName(value = "reason") @Required val reason: kotlin.String

) {


}

