/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FilterFunction
import org.openapitools.client.models.UserDataIdentifier

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param reason Reason for the data decryption. This will be logged
 * @param fields List of data identifiers to decrypt. For example, `id.first_name`, `id.ssn4`,  `custom.bank_account`
 * @param transforms A list of filter and transform functions to apply to each decrypted datum.  Omit or leave empty to apply no transforms.  Can find more information on allowed transform functions on our docs
 * @param versionAt When provided, decrypts the user's data as it existed at the provided timestamp.  Provided as an ISO 8601 timestamp string, like `2024-01-01T12:00:00Z`.
 */
@Serializable

data class UserDecryptRequest (

    /* Reason for the data decryption. This will be logged */
    @SerialName(value = "reason") @Required val reason: kotlin.String,

    /* List of data identifiers to decrypt. For example, `id.first_name`, `id.ssn4`,  `custom.bank_account` */
    @SerialName(value = "fields") val fields: kotlin.collections.List<UserDataIdentifier>? = null,

    /* A list of filter and transform functions to apply to each decrypted datum.  Omit or leave empty to apply no transforms.  Can find more information on allowed transform functions on our docs */
    @SerialName(value = "transforms") val transforms: kotlin.collections.List<FilterFunction>? = null,

    /* When provided, decrypts the user's data as it existed at the provided timestamp.  Provided as an ISO 8601 timestamp string, like `2024-01-01T12:00:00Z`. */
    @SerialName(value = "version_at") val versionAt: kotlinx.datetime.Instant? = null

) {


}

