/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeResponse The response to the challenge. Either SMS/email PIN code or passkey response
 * @param challengeToken The token given from initiating the challenge
 */
@Serializable

data class UserChallengeVerifyRequest (

    /* The response to the challenge. Either SMS/email PIN code or passkey response */
    @SerialName(value = "challenge_response") @Required val challengeResponse: kotlin.String,

    /* The token given from initiating the challenge */
    @SerialName(value = "challenge_token") @Required val challengeToken: kotlin.String

) {


}

