/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ActionKind
import org.openapitools.client.models.AuthMethodKind

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionKind 
 * @param kind 
 * @param email If the challenge kind is email, the email address to send the challenge to
 * @param phoneNumber If the challenge kind is SMS, the phone number to send the challenge to
 */
@Serializable

data class UserChallengeRequest (

    @SerialName(value = "action_kind") @Required val actionKind: ActionKind,

    @SerialName(value = "kind") @Required val kind: AuthMethodKind,

    /* If the challenge kind is email, the email address to send the challenge to */
    @SerialName(value = "email") val email: kotlin.String? = null,

    /* If the challenge kind is SMS, the phone number to send the challenge to */
    @SerialName(value = "phone_number") val phoneNumber: kotlin.String? = null

) {


}

