/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param showCompletionPage 
 * @param showLogo 
 */
@Serializable

data class VerifyV1Options (

    @SerialName(value = "show_completion_page") val showCompletionPage: kotlin.Boolean? = null,

    @SerialName(value = "show_logo") val showLogo: kotlin.Boolean? = null

) {


}

