/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WorkflowRequestConfigAnyOf1Data

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind Upload a new document and re-run the decision engine
 */
@Serializable

data class WorkflowRequestConfigAnyOf1 (

    @SerialName(value = "data") @Required val `data`: WorkflowRequestConfigAnyOf1Data,

    /* Upload a new document and re-run the decision engine */
    @SerialName(value = "kind") @Required val kind: WorkflowRequestConfigAnyOf1.Kind

) {

    /**
     * Upload a new document and re-run the decision engine
     *
     * Values: document
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "document") document("document");
    }

}

