/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DocumentRequestConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Upload a new document and re-run the decision engine
 *
 * @param businessConfigs 
 * @param configs 
 */
@Serializable

data class WorkflowRequestConfigDocumentData (

    @SerialName(value = "business_configs") @Required val businessConfigs: kotlin.collections.List<DocumentRequestConfig>,

    @SerialName(value = "configs") @Required val configs: kotlin.collections.List<DocumentRequestConfig>

) {


}

