ALTER TABLE tenant_api_keys ALTER COLUMN is_live SET DEFAULT TRUE;
ALTER TABLE ob_configurations ALTER COLUMN is_live SET DEFAULT TRUE;
ALTER TABLE onboardings ALTER COLUMN is_live SET DEFAULT TRUE;
ALTER TABLE user_vaults ALTER COLUMN is_live SET DEFAULT TRUE;