- name: Add Datadog repo
  copy:
    src: etc/yum.repos.d/datadog.repo
    dest: /etc/yum.repos.d/datadog.repo
    owner: root
    group: root
    mode: "0644"

- name: Install Datadog agent
  dnf:
    name: datadog-agent
    state: present
    update_cache: yes

- name: Enable Datadog agent
  systemd:
    name: datadog-agent
    enabled: yes
    state: stopped

- name: Add dd-agent to systemd-journal group
  user:
    name: dd-agent
    groups: systemd-journal
    append: yes

- name: Add Datadog agent config
  copy:
    src: etc/datadog-agent/datadog.yaml
    dest: /etc/datadog-agent/datadog.yaml
    owner: dd-agent
    group: dd-agent
    mode: "0640"

- name: Add Datadog journald config
  copy:
    src: etc/datadog-agent/conf.d/journald.d/conf.yaml
    dest: /etc/datadog-agent/conf.d/journald.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: "0640"

- name: Create nitro_enclaves.d directory
  file:
    path: /etc/datadog-agent/conf.d/nitro_enclaves.d
    state: directory
    mode: "0755"

- name: Add Datadog nitro_enclaves log collection config
  copy:
    src: etc/datadog-agent/conf.d/nitro_enclaves.d/conf.yaml
    dest: /etc/datadog-agent/conf.d/nitro_enclaves.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: "0640"
