secretsprovider: awskms://4e61ea01-1193-475e-82ee-e9639743efd6?region=us-east-1
encryptedkey: AQICAHierjVilfttqs7gag2b9al8BtcDNoSoVbmhJTJW+UU0GgGJuMYg+vgtHDUvKoWRioMaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj/Vfw62zBk4QWSoCAgEQgDsy8VwUnEWcqNAUnFt4UwBe7p2HQDRQCLrCkNyGqXAKPv6DtxBKkM88enMkwb5vgLpEt+v7FCq91wLy9A==
config:
  aws:region: us-east-1
  infra:constants:
    airplane:
      apiToken:
        secure: v1:87RDKonGk+sxikjQ:HDZ9lz9jGhBb1oQmYdyHvGX2BVGq6kkpGZ0MK5eLMgiAT9TnrZ/jUd/ZeoP5Jac3T9sW+rdDEaU=
      teamId: tea20220706zs7g4auu0i6
    containers:
      apiVersion: latest
      enclaveVersion: latest
    deletionProtection: false
    domain:
      assets: i-dev.onefp.net
      base: dev.onefootprint.com
      frontendBase: preview.onefootprint.com
      prefix: api.
    elastic:
      apiKey:
        secure: v1:kY0kR444OvfOf2Cr:gpD4whb9fFctHbhO+WxwZmXLo9Na0wc+zbkMtGUUIIlfr0FGEnM=
      apmAgentKey:
        secure: v1:/j+tQQrAZu22zElr:/U7YkTF6tIlg667BydswZUqKeGS9ByYAIXVhAUZdlzso0bY7+9RgFdVNXIi4cZxIKbYUhaQfqWT+CXow5Z7BpWJArnufqewpHo42pQ==
      apmEndpoint: 66e04f7b644c4d1c98e26e58b75de669.apm.us-east-2.aws.elastic-cloud.com:443
      heartbeatCloudId: dXMtZWFzdC0yLmF3cy5lbGFzdGljLWNsb3VkLmNvbSQ0MDZmYjczZWNlZjk0MDViODY5NzI3MmMwMDE1N2ExZCRjNGExNTAzOTBiMmU0M2UzODVlNWQ5OWY0YWRlYTc3OA==
      id: omacKoQBB6pi8-b5UVPY
    enclaveCertPCR8: 48cb393ec504192fb147ffb2818c2a00c8e2d74659b509cc449a48ffe1c257a266b6a9f9ac356c4cd38a6c11825dd600
    grafana:
      prometheusPushAuth:
        secure: v1:VdwOY1dTgkXEMk4W:i3PexS68jj8BwxdeHPPugmMQdl6ygvRTfBXb3K60uQwpJnuMy3N1HEERTa3t0tM2PBSJZbhCobPfOq2LtQG7ALfSKn32zpU75nujiT5KViRm7ZJWNHmaJ0kl15WZj/gRr/tvLsupnW8U/E3hAfkQoqN/IknVqW3qjeQdlL3oP88QHce1PBbAQM+oepcJlLFNrrVgaHdEqwsZJn/4
    idology:
      password:
        secure: v1:TBB0qHiZFw3gwDSW:nXXk0InuunaS/PY9J/bvSwVW4tD5OSFbtkrWWKm03o9FlvUePlLzFzgPoe5bixLpYr+Nb88rj5bJhtYRmUw=
      username:
        secure: v1:eE5PgSdUCZgqxINP:UskiQw508mR4BiZs+8NX5pxZYJEbIeQULdqjbURx0opNjV5SHA0E
    launchDarkly:
      launchDarklySdkKey:
        secure: v1:UDxCGOYtRW7Wj7hH:hf5y2xIB89mGz6PiW8tkKL5tDvTC1CmUAtwNTMURbfK0BvcOJymessVR0TbfptH4Bp/97+bU6hE=
    resources:
      cpuUnits: 256
      instances: 2
      memoryMB: 512
    rpId: onefootprint.com
    s3:
      documentImagesBucketNamePrefix: opaque-documents
    sendgrid:
      apiKey:
        secure: v1:rcN9jM7uB9KA3jjQ:H49idM5tdoD3IoVXyA2T5rSIbr5xvjxqJJXHYh7jCtKefwzpE7VakZc2VzMeAC3kAX4W0uRTdvI9iSKycCMFDAXYaLH5P715BhcWm9lr739sJ849wg==
      fromEmail: verify@noreply.onefootprint.com
    sentryUrl:
      secure: v1:Ppt53FIYgHl6OQN8:eV5cnm9Eqlo1XPMv/nXYd7V7HqgeizALAvdntlpsutbGsFln9Di1hnf8kMogZJj6JVw8ECgFDbo3WUYScuXlKfI6zmp7tjwYG5lO2M8/ycL1qBbJV+teR3zL
    socure:
      certificationApiKey:
        secure: v1:+aZfvN92irHYxlcW:L4orljMQLkT681z+XjSgYq2nkS+xKH4kKBnp/LXnAqeBDWSsHTXOWQfmj3SwftO8eLYy2A==
      productionApiKey:
        secure: v1:qvdpWPO/cjNqw2E9:8M9wZQ9/AzdQJEAg/sDilSmjFpzmQDqBHkbNrg7idxWmtFNlW95Mdkoj+VMkW1n33iRlzQ==
      sandboxApiKey:
        secure: v1:E/Vv2txLN2q/bNr8:dTiRlaKK+HXTMsYVV4xUwg4V3MUNBBMd52Q9iP6UKW3HjbyLAQTvO1T67TbUHu16+mKE8g==
    stripe:
      apiKey:
        secure: v1:CwuAHUsNqEspf1Cy:gGUJpTuJz+qJXLj8S1+XhxH06h4R57xymLwcO8gWD7ulKVCtRH7opUXAttjxIEBLb+XN0f4e0bkP3zslcWWLYITmsajivNyQXaG5sjCyp02voARB9V4N/SM6tGzkGf4EGPyVIV4T0P0e2sZDJ2oT9aZorJV3IqSsDvBN
    svix:
      authToken:
        secure: v1:62LpQHhq4cJ7TcAM:1pW6m/ihRXBX0d9wzlYpR3EMilk0E95608Zq9RPCrcFITw6rk7tlGKN1LMitafcFkvJ3IANJ8rj7ww==
    twilio:
      accountSid: AC675cd7f6557fb29b4fd3483fe49f6ff0
      apiKey:
        secure: v1:TddbkBlhZ7cYtOFN:ZsI5nrIil+wAJHlVffj8YcI8sn82QZuLxbb8E2ekbBg4TUAqffmXMvNoahef/hyzKnc=
      apiKeySecret:
        secure: v1:Mj1lvo0d2hHkitB4:bc7qwKQOSkoIe0WhqEJ3nRIqGK4Zht2klh96woc9EL3HNBp8R9GAcmxuE2TbVJYt
      integrationTestPhoneNumber: "+13393311410"
      phoneNumber: "+15105883668"
    workos:
      clientId: client_01G371B7G8Y43RETQKQ0D63F88
      defaultOrg: org_01G39KR1V1E52JEZV6BYNG590J
      secretKey:
        secure: v1:UrxmsAzi5youwRK1:Jlywwi1ZR82IGh3ZSJe58HQmEni8yL5+Ff/3DPQbcMbN5qE2wTJ1Yuye4vhADlRDaCaZf5kBhZGWC3Uxx4SZ47wmg8b+C123NVk8K1ieVGqO6IYF4HTKNI8KsQFyv6MA3QbD
  infra:serverTailscaleKey:
    secure: v1:YBhIVkjgy+ZPhPEJ:+AT6qs41kdA+kWaQUhMooSAC9ETulX8+7EX6MIpJR/gAQxEDlrCORv4oorz061KD5xwljnJ4pbPwPiaG5XUcRuCG+SwR2sKg6g==
  infra:tailscaleKey:
    secure: v1:/iSkf00jwJxz6Psy:oAWHYMOZlNg1Rk95qTownA3fb1RA+xtZg7oc6ma3Hv+74K5b84RUfkKrfGQ5IuKTEuFXgntMLfMTpCkOFaf4rP7SudP6PVKA
