secretsprovider: awskms://2d02d130-c1a6-4aab-b318-797f6d8253ee?region=us-east-1
encryptedkey: AQICAHgpY5Udo7qUEpCiqKUsoEkW+S7YqIg73iLR+fnkXhfd3wHP9rr2NW7SwYOE+iCCGYT7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5icsLWsDynzJkv8PAgEQgDuaWus35hln+Yyqbm+6R3SV3B4SWgUuQi7huWelhEe6x6vaSwdxkrmLbe9arjVDHnwPK8f1ymcQVHbeiA==
config:
  aws:region: us-east-1
  datadog:apiKey:
    secure: v1:0BmPOWIqd+L1r3f3:apsMuxb9Qg5/OoIAiAVjtMG3mmTzbwPEKyLCwQ4MJHB+6BHbC9QOcZPqnYD5hoLq
  datadog:appKey:
    secure: v1:VUpCO0wcRhqvFtC1:j4ocbHhC16odto566GpEbNwFD+jV+ZXUqaUWmIVb7rSRMT/6mvDmQNqbKN3cU5ca3OlQj5rEAY4=
  infra:constants:
    apple:
      deviceCheckPrivateKey:
        secure: v1:FcixnMvgpC0LACRd:t9xtI2M0q1tmxiOBjOvYeCTm4ZNj9HNYNqTcFC6KDX7IRteAqBmOU4UcNzGqRQDnbUlQf0s7EoO6zZ29X4MD32mFB2gNeItsPjGp0/eNkI7MjNv/GLw0mQepGpGvnSykgLIRWgQjlb7NGpmlm2shn2iVoLlM4VtN+ux460nCe+ByBrTTKFpNKX9YiIoSaOfzFC4oyht9TM3e3yeEsjS2pC6udMnX/XIQs2ftFLn5Z6+tsg9VIVhWgBOXvU4s6U4muxsmNysCEf2dZo4toj1tvgobRM5pk8SBYHNogNtk+JhSAhj4ElXGa47HcHl66WB66RNc0H5qgbkuRsiAdOAZmX78O3ox5HgluEMypyibRcWc
      keyId: 3A9LZR4SKP
    containers:
      apiVersion: latest
      enclaveVersion: latest
    cronTasks:
    - args:
      - create-overdue-watchlist-check-tasks
      - --limit=1000
      cpuUnits: 1024
      memoryMB: 2048
      name: overdue-watchlist
      schedule: cron(0 17 * * ? *)
    - args:
      - generate-invoices
      cpuUnits: 1024
      memoryMB: 2048
      name: generate-invoices
      schedule: cron(0 * * * ? *)
    db:
      deletionProtection: true
      maxAcus: 64
      minAcus: 16
    domain:
      assets: i.onefp.net
      base: api.onefootprint.com
      frontendBase: onefootprint.com
      prefix: ""
    elastic:
      apiKey:
        secure: v1:IuM1QjcgUc76uhEs:UzHJyEWwdT0iWEya1qfHfkIrYMESzQEZud0r70ygpwGW7V+9ptc=
      apmAgentKey:
        secure: v1:iFfrD+SyngCdEYCL:oeLX7nICFaJwJepbKblqZrR3d3s5gfkkzQ4PKkA/LQP/25cRHTvVlATLM3lwUTBxaEzgMikeMaNbdGpRuWD3IfJOVLzmyc7W6DMT3A==
      apmEndpoint: 66e04f7b644c4d1c98e26e58b75de669.apm.us-east-2.aws.elastic-cloud.com:443
      heartbeatCloudId: dXMtZWFzdC0yLmF3cy5lbGFzdGljLWNsb3VkLmNvbSQ0MDZmYjczZWNlZjk0MDViODY5NzI3MmMwMDE1N2ExZCRjNGExNTAzOTBiMmU0M2UzODVlNWQ5OWY0YWRlYTc3OA==
      id: omacKoQBB6pi8-b5UVPY
    enclave:
      certPCR8: e865feba7ebc599a657c329387caa88db6b487591e249b65a8edf0ddf7a2bcf269f3a7aa952f56741b18bdafe6766b96
      encryptionSealedIkek: 0102010078d60908a902e09468073c42ef11aec9d74032ecf5883ca24187d76552bdb7e5df01818033e8ec593ebe2c7db7fa15ebe0720000007e307c06092a864886f70d010706a06f306d020100306806092a864886f70d010701301e060960864801650304012e3011040cc7e25a39b26a33ccdecfc7bb020110803b380a6c909048507f2b0655d5ed175d679235f95b55aa3d0b6362c7896129e4efa7e7591a34d1277d2dc9a8c5a1e938273a0058222da35a4e271545
      resources:
        cid: 16
        cpus: 2
        instance: c5a.xlarge
        maxInstances: 50
        memory: 4096
        minInstances: 6
      signingSealedIkek: 0102010078d60908a902e09468073c42ef11aec9d74032ecf5883ca24187d76552bdb7e5df0107a5f5e67bd7aec30e66842e4f85feb10000007e307c06092a864886f70d010706a06f306d020100306806092a864886f70d010701301e060960864801650304012e3011040c477422e72e1878522107e16f020110803be8ab2eee542229e0f8dd2f128dc7e1bf980f324041570168d1f2a545481f787be91f6542526a87e3005a65d3228ecfa9404ad09518b5bf93fa59cb
    experian:
      authClientId:
        secure: v1:nKH6gAZEyJmAV3v+:i53g5Yqq4/bwPZTY2l8bKnebzJjcK2P2reAbWD8ySBi2uqumN1+EksM7Ay9sCvqT
      authClientSecret:
        secure: v1:ZIckzBZbX6QsUjAd:Rqpr3hcBNPESndBB+0PE5uiEJbbg/QQ2AFDtFcMrviE=
      authPassword:
        secure: v1:ZY2jHzMlxncFgLJx:efvXEuxdidwQeMkg4fXXV8AJnlTWraC17cKtD0KEaIsHXmwu
      authUsername:
        secure: v1:gN3HRu4vD+cyCn7o:0Qd3VH5hZvazjgnMs0bCp4lFnvls3HU3szF2RYNUEY3tsqbFN5A2WnSuDu3aJbxw
      crossCorePassword:
        secure: v1:pP4cIHpZc1xX/NAM:GZ9FU6JsFQYb2Xthx9lpBO/OFaDrD3+6REX8EvdwS/WSvgoO
      crossCoreSubscriberCode:
        secure: v1:e1/a6J/MlJzhfBEg:kXiwWudlbD+jXVnfaoz89OZ49Eri9Sc=
      crossCoreUsername:
        secure: v1:1VQb93G3yV3CAE4+:c9GLMxpylAjgRJg5h8GBoUvqmwq9myog
    fingerprint:
      fingerprintSdkKey:
        secure: v1:vM4Ei3NKCOggmINc:nCqVE0nBwd+A32iIVQterKi9D7qFbbgjAeDHaR9MuMB8+r68
    google:
      playIntegrityDecryptionKey:
        secure: v1:9qmtmq5TsShONzpa:FvswZZmBJ8HRvexIDldHXnQpthBkloKnDmsrrwMPsoQB5ghoqOSYqSI0lov5mgEin3WspfoFn4c8M2Fp
      playIntegrityVerificationKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEaqWPAmaBoLl5/UiQj+ZHHVtGjcIOnrJFQvLe1ef2Q2Sf3vrkNejer4HnZGkG2YWaq+HyMVBtFYk5qaoshVTdbw==
    grafana:
      prometheusPushAuth:
        secure: v1:FXHou6OrQ3YFgFlV:y9ey0toUO1aUQ4B+QXdvw+y85WeMdTl7igNw0gatavxDSwmwYiWkmJvt5ajN/JMaLA39Pmn7A/spSlnDSm+rLFOuhFtK80yuUkODTmwwHbx3o/Y1jltKgffcgEvmDpAwpWOaLXQUf8gL+s37OI8zTzxz4xHctvgJ0MtOvsOW9C5pLMMndAzwiARrKvuxUQ2pzexgWhDVoDgLHEg/
    honeycomb:
      apiKey:
        secure: v1:Ce0tjudyHFJXIVV3:ueTGniimIBurf6L9skMp201n5A3lZ4E8xszyltSCM00/dSWC/90=
    idology:
      fractionalPassword:
        secure: v1:kkVsTk2Eg0VcC1r4:PbFSccgDuJNXnDsAwM1CYZq7fAoeoiLjaWUTKc39Vcb1VvBafmYyMSVo6yw8MchyMgvoe+A6uxpeBgEtSCdm
      fractionalUsername:
        secure: v1:6DHMF69uw/GfiwdS:W4D6Qf46a4tFdrYAqIc7rWmQfcwcxdpwCo/S2InQ
      password:
        secure: v1:q92hc+VbZdquciLs:zGgLapi+yhg6psjd8RbW6mptrg6kzvx8NKfi0a1qa9jyByceiJ+2KFLEuKtDKkrpLEI7kqRNvSmsNrdiiLU=
      username:
        secure: v1:NEy9kUqxfuQKj1Xb:BQoRc+VSA5pdkg2mv79OwGSNnUEZ71DUfFOTN+lT7/lASQlbI0ol
    incode:
      incodeApiKey:
        secure: v1:37W0G9xCT0syBue4:tqukREyz1n31Q8b2MeYUyoG9Dl3m6nd31Vg2gAEkbAxCOMxZ68Z8AMTo74gx+yitacESDOxqdMo=
      incodeBaseUrl:
        secure: v1:wcySrPY9VMPQI4wo:4RZALbcJqUk0skGL0DvwOsb2Le0GKAdvIuiX0eYsSpnSGMJguL2PuD9e0gv5a0ks
      incodeDemoApiKey:
        secure: v1:NmOQJBplMbwr+6+U:kN47jfP+YNsb/sPrhGLIB9aeX2pgAxjfC/VY7rsOURQjVJE/3DkS8Yzl0Uw/yP+6pPeCwbT9h7k=
      incodeDemoBaseUrl:
        secure: v1:gGmXY7Z4S19Pe3rs:fi6y6nE1LTAuHqBxAlyWanaeIfvBMXs4eBdOUy27ssbOplBipqhbkqtKvNUzfHwG
      incodeDemoDocumentFlowId:
        secure: v1:bs+NjS664WSv2n45:Q8OvVuIrfaSTh3fmXtaHzR03/TAS0jK5T1a+VTGZGFp+h7TzGOgJzQ==
      incodeDemoSelfieFlowId:
        secure: v1:aE9j+DY+yvHsCBZ6:XEEmO8lCKRr2fqaiO4NPnbwWkx7U5pLTvcUPybptcnL7FXr63b0x1w==
      incodeDocumentFlowId:
        secure: v1:/hTQSCa+tLgorbRI:nG8KWxDpgtHIQwikwP5mNZxF1YnDtIQHvFTgHQUWbY2SBga9rY0orA==
      incodeSelfieFlowId:
        secure: v1:e8Gg1P6We6YtN9zP:SsT2WS903nZIwLrn60NUqu2RJgnmk+R2ORJn3dcALIhp/xZO/rlN/g==
    launchDarkly:
      launchDarklySdkKey:
        secure: v1:DrKn4q/fyK2+S+sJ:V/huczZNR1v2VKctscz6cCDZhx3nl8DyDBw+njGsun69ftSiRh7Z08QDoYAKBCyG9ItmpSiL0YY=
    lexis:
      password:
        secure: v1:M89G+jsg+97QAZ8o:NyS76wTAT+P+spvvgrNLpM43vxoBfZhTGzbY8w==
      userId:
        secure: v1:IgLfcPMF8meodCI3:W/FqpgAO8MkiZOCtwlBOjWi4LGtYjw==
    middesk:
      apiKey:
        secure: v1:WXNa8UEapgUz2KjX:hRZUhufEmcOhpzYggPFLHzCwK7oFnXjI+mWmTNZx0pWmhoIfO5HbSv0jJFp9AbVm
      baseUrl:
        secure: v1:dzUFaOSpvPFI9Tpt:8DtlgXBFIuL7FzuS7uhGLjD4BWbi6T8NJqy1YUe9eKblujsFyHkRbCAqHQ==
      webhookSecret:
        secure: v1:JwLRbuAPf0pSaGKC:UXrgvZZ1LmLXmmeJcWGekg40tnmEvCkKhj/cYVcVu4jRmHDxppMyTpZArO/D3Picu1rEGh2UgiAMTKZfSFzBTZo=
    neuro:
      apiKey:
        secure: v1:iKIx28wCAXMwkjAB:LsdkiIu8bqhWS4zX9TEGr/935oL8qaFinKeT5Tdi5eY5TFfXPtmG1nsDZufxHhkA+g==
      apiKeyTest:
        secure: v1:El9JuX14SRD+34/B:Y4vGbXddnQ3zl+vHcc8jKihlmF9l0OqxOj1hUCJv7YZSPYVgqbeMDQh3v7hicnyM1Q==
    openaiApiKey:
      secure: v1:+HiZvlcAp+99FP7D:afNMGxYpT3FL6RJu/6QsSrLAtGAjlmSFANNuMxdtIlkejK8CZMucv5qUQWqrKLx+wOmAqwfeDyMzlpBJyLcCKfJPZQ==
    resources:
      cpuUnits: 4096
      maxInstances: 50
      memoryMB: 16384
      minInstances: 6
      targetCpuUtilization: 60
      targetMemoryUtilization: 60
    rpId: onefootprint.com
    s3:
      documentImagesBucketNamePrefix: opaque-documents
    samba:
      apiKey:
        secure: v1:3SL0o90GDsXzb/Uf:AhC5wjV5+ZJxCINtnnnLUJJgEjh/hXzysYjTkNTzjpKhzbAyJG3mC7eqXjhkhXK0zQdR5HMPw+8=
      authPassword:
        secure: v1:gLjQhsl3ogut7dUM:p9TReXFzik/XSi9ViBEA0Y1baS04BjQjt4UDgBoCgjqYvodtvZY8HVqyae1CsXW3t+WxLu7pmvzsbiuv8c67JTx1bSVdRFGoUkJs5w3rV+s=
      authUsername:
        secure: v1:WX42PQYaqKZooKgG:n24qmp9R8MsgdBlF4hMrctXrkOgSjQE02Ci1r2dJaViNMhWs
      baseUrl:
        secure: v1:fN6o2R3sCQDBuQBO:+vfvTucB3erP5y87lQ+OCJryZTbsq4iBWvY5xFnXNEc634yv/Fx9Gke4KYqds9A=
    sendgrid:
      apiKey:
        secure: v1:bKv7D+zTxpPdjHoO:qfXikLY0jplLN/CmQ4/P0/Ts4akQLZttRFJKjW08xIEQDuFGW5DUK2VnihJq1OVtS0CgV81VJTeHdJfE5YesX4GCRVdO03bnR010AC5tJeyPnHPs/Q==
      fromEmail: verify@noreply.onefootprint.com
    sentryUrl:
      secure: v1:WtHZGm3z+ldCM2Hu:pGr/a63SHFQiYKm1Wa53xwNM0P268cqpgVIBfBlN2cJ/DUB15PebePtgF8eS+bERXNVsQP5Hw+8bViuhs0CgQfsErTvtE2DGRFcpzdNjCcRkrTMLAUjlXnav
    socure:
      certificationApiKey:
        secure: v1:hu3JSlQDBxn2W+wI:kawQei7qPaCswzA51+1I4VNbr273Wqs1OSNpH1iLAYuLtMhfTRNDHdgvGoo9SsoaR3z6Yg==
      productionApiKey:
        secure: v1:/ZIGrHtMus1VsKjO:GnyJ+C1FM+la2TDa9CZylt9HZ/fvjNwpN6VemWNjxX55xyvtbCHfDL6TjnzDmBa1o6Urhg==
      sandboxApiKey:
        secure: v1:WRoRIuzYLRosCaSz:ccesq8xPn8lzvmo0LPM7DQQhglEeCX9PlH/BseYHw/8OEJa2z1ZVgLceyqjOQ6OrsGSV6Q==
    stripe:
      apiKey:
        secure: v1:M7HjVZ81Nh2vF2/T:n//gfJmgaVdleXGkcfTQH7gkcNYjXO4H35yGWnsiuE9j7q7tOoChfHj45W+R7XefyQYNd7AAshREC6U7fyPC9p9KexaOgV6dslmrHZMCnno80/XsbLSsSRGIdHzT2fO/w1UTQa4YqB4UmVnBtf+47ybacSeIW+AbyJ8R
    stytch:
      project:
        secure: v1:l0L/r32xm9lkc/0X:x6iLKfZKYC/t3PEsW2Exj33dPlzCFsxihTK7FC86lFSSr3iMFK2aQU8htC6y6Vob9cyECKZXhIvV9WHu9ct6xVY=
      secret:
        secure: v1:19SFFEWJNJo3Ysr/:LCoxIl3CtwXJRx9wksqX1JU+23ZCRnl8AZmmvL6K2p47XKf5T8TYLHoiZgMGmI/6k4BGj1TvH2dOV1n7UrOvPA==
    svix:
      authToken:
        secure: v1:EB18OjkgS2mqtf8b:ZZXYDnFMxA/wEoYGA40l7yBLtMB7MsZFCbMg402qqSuY9faTZ4AM7yV0i9zOc8MTh8kbAOoI
    twilio:
      accountSid: ACa14b32002b6d99a8e6c3e5c6344a00ca
      apiKey:
        secure: v1:Md3FtwNwl+7bxKrr:ihwacs4t71LgGl8FlkIdS4XuCKbyvVEkaNmUku27OFcThcrr87SuH9GLz1RiTvezia4=
      apiKeySecret:
        secure: v1:6Sct1OQ1Y3A0QapO:dA7CqK0HR3NsmSDgJAR/kicJY7+i7k5KLfugEoCHIn1MqTsQ6BFOv0qKbqVWWT27
      phoneNumber: "+14152129648"
      whatsappOtpTemplateId: HX728369d784be2b98babfae0e399b8d1f
      whatsappSenderId: MGf4b90d6bc32195702ba16a4606f049bf
    twilioBackup:
      accountSid: AC675cd7f6557fb29b4fd3483fe49f6ff0
      apiKey:
        secure: v1:g/Buavshjo4oCE/9:iYXVkuHQxY8XO4HFDPvM69p/Xph/A6VZoYYtwgYJmN7Ofh9mwWxMUQAdl9cmckt25gM=
      apiKeySecret:
        secure: v1:WTH51OSrsdCEdap7:bIRwAeQZYkdPq0+VXdOeL2/A3eDYJ1/pruElC2LyDU/XMnZgQniODR9bWbfqGo44
      phoneNumber: "+15105883668"
      whatsappOtpTemplateId: HXeb04132acb5883c98bf6ff80dbeeb2b6
      whatsappSenderId: MG25d83f1f121913d74d8bc2ea96e35db6
    workerTasks:
    - args:
      - execute-tasks
      - --batch-size=50
      - --poll-period-ms=500
      cpuUnits: 1024
      memoryMB: 2048
      name: execute-tasks
    workos:
      clientId: client_01G371B7G8Y43RETQKQ0D63F88
      defaultOrg: org_01G39KR1V1E52JEZV6BYNG590J
      secretKey:
        secure: v1:qBwY9xkQ5AxOOFFR:nJs8FBGP1lGvhsAUJ/ANgv2PKoIWYJovYxCyLtDBWa24r+sDRpLxD7EC3z6ZWcVOlBb2hoYuR4vJobSyQ/3FBe7jPAFqLDJhrL9m6LEsX0NFg6iP/hYMKnPCqVfE+L2YaE5m
  infra:datadogApiKey:
    secure: v1:0BmPOWIqd+L1r3f3:apsMuxb9Qg5/OoIAiAVjtMG3mmTzbwPEKyLCwQ4MJHB+6BHbC9QOcZPqnYD5hoLq
  infra:honeycomb:
    apiKey:
      secure: v1:t/fTPilvkE289hWA:DoGjpZ/6qq/jI8FK9T7k+5eUwpQ+raqhPVB36GXR4f/RxGshmqk=
  infra:serverTailscaleKey:
    secure: v1:zRw0LH2Ah+YRTxmE:RHwU/0V0aUF3wesqLamjwk9c7cMWp4oCAuGkQ5MZHqPHW+dgEz0X0NQ9M8gof3YIlba2cFua6YOd2qlLHrCxSwP5UVmRMFIb
  infra:tailscaleKey:
    secure: v1:CAXjTeypjanGw1iz:Xy2dX8cvfnGNOfUlHVi4VHVBoR2bNMwUDd1PPAu/DpeowExqgeUGRqh6rCPw5yQ2q4lqFpnqSl2lFS6n58wFLNbf8r38X5Uz
  tailscale:oauthClientId: kwath66CNTRL
  tailscale:oauthClientSecret:
    secure: v1:MIC4lr+S2pN2mGSj:Xpe/RSz3JwA7Zp/rObBVo6bPNk76q9+IKod/TFcIn0NCkvIZ8w+zZdtav/LzZzVC5wAk3zMSTot5WHt28DLD+g7oU5FTRx8BEgxH
  tailscale:tailnet: onefootprint.com
