secretsprovider: awskms://alias/pulumi_secrets?region=us-east-1
encryptedkey: AQICAHierjVilfttqs7gag2b9al8BtcDNoSoVbmhJTJW+UU0GgGJuMYg+vgtHDUvKoWRioMaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj/Vfw62zBk4QWSoCAgEQgDsy8VwUnEWcqNAUnFt4UwBe7p2HQDRQCLrCkNyGqXAKPv6DtxBKkM88enMkwb5vgLpEt+v7FCq91wLy9A==
config:
  aws:region: us-east-1
  datadog:apiKey:
    secure: v1:qrIj6oPumKT7EcOa:bQ/WVSwrmVucwwj3cGN8SbP6MoXbOBC2bbEYb+mRpUBiY8rxmofqRFdufkyWw4sP
  datadog:appKey:
    secure: v1:05ky/WfsOxOVc27O:f0uOD4qJPZOITicyezH3gmm9MMsNPJ/JfyTOjph6YCpKF84n3rsWM00qwsvaSiY8mJmUZtDVJ/U=
  infra:constants:
    apple:
      deviceCheckPrivateKey:
        secure: v1:s7NbeVTk3C4I0YwL:m1UVvIk/x6tFafyU5lvrRhMwbjENM11OImtnaNyx0epPsxyKb/bsTjoAljd3FSdFVhu6LbZZAAgkcZja41iBlE3w1r4paxOswHRi+CjokBjevEFDCiM4DS+CqqP28BLu2sCRKAAjMeohlynPxnYln06TITB1E/voo46A/zvdIw6C6MN4N4Ur562wveFtwqhLYlcIxthrTKiZ69p18yOA6Z6Tq04x1Y2FWGAEMNa9lgbMbw8c8GDIbUS7LDPpixENLTVl4YFf0USGtcNFEyxVRKHdQl8cyhB8OaxNumAAlNYiUFFxvgMjeaqZQQbQBnSveiLCujX0qkdLYuR0ICxx5ELIhR7GxTRUIGKMtHdqWAFN
      keyId: 3A9LZR4SKP
    containers:
      apiVersion: latest
      enclaveVersion: latest
    cronTasks:
    - args:
      - create-overdue-watchlist-check-tasks
      - --limit=1000
      cpuUnits: 512
      memoryMB: 1024
      name: overdue-watchlist
      schedule: cron(0 17 * * ? *)
    db:
      deletionProtection: false
      maxAcus: 32
      minAcus: 4
    domain:
      assets: i-dev.onefp.net
      base: dev.onefootprint.com
      frontendBase: preview.onefootprint.com
      id2Base: dev.onefootprint.com
      id2Prefix: id2.
      idOrigin: id.preview.onefootprint.com
      prefix: api.
    elastic:
      apiKey:
        secure: v1:kY0kR444OvfOf2Cr:gpD4whb9fFctHbhO+WxwZmXLo9Na0wc+zbkMtGUUIIlfr0FGEnM=
      apmAgentKey:
        secure: v1:/j+tQQrAZu22zElr:/U7YkTF6tIlg667BydswZUqKeGS9ByYAIXVhAUZdlzso0bY7+9RgFdVNXIi4cZxIKbYUhaQfqWT+CXow5Z7BpWJArnufqewpHo42pQ==
      apmEndpoint: 66e04f7b644c4d1c98e26e58b75de669.apm.us-east-2.aws.elastic-cloud.com:443
      heartbeatCloudId: dXMtZWFzdC0yLmF3cy5lbGFzdGljLWNsb3VkLmNvbSQ0MDZmYjczZWNlZjk0MDViODY5NzI3MmMwMDE1N2ExZCRjNGExNTAzOTBiMmU0M2UzODVlNWQ5OWY0YWRlYTc3OA==
      id: omacKoQBB6pi8-b5UVPY
    enclave:
      certPCR8: 48cb393ec504192fb147ffb2818c2a00c8e2d74659b509cc449a48ffe1c257a266b6a9f9ac356c4cd38a6c11825dd600
      encryptionSealedIkek: 0102010078691c3df6e54c78ffe3c192c6d55f17bc23005299e722f6c6e7a30bba69f084c8013b8224781971f4202d96793eacfc5bdf0000007e307c06092a864886f70d010706a06f306d020100306806092a864886f70d010701301e060960864801650304012e3011040c2cd252c9d884e266883edfc8020110803bdb19897b8c5d74d6f798842ba57a6c5877251697f69e41b42f0702ee5414d3c68a21fda33281838909cb09a61a79d92776a403dda08fc96a1d93e1
      resources:
        instance: c5a.xlarge
        maxInstances: 4
        minInstances: 2
      signingSealedIkek: 0102010078691c3df6e54c78ffe3c192c6d55f17bc23005299e722f6c6e7a30bba69f084c8011b29da25d49e0ff8875c36a2df50e3a30000007e307c06092a864886f70d010706a06f306d020100306806092a864886f70d010701301e060960864801650304012e3011040ccd8f032a1bdcf8d452c32d99020110803bd3491c3f202b164e0adf1dd3856ff50a1ce6aa156def702c64b7e2dc1f7a272429904b34f54b3fd9739ec36292b1430d442e99e89b0c49d2c0296b
    experian:
      authClientId:
        secure: v1:unfbwS5zFVaOGfO9:/e9b9dCYCMsg5gZUMf41LP0=
      authClientSecret:
        secure: v1:ModTej1vm6xTBFMF:Aw9ylPiuaJku5hvLfL0xxcE=
      authPassword:
        secure: v1:+8Bjx1b4y1B7qSkl:/O/V1LBxcxC4jje7P+Pkgtg=
      authUsername:
        secure: v1:gwMHX176qoV6ots2:Om7CN9qC/Q2VCZWnPoeAu8o=
      crossCorePassword:
        secure: v1:P06WmGgWifwn8l3E:jJG+h7aHTsiJRjdjh2/TnFg=
      crossCoreSubscriberCode:
        secure: v1:Wki6tvPguF40QCSG:LmSJKHGtnYOVTaf4DA5DOBw=
      crossCoreUsername:
        secure: v1:zaOCGtKaEamTeTmm:xAwLlNGY0GVTYMELpjzxIiY=
    fingerprint:
      fingerprintSdkKey:
        secure: v1:ShqC3sYp5bwUGSIi:1Wcf0WjDOj6NSh2ZBOWffhqskNZVxExTOGkaDd/JDH5WdIvR
    google:
      playIntegrityDecryptionKey:
        secure: v1:Csjb7lPxnUdwMSpM:SZeFVWTVNAg8JUW1d/HgIeFKuYUkQBnzETvLRyTKdVbZBdR1tPZiUg7IF32aD0m4RpzANkKnQHyTPEFa
      playIntegrityVerificationKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEaqWPAmaBoLl5/UiQj+ZHHVtGjcIOnrJFQvLe1ef2Q2Sf3vrkNejer4HnZGkG2YWaq+HyMVBtFYk5qaoshVTdbw==
    grafana:
      prometheusPushAuth:
        secure: v1:VdwOY1dTgkXEMk4W:i3PexS68jj8BwxdeHPPugmMQdl6ygvRTfBXb3K60uQwpJnuMy3N1HEERTa3t0tM2PBSJZbhCobPfOq2LtQG7ALfSKn32zpU75nujiT5KViRm7ZJWNHmaJ0kl15WZj/gRr/tvLsupnW8U/E3hAfkQoqN/IknVqW3qjeQdlL3oP88QHce1PBbAQM+oepcJlLFNrrVgaHdEqwsZJn/4
    honeycomb:
      apiKey:
        secure: v1:x0zSJWGjGXy5N/8r:UfFqMqKMf6sCO9LLkl4d82oBxGYOdzRJYUailion7a5TaEqVueY=
      ephemeralApiKey:
        secure: v1:g2e85wuR8QP1jgJM:oHubF10POp7QIEIafYM6QOY+AwtvmMMAzKSByhVagmx40+kpUKE=
    idology:
      fractionalPassword:
        secure: v1:mp8/g1ishUpV++0P:cwGLEnx/X7/iwJALfSGlf8w=
      fractionalUsername:
        secure: v1:XOO66Xq6lLYCxovE:6180Q41gZnKkJ/4fKhyGOCQ=
      password:
        secure: v1:TBB0qHiZFw3gwDSW:nXXk0InuunaS/PY9J/bvSwVW4tD5OSFbtkrWWKm03o9FlvUePlLzFzgPoe5bixLpYr+Nb88rj5bJhtYRmUw=
      username:
        secure: v1:eE5PgSdUCZgqxINP:UskiQw508mR4BiZs+8NX5pxZYJEbIeQULdqjbURx0opNjV5SHA0E
    incode:
      incodeApiKey:
        secure: v1:H5nhKgfH0nMLUp8e:YUE2teYkDPFEsaohxczRC4nlgYz958HAsXea/GXOhbQARzrUNTvLYSTLO+Y2db41n+70B3R8eIc=
      incodeBaseUrl:
        secure: v1:e/D91lOrER6lhRLR:/kc3JjCgTyA2DTIwOHVzZN0pKVMPQlxgAkVFVIusxG1lnL69aV/mdvuAvTgf/tSj
      incodeDemoApiKey:
        secure: v1:qkH4u5kyompAdYfp:KBEnGVSGc4wQlPrRktihLs2v6b3JIY3nVscN6SmQEBRGeoCarl/wb2PLmtnhCtzxaoiwc0piV08=
      incodeDemoBaseUrl:
        secure: v1:HC5NzX2KjdE1QeRd:KQL0upuqVHRdVVcKP0pOUzAqEXXqt/SEn/oC45rbDO/nPdEPN1OZQX/ru6v/1UpK
      incodeDemoDocumentFlowId:
        secure: v1:hqQI05F8dcy7W/2i:qrjYjhwhYAXD0efnC1wVXQUoHyI4AXC1C17kMnX66uZ6KCjNjTfWyg==
      incodeDemoSelfieFlowId:
        secure: v1:t1eBJ3QmQt9FVcMk:T6pqCW/rBZHtbO7YbqjKnJj8Q6Gc9+o8gEAuF7Q1LUuoiQ7zFTAWsA==
      incodeDocumentFlowId:
        secure: v1:XEcXshrWL1DuUfvU:9wjQdVCn9557clzq1Ii1QIZonzbxS+UWULOps5KlNIf0AcpV9RmWfQ==
      incodeSelfieFlowId:
        secure: v1:1bDBDR1/+vTSDnkN:To8lU/E3uNwVHyc6lYuCw/vVbg/XnAOy4IQRBt62Jg1LiloVLc28Sw==
    launchDarkly:
      launchDarklySdkKey:
        secure: v1:UDxCGOYtRW7Wj7hH:hf5y2xIB89mGz6PiW8tkKL5tDvTC1CmUAtwNTMURbfK0BvcOJymessVR0TbfptH4Bp/97+bU6hE=
    lexis:
      password:
        secure: v1:xFtWxpCbaCKCdWTm:Imsm4P+kt/c5LV0/3HRJvsufwnpOLxpImuAKWw==
      userId:
        secure: v1:+hcMwHOl3/HyiPEo:8/1F89myIlhyG5cndcAUnMaHmapYgg==
    middesk:
      apiKey:
        secure: v1:xtdaUeliAIgFqHjM:SoQBIALTVJdwz/fpovGd1nvNQLpJoz4Q85B+AS2LvmdqgKhAiiLUrAemlAfK0X/X
      baseUrl:
        secure: v1:KOd46J2re36iezi8:4tlk/l6S81SZ7HSbCX718nccBoQ9fdrPKVRGfHBp1V1ozf3qWEQ74U6mwv8YYqtvOAOz
      webhookSecret:
        secure: v1:pEdCWHncA7z7jfpm:Y/925Y6RiRhHoHPHx+SQDmCmyCHR67OWPQQEn0qcAfS6LHxBUXisSvn7Wfmdl7wtcpOBcpV3I1Gkng==
    neuro:
      apiKey:
        secure: v1:PE+0+YWFXIu38AN6:/Cg0fli8qt45dtfYHups9Ba+6oagHDX9bbjrR41i8EBGclFPHG5dQ4KFseqg4H5eJA==
      apiKeyTest:
        secure: v1:8idImQrp1iNa9PA/:wbzYF/kBn1w5utO10/NjpQvnk71fL7/6iL6Lp9nVNPJI9rxXpSYEiMYGYpTImaFe7g==
    openaiApiKey:
      secure: v1:du0pxYZ+lwWtlim8:hSjpDmZFOnSWbcBmaMWPTNsNEKs4hDoZ1Zg+wSwBiVJyVFfREo3n3+qwg1HulbTMCuDS0eCa0/vnHi/dpVUCvezaAg==
    resources:
      cpuUnits: 1024
      maxInstances: 6
      memoryMB: 2048
      minInstances: 2
      targetCpuUtilization: 60
      targetMemoryUtilization: 60
    rpId: onefootprint.com
    s3:
      documentImagesBucketNamePrefix: opaque-documents
    samba:
      apiKey:
        secure: v1:r50Ntk71dRghYE83:0io5yUJ67Cjw5zLqixMaY3OtdAeXssQHx+rMM9mufQ2h0K7mZtuntxAt1i0denk+mPAFE/sxITY=
      authPassword:
        secure: v1:DELWgeDl7qRrcbsd:1ngP4uwZPufmAwN4cbBGcM2UiWQ/zZ3g59kLr90/zphMQThTgF9FlByaIPtzm7gTFjT9km1Kv8URqoC1qdMtM/8g7Vj3xdjJCIFjJz7T3Cs=
      authUsername:
        secure: v1:DZO6XcP3qYmtYEMv:uUFSxYiDnG7nsPYQgcDWQwHUKbL/Hr48jvApOupQoEjnz+qk
      baseUrl:
        secure: v1:eIAbVTzjPgptHV6K:KGbnPj7NachTFecPKPcAom5AK5n10Xb4wZ9nxs+tlQVF0G7+zCszi+GJWB6gSnk=
    sendgrid:
      apiKey:
        secure: v1:rcN9jM7uB9KA3jjQ:H49idM5tdoD3IoVXyA2T5rSIbr5xvjxqJJXHYh7jCtKefwzpE7VakZc2VzMeAC3kAX4W0uRTdvI9iSKycCMFDAXYaLH5P715BhcWm9lr739sJ849wg==
      fromEmail: verify@noreply.onefootprint.com
    sentilink:
      authPassword:
        secure: v1:iq3XA8NBL9h0d+P2:VDoBpynv35wVnDzMLYTc+O3q243ho2GIOPbPDlC9roVvviYIgkTmwiFKemiwmn0A
      authUsername:
        secure: v1:RMrHA2ssWWjSEBYN:Z14d0hiJS0HfffcpomYcDzP+7syQMq312ahCK5JD4tWo8dV1/N5+iGBT
      baseUrl:
        secure: v1:xwy8zqz360nOEV3g:yAm46byKCyRNxxHgVkIECX0EZuzuvAbhmEEaMBU+JyaDmnk59uH24z1t+yL6PCfF0A==
    socure:
      certificationApiKey:
        secure: v1:+aZfvN92irHYxlcW:L4orljMQLkT681z+XjSgYq2nkS+xKH4kKBnp/LXnAqeBDWSsHTXOWQfmj3SwftO8eLYy2A==
      productionApiKey:
        secure: v1:qvdpWPO/cjNqw2E9:8M9wZQ9/AzdQJEAg/sDilSmjFpzmQDqBHkbNrg7idxWmtFNlW95Mdkoj+VMkW1n33iRlzQ==
      sandboxApiKey:
        secure: v1:E/Vv2txLN2q/bNr8:dTiRlaKK+HXTMsYVV4xUwg4V3MUNBBMd52Q9iP6UKW3HjbyLAQTvO1T67TbUHu16+mKE8g==
    stripe:
      apiKey:
        secure: v1:CwuAHUsNqEspf1Cy:gGUJpTuJz+qJXLj8S1+XhxH06h4R57xymLwcO8gWD7ulKVCtRH7opUXAttjxIEBLb+XN0f4e0bkP3zslcWWLYITmsajivNyQXaG5sjCyp02voARB9V4N/SM6tGzkGf4EGPyVIV4T0P0e2sZDJ2oT9aZorJV3IqSsDvBN
    stytch:
      project:
        secure: v1:yt366i0AkYbLpf3A:b28iSB/HK2bjF1M4n/rgIo2dYzHGM6L6Hhtubr/k5kjaFrddE28nWICKLTrQSi4qu7sY4xmMMkvDLUvEtXGONUs=
      secret:
        secure: v1:lG0D0HlmMPLEm1Gk:wwDrUmrfM1wDcJU67r6IzEi4pqpMCZp06vpzRjGGDYnHmBPZ2GidRJmN0GTAV/tcBSOFt7gicJufRK1KMY1tGA==
    svix:
      authToken:
        secure: v1:62LpQHhq4cJ7TcAM:1pW6m/ihRXBX0d9wzlYpR3EMilk0E95608Zq9RPCrcFITw6rk7tlGKN1LMitafcFkvJ3IANJ8rj7ww==
    twilio:
      accountSid: AC675cd7f6557fb29b4fd3483fe49f6ff0
      apiKey:
        secure: v1:TddbkBlhZ7cYtOFN:ZsI5nrIil+wAJHlVffj8YcI8sn82QZuLxbb8E2ekbBg4TUAqffmXMvNoahef/hyzKnc=
      apiKeySecret:
        secure: v1:Mj1lvo0d2hHkitB4:bc7qwKQOSkoIe0WhqEJ3nRIqGK4Zht2klh96woc9EL3HNBp8R9GAcmxuE2TbVJYt
      authKeyWebhooks:
        secure: v1:4XVVVilb3hupRtqK:CXfkj+lyLFli8HN+YfWep024xh1jHZYyqDzK9LuW0he0mX+JyzAcMEA1Qxeia5MS
      phoneNumber: "+15105883668"
      whatsappOtpTemplateId: HXeb04132acb5883c98bf6ff80dbeeb2b6
      whatsappSenderId: MG25d83f1f121913d74d8bc2ea96e35db6
    twilioBackup:
      accountSid: AC675cd7f6557fb29b4fd3483fe49f6ff0
      apiKey:
        secure: v1:TddbkBlhZ7cYtOFN:ZsI5nrIil+wAJHlVffj8YcI8sn82QZuLxbb8E2ekbBg4TUAqffmXMvNoahef/hyzKnc=
      apiKeySecret:
        secure: v1:Mj1lvo0d2hHkitB4:bc7qwKQOSkoIe0WhqEJ3nRIqGK4Zht2klh96woc9EL3HNBp8R9GAcmxuE2TbVJYt
      authKeyWebhooks:
        secure: v1:4XVVVilb3hupRtqK:CXfkj+lyLFli8HN+YfWep024xh1jHZYyqDzK9LuW0he0mX+JyzAcMEA1Qxeia5MS
      phoneNumber: "+15105883668"
      whatsappOtpTemplateId: HXeb04132acb5883c98bf6ff80dbeeb2b6
      whatsappSenderId: MG25d83f1f121913d74d8bc2ea96e35db6
    workerTasks:
    - args:
      - execute-tasks
      - --batch-size=100
      - --poll-period-ms=1000
      cpuUnits: 512
      memoryMB: 1024
      name: execute-tasks
    - args:
        - vault-dr-worker
        - --manifest-batch-size=1024
        - --blob-batch-size=2048
        - --poll-period-ms=5000
        - --record-task-concurrency=64
        - --manifest-task-concurrency=64
      cpuUnits: 1024
      memoryMB: 2048
      name: vault-dr
    workos:
      clientId: client_01G371B7G8Y43RETQKQ0D63F88
      defaultOrg: org_01G39KR1V1E52JEZV6BYNG590J
      secretKey:
        secure: v1:UrxmsAzi5youwRK1:Jlywwi1ZR82IGh3ZSJe58HQmEni8yL5+Ff/3DPQbcMbN5qE2wTJ1Yuye4vhADlRDaCaZf5kBhZGWC3Uxx4SZ47wmg8b+C123NVk8K1ieVGqO6IYF4HTKNI8KsQFyv6MA3QbD
  infra:datadogApiKey:
    secure: v1:qrIj6oPumKT7EcOa:bQ/WVSwrmVucwwj3cGN8SbP6MoXbOBC2bbEYb+mRpUBiY8rxmofqRFdufkyWw4sP
  infra:honeycomb:
    apiKey:
      secure: v1:OvsQ2EQpwZgDtXX2:gnCIfaNIoMI6yGAeDyc0qBFzp9f3WgptY1RBtOtR9mZBEAsf2bo=
  infra:neon:
    apiKey:
      secure: v1:DTxrP6ue5m+XRElP:F0NmXy8+hG3p2oIqjwBxQReI8O5HHWNRMMYWm2gaSyacA6PMAEes/wjY6fuXfXximCNjjKsBsfw4YJr2BbSAf2/p82rljaWgCTMFHUd1z58=
  infra:serverTailscaleKey:
    secure: v1:c0ihJZFCM5gTow8e:glADH70XuRsaKrdMImkUI2YrH5wp2tKJf2ACtVq8Hs7AuJsXL7rXbPjYiZKj7MIiteDmkz2ibyxMHazegolM5RdpqDoUoq/V
  infra:tailscaleKey:
    secure: v1:LugjtwdSpINaX+pN:qYThPPztuSbW9vNGWJ4y3O/zzNzPBfQ7oNFAdd+LvEsFuDzeccSsOdDp3QN+6JjPsH7Heq7TtMjMN9GZYu/nCYcygNJeJBv7
  tailscale:oauthClientId: kGLbCo3CNTRL
  tailscale:oauthClientSecret:
    secure: v1:I4bkKTmiXjae5UgT:rMQlp203ERmmLOs4QOh7F+5DEkQPuZDwGg6gIDZ/n2s8ZaOTiJY1asp0rVr2UjPojcNvWqohHpTyNTNtDc1/0uD9/3s05RPo9bN/
  tailscale:tailnet: onefootprint.com
