secretsprovider: awskms://2d02d130-c1a6-4aab-b318-797f6d8253ee?region=us-east-1
encryptedkey: AQICAHgpY5Udo7qUEpCiqKUsoEkW+S7YqIg73iLR+fnkXhfd3wHP9rr2NW7SwYOE+iCCGYT7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5icsLWsDynzJkv8PAgEQgDuaWus35hln+Yyqbm+6R3SV3B4SWgUuQi7huWelhEe6x6vaSwdxkrmLbe9arjVDHnwPK8f1ymcQVHbeiA==
config:
  aws:region: us-east-1
  infra:constants:
    airplane:
      apiToken:
        secure: v1:55HGj2SicsoDxPjb:vzL+Naq2v8YsHrULZACPMycL36JsouJlrIonJJyFZFV47PjOq2qFMXuNdARsKzIRiqIOdxrqTBQ=
      teamId: tea20220706zs7g4auu0i6
    containers:
      apiVersion: latest
      enclaveVersion: latest
    deletionProtection: true
    domain:
      assets: i.onefp.net
      base: api.onefootprint.com
      frontendBase: onefootprint.com
      prefix: ''
    elastic:
      apiKey:
        secure: v1:IuM1QjcgUc76uhEs:UzHJyEWwdT0iWEya1qfHfkIrYMESzQEZud0r70ygpwGW7V+9ptc=
      apmAgentKey:
        secure: v1:iFfrD+SyngCdEYCL:oeLX7nICFaJwJepbKblqZrR3d3s5gfkkzQ4PKkA/LQP/25cRHTvVlATLM3lwUTBxaEzgMikeMaNbdGpRuWD3IfJOVLzmyc7W6DMT3A==
      apmEndpoint: 66e04f7b644c4d1c98e26e58b75de669.apm.us-east-2.aws.elastic-cloud.com:443
      heartbeatCloudId: dXMtZWFzdC0yLmF3cy5lbGFzdGljLWNsb3VkLmNvbSQ0MDZmYjczZWNlZjk0MDViODY5NzI3MmMwMDE1N2ExZCRjNGExNTAzOTBiMmU0M2UzODVlNWQ5OWY0YWRlYTc3OA==
      id: omacKoQBB6pi8-b5UVPY
    enclaveCertPCR8: e865feba7ebc599a657c329387caa88db6b487591e249b65a8edf0ddf7a2bcf269f3a7aa952f56741b18bdafe6766b96
    grafana:
      prometheusPushAuth:
        secure: v1:FXHou6OrQ3YFgFlV:y9ey0toUO1aUQ4B+QXdvw+y85WeMdTl7igNw0gatavxDSwmwYiWkmJvt5ajN/JMaLA39Pmn7A/spSlnDSm+rLFOuhFtK80yuUkODTmwwHbx3o/Y1jltKgffcgEvmDpAwpWOaLXQUf8gL+s37OI8zTzxz4xHctvgJ0MtOvsOW9C5pLMMndAzwiARrKvuxUQ2pzexgWhDVoDgLHEg/
    idology:
      password:
        secure: v1:uUrtEHQdUH9reQE/:+x3knOg6qN3Sm9nPd29n/cHW0ceb0RedNNasUWXvHdn3GDH6Pkn1Zefn5YnBP556aIH5aCILRzfy3ifZXTVg
      username:
        secure: v1:vqDUmfCNbHUHTrzU:Gylq4WsOKql3sK+7O05PpkjakU+LS2cHE2zL1TPF
    launchDarkly:
      launchDarklySdkKey:
        secure: v1:Ejh/oU+Ev4JTICIn:fEH+pIJ8Ekb258tFuoTMdU7hOw75grl5XniVgeGFOHcNCUgbSYalBuPQyc8ICbOQLuowMHQDF9U=
    resources:
      cpuUnits: 2048
      instances: 2
      memoryMB: 4096
    rpId: onefootprint.com
    s3:
      documentImagesBucketNamePrefix: opaque-documents
    sendgrid:
      apiKey:
        secure: v1:bKv7D+zTxpPdjHoO:qfXikLY0jplLN/CmQ4/P0/Ts4akQLZttRFJKjW08xIEQDuFGW5DUK2VnihJq1OVtS0CgV81VJTeHdJfE5YesX4GCRVdO03bnR010AC5tJeyPnHPs/Q==
      fromEmail: verify@noreply.onefootprint.com
    sentryUrl:
      secure: v1:WtHZGm3z+ldCM2Hu:pGr/a63SHFQiYKm1Wa53xwNM0P268cqpgVIBfBlN2cJ/DUB15PebePtgF8eS+bERXNVsQP5Hw+8bViuhs0CgQfsErTvtE2DGRFcpzdNjCcRkrTMLAUjlXnav
    socure:
      certificationApiKey:
        secure: v1:hu3JSlQDBxn2W+wI:kawQei7qPaCswzA51+1I4VNbr273Wqs1OSNpH1iLAYuLtMhfTRNDHdgvGoo9SsoaR3z6Yg==
      productionApiKey:
        secure: v1:/ZIGrHtMus1VsKjO:GnyJ+C1FM+la2TDa9CZylt9HZ/fvjNwpN6VemWNjxX55xyvtbCHfDL6TjnzDmBa1o6Urhg==
      sandboxApiKey:
        secure: v1:WRoRIuzYLRosCaSz:ccesq8xPn8lzvmo0LPM7DQQhglEeCX9PlH/BseYHw/8OEJa2z1ZVgLceyqjOQ6OrsGSV6Q==
    twilio:
      accountSid: AC675cd7f6557fb29b4fd3483fe49f6ff0
      apiKey:
        secure: v1:g/Buavshjo4oCE/9:iYXVkuHQxY8XO4HFDPvM69p/Xph/A6VZoYYtwgYJmN7Ofh9mwWxMUQAdl9cmckt25gM=
      apiKeySecret:
        secure: v1:WTH51OSrsdCEdap7:bIRwAeQZYkdPq0+VXdOeL2/A3eDYJ1/pruElC2LyDU/XMnZgQniODR9bWbfqGo44
      integrationTestPhoneNumber: '+13393311410'
      phoneNumber: '+15105883668'
    workos:
      clientId: client_01G371B7G8Y43RETQKQ0D63F88
      defaultOrg: org_01G39KR1V1E52JEZV6BYNG590J
      secretKey:
        secure: v1:qBwY9xkQ5AxOOFFR:nJs8FBGP1lGvhsAUJ/ANgv2PKoIWYJovYxCyLtDBWa24r+sDRpLxD7EC3z6ZWcVOlBb2hoYuR4vJobSyQ/3FBe7jPAFqLDJhrL9m6LEsX0NFg6iP/hYMKnPCqVfE+L2YaE5m
    svix:
      authToken:
        secure: v1:EB18OjkgS2mqtf8b:ZZXYDnFMxA/wEoYGA40l7yBLtMB7MsZFCbMg402qqSuY9faTZ4AM7yV0i9zOc8MTh8kbAOoI
  infra:serverTailscaleKey:
    secure: v1:74fYef0kxnzqqVdG:dI4iBlokPSB9a81jK25wCB0bxARp1Mp3oEJ2N4Gsgek4eQ9PuNTBOpaan6UK8zX5djbZHm7UBoN2YUF0QCO0yBeUt1b2oDtl
  infra:tailscaleKey:
    secure: v1:yMtykcvg7+KpmJH2:uovCcKOtdANStsy+dUD0MkaSjKh3Uh6AHXz1CxR9yuKDWcNIWmYbiCSXFp8uCrelR48AVEzLb8zvQMLzUnoUTru+Ir8ksc2k
