import { CountryCode3, IdDocType } from '@onefootprint/types';

const AcceptedIdDocTypesByCountry: Record<CountryCode3, IdDocType[]> = {
  USA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  AFG: [IdDocType.passport],
  ALA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ALB: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  DZA: [IdDocType.passport],
  ASM: [IdDocType.driversLicense],
  AND: [IdDocType.passport, IdDocType.driversLicense],
  AGO: [IdDocType.passport, IdDocType.driversLicense],
  AIA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ATG: [IdDocType.passport, IdDocType.driversLicense],
  ARG: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ARM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ABW: [IdDocType.driversLicense],
  AUS: [IdDocType.passport, IdDocType.idCard],
  AUT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  AZE: [IdDocType.passport],
  BHS: [IdDocType.passport, IdDocType.driversLicense],
  BHR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BGD: [IdDocType.passport, IdDocType.driversLicense],
  BRB: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BLR: [IdDocType.passport, IdDocType.driversLicense],
  BEL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BLZ: [IdDocType.passport, IdDocType.driversLicense],
  BEN: [IdDocType.passport],
  BMU: [IdDocType.passport, IdDocType.driversLicense],
  BTN: [IdDocType.passport],
  BOL: [IdDocType.passport, IdDocType.idCard],
  BIH: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BWA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BVT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BRA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  IOT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BRN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BGR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BFA: [IdDocType.passport, IdDocType.idCard],
  BDI: [IdDocType.passport],
  KHM: [IdDocType.passport, IdDocType.driversLicense],
  CMR: [IdDocType.passport, IdDocType.idCard],
  CAN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CPV: [IdDocType.passport],
  CYM: [IdDocType.driversLicense],
  CAF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TCD: [IdDocType.passport],
  CHL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CHN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CXR: [IdDocType.idCard, IdDocType.driversLicense],
  CCK: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  COL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  COM: [IdDocType.passport],
  COG: [IdDocType.passport],
  COK: [IdDocType.driversLicense],
  CRI: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CIV: [IdDocType.passport],
  HRV: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CUB: [IdDocType.passport],
  CUW: [IdDocType.driversLicense],
  CYP: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CZE: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  COD: [IdDocType.passport],
  DNK: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  DJI: [IdDocType.passport],
  DMA: [IdDocType.passport],
  DOM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ECU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  EGY: [IdDocType.passport, IdDocType.idCard],
  SLV: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GNQ: [IdDocType.passport],
  ERI: [IdDocType.passport],
  EST: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ETH: [IdDocType.passport],
  FLK: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  FRO: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  FJI: [IdDocType.passport, IdDocType.driversLicense],
  FIN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  FRA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GUF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PYF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ATF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GAB: [IdDocType.passport],
  GMB: [IdDocType.passport],
  GEO: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  DEU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GHA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GIB: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GRC: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GRL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GRD: [IdDocType.passport, IdDocType.driversLicense],
  GLP: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GUM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GTM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GGY: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GIN: [IdDocType.passport],
  GNB: [IdDocType.passport],
  GUY: [IdDocType.passport],
  HTI: [IdDocType.passport, IdDocType.idCard],
  HMD: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  VAT: [IdDocType.passport],
  HND: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  HKG: [IdDocType.idCard],
  HUN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ISL: [IdDocType.passport, IdDocType.driversLicense],
  IND: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  IDN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  IRN: [IdDocType.passport],
  IRQ: [IdDocType.passport],
  IRL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  IMN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ISR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ITA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  JAM: [IdDocType.passport, IdDocType.driversLicense],
  JPN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  JEY: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  JOR: [IdDocType.passport, IdDocType.idCard],
  KAZ: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  KEN: [IdDocType.passport, IdDocType.idCard],
  KIR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  KWT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  KGZ: [IdDocType.passport, IdDocType.driversLicense],
  LAO: [IdDocType.passport],
  LVA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  LBN: [IdDocType.passport],
  LSO: [IdDocType.passport],
  LBR: [IdDocType.passport],
  LBY: [IdDocType.passport],
  LIE: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  LTU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  LUX: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MAC: [IdDocType.idCard],
  MDG: [IdDocType.passport],
  MWI: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MYS: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MDV: [IdDocType.passport],
  MLI: [IdDocType.passport],
  MLT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MHL: [IdDocType.passport],
  MTQ: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MRT: [IdDocType.passport, IdDocType.idCard],
  MUS: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MYT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MEX: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  FSM: [IdDocType.passport],
  MDA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MCO: [IdDocType.passport, IdDocType.idCard],
  MNG: [IdDocType.passport, IdDocType.driversLicense],
  MNE: [IdDocType.passport, IdDocType.idCard],
  MSR: [IdDocType.passport],
  MAR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MOZ: [IdDocType.passport, IdDocType.idCard],
  MMR: [IdDocType.passport, IdDocType.driversLicense],
  NAM: [IdDocType.passport],
  NRU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  NPL: [IdDocType.passport],
  NLD: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  NCL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  NZL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  NIC: [IdDocType.passport, IdDocType.idCard],
  NER: [IdDocType.passport],
  NGA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  NIU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  NFK: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MNP: [IdDocType.driversLicense],
  NOR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  OMN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PAK: [IdDocType.passport, IdDocType.idCard],
  PLW: [IdDocType.passport],
  PSE: [IdDocType.passport],
  PAN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PNG: [IdDocType.passport],
  PRY: [IdDocType.passport, IdDocType.idCard],
  PER: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PHL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PCN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  POL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PRT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  PRI: [IdDocType.idCard, IdDocType.driversLicense],
  QAT: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  MKD: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  REU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ROU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  RUS: [IdDocType.passport, IdDocType.driversLicense],
  RWA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  BLM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SHN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  KNA: [IdDocType.passport, IdDocType.driversLicense],
  LCA: [IdDocType.passport, IdDocType.driversLicense],
  MAF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SPM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  VCT: [IdDocType.passport],
  WSM: [IdDocType.passport],
  SMR: [IdDocType.passport],
  STP: [IdDocType.passport],
  SAU: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SEN: [IdDocType.passport, IdDocType.idCard],
  SRB: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SYC: [IdDocType.passport],
  SLE: [IdDocType.passport],
  SGP: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SXM: [IdDocType.driversLicense],
  SVK: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SVN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SLB: [IdDocType.passport],
  SOM: [IdDocType.passport],
  ZAF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SGS: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  KOR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SSD: [IdDocType.passport],
  ESP: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  LKA: [IdDocType.passport, IdDocType.driversLicense],
  SUR: [IdDocType.passport],
  SJM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SWZ: [IdDocType.passport],
  SWE: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  CHE: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  SYR: [IdDocType.passport],
  TWN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TJK: [IdDocType.passport],
  TZA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  THA: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TLS: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TGO: [IdDocType.passport],
  TKL: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TON: [IdDocType.passport, IdDocType.idCard],
  TTO: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TUN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TUR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  TKM: [IdDocType.passport],
  TCA: [IdDocType.driversLicense],
  TUV: [IdDocType.passport],
  UGA: [IdDocType.passport, IdDocType.driversLicense],
  UKR: [IdDocType.passport, IdDocType.driversLicense],
  ARE: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  GBR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  UMI: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  URY: [IdDocType.passport, IdDocType.idCard],
  UZB: [IdDocType.passport],
  VUT: [IdDocType.driversLicense],
  VEN: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  VNM: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  VIR: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  VGB: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  WLF: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  ESH: [IdDocType.passport, IdDocType.idCard, IdDocType.driversLicense],
  YEM: [IdDocType.passport],
  ZMB: [IdDocType.passport, IdDocType.driversLicense],
  ZWE: [IdDocType.passport],
};

export default AcceptedIdDocTypesByCountry;
