import { CountryCode3, IdScanDocType } from '@onefootprint/types';

const AcceptedIdDocTypesByCountry: Record<CountryCode3, IdScanDocType[]> = {
  USA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  AFG: [IdScanDocType.passport],
  ALA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ALB: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  DZA: [IdScanDocType.passport],
  ASM: [IdScanDocType.driversLicense],
  AND: [IdScanDocType.passport, IdScanDocType.driversLicense],
  AGO: [IdScanDocType.passport, IdScanDocType.driversLicense],
  AIA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ATG: [IdScanDocType.passport, IdScanDocType.driversLicense],
  ARG: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ARM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ABW: [IdScanDocType.driversLicense],
  AUS: [IdScanDocType.passport, IdScanDocType.idCard],
  AUT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  AZE: [IdScanDocType.passport],
  BHS: [IdScanDocType.passport, IdScanDocType.driversLicense],
  BHR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BGD: [IdScanDocType.passport, IdScanDocType.driversLicense],
  BRB: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BLR: [IdScanDocType.passport, IdScanDocType.driversLicense],
  BEL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BLZ: [IdScanDocType.passport, IdScanDocType.driversLicense],
  BEN: [IdScanDocType.passport],
  BMU: [IdScanDocType.passport, IdScanDocType.driversLicense],
  BTN: [IdScanDocType.passport],
  BOL: [IdScanDocType.passport, IdScanDocType.idCard],
  BIH: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BWA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BVT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BRA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  IOT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BRN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BGR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BFA: [IdScanDocType.passport, IdScanDocType.idCard],
  BDI: [IdScanDocType.passport],
  KHM: [IdScanDocType.passport, IdScanDocType.driversLicense],
  CMR: [IdScanDocType.passport, IdScanDocType.idCard],
  CAN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CPV: [IdScanDocType.passport],
  CYM: [IdScanDocType.driversLicense],
  CAF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TCD: [IdScanDocType.passport],
  CHL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CHN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CXR: [IdScanDocType.idCard, IdScanDocType.driversLicense],
  CCK: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  COL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  COM: [IdScanDocType.passport],
  COG: [IdScanDocType.passport],
  COK: [IdScanDocType.driversLicense],
  CRI: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CIV: [IdScanDocType.passport],
  HRV: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CUB: [IdScanDocType.passport],
  CUW: [IdScanDocType.driversLicense],
  CYP: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CZE: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  COD: [IdScanDocType.passport],
  DNK: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  DJI: [IdScanDocType.passport],
  DMA: [IdScanDocType.passport],
  DOM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ECU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  EGY: [IdScanDocType.passport, IdScanDocType.idCard],
  SLV: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GNQ: [IdScanDocType.passport],
  ERI: [IdScanDocType.passport],
  EST: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ETH: [IdScanDocType.passport],
  FLK: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  FRO: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  FJI: [IdScanDocType.passport, IdScanDocType.driversLicense],
  FIN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  FRA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GUF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PYF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ATF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GAB: [IdScanDocType.passport],
  GMB: [IdScanDocType.passport],
  GEO: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  DEU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GHA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GIB: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GRC: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GRL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GRD: [IdScanDocType.passport, IdScanDocType.driversLicense],
  GLP: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GUM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GTM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GGY: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GIN: [IdScanDocType.passport],
  GNB: [IdScanDocType.passport],
  GUY: [IdScanDocType.passport],
  HTI: [IdScanDocType.passport, IdScanDocType.idCard],
  HMD: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  VAT: [IdScanDocType.passport],
  HND: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  HKG: [IdScanDocType.idCard],
  HUN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ISL: [IdScanDocType.passport, IdScanDocType.driversLicense],
  IND: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  IDN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  IRN: [IdScanDocType.passport],
  IRQ: [IdScanDocType.passport],
  IRL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  IMN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ISR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ITA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  JAM: [IdScanDocType.passport, IdScanDocType.driversLicense],
  JPN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  JEY: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  JOR: [IdScanDocType.passport, IdScanDocType.idCard],
  KAZ: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  KEN: [IdScanDocType.passport, IdScanDocType.idCard],
  KIR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  KWT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  KGZ: [IdScanDocType.passport, IdScanDocType.driversLicense],
  LAO: [IdScanDocType.passport],
  LVA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  LBN: [IdScanDocType.passport],
  LSO: [IdScanDocType.passport],
  LBR: [IdScanDocType.passport],
  LBY: [IdScanDocType.passport],
  LIE: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  LTU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  LUX: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MAC: [IdScanDocType.idCard],
  MDG: [IdScanDocType.passport],
  MWI: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MYS: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MDV: [IdScanDocType.passport],
  MLI: [IdScanDocType.passport],
  MLT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MHL: [IdScanDocType.passport],
  MTQ: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MRT: [IdScanDocType.passport, IdScanDocType.idCard],
  MUS: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MYT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MEX: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  FSM: [IdScanDocType.passport],
  MDA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MCO: [IdScanDocType.passport, IdScanDocType.idCard],
  MNG: [IdScanDocType.passport, IdScanDocType.driversLicense],
  MNE: [IdScanDocType.passport, IdScanDocType.idCard],
  MSR: [IdScanDocType.passport],
  MAR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MOZ: [IdScanDocType.passport, IdScanDocType.idCard],
  MMR: [IdScanDocType.passport, IdScanDocType.driversLicense],
  NAM: [IdScanDocType.passport],
  NRU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  NPL: [IdScanDocType.passport],
  NLD: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  NCL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  NZL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  NIC: [IdScanDocType.passport, IdScanDocType.idCard],
  NER: [IdScanDocType.passport],
  NGA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  NIU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  NFK: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MNP: [IdScanDocType.driversLicense],
  NOR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  OMN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PAK: [IdScanDocType.passport, IdScanDocType.idCard],
  PLW: [IdScanDocType.passport],
  PSE: [IdScanDocType.passport],
  PAN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PNG: [IdScanDocType.passport],
  PRY: [IdScanDocType.passport, IdScanDocType.idCard],
  PER: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PHL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PCN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  POL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PRT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  PRI: [IdScanDocType.idCard, IdScanDocType.driversLicense],
  QAT: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  MKD: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  REU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ROU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  RUS: [IdScanDocType.passport, IdScanDocType.driversLicense],
  RWA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  BLM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SHN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  KNA: [IdScanDocType.passport, IdScanDocType.driversLicense],
  LCA: [IdScanDocType.passport, IdScanDocType.driversLicense],
  MAF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SPM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  VCT: [IdScanDocType.passport],
  WSM: [IdScanDocType.passport],
  SMR: [IdScanDocType.passport],
  STP: [IdScanDocType.passport],
  SAU: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SEN: [IdScanDocType.passport, IdScanDocType.idCard],
  SRB: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SYC: [IdScanDocType.passport],
  SLE: [IdScanDocType.passport],
  SGP: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SXM: [IdScanDocType.driversLicense],
  SVK: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SVN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SLB: [IdScanDocType.passport],
  SOM: [IdScanDocType.passport],
  ZAF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SGS: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  KOR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SSD: [IdScanDocType.passport],
  ESP: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  LKA: [IdScanDocType.passport, IdScanDocType.driversLicense],
  SUR: [IdScanDocType.passport],
  SJM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SWZ: [IdScanDocType.passport],
  SWE: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  CHE: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  SYR: [IdScanDocType.passport],
  TWN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TJK: [IdScanDocType.passport],
  TZA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  THA: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TLS: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TGO: [IdScanDocType.passport],
  TKL: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TON: [IdScanDocType.passport, IdScanDocType.idCard],
  TTO: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TUN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TUR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  TKM: [IdScanDocType.passport],
  TCA: [IdScanDocType.driversLicense],
  TUV: [IdScanDocType.passport],
  UGA: [IdScanDocType.passport, IdScanDocType.driversLicense],
  UKR: [IdScanDocType.passport, IdScanDocType.driversLicense],
  ARE: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  GBR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  UMI: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  URY: [IdScanDocType.passport, IdScanDocType.idCard],
  UZB: [IdScanDocType.passport],
  VUT: [IdScanDocType.driversLicense],
  VEN: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  VNM: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  VIR: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  VGB: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  WLF: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  ESH: [
    IdScanDocType.passport,
    IdScanDocType.idCard,
    IdScanDocType.driversLicense,
  ],
  YEM: [IdScanDocType.passport],
  ZMB: [IdScanDocType.passport, IdScanDocType.driversLicense],
  ZWE: [IdScanDocType.passport],
};

export default AcceptedIdDocTypesByCountry;
