import type { CountryCode, CountryCode3 } from '@onefootprint/types';

export type CountryRecord = {
  value: CountryCode;
  value3: CountryCode3;
  label: string;
  passport: boolean;
  idCard: boolean;
  driversLicense: boolean;
  visa: boolean;
  workPermit: boolean;
  residenceDocument: boolean;
};

export const COUNTRIES: CountryRecord[] = [
  {
    label: 'United States of America',
    value: 'US',
    value3: 'USA',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Afghanistan',
    value: 'AF',
    value3: 'AFG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Albania',
    value: 'AL',
    value3: 'ALB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Algeria',
    value: 'DZ',
    value3: 'DZA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'American Samoa',
    value: 'AS',
    value3: 'ASM',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Andorra',
    value: 'AD',
    value3: 'AND',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Angola',
    value: 'AO',
    value3: 'AGO',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Antigua and Barbuda',
    value: 'AG',
    value3: 'ATG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Argentina',
    value: 'AR',
    value3: 'ARG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Armenia',
    value: 'AM',
    value3: 'ARM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Australia',
    value: 'AU',
    value3: 'AUS',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Austria',
    value: 'AT',
    value3: 'AUT',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Azerbaijan',
    value: 'AZ',
    value3: 'AZE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bahamas',
    value: 'BS',
    value3: 'BHS',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bahrain',
    value: 'BH',
    value3: 'BHR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bangladesh',
    value: 'BD',
    value3: 'BGD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Barbados',
    value: 'BB',
    value3: 'BRB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Belarus',
    value: 'BY',
    value3: 'BLR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Belgium',
    value: 'BE',
    value3: 'BEL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Belize',
    value: 'BZ',
    value3: 'BLZ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Benin',
    value: 'BJ',
    value3: 'BEN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bermuda',
    value: 'BM',
    value3: 'BMU',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bolivia',
    value: 'BO',
    value3: 'BOL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bosnia and Herzegovina',
    value: 'BA',
    value3: 'BIH',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Botswana',
    value: 'BW',
    value3: 'BWA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Brazil',
    value: 'BR',
    value3: 'BRA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Brunei Darussalam',
    value: 'BN',
    value3: 'BRN',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Bulgaria',
    value: 'BG',
    value3: 'BGR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Burkina Faso',
    value: 'BF',
    value3: 'BFA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Burundi',
    value: 'BI',
    value3: 'BDI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Cambodia',
    value: 'KH',
    value3: 'KHM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Cameroon',
    value: 'CM',
    value3: 'CMR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Canada',
    value: 'CA',
    value3: 'CAN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Cape Verde',
    value: 'CV',
    value3: 'CPV',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Cayman Islands',
    value: 'KY',
    value3: 'CYM',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Chad',
    value: 'TD',
    value3: 'TCD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Chile',
    value: 'CL',
    value3: 'CHL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'China',
    value: 'CN',
    value3: 'CHN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Colombia',
    value: 'CO',
    value3: 'COL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Congo (Democratic Republic)',
    value: 'CD',
    value3: 'COD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Congo (Republic of)',
    value: 'CG',
    value3: 'COG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Costa Rica',
    value: 'CR',
    value3: 'CRI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Côte d’Ivoire',
    value: 'CI',
    value3: 'CIV',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Croatia',
    value: 'HR',
    value3: 'HRV',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Cuba',
    value: 'CU',
    value3: 'CUB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Cyprus',
    value: 'CY',
    value3: 'CYP',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Czech Republic',
    value: 'CZ',
    value3: 'CZE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Denmark',
    value: 'DK',
    value3: 'DNK',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Djibouti',
    value: 'DJ',
    value3: 'DJI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Dominica',
    value: 'DM',
    value3: 'DMA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Dominican Republic',
    value: 'DO',
    value3: 'DOM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Ecuador',
    value: 'EC',
    value3: 'ECU',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Egypt',
    value: 'EG',
    value3: 'EGY',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'El Salvador',
    value: 'SV',
    value3: 'SLV',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Guinea',
    value: 'GQ',
    value3: 'GNQ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Eritrea',
    value: 'ER',
    value3: 'ERI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Estonia',
    value: 'EE',
    value3: 'EST',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Eswatini (Swaziland)',
    value: 'SZ',
    value3: 'SWZ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Ethiopia',
    value: 'ET',
    value3: 'ETH',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Fiji',
    value: 'FJ',
    value3: 'FJI',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Finland',
    value: 'FI',
    value3: 'FIN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'France',
    value: 'FR',
    value3: 'FRA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Gabon',
    value: 'GA',
    value3: 'GAB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Gambia',
    value: 'GM',
    value3: 'GMB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Georgia',
    value: 'GE',
    value3: 'GEO',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Germany',
    value: 'DE',
    value3: 'DEU',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Ghana',
    value: 'GH',
    value3: 'GHA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Greece',
    value: 'GR',
    value3: 'GRC',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Grenada',
    value: 'GD',
    value3: 'GRD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Guam',
    value: 'GU',
    value3: 'GUM',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Guatemala',
    value: 'GT',
    value3: 'GTM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Guinea',
    value: 'GN',
    value3: 'GIN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Guinea-Bissau',
    value: 'GW',
    value3: 'GNB',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Guyana',
    value: 'GY',
    value3: 'GUY',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Haiti',
    value: 'HT',
    value3: 'HTI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Holy See (Vatican City State)',
    value: 'VA',
    value3: 'VAT',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Honduras',
    value: 'HN',
    value3: 'HND',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Hong Kong',
    value: 'HK',
    value3: 'HKG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Hungary',
    value: 'HU',
    value3: 'HUN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Iceland',
    value: 'IS',
    value3: 'ISL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'India',
    value: 'IN',
    value3: 'IND',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Indonesia',
    value: 'ID',
    value3: 'IDN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Iran',
    value: 'IR',
    value3: 'IRN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Iraq',
    value: 'IQ',
    value3: 'IRQ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Ireland',
    value: 'IE',
    value3: 'IRL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Israel',
    value: 'IL',
    value3: 'ISR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Italy',
    value: 'IT',
    value3: 'ITA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Jamaica',
    value: 'JM',
    value3: 'JAM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Japan',
    value: 'JP',
    value3: 'JPN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Jordan',
    value: 'JO',
    value3: 'JOR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Kazakhstan',
    value: 'KZ',
    value3: 'KAZ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Kenya',
    value: 'KE',
    value3: 'KEN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Kosovo',
    value: 'KR',
    value3: 'KOR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Kuwait',
    value: 'KW',
    value3: 'KWT',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Kyrgyzstan',
    value: 'KG',
    value3: 'KGZ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Laos',
    value: 'LA',
    value3: 'LAO',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Latvia',
    value: 'LV',
    value3: 'LVA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Lebanon',
    value: 'LB',
    value3: 'LBN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Lesotho',
    value: 'LS',
    value3: 'LSO',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Liberia',
    value: 'LR',
    value3: 'LBR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Libya',
    value: 'LY',
    value3: 'LBY',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Liechtenstein',
    value: 'LI',
    value3: 'LIE',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Lithuania',
    value: 'LT',
    value3: 'LTU',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Luxembourg',
    value: 'LU',
    value3: 'LUX',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Macao',
    value: 'MO',
    value3: 'MAC',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Macedonia ',
    value: 'MK',
    value3: 'MKD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Madagascar',
    value: 'MG',
    value3: 'MDG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Malawi',
    value: 'MW',
    value3: 'MWI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Malaysia',
    value: 'MY',
    value3: 'MYS',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Maldives',
    value: 'MV',
    value3: 'MDV',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Mali',
    value: 'ML',
    value3: 'MLI',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Malta',
    value: 'MT',
    value3: 'MLT',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Marshall Islands',
    value: 'MH',
    value3: 'MHL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Mauritius',
    value: 'MU',
    value3: 'MUS',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Mexico',
    value: 'MX',
    value3: 'MEX',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Micronesia (Federal States of)',
    value: 'FM',
    value3: 'FSM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Moldova',
    value: 'MD',
    value3: 'MDA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Monaco',
    value: 'MC',
    value3: 'MCO',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Mongolia',
    value: 'MN',
    value3: 'MNG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Montenegro',
    value: 'ME',
    value3: 'MNE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Montserrat',
    value: 'MS',
    value3: 'MSR',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Morocco',
    value: 'MA',
    value3: 'MAR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Mozambique',
    value: 'MZ',
    value3: 'MOZ',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Myanmar',
    value: 'MM',
    value3: 'MMR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Namibia',
    value: 'NA',
    value3: 'NAM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Nepal',
    value: 'NP',
    value3: 'NPL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Netherlands',
    value: 'NL',
    value3: 'NLD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Netherlands Antilles',
    value: 'AN',
    value3: 'ANT',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'New Zealand',
    value: 'NZ',
    value3: 'NZL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Nicaragua',
    value: 'NI',
    value3: 'NIC',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Niger',
    value: 'NE',
    value3: 'NER',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Nigeria',
    value: 'NG',
    value3: 'NGA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'North Korea',
    value: 'NF',
    value3: 'NFK',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Northern Mariana Islands',
    value: 'MP',
    value3: 'MNP',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Norway',
    value: 'NO',
    value3: 'NOR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Oman',
    value: 'OM',
    value3: 'OMN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Pakistan',
    value: 'PK',
    value3: 'PAK',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Palau',
    value: 'PW',
    value3: 'PLW',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Palestine (State of)',
    value: 'PS',
    value3: 'PSE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Panama',
    value: 'PA',
    value3: 'PAN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Papua New Guinea',
    value: 'PG',
    value3: 'PNG',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Paraguay',
    value: 'PY',
    value3: 'PRY',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Peru',
    value: 'PE',
    value3: 'PER',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Philippines',
    value: 'PH',
    value3: 'PHL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Poland',
    value: 'PL',
    value3: 'POL',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Portugal',
    value: 'PT',
    value3: 'PRT',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Puerto Rico',
    value: 'PR',
    value3: 'PRI',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Qatar',
    value: 'QA',
    value3: 'QAT',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Romania',
    value: 'RO',
    value3: 'ROU',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Russian Federation',
    value: 'RU',
    value3: 'RUS',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Rwanda',
    value: 'RW',
    value3: 'RWA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Saint Kitts and Nevis',
    value: 'KN',
    value3: 'KNA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Saint Lucia',
    value: 'LC',
    value3: 'LCA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'VC',
    value3: 'VCT',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Samoa',
    value: 'WS',
    value3: 'WSM',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'San Marino',
    value: 'SM',
    value3: 'SMR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Sao Tome and Principe',
    value: 'ST',
    value3: 'STP',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Saudi Arabia',
    value: 'SA',
    value3: 'SAU',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Senegal',
    value: 'SN',
    value3: 'SEN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Serbia',
    value: 'RS',
    value3: 'SRB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Seychelles',
    value: 'SC',
    value3: 'SYC',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Sierra Leone',
    value: 'SL',
    value3: 'SLE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Singapore',
    value: 'SG',
    value3: 'SGP',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Sint Maarten',
    value: 'SX',
    value3: 'SXM',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Slovakia',
    value: 'SK',
    value3: 'SVK',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Slovenia',
    value: 'SI',
    value3: 'SVN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Solomon Islands',
    value: 'SB',
    value3: 'SLB',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Somalia',
    value: 'SO',
    value3: 'SOM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'South Africa',
    value: 'ZA',
    value3: 'ZAF',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'South Korea',
    value: 'GS',
    value3: 'SGS',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'South Sudan',
    value: 'SS',
    value3: 'SSD',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Spain',
    value: 'ES',
    value3: 'ESP',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Sri Lanka',
    value: 'LK',
    value3: 'LKA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Sudan',
    value: 'SD',
    value3: 'SDN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Suriname',
    value: 'SR',
    value3: 'SUR',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Sweden',
    value: 'SE',
    value3: 'SWE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Switzerland',
    value: 'CH',
    value3: 'CHE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Syria',
    value: 'SY',
    value3: 'SYR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Taiwan',
    value: 'TW',
    value3: 'TWN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Tajikistan',
    value: 'TJ',
    value3: 'TJK',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Tanzania',
    value: 'TZ',
    value3: 'TZA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Thailand',
    value: 'TH',
    value3: 'THA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Togo',
    value: 'TG',
    value3: 'TGO',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Tonga',
    value: 'TO',
    value3: 'TON',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Trinidad and Tobago',
    value: 'TT',
    value3: 'TTO',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Tunisia',
    value: 'TN',
    value3: 'TUN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Turkey',
    value: 'TR',
    value3: 'TUR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Turkmenistan',
    value: 'TM',
    value3: 'TKM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Tuvalu',
    value: 'TV',
    value3: 'TUV',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Uganda',
    value: 'UG',
    value3: 'UGA',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Ukraine',
    value: 'UA',
    value3: 'UKR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'United Arab Emirates',
    value: 'AE',
    value3: 'ARE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'United Kingdom',
    value: 'GB',
    value3: 'GBR',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'United States Minor Outlying Islands',
    value: 'UM',
    value3: 'UMI',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Uruguay',
    value: 'UY',
    value3: 'URY',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Uzbekistan',
    value: 'UZ',
    value3: 'UZB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Vanuatu',
    value: 'VU',
    value3: 'VUT',
    passport: false,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Venezuela',
    value: 'VE',
    value3: 'VEN',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Vietnam',
    value: 'VN',
    value3: 'VNM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Virgin Islands',
    value: 'VI',
    value3: 'VIR',
    passport: true,
    idCard: true,
    driversLicense: true,
    visa: true,
    workPermit: true,
    residenceDocument: true,
  },
  {
    label: 'Yemen',
    value: 'YE',
    value3: 'YEM',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Zambia',
    value: 'ZM',
    value3: 'ZMB',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
  {
    label: 'Zimbabwe',
    value: 'ZW',
    value3: 'ZWE',
    passport: true,
    idCard: false,
    driversLicense: false,
    visa: false,
    workPermit: false,
    residenceDocument: false,
  },
];

export const [DEFAULT_COUNTRY] = COUNTRIES;

export const BANNED_COUNTRIES = [];

export const COUNTRIES_WITH_STATES: CountryCode[] = [
  'US',
  'AU',
  'AT',
  'BR',
  'DE',
  'IN',
  'MY',
  'MX',
  'FM',
  'MM',
  'NZ',
  'NG',
  'PW',
  'SS',
];

export const COUNTRIES_WITH_PROVINCES: CountryCode[] = [
  'AF',
  'DZ',
  'AO',
  'AM',
  'AR',
  'TR',
  'BG',
  'BI',
  'CA',
  'KH',
  'CN',
  'CR',
  'CG',
  'CU',
  'DO',
  'EC',
  'GQ',
  'GA',
  'ID',
  'LA',
  'NP',
  'PK',
  'SL',
  'ZA',
  'SB',
  'LK',
  'TO',
  'VU',
  'VN',
  'ZM',
  'ZW',
];

export const US_TERRITORY_COUNTRY_CODES = ['AS', 'GU', 'MP', 'PR', 'VI'];
