# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Footprint', :path => '../../packages/verify-ios-sdk/footprint-ios.podspec'

  # Pods for demo-swift

end
