// extension required due to limitations of KMM not able to generate default values in obj-c
public extension VaultData {
    convenience init(
        idAddressLine1: String? = nil,
        idAddressLine2: String? = nil,
        idCitizenships: [Iso3166TwoDigitCountryCode]? = nil,
        idCity: String? = nil,
        idCountry: String? = nil,
        idDob: String? = nil,
        idDriversLicenseNumber: String? = nil,
        idDriversLicenseState: String? = nil,
        idEmail: String? = nil,
        idFirstName: String? = nil,
        idItin: String? = nil,
        idLastName: String? = nil,
        idMiddleName: String? = nil,
        idNationality: String? = nil,
        idPhoneNumber: String? = nil,
        idSsn4: String? = nil,
        idSsn9: String? = nil,
        idState: String? = nil,
        idUsLegalStatus: String? = nil,
        idUsTaxId: String? = nil,
        idVisaExpirationDate: String? = nil,
        idVisaKind: String? = nil,
        idZip: String? = nil,
        investorProfileAnnualIncome: String? = nil,
        investorProfileBrokerageFirmEmployer: String? = nil,
        investorProfileDeclarations: [InvestorProfileDeclaration]? = nil,
        investorProfileEmployer: String? = nil,
        investorProfileEmploymentStatus: String? = nil,
        investorProfileFamilyMemberNames: [String]? = nil,
        investorProfileFundingSources: [InvestorProfileFundingSource]? = nil,
        investorProfileInvestmentGoals: [InvestorProfileInvestmentGoal]? = nil,
        investorProfileNetWorth: String? = nil,
        investorProfileOccupation: String? = nil,
        investorProfilePoliticalOrganization: String? = nil,
        investorProfileRiskTolerance: String? = nil,
        investorProfileSeniorExecutiveSymbols: [String]? = nil
    ) {
        self.init(
            idAddressLine1: idAddressLine1,
            idAddressLine2: idAddressLine2,
            idCitizenships: idCitizenships,
            idCity: idCity,
            idCountry: idCountry,
            idDob: idDob,
            idDriversLicenseNumber: idDriversLicenseNumber,
            idDriversLicenseState: idDriversLicenseState,
            idEmail: idEmail,
            idFirstName: idFirstName,
            idItin: idItin,
            idLastName: idLastName,
            idMiddleName: idMiddleName,
            idNationality: idNationality,
            idPhoneNumber: idPhoneNumber,
            idSsn4: idSsn4,
            idSsn9: idSsn9,
            idState: idState,
            idUsLegalStatus: idUsLegalStatus,
            idUsTaxId: idUsTaxId,
            idVisaExpirationDate: idVisaExpirationDate,
            idVisaKind: idVisaKind,
            idZip: idZip,
            investorProfileAnnualIncome: investorProfileAnnualIncome,
            investorProfileBrokerageFirmEmployer: investorProfileBrokerageFirmEmployer,
            investorProfileDeclarations: investorProfileDeclarations,
            investorProfileEmployer: investorProfileEmployer,
            investorProfileEmploymentStatus: investorProfileEmploymentStatus,
            investorProfileFamilyMemberNames: investorProfileFamilyMemberNames,
            investorProfileFundingSources: investorProfileFundingSources,
            investorProfileInvestmentGoals: investorProfileInvestmentGoals,
            investorProfileNetWorth: investorProfileNetWorth,
            investorProfileOccupation: investorProfileOccupation,
            investorProfilePoliticalOrganization: investorProfilePoliticalOrganization,
            investorProfileRiskTolerance: investorProfileRiskTolerance,
            investorProfileSeniorExecutiveSymbols: investorProfileSeniorExecutiveSymbols
        )
    }
}
