extensions:
  health_check:

receivers:
  awsecscontainermetrics:
  prometheus:
    config:
      scrape_configs:
        - job_name: "prometheus-metrics"
          scrape_interval: 30s
          metrics_path: "/${API_SERVER_METRICS_ENDPOINT_PATH}"
          static_configs:
            - targets: ["${API_SERVER_TARGET}"]

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.reserved
          - ecs.task.memory.utilized
          - ecs.task.cpu.reserved
          - ecs.task.cpu.utilized
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
          - container.duration

exporters:
  logging:
    loglevel: debug

  otlp/elastic:
    endpoint: '${ELASTIC_APM_SERVER_ENDPOINT}'
    headers:
      Authorization: 'ApiKey ${ELASTIC_APM_API_KEY}'

  prometheusremotewrite:
    endpoint: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    headers:
      'Authorization': "Basic ${GRAFANA_PROMETHEUS_PUSH_AUTH}"

  prometheusremotewrite/observe:
    endpoint: 'https://collect.observeinc.com/v1/prometheus'
    headers:
      'Authorization': 'Bearer 189225732777 ds1CdgeCvHzZp3oRu7Rc:s3PHTK91XmE7_ykZ7vk1J-BsLl6jWg0Y'

service:
  pipelines:
    metrics/application:
      receivers: [prometheus]
      processors: []
      exporters: [logging, prometheusremotewrite, prometheusremotewrite/observe, otlp/elastic]
    metrics/performance:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging, prometheusremotewrite, prometheusremotewrite/observe, otlp/elastic]
  extensions: [health_check]