export type CountryRecord = {
  label: string;
  passport: boolean;
  idCard: boolean;
  driversLicense: boolean;
};

export const COUNTRIES: CountryRecord[] = [
  {
    label: 'United States of America',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Afghanistan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Albania',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Algeria',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'American Samoa',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Andorra',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Angola',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Antigua and Barbuda',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Argentina',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Armenia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Australia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Austria',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Azerbaijan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bahamas',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bahrain',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bangladesh',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Barbados',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Belarus',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Belgium',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Belize',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Benin',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bermuda',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bolivia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bosnia and Herzegovina',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Botswana',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Brazil',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Brunei Darussalam',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Bulgaria',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Burkina Faso',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Burundi',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Cambodia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Cameroon',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Canada',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Cape Verde',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Cayman Islands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Chad',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Chile',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'China',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Colombia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Congo (Democratic Republic)',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Congo (Republic of)',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Costa Rica',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: "Côte d'Ivoire",
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Croatia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Cuba',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Cyprus',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Czech Republic',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Denmark',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Djibouti',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Dominica',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Dominican Republic',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Ecuador',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Egypt',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'El Salvador',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Guinea',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Eritrea',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Estonia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Eswatini (Swaziland)',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Ethiopia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Fiji',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Finland',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'France',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Gabon',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Gambia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Georgia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Germany',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Ghana',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Greece',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Grenada',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Guam',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Guatemala',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Guinea',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Guinea-Bissau',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Guyana',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Haiti',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Holy See (Vatican City State)',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Honduras',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Hong Kong',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Hungary',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Iceland',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'India',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Indonesia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Iran',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Iraq',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Ireland',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Israel',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Italy',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Jamaica',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Japan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Jordan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Kazakhstan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Kenya',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Kosovo',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Kuwait',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Kyrgyzstan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Laos',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Latvia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Lebanon',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Lesotho',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Liberia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Libya',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Liechtenstein',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Lithuania',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Luxembourg',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Macao',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Macedonia ',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Madagascar',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Malawi',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Malaysia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Maldives',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Mali',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Malta',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Marshall Islands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Mauritius',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Mexico',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Micronesia (Federal States of)',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Moldova',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Monaco',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Mongolia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Montenegro',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Montserrat',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Morocco',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Mozambique',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Myanmar',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Namibia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Nepal',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Netherlands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Netherlands Antilles',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'New Zealand',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Nicaragua',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Niger',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Nigeria',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'North Korea',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Northern Mariana Islands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Norway',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Oman',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Pakistan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Palau',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Palestine (State of)',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Panama',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Papua New Guinea',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Paraguay',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Peru',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Philippines',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Poland',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Portugal',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Puerto Rico',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Qatar',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Romania',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Russian Federation',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Rwanda',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Saint Kitts and Nevis',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Saint Lucia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Saint Vincent and the Grenadines',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Samoa',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'San Marino',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Sao Tome and Principe',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Saudi Arabia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Senegal',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Serbia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Seychelles',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Sierra Leone',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Singapore',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Sint Maarten',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Slovakia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Slovenia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Solomon Islands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Somalia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'South Africa',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'South Korea',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'South Sudan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Spain',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Sri Lanka',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Sudan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Suriname',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Sweden',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Switzerland',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Syria',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Taiwan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Tajikistan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Tanzania',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Thailand',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Togo',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Tonga',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Trinidad and Tobago',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Tunisia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Turkey',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Turkmenistan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Tuvalu',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Uganda',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Ukraine',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'United Arab Emirates',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'United Kingdom',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'United States Minor Outlying Islands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Uruguay',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Uzbekistan',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Vanuatu',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Venezuela',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Vietnam',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Virgin Islands',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Yemen',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Zambia',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
  {
    label: 'Zimbabwe',
    passport: true,
    idCard: true,
    driversLicense: true,
  },
];
