BEGIN;
ALTER TABLE access_events ADD COLUMN reason VARCHAR(250) DEFAULT '';
ALTER TABLE access_events ALTER COLUMN reason SET NOT NULL;
ALTER TABLE access_events ALTER COLUMN reason DROP DEFAULT;
COMMIT;