ALTER TABLE fingerprint
  ADD COLUMN IF NOT EXISTS scoped_vault_id TEXT,
  ADD COLUMN IF NOT EXISTS vault_id TEXT,
  ADD COLUMN IF NOT EXISTS tenant_id TEXT,
  ADD COLUMN IF NOT EXISTS is_live BOOL,
  ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMPTZ;