// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-axios';
import type {
  GetHostedBusinessData,
  GetHostedBusinessOwnersData,
  GetHostedBusinessesData,
  GetHostedCheckSessionData,
  GetHostedOnboardingConfigData,
  GetHostedOnboardingNidData,
  GetHostedOnboardingPrivacyPassData,
  GetHostedOnboardingSessionData,
  GetHostedOnboardingStatusData,
  GetHostedUserAuthMethodsData,
  GetHostedUserAuthRequirementsData,
  GetHostedUserAuthorizedOrgsData,
  GetHostedUserPrivateTokenData,
  GetHostedUserTokenData,
  GetOrgSdkArgsData,
  HostedOnboardingD2pGenerateData,
  HostedOnboardingD2pGenerateError,
  HostedOnboardingD2pGenerateResponse,
  HostedOnboardingD2pSmsData,
  HostedOnboardingD2pSmsError,
  HostedOnboardingD2pSmsResponse,
  HostedOnboardingD2pStatusData,
  HostedOnboardingD2pStatusPostData,
  HostedOnboardingD2pStatusPostError,
  HostedOnboardingD2pStatusPostResponse,
  PatchHostedBusinessOwnersData,
  PatchHostedBusinessOwnersError,
  PatchHostedBusinessOwnersResponse,
  PatchHostedBusinessVaultData,
  PatchHostedBusinessVaultError,
  PatchHostedBusinessVaultResponse,
  PatchHostedUserVaultData,
  PatchHostedUserVaultError,
  PatchHostedUserVaultResponse,
  PostHostedBusinessOnboardingData,
  PostHostedBusinessOnboardingError,
  PostHostedBusinessOnboardingResponse,
  PostHostedBusinessVaultDecryptData,
  PostHostedBusinessVaultDecryptError,
  PostHostedBusinessVaultDecryptResponse,
  PostHostedBusinessVaultValidateData,
  PostHostedBusinessVaultValidateError,
  PostHostedBusinessVaultValidateResponse,
  PostHostedDocumentsByIdProcessData,
  PostHostedDocumentsByIdProcessError,
  PostHostedDocumentsByIdProcessResponse,
  PostHostedDocumentsByIdUploadBySideData,
  PostHostedDocumentsByIdUploadBySideError,
  PostHostedDocumentsByIdUploadBySideResponse,
  PostHostedDocumentsData,
  PostHostedDocumentsError,
  PostHostedDocumentsResponse,
  PostHostedIdentifyData,
  PostHostedIdentifyError,
  PostHostedIdentifyKbaData,
  PostHostedIdentifyKbaError,
  PostHostedIdentifyKbaResponse,
  PostHostedIdentifyLiteData,
  PostHostedIdentifyLiteError,
  PostHostedIdentifyLiteResponse,
  PostHostedIdentifyLoginChallengeData,
  PostHostedIdentifyLoginChallengeError,
  PostHostedIdentifyLoginChallengeResponse,
  PostHostedIdentifyResponse,
  PostHostedIdentifySignupChallengeData,
  PostHostedIdentifySignupChallengeError,
  PostHostedIdentifySignupChallengeResponse,
  PostHostedIdentifyValidationTokenData,
  PostHostedIdentifyValidationTokenError,
  PostHostedIdentifyValidationTokenResponse,
  PostHostedIdentifyVerifyData,
  PostHostedIdentifyVerifyError,
  PostHostedIdentifyVerifyResponse,
  PostHostedOnboardingAuthorizeData,
  PostHostedOnboardingAuthorizeError,
  PostHostedOnboardingAuthorizeResponse,
  PostHostedOnboardingData,
  PostHostedOnboardingError,
  PostHostedOnboardingFpData,
  PostHostedOnboardingFpError,
  PostHostedOnboardingFpResponse,
  PostHostedOnboardingProcessData,
  PostHostedOnboardingProcessError,
  PostHostedOnboardingProcessResponse,
  PostHostedOnboardingResponse,
  PostHostedOnboardingSdsData,
  PostHostedOnboardingSdsError,
  PostHostedOnboardingSdsResponse,
  PostHostedOnboardingSkipPasskeyRegisterData,
  PostHostedOnboardingSkipPasskeyRegisterError,
  PostHostedOnboardingSkipPasskeyRegisterResponse,
  PostHostedOnboardingTelData,
  PostHostedOnboardingTelError,
  PostHostedOnboardingTelResponse,
  PostHostedOnboardingTimelineData,
  PostHostedOnboardingTimelineError,
  PostHostedOnboardingTimelineResponse,
  PostHostedOnboardingValidateData,
  PostHostedOnboardingValidateError,
  PostHostedOnboardingValidateResponse,
  PostHostedUserAttestDeviceChallengeData,
  PostHostedUserAttestDeviceChallengeError,
  PostHostedUserAttestDeviceChallengeResponse,
  PostHostedUserAttestDeviceData,
  PostHostedUserAttestDeviceError,
  PostHostedUserAttestDeviceResponse,
  PostHostedUserChallengeData,
  PostHostedUserChallengeError,
  PostHostedUserChallengeResponse,
  PostHostedUserChallengeVerifyData,
  PostHostedUserChallengeVerifyError,
  PostHostedUserChallengeVerifyResponse,
  PostHostedUserConsentData,
  PostHostedUserConsentError,
  PostHostedUserConsentResponse,
  PostHostedUserDocumentsByIdProcessData,
  PostHostedUserDocumentsByIdProcessError,
  PostHostedUserDocumentsByIdProcessResponse,
  PostHostedUserDocumentsByIdUploadBySideData,
  PostHostedUserDocumentsByIdUploadBySideError,
  PostHostedUserDocumentsByIdUploadBySideResponse,
  PostHostedUserDocumentsData,
  PostHostedUserDocumentsError,
  PostHostedUserDocumentsResponse,
  PostHostedUserEmailVerifyData,
  PostHostedUserEmailVerifyError,
  PostHostedUserEmailVerifyResponse,
  PostHostedUserTokensData,
  PostHostedUserTokensError,
  PostHostedUserTokensResponse,
  PostHostedUserUploadByDocumentIdentifierData,
  PostHostedUserUploadByDocumentIdentifierError,
  PostHostedUserUploadByDocumentIdentifierResponse,
  PostHostedUserVaultDecryptData,
  PostHostedUserVaultDecryptError,
  PostHostedUserVaultDecryptResponse,
  PostHostedUserVaultValidateData,
  PostHostedUserVaultValidateError,
  PostHostedUserVaultValidateResponse,
  PostOrgSdkArgsData,
  PostOrgSdkArgsError,
  PostOrgSdkArgsResponse,
  PostOrgSdkTelemetryData,
  PostOrgSdkTelemetryError,
  PostOrgSdkTelemetryResponse,
} from '@onefootprint/request-types';
import { type UseMutationOptions, queryOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';
import {
  client,
  getHostedBusiness,
  getHostedBusinessOwners,
  getHostedBusinesses,
  getHostedCheckSession,
  getHostedOnboardingConfig,
  getHostedOnboardingNid,
  getHostedOnboardingPrivacyPass,
  getHostedOnboardingSession,
  getHostedOnboardingStatus,
  getHostedUserAuthMethods,
  getHostedUserAuthRequirements,
  getHostedUserAuthorizedOrgs,
  getHostedUserPrivateToken,
  getHostedUserToken,
  getOrgSdkArgs,
  hostedOnboardingD2pGenerate,
  hostedOnboardingD2pSms,
  hostedOnboardingD2pStatus,
  hostedOnboardingD2pStatusPost,
  patchHostedBusinessOwners,
  patchHostedBusinessVault,
  patchHostedUserVault,
  postHostedBusinessOnboarding,
  postHostedBusinessVaultDecrypt,
  postHostedBusinessVaultValidate,
  postHostedDocuments,
  postHostedDocumentsByIdProcess,
  postHostedDocumentsByIdUploadBySide,
  postHostedIdentify,
  postHostedIdentifyKba,
  postHostedIdentifyLite,
  postHostedIdentifyLoginChallenge,
  postHostedIdentifySignupChallenge,
  postHostedIdentifyValidationToken,
  postHostedIdentifyVerify,
  postHostedOnboarding,
  postHostedOnboardingAuthorize,
  postHostedOnboardingFp,
  postHostedOnboardingProcess,
  postHostedOnboardingSds,
  postHostedOnboardingSkipPasskeyRegister,
  postHostedOnboardingTel,
  postHostedOnboardingTimeline,
  postHostedOnboardingValidate,
  postHostedUserAttestDevice,
  postHostedUserAttestDeviceChallenge,
  postHostedUserChallenge,
  postHostedUserChallengeVerify,
  postHostedUserConsent,
  postHostedUserDocuments,
  postHostedUserDocumentsByIdProcess,
  postHostedUserDocumentsByIdUploadBySide,
  postHostedUserEmailVerify,
  postHostedUserTokens,
  postHostedUserUploadByDocumentIdentifier,
  postHostedUserVaultDecrypt,
  postHostedUserVaultValidate,
  postOrgSdkArgs,
  postOrgSdkTelemetry,
} from '../services.gen';

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const getHostedBusinessQueryKey = (options?: Options<GetHostedBusinessData>) => [
  createQueryKey('getHostedBusiness', options),
];

export const getHostedBusinessOptions = (options?: Options<GetHostedBusinessData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedBusiness({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedBusinessQueryKey(options),
  });
};

export const postHostedBusinessOnboardingQueryKey = (options: Options<PostHostedBusinessOnboardingData>) => [
  createQueryKey('postHostedBusinessOnboarding', options),
];

export const postHostedBusinessOnboardingOptions = (options: Options<PostHostedBusinessOnboardingData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedBusinessOnboarding({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedBusinessOnboardingQueryKey(options),
  });
};

export const postHostedBusinessOnboardingMutation = (options?: Partial<Options<PostHostedBusinessOnboardingData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedBusinessOnboardingResponse,
    AxiosError<PostHostedBusinessOnboardingError>,
    Options<PostHostedBusinessOnboardingData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedBusinessOnboarding({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedBusinessOwnersQueryKey = (options?: Options<GetHostedBusinessOwnersData>) => [
  createQueryKey('getHostedBusinessOwners', options),
];

export const getHostedBusinessOwnersOptions = (options?: Options<GetHostedBusinessOwnersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedBusinessOwners({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedBusinessOwnersQueryKey(options),
  });
};

export const patchHostedBusinessOwnersMutation = (options?: Partial<Options<PatchHostedBusinessOwnersData>>) => {
  const mutationOptions: UseMutationOptions<
    PatchHostedBusinessOwnersResponse,
    AxiosError<PatchHostedBusinessOwnersError>,
    Options<PatchHostedBusinessOwnersData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await patchHostedBusinessOwners({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const patchHostedBusinessVaultMutation = (options?: Partial<Options<PatchHostedBusinessVaultData>>) => {
  const mutationOptions: UseMutationOptions<
    PatchHostedBusinessVaultResponse,
    AxiosError<PatchHostedBusinessVaultError>,
    Options<PatchHostedBusinessVaultData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await patchHostedBusinessVault({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedBusinessVaultDecryptQueryKey = (options: Options<PostHostedBusinessVaultDecryptData>) => [
  createQueryKey('postHostedBusinessVaultDecrypt', options),
];

export const postHostedBusinessVaultDecryptOptions = (options: Options<PostHostedBusinessVaultDecryptData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedBusinessVaultDecrypt({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedBusinessVaultDecryptQueryKey(options),
  });
};

export const postHostedBusinessVaultDecryptMutation = (
  options?: Partial<Options<PostHostedBusinessVaultDecryptData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedBusinessVaultDecryptResponse,
    AxiosError<PostHostedBusinessVaultDecryptError>,
    Options<PostHostedBusinessVaultDecryptData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedBusinessVaultDecrypt({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedBusinessVaultValidateQueryKey = (options: Options<PostHostedBusinessVaultValidateData>) => [
  createQueryKey('postHostedBusinessVaultValidate', options),
];

export const postHostedBusinessVaultValidateOptions = (options: Options<PostHostedBusinessVaultValidateData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedBusinessVaultValidate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedBusinessVaultValidateQueryKey(options),
  });
};

export const postHostedBusinessVaultValidateMutation = (
  options?: Partial<Options<PostHostedBusinessVaultValidateData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedBusinessVaultValidateResponse,
    AxiosError<PostHostedBusinessVaultValidateError>,
    Options<PostHostedBusinessVaultValidateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedBusinessVaultValidate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedBusinessesQueryKey = (options?: Options<GetHostedBusinessesData>) => [
  createQueryKey('getHostedBusinesses', options),
];

export const getHostedBusinessesOptions = (options?: Options<GetHostedBusinessesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedBusinesses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedBusinessesQueryKey(options),
  });
};

export const getHostedCheckSessionQueryKey = (options?: Options<GetHostedCheckSessionData>) => [
  createQueryKey('getHostedCheckSession', options),
];

export const getHostedCheckSessionOptions = (options?: Options<GetHostedCheckSessionData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedCheckSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedCheckSessionQueryKey(options),
  });
};

export const postHostedDocumentsQueryKey = (options: Options<PostHostedDocumentsData>) => [
  createQueryKey('postHostedDocuments', options),
];

export const postHostedDocumentsOptions = (options: Options<PostHostedDocumentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedDocuments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedDocumentsQueryKey(options),
  });
};

export const postHostedDocumentsMutation = (options?: Partial<Options<PostHostedDocumentsData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedDocumentsResponse,
    AxiosError<PostHostedDocumentsError>,
    Options<PostHostedDocumentsData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedDocuments({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedDocumentsByIdProcessQueryKey = (options: Options<PostHostedDocumentsByIdProcessData>) => [
  createQueryKey('postHostedDocumentsByIdProcess', options),
];

export const postHostedDocumentsByIdProcessOptions = (options: Options<PostHostedDocumentsByIdProcessData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedDocumentsByIdProcess({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedDocumentsByIdProcessQueryKey(options),
  });
};

export const postHostedDocumentsByIdProcessMutation = (
  options?: Partial<Options<PostHostedDocumentsByIdProcessData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedDocumentsByIdProcessResponse,
    AxiosError<PostHostedDocumentsByIdProcessError>,
    Options<PostHostedDocumentsByIdProcessData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedDocumentsByIdProcess({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedDocumentsByIdUploadBySideQueryKey = (
  options: Options<PostHostedDocumentsByIdUploadBySideData>,
) => [createQueryKey('postHostedDocumentsByIdUploadBySide', options)];

export const postHostedDocumentsByIdUploadBySideOptions = (
  options: Options<PostHostedDocumentsByIdUploadBySideData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedDocumentsByIdUploadBySide({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedDocumentsByIdUploadBySideQueryKey(options),
  });
};

export const postHostedDocumentsByIdUploadBySideMutation = (
  options?: Partial<Options<PostHostedDocumentsByIdUploadBySideData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedDocumentsByIdUploadBySideResponse,
    AxiosError<PostHostedDocumentsByIdUploadBySideError>,
    Options<PostHostedDocumentsByIdUploadBySideData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedDocumentsByIdUploadBySide({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifyQueryKey = (options: Options<PostHostedIdentifyData>) => [
  createQueryKey('postHostedIdentify', options),
];

export const postHostedIdentifyOptions = (options: Options<PostHostedIdentifyData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentify({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifyQueryKey(options),
  });
};

export const postHostedIdentifyMutation = (options?: Partial<Options<PostHostedIdentifyData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifyResponse,
    AxiosError<PostHostedIdentifyError>,
    Options<PostHostedIdentifyData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentify({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifyKbaQueryKey = (options: Options<PostHostedIdentifyKbaData>) => [
  createQueryKey('postHostedIdentifyKba', options),
];

export const postHostedIdentifyKbaOptions = (options: Options<PostHostedIdentifyKbaData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentifyKba({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifyKbaQueryKey(options),
  });
};

export const postHostedIdentifyKbaMutation = (options?: Partial<Options<PostHostedIdentifyKbaData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifyKbaResponse,
    AxiosError<PostHostedIdentifyKbaError>,
    Options<PostHostedIdentifyKbaData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentifyKba({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifyLiteQueryKey = (options: Options<PostHostedIdentifyLiteData>) => [
  createQueryKey('postHostedIdentifyLite', options),
];

export const postHostedIdentifyLiteOptions = (options: Options<PostHostedIdentifyLiteData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentifyLite({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifyLiteQueryKey(options),
  });
};

export const postHostedIdentifyLiteMutation = (options?: Partial<Options<PostHostedIdentifyLiteData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifyLiteResponse,
    AxiosError<PostHostedIdentifyLiteError>,
    Options<PostHostedIdentifyLiteData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentifyLite({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifyLoginChallengeQueryKey = (options: Options<PostHostedIdentifyLoginChallengeData>) => [
  createQueryKey('postHostedIdentifyLoginChallenge', options),
];

export const postHostedIdentifyLoginChallengeOptions = (options: Options<PostHostedIdentifyLoginChallengeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentifyLoginChallenge({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifyLoginChallengeQueryKey(options),
  });
};

export const postHostedIdentifyLoginChallengeMutation = (
  options?: Partial<Options<PostHostedIdentifyLoginChallengeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifyLoginChallengeResponse,
    AxiosError<PostHostedIdentifyLoginChallengeError>,
    Options<PostHostedIdentifyLoginChallengeData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentifyLoginChallenge({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifySignupChallengeQueryKey = (options: Options<PostHostedIdentifySignupChallengeData>) => [
  createQueryKey('postHostedIdentifySignupChallenge', options),
];

export const postHostedIdentifySignupChallengeOptions = (options: Options<PostHostedIdentifySignupChallengeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentifySignupChallenge({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifySignupChallengeQueryKey(options),
  });
};

export const postHostedIdentifySignupChallengeMutation = (
  options?: Partial<Options<PostHostedIdentifySignupChallengeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifySignupChallengeResponse,
    AxiosError<PostHostedIdentifySignupChallengeError>,
    Options<PostHostedIdentifySignupChallengeData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentifySignupChallenge({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifyValidationTokenQueryKey = (options?: Options<PostHostedIdentifyValidationTokenData>) => [
  createQueryKey('postHostedIdentifyValidationToken', options),
];

export const postHostedIdentifyValidationTokenOptions = (options?: Options<PostHostedIdentifyValidationTokenData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentifyValidationToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifyValidationTokenQueryKey(options),
  });
};

export const postHostedIdentifyValidationTokenMutation = (
  options?: Partial<Options<PostHostedIdentifyValidationTokenData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifyValidationTokenResponse,
    AxiosError<PostHostedIdentifyValidationTokenError>,
    Options<PostHostedIdentifyValidationTokenData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentifyValidationToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedIdentifyVerifyQueryKey = (options: Options<PostHostedIdentifyVerifyData>) => [
  createQueryKey('postHostedIdentifyVerify', options),
];

export const postHostedIdentifyVerifyOptions = (options: Options<PostHostedIdentifyVerifyData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedIdentifyVerify({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedIdentifyVerifyQueryKey(options),
  });
};

export const postHostedIdentifyVerifyMutation = (options?: Partial<Options<PostHostedIdentifyVerifyData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedIdentifyVerifyResponse,
    AxiosError<PostHostedIdentifyVerifyError>,
    Options<PostHostedIdentifyVerifyData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedIdentifyVerify({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedOnboardingQueryKey = (options?: Options<PostHostedOnboardingData>) => [
  createQueryKey('postHostedOnboarding', options),
];

export const postHostedOnboardingOptions = (options?: Options<PostHostedOnboardingData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboarding({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingQueryKey(options),
  });
};

export const postHostedOnboardingMutation = (options?: Partial<Options<PostHostedOnboardingData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingResponse,
    AxiosError<PostHostedOnboardingError>,
    Options<PostHostedOnboardingData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboarding({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedOnboardingAuthorizeQueryKey = (options?: Options<PostHostedOnboardingAuthorizeData>) => [
  createQueryKey('postHostedOnboardingAuthorize', options),
];

export const postHostedOnboardingAuthorizeOptions = (options?: Options<PostHostedOnboardingAuthorizeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingAuthorize({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingAuthorizeQueryKey(options),
  });
};

export const postHostedOnboardingAuthorizeMutation = (
  options?: Partial<Options<PostHostedOnboardingAuthorizeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingAuthorizeResponse,
    AxiosError<PostHostedOnboardingAuthorizeError>,
    Options<PostHostedOnboardingAuthorizeData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingAuthorize({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedOnboardingConfigQueryKey = (options?: Options<GetHostedOnboardingConfigData>) => [
  createQueryKey('getHostedOnboardingConfig', options),
];

export const getHostedOnboardingConfigOptions = (options?: Options<GetHostedOnboardingConfigData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedOnboardingConfig({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedOnboardingConfigQueryKey(options),
  });
};

export const hostedOnboardingD2pGenerateQueryKey = (options: Options<HostedOnboardingD2pGenerateData>) => [
  createQueryKey('hostedOnboardingD2pGenerate', options),
];

export const hostedOnboardingD2pGenerateOptions = (options: Options<HostedOnboardingD2pGenerateData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await hostedOnboardingD2pGenerate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: hostedOnboardingD2pGenerateQueryKey(options),
  });
};

export const hostedOnboardingD2pGenerateMutation = (options?: Partial<Options<HostedOnboardingD2pGenerateData>>) => {
  const mutationOptions: UseMutationOptions<
    HostedOnboardingD2pGenerateResponse,
    AxiosError<HostedOnboardingD2pGenerateError>,
    Options<HostedOnboardingD2pGenerateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await hostedOnboardingD2pGenerate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const hostedOnboardingD2pSmsQueryKey = (options: Options<HostedOnboardingD2pSmsData>) => [
  createQueryKey('hostedOnboardingD2pSms', options),
];

export const hostedOnboardingD2pSmsOptions = (options: Options<HostedOnboardingD2pSmsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await hostedOnboardingD2pSms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: hostedOnboardingD2pSmsQueryKey(options),
  });
};

export const hostedOnboardingD2pSmsMutation = (options?: Partial<Options<HostedOnboardingD2pSmsData>>) => {
  const mutationOptions: UseMutationOptions<
    HostedOnboardingD2pSmsResponse,
    AxiosError<HostedOnboardingD2pSmsError>,
    Options<HostedOnboardingD2pSmsData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await hostedOnboardingD2pSms({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const hostedOnboardingD2pStatusQueryKey = (options?: Options<HostedOnboardingD2pStatusData>) => [
  createQueryKey('hostedOnboardingD2pStatus', options),
];

export const hostedOnboardingD2pStatusOptions = (options?: Options<HostedOnboardingD2pStatusData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await hostedOnboardingD2pStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: hostedOnboardingD2pStatusQueryKey(options),
  });
};

export const hostedOnboardingD2pStatusPostQueryKey = (options: Options<HostedOnboardingD2pStatusPostData>) => [
  createQueryKey('hostedOnboardingD2pStatusPost', options),
];

export const hostedOnboardingD2pStatusPostOptions = (options: Options<HostedOnboardingD2pStatusPostData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await hostedOnboardingD2pStatusPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: hostedOnboardingD2pStatusPostQueryKey(options),
  });
};

export const hostedOnboardingD2pStatusPostMutation = (
  options?: Partial<Options<HostedOnboardingD2pStatusPostData>>,
) => {
  const mutationOptions: UseMutationOptions<
    HostedOnboardingD2pStatusPostResponse,
    AxiosError<HostedOnboardingD2pStatusPostError>,
    Options<HostedOnboardingD2pStatusPostData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await hostedOnboardingD2pStatusPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedOnboardingFpQueryKey = (options: Options<PostHostedOnboardingFpData>) => [
  createQueryKey('postHostedOnboardingFp', options),
];

export const postHostedOnboardingFpOptions = (options: Options<PostHostedOnboardingFpData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingFp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingFpQueryKey(options),
  });
};

export const postHostedOnboardingFpMutation = (options?: Partial<Options<PostHostedOnboardingFpData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingFpResponse,
    AxiosError<PostHostedOnboardingFpError>,
    Options<PostHostedOnboardingFpData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingFp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedOnboardingNidQueryKey = (options?: Options<GetHostedOnboardingNidData>) => [
  createQueryKey('getHostedOnboardingNid', options),
];

export const getHostedOnboardingNidOptions = (options?: Options<GetHostedOnboardingNidData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedOnboardingNid({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedOnboardingNidQueryKey(options),
  });
};

export const getHostedOnboardingPrivacyPassQueryKey = (options?: Options<GetHostedOnboardingPrivacyPassData>) => [
  createQueryKey('getHostedOnboardingPrivacyPass', options),
];

export const getHostedOnboardingPrivacyPassOptions = (options?: Options<GetHostedOnboardingPrivacyPassData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedOnboardingPrivacyPass({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedOnboardingPrivacyPassQueryKey(options),
  });
};

export const postHostedOnboardingProcessQueryKey = (options?: Options<PostHostedOnboardingProcessData>) => [
  createQueryKey('postHostedOnboardingProcess', options),
];

export const postHostedOnboardingProcessOptions = (options?: Options<PostHostedOnboardingProcessData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingProcess({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingProcessQueryKey(options),
  });
};

export const postHostedOnboardingProcessMutation = (options?: Partial<Options<PostHostedOnboardingProcessData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingProcessResponse,
    AxiosError<PostHostedOnboardingProcessError>,
    Options<PostHostedOnboardingProcessData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingProcess({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedOnboardingSdsQueryKey = (options: Options<PostHostedOnboardingSdsData>) => [
  createQueryKey('postHostedOnboardingSds', options),
];

export const postHostedOnboardingSdsOptions = (options: Options<PostHostedOnboardingSdsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingSds({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingSdsQueryKey(options),
  });
};

export const postHostedOnboardingSdsMutation = (options?: Partial<Options<PostHostedOnboardingSdsData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingSdsResponse,
    AxiosError<PostHostedOnboardingSdsError>,
    Options<PostHostedOnboardingSdsData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingSds({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedOnboardingSessionQueryKey = (options?: Options<GetHostedOnboardingSessionData>) => [
  createQueryKey('getHostedOnboardingSession', options),
];

export const getHostedOnboardingSessionOptions = (options?: Options<GetHostedOnboardingSessionData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedOnboardingSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedOnboardingSessionQueryKey(options),
  });
};

export const postHostedOnboardingSkipPasskeyRegisterQueryKey = (
  options: Options<PostHostedOnboardingSkipPasskeyRegisterData>,
) => [createQueryKey('postHostedOnboardingSkipPasskeyRegister', options)];

export const postHostedOnboardingSkipPasskeyRegisterOptions = (
  options: Options<PostHostedOnboardingSkipPasskeyRegisterData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingSkipPasskeyRegister({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingSkipPasskeyRegisterQueryKey(options),
  });
};

export const postHostedOnboardingSkipPasskeyRegisterMutation = (
  options?: Partial<Options<PostHostedOnboardingSkipPasskeyRegisterData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingSkipPasskeyRegisterResponse,
    AxiosError<PostHostedOnboardingSkipPasskeyRegisterError>,
    Options<PostHostedOnboardingSkipPasskeyRegisterData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingSkipPasskeyRegister({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedOnboardingStatusQueryKey = (options?: Options<GetHostedOnboardingStatusData>) => [
  createQueryKey('getHostedOnboardingStatus', options),
];

export const getHostedOnboardingStatusOptions = (options?: Options<GetHostedOnboardingStatusData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedOnboardingStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedOnboardingStatusQueryKey(options),
  });
};

export const postHostedOnboardingTelQueryKey = (options: Options<PostHostedOnboardingTelData>) => [
  createQueryKey('postHostedOnboardingTel', options),
];

export const postHostedOnboardingTelOptions = (options: Options<PostHostedOnboardingTelData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingTel({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingTelQueryKey(options),
  });
};

export const postHostedOnboardingTelMutation = (options?: Partial<Options<PostHostedOnboardingTelData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingTelResponse,
    AxiosError<PostHostedOnboardingTelError>,
    Options<PostHostedOnboardingTelData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingTel({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedOnboardingTimelineQueryKey = (options: Options<PostHostedOnboardingTimelineData>) => [
  createQueryKey('postHostedOnboardingTimeline', options),
];

export const postHostedOnboardingTimelineOptions = (options: Options<PostHostedOnboardingTimelineData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingTimeline({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingTimelineQueryKey(options),
  });
};

export const postHostedOnboardingTimelineMutation = (options?: Partial<Options<PostHostedOnboardingTimelineData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingTimelineResponse,
    AxiosError<PostHostedOnboardingTimelineError>,
    Options<PostHostedOnboardingTimelineData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingTimeline({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedOnboardingValidateQueryKey = (options?: Options<PostHostedOnboardingValidateData>) => [
  createQueryKey('postHostedOnboardingValidate', options),
];

export const postHostedOnboardingValidateOptions = (options?: Options<PostHostedOnboardingValidateData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedOnboardingValidate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedOnboardingValidateQueryKey(options),
  });
};

export const postHostedOnboardingValidateMutation = (options?: Partial<Options<PostHostedOnboardingValidateData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedOnboardingValidateResponse,
    AxiosError<PostHostedOnboardingValidateError>,
    Options<PostHostedOnboardingValidateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedOnboardingValidate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserAttestDeviceQueryKey = (options: Options<PostHostedUserAttestDeviceData>) => [
  createQueryKey('postHostedUserAttestDevice', options),
];

export const postHostedUserAttestDeviceOptions = (options: Options<PostHostedUserAttestDeviceData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserAttestDevice({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserAttestDeviceQueryKey(options),
  });
};

export const postHostedUserAttestDeviceMutation = (options?: Partial<Options<PostHostedUserAttestDeviceData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserAttestDeviceResponse,
    AxiosError<PostHostedUserAttestDeviceError>,
    Options<PostHostedUserAttestDeviceData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserAttestDevice({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserAttestDeviceChallengeQueryKey = (
  options: Options<PostHostedUserAttestDeviceChallengeData>,
) => [createQueryKey('postHostedUserAttestDeviceChallenge', options)];

export const postHostedUserAttestDeviceChallengeOptions = (
  options: Options<PostHostedUserAttestDeviceChallengeData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserAttestDeviceChallenge({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserAttestDeviceChallengeQueryKey(options),
  });
};

export const postHostedUserAttestDeviceChallengeMutation = (
  options?: Partial<Options<PostHostedUserAttestDeviceChallengeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserAttestDeviceChallengeResponse,
    AxiosError<PostHostedUserAttestDeviceChallengeError>,
    Options<PostHostedUserAttestDeviceChallengeData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserAttestDeviceChallenge({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedUserAuthMethodsQueryKey = (options?: Options<GetHostedUserAuthMethodsData>) => [
  createQueryKey('getHostedUserAuthMethods', options),
];

export const getHostedUserAuthMethodsOptions = (options?: Options<GetHostedUserAuthMethodsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedUserAuthMethods({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedUserAuthMethodsQueryKey(options),
  });
};

export const getHostedUserAuthRequirementsQueryKey = (options?: Options<GetHostedUserAuthRequirementsData>) => [
  createQueryKey('getHostedUserAuthRequirements', options),
];

export const getHostedUserAuthRequirementsOptions = (options?: Options<GetHostedUserAuthRequirementsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedUserAuthRequirements({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedUserAuthRequirementsQueryKey(options),
  });
};

export const getHostedUserAuthorizedOrgsQueryKey = (options?: Options<GetHostedUserAuthorizedOrgsData>) => [
  createQueryKey('getHostedUserAuthorizedOrgs', options),
];

export const getHostedUserAuthorizedOrgsOptions = (options?: Options<GetHostedUserAuthorizedOrgsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedUserAuthorizedOrgs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedUserAuthorizedOrgsQueryKey(options),
  });
};

export const postHostedUserChallengeQueryKey = (options: Options<PostHostedUserChallengeData>) => [
  createQueryKey('postHostedUserChallenge', options),
];

export const postHostedUserChallengeOptions = (options: Options<PostHostedUserChallengeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserChallenge({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserChallengeQueryKey(options),
  });
};

export const postHostedUserChallengeMutation = (options?: Partial<Options<PostHostedUserChallengeData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserChallengeResponse,
    AxiosError<PostHostedUserChallengeError>,
    Options<PostHostedUserChallengeData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserChallenge({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserChallengeVerifyQueryKey = (options: Options<PostHostedUserChallengeVerifyData>) => [
  createQueryKey('postHostedUserChallengeVerify', options),
];

export const postHostedUserChallengeVerifyOptions = (options: Options<PostHostedUserChallengeVerifyData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserChallengeVerify({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserChallengeVerifyQueryKey(options),
  });
};

export const postHostedUserChallengeVerifyMutation = (
  options?: Partial<Options<PostHostedUserChallengeVerifyData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserChallengeVerifyResponse,
    AxiosError<PostHostedUserChallengeVerifyError>,
    Options<PostHostedUserChallengeVerifyData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserChallengeVerify({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserConsentQueryKey = (options: Options<PostHostedUserConsentData>) => [
  createQueryKey('postHostedUserConsent', options),
];

export const postHostedUserConsentOptions = (options: Options<PostHostedUserConsentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserConsent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserConsentQueryKey(options),
  });
};

export const postHostedUserConsentMutation = (options?: Partial<Options<PostHostedUserConsentData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserConsentResponse,
    AxiosError<PostHostedUserConsentError>,
    Options<PostHostedUserConsentData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserConsent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserDocumentsQueryKey = (options: Options<PostHostedUserDocumentsData>) => [
  createQueryKey('postHostedUserDocuments', options),
];

export const postHostedUserDocumentsOptions = (options: Options<PostHostedUserDocumentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserDocuments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserDocumentsQueryKey(options),
  });
};

export const postHostedUserDocumentsMutation = (options?: Partial<Options<PostHostedUserDocumentsData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserDocumentsResponse,
    AxiosError<PostHostedUserDocumentsError>,
    Options<PostHostedUserDocumentsData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserDocuments({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserDocumentsByIdProcessQueryKey = (
  options: Options<PostHostedUserDocumentsByIdProcessData>,
) => [createQueryKey('postHostedUserDocumentsByIdProcess', options)];

export const postHostedUserDocumentsByIdProcessOptions = (options: Options<PostHostedUserDocumentsByIdProcessData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserDocumentsByIdProcess({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserDocumentsByIdProcessQueryKey(options),
  });
};

export const postHostedUserDocumentsByIdProcessMutation = (
  options?: Partial<Options<PostHostedUserDocumentsByIdProcessData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserDocumentsByIdProcessResponse,
    AxiosError<PostHostedUserDocumentsByIdProcessError>,
    Options<PostHostedUserDocumentsByIdProcessData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserDocumentsByIdProcess({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserDocumentsByIdUploadBySideQueryKey = (
  options: Options<PostHostedUserDocumentsByIdUploadBySideData>,
) => [createQueryKey('postHostedUserDocumentsByIdUploadBySide', options)];

export const postHostedUserDocumentsByIdUploadBySideOptions = (
  options: Options<PostHostedUserDocumentsByIdUploadBySideData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserDocumentsByIdUploadBySide({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserDocumentsByIdUploadBySideQueryKey(options),
  });
};

export const postHostedUserDocumentsByIdUploadBySideMutation = (
  options?: Partial<Options<PostHostedUserDocumentsByIdUploadBySideData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserDocumentsByIdUploadBySideResponse,
    AxiosError<PostHostedUserDocumentsByIdUploadBySideError>,
    Options<PostHostedUserDocumentsByIdUploadBySideData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserDocumentsByIdUploadBySide({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserEmailVerifyQueryKey = (options: Options<PostHostedUserEmailVerifyData>) => [
  createQueryKey('postHostedUserEmailVerify', options),
];

export const postHostedUserEmailVerifyOptions = (options: Options<PostHostedUserEmailVerifyData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserEmailVerify({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserEmailVerifyQueryKey(options),
  });
};

export const postHostedUserEmailVerifyMutation = (options?: Partial<Options<PostHostedUserEmailVerifyData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserEmailVerifyResponse,
    AxiosError<PostHostedUserEmailVerifyError>,
    Options<PostHostedUserEmailVerifyData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserEmailVerify({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHostedUserPrivateTokenQueryKey = (options?: Options<GetHostedUserPrivateTokenData>) => [
  createQueryKey('getHostedUserPrivateToken', options),
];

export const getHostedUserPrivateTokenOptions = (options?: Options<GetHostedUserPrivateTokenData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedUserPrivateToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedUserPrivateTokenQueryKey(options),
  });
};

export const getHostedUserTokenQueryKey = (options?: Options<GetHostedUserTokenData>) => [
  createQueryKey('getHostedUserToken', options),
];

export const getHostedUserTokenOptions = (options?: Options<GetHostedUserTokenData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHostedUserToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHostedUserTokenQueryKey(options),
  });
};

export const postHostedUserTokensQueryKey = (options: Options<PostHostedUserTokensData>) => [
  createQueryKey('postHostedUserTokens', options),
];

export const postHostedUserTokensOptions = (options: Options<PostHostedUserTokensData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserTokens({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserTokensQueryKey(options),
  });
};

export const postHostedUserTokensMutation = (options?: Partial<Options<PostHostedUserTokensData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserTokensResponse,
    AxiosError<PostHostedUserTokensError>,
    Options<PostHostedUserTokensData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserTokens({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserUploadByDocumentIdentifierQueryKey = (
  options: Options<PostHostedUserUploadByDocumentIdentifierData>,
) => [createQueryKey('postHostedUserUploadByDocumentIdentifier', options)];

export const postHostedUserUploadByDocumentIdentifierOptions = (
  options: Options<PostHostedUserUploadByDocumentIdentifierData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserUploadByDocumentIdentifier({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserUploadByDocumentIdentifierQueryKey(options),
  });
};

export const postHostedUserUploadByDocumentIdentifierMutation = (
  options?: Partial<Options<PostHostedUserUploadByDocumentIdentifierData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserUploadByDocumentIdentifierResponse,
    AxiosError<PostHostedUserUploadByDocumentIdentifierError>,
    Options<PostHostedUserUploadByDocumentIdentifierData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserUploadByDocumentIdentifier({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const patchHostedUserVaultMutation = (options?: Partial<Options<PatchHostedUserVaultData>>) => {
  const mutationOptions: UseMutationOptions<
    PatchHostedUserVaultResponse,
    AxiosError<PatchHostedUserVaultError>,
    Options<PatchHostedUserVaultData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await patchHostedUserVault({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserVaultDecryptQueryKey = (options: Options<PostHostedUserVaultDecryptData>) => [
  createQueryKey('postHostedUserVaultDecrypt', options),
];

export const postHostedUserVaultDecryptOptions = (options: Options<PostHostedUserVaultDecryptData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserVaultDecrypt({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserVaultDecryptQueryKey(options),
  });
};

export const postHostedUserVaultDecryptMutation = (options?: Partial<Options<PostHostedUserVaultDecryptData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserVaultDecryptResponse,
    AxiosError<PostHostedUserVaultDecryptError>,
    Options<PostHostedUserVaultDecryptData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserVaultDecrypt({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postHostedUserVaultValidateQueryKey = (options: Options<PostHostedUserVaultValidateData>) => [
  createQueryKey('postHostedUserVaultValidate', options),
];

export const postHostedUserVaultValidateOptions = (options: Options<PostHostedUserVaultValidateData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postHostedUserVaultValidate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postHostedUserVaultValidateQueryKey(options),
  });
};

export const postHostedUserVaultValidateMutation = (options?: Partial<Options<PostHostedUserVaultValidateData>>) => {
  const mutationOptions: UseMutationOptions<
    PostHostedUserVaultValidateResponse,
    AxiosError<PostHostedUserVaultValidateError>,
    Options<PostHostedUserVaultValidateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postHostedUserVaultValidate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOrgSdkArgsQueryKey = (options?: Options<GetOrgSdkArgsData>) => [
  createQueryKey('getOrgSdkArgs', options),
];

export const getOrgSdkArgsOptions = (options?: Options<GetOrgSdkArgsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOrgSdkArgs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOrgSdkArgsQueryKey(options),
  });
};

export const postOrgSdkArgsQueryKey = (options: Options<PostOrgSdkArgsData>) => [
  createQueryKey('postOrgSdkArgs', options),
];

export const postOrgSdkArgsOptions = (options: Options<PostOrgSdkArgsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postOrgSdkArgs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postOrgSdkArgsQueryKey(options),
  });
};

export const postOrgSdkArgsMutation = (options?: Partial<Options<PostOrgSdkArgsData>>) => {
  const mutationOptions: UseMutationOptions<
    PostOrgSdkArgsResponse,
    AxiosError<PostOrgSdkArgsError>,
    Options<PostOrgSdkArgsData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postOrgSdkArgs({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postOrgSdkTelemetryQueryKey = (options: Options<PostOrgSdkTelemetryData>) => [
  createQueryKey('postOrgSdkTelemetry', options),
];

export const postOrgSdkTelemetryOptions = (options: Options<PostOrgSdkTelemetryData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postOrgSdkTelemetry({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postOrgSdkTelemetryQueryKey(options),
  });
};

export const postOrgSdkTelemetryMutation = (options?: Partial<Options<PostOrgSdkTelemetryData>>) => {
  const mutationOptions: UseMutationOptions<
    PostOrgSdkTelemetryResponse,
    AxiosError<PostOrgSdkTelemetryError>,
    Options<PostOrgSdkTelemetryData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await postOrgSdkTelemetry({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
