/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: financial_crime,violent_crime,sexual_crime,cyber_crime,terrorism,fraud,narcotics,general_serious,general_minor
 */
@Serializable
enum class AdverseMediaListKind(val value: kotlin.String) {

    @SerialName(value = "financial_crime")
    financial_crime("financial_crime"),

    @SerialName(value = "violent_crime")
    violent_crime("violent_crime"),

    @SerialName(value = "sexual_crime")
    sexual_crime("sexual_crime"),

    @SerialName(value = "cyber_crime")
    cyber_crime("cyber_crime"),

    @SerialName(value = "terrorism")
    terrorism("terrorism"),

    @SerialName(value = "fraud")
    fraud("fraud"),

    @SerialName(value = "narcotics")
    narcotics("narcotics"),

    @SerialName(value = "general_serious")
    general_serious("general_serious"),

    @SerialName(value = "general_minor")
    general_minor("general_minor");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AdverseMediaListKind) "$data" else null

        /**
         * Returns a valid [AdverseMediaListKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AdverseMediaListKind? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

