/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: exact_name_and_dob_year,exact_name,fuzzy_high,fuzzy_medium,fuzzy_low
 */
@Serializable
enum class AmlMatchKind(val value: kotlin.String) {

    @SerialName(value = "exact_name_and_dob_year")
    exact_name_and_dob_year("exact_name_and_dob_year"),

    @SerialName(value = "exact_name")
    exact_name("exact_name"),

    @SerialName(value = "fuzzy_high")
    fuzzy_high("fuzzy_high"),

    @SerialName(value = "fuzzy_medium")
    fuzzy_medium("fuzzy_medium"),

    @SerialName(value = "fuzzy_low")
    fuzzy_low("fuzzy_low");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AmlMatchKind) "$data" else null

        /**
         * Returns a valid [AmlMatchKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AmlMatchKind? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

