/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param op 
 * @param uuid 
 */
@Serializable

data class BatchHostedBusinessOwnerRequestDelete (

    @SerialName(value = "op") @Required val op: BatchHostedBusinessOwnerRequestDelete.Op,

    @SerialName(value = "uuid") @Required val uuid: kotlin.String

) {

    /**
     * 
     *
     * Values: delete
     */
    @Serializable
    enum class Op(val value: kotlin.String) {
        @SerialName(value = "delete") delete("delete");
    }

}

