/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeToken Opaque challenge state token
 * @param challengeResponse Required for challenges other than SMS link
 */
@Serializable

data class ChallengeVerifyRequest (

    /* Opaque challenge state token */
    @SerialName(value = "challenge_token") @Required val challengeToken: kotlin.String,

    /* Required for challenges other than SMS link */
    @SerialName(value = "challenge_response") val challengeResponse: kotlin.String? = null

) {


}

