/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param kind 
 */
@Serializable

data class CollectDocumentConfigProofOfSsn (

    @SerialName(value = "kind") @Required val kind: CollectDocumentConfigProofOfSsn.Kind

) {

    /**
     * 
     *
     * Values: proof_of_ssn
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "proof_of_ssn") proof_of_ssn("proof_of_ssn");
    }

}

