/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param kind 
 * @param shouldCollectConsent 
 * @param shouldCollectSelfie 
 * @param supportedCountryAndDocTypes 
 */
@Serializable

data class CollectDocumentConfigIdentity (

    @SerialName(value = "kind") @Required val kind: CollectDocumentConfigIdentity.Kind,

    @SerialName(value = "should_collect_consent") @Required val shouldCollectConsent: kotlin.Boolean,

    @SerialName(value = "should_collect_selfie") @Required val shouldCollectSelfie: kotlin.Boolean,

    @SerialName(value = "supported_country_and_doc_types") @Required val supportedCountryAndDocTypes: kotlin.String

) {

    /**
     * 
     *
     * Values: identity
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "identity") identity("identity");
    }

}

