/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DeviceType
import org.openapitools.client.models.DocumentFixtureResult
import org.openapitools.client.models.DocumentKind
import org.openapitools.client.models.Iso3166TwoDigitCountryCode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param documentType 
 * @param countryCode 
 * @param deviceType 
 * @param fixtureResult 
 * @param requestId 
 * @param skipSelfie 
 */
@Serializable

data class CreateDocumentRequest (

    @SerialName(value = "document_type") @Required val documentType: DocumentKind,

    @SerialName(value = "country_code") val countryCode: Iso3166TwoDigitCountryCode? = null,

    @SerialName(value = "device_type") val deviceType: DeviceType? = null,

    @SerialName(value = "fixture_result") val fixtureResult: DocumentFixtureResult? = null,

    @SerialName(value = "request_id") val requestId: kotlin.String? = null,

    @SerialName(value = "skip_selfie") val skipSelfie: kotlin.Boolean? = null

) {


}

