/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attestation base64 encoded attestation
 * @param state state from `DeviceAttestationChallengeResponse`
 */
@Serializable

data class CreateDeviceAttestationRequest (

    /* base64 encoded attestation */
    @SerialName(value = "attestation") @Required val attestation: kotlin.String,

    /* state from `DeviceAttestationChallengeResponse` */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

