/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.*

/**
 * 
 *
 */
@Serializable
enum class DataIdentifier(val value: kotlin.String) {

    @SerialName(value = "id.first_name")
    idFirstName("id.first_name"),

    @SerialName(value = "id.middle_name")
    idMiddleName("id.middle_name"),

    @SerialName(value = "id.last_name")
    idLastName("id.last_name"),

    @SerialName(value = "id.dob")
    idDob("id.dob"),

    @SerialName(value = "id.ssn4")
    idSsn4("id.ssn4"),

    @SerialName(value = "id.ssn9")
    idSsn9("id.ssn9"),

    @SerialName(value = "id.address_line1")
    idAddressLine1("id.address_line1"),

    @SerialName(value = "id.address_line2")
    idAddressLine2("id.address_line2"),

    @SerialName(value = "id.city")
    idCity("id.city"),

    @SerialName(value = "id.state")
    idState("id.state"),

    @SerialName(value = "id.zip")
    idZip("id.zip"),

    @SerialName(value = "id.country")
    idCountry("id.country"),

    @SerialName(value = "id.email")
    idEmail("id.email"),

    @SerialName(value = "id.phone_number")
    idPhoneNumber("id.phone_number"),

    @SerialName(value = "id.us_legal_status")
    idUsLegalStatus("id.us_legal_status"),

    @SerialName(value = "id.visa_kind")
    idVisaKind("id.visa_kind"),

    @SerialName(value = "id.visa_expiration_date")
    idVisaExpirationDate("id.visa_expiration_date"),

    @SerialName(value = "id.nationality")
    idNationality("id.nationality"),

    @SerialName(value = "id.citizenships")
    idCitizenships("id.citizenships"),

    @SerialName(value = "id.drivers_license_number")
    idDriversLicenseNumber("id.drivers_license_number"),

    @SerialName(value = "id.drivers_license_state")
    idDriversLicenseState("id.drivers_license_state"),

    @SerialName(value = "id.itin")
    idItin("id.itin"),

    @SerialName(value = "id.us_tax_id")
    idUsTaxId("id.us_tax_id"),

    @SerialName(value = "investor_profile.employment_status")
    investorProfileEmploymentStatus("investor_profile.employment_status"),

    @SerialName(value = "investor_profile.occupation")
    investorProfileOccupation("investor_profile.occupation"),

    @SerialName(value = "investor_profile.employer")
    investorProfileEmployer("investor_profile.employer"),

    @SerialName(value = "investor_profile.annual_income")
    investorProfileAnnualIncome("investor_profile.annual_income"),

    @SerialName(value = "investor_profile.net_worth")
    investorProfileNetWorth("investor_profile.net_worth"),

    @SerialName(value = "investor_profile.investment_goals")
    investorProfileInvestmentGoals("investor_profile.investment_goals"),

    @SerialName(value = "investor_profile.risk_tolerance")
    investorProfileRiskTolerance("investor_profile.risk_tolerance"),

    @SerialName(value = "investor_profile.declarations")
    investorProfileDeclarations("investor_profile.declarations"),

    @SerialName(value = "investor_profile.brokerage_firm_employer")
    investorProfileBrokerageFirmEmployer("investor_profile.brokerage_firm_employer"),

    @SerialName(value = "investor_profile.senior_executive_symbols")
    investorProfileSeniorExecutiveSymbols("investor_profile.senior_executive_symbols"),

    @SerialName(value = "investor_profile.family_member_names")
    investorProfileFamilyMemberNames("investor_profile.family_member_names"),

    @SerialName(value = "investor_profile.political_organization")
    investorProfilePoliticalOrganization("investor_profile.political_organization"),

    @SerialName(value = "investor_profile.funding_sources")
    investorProfileFundingSources("investor_profile.funding_sources");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DataIdentifier) "$data" else null

        /**
         * Returns a valid [DataIdentifier] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DataIdentifier? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}