/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: id_card,drivers_license,passport,passport_card,permit,visa,residence_document,voter_identification,ssn_card,proof_of_address,custom
 */
@Serializable
enum class DocumentKind(val value: kotlin.String) {

    @SerialName(value = "id_card")
    id_card("id_card"),

    @SerialName(value = "drivers_license")
    drivers_license("drivers_license"),

    @SerialName(value = "passport")
    passport("passport"),

    @SerialName(value = "passport_card")
    passport_card("passport_card"),

    @SerialName(value = "permit")
    permit("permit"),

    @SerialName(value = "visa")
    visa("visa"),

    @SerialName(value = "residence_document")
    residence_document("residence_document"),

    @SerialName(value = "voter_identification")
    voter_identification("voter_identification"),

    @SerialName(value = "ssn_card")
    ssn_card("ssn_card"),

    @SerialName(value = "proof_of_address")
    proof_of_address("proof_of_address"),

    @SerialName(value = "custom")
    custom("custom");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DocumentKind) "$data" else null

        /**
         * Returns a valid [DocumentKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DocumentKind? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

