/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DocumentRequestConfigIdentityData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class DocumentRequestConfigIdentity (

    @SerialName(value = "data") @Required val `data`: DocumentRequestConfigIdentityData,

    @SerialName(value = "kind") @Required val kind: DocumentRequestConfigIdentity.Kind

) {

    /**
     * 
     *
     * Values: identity
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "identity") identity("identity");
    }

}

