/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param hideButtons 
 * @param hideCancelButton 
 * @param hideFootprintLogo 
 */
@Serializable

data class FormV1Options (

    @SerialName(value = "hide_buttons") val hideButtons: kotlin.Boolean? = null,

    @SerialName(value = "hide_cancel_button") val hideCancelButton: kotlin.Boolean? = null,

    @SerialName(value = "hide_footprint_logo") val hideFootprintLogo: kotlin.Boolean? = null

) {


}

