/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DeviceAttestationType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deviceType 
 * @param androidPackageName required if running footprint sdk in android
 * @param iosBundleId required if running footprint sdk in ios
 */
@Serializable

data class GetDeviceAttestationChallengeRequest (

    @SerialName(value = "device_type") @Required val deviceType: DeviceAttestationType,

    /* required if running footprint sdk in android */
    @SerialName(value = "android_package_name") val androidPackageName: kotlin.String? = null,

    /* required if running footprint sdk in ios */
    @SerialName(value = "ios_bundle_id") val iosBundleId: kotlin.String? = null

) {


}

