/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InsightEvent

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param isVerified 
 * @param originInsightEvent 
 * @param tenantName 
 */
@Serializable

data class GetVerifyContactInfoResponse (

    @SerialName(value = "is_verified") @Required val isVerified: kotlin.Boolean,

    @SerialName(value = "origin_insight_event") @Required val originInsightEvent: InsightEvent,

    @SerialName(value = "tenant_name") @Required val tenantName: kotlin.String

) {


}

