/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.L10n

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Embeds extra information in the d2p token to pass from the desktop to handoff session.  NOTE: changes to this struct should be backwards-compatible since we may use this struct  to deserialize old versions
 *
 * @param l10n 
 * @param opener 
 * @param redirectUrl 
 * @param sandboxIdDocOutcome 
 * @param sessionId 
 * @param styleParams 
 */
@Serializable

data class HandoffMetadata (

    @SerialName(value = "l10n") val l10n: L10n? = null,

    @SerialName(value = "opener") val opener: kotlin.String? = null,

    @SerialName(value = "redirect_url") val redirectUrl: kotlin.String? = null,

    @SerialName(value = "sandbox_id_doc_outcome") val sandboxIdDocOutcome: kotlin.String? = null,

    @SerialName(value = "session_id") val sessionId: kotlin.String? = null,

    @SerialName(value = "style_params") val styleParams: kotlin.String? = null

) {


}

