/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WorkflowRequestConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param config 
 * @param note 
 */
@Serializable

data class HostedWorkflowRequest (

    @SerialName(value = "config") @Required val config: WorkflowRequestConfig,

    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

