/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param timestamp 
 * @param city 
 * @param country 
 * @param ipAddress 
 * @param latitude 
 * @param longitude 
 * @param metroCode 
 * @param postalCode 
 * @param region 
 * @param regionName 
 * @param sessionId 
 * @param timeZone 
 * @param userAgent 
 */
@Serializable

data class InsightEvent (

    @SerialName(value = "timestamp") @Required val timestamp: kotlinx.datetime.Instant,

    @SerialName(value = "city") val city: kotlin.String? = null,

    @SerialName(value = "country") val country: kotlin.String? = null,

    @SerialName(value = "ip_address") val ipAddress: kotlin.String? = null,

    @SerialName(value = "latitude") val latitude: kotlin.Double? = null,

    @SerialName(value = "longitude") val longitude: kotlin.Double? = null,

    @SerialName(value = "metro_code") val metroCode: kotlin.String? = null,

    @SerialName(value = "postal_code") val postalCode: kotlin.String? = null,

    @SerialName(value = "region") val region: kotlin.String? = null,

    @SerialName(value = "region_name") val regionName: kotlin.String? = null,

    @SerialName(value = "session_id") val sessionId: kotlin.String? = null,

    @SerialName(value = "time_zone") val timeZone: kotlin.String? = null,

    @SerialName(value = "user_agent") val userAgent: kotlin.String? = null

) {


}

