/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: employment_income,investments,inheritance,business_income,savings,family
 */
@Serializable
enum class InvestorProfileFundingSource(val value: kotlin.String) {

    @SerialName(value = "employment_income")
    employment_income("employment_income"),

    @SerialName(value = "investments")
    investments("investments"),

    @SerialName(value = "inheritance")
    inheritance("inheritance"),

    @SerialName(value = "business_income")
    business_income("business_income"),

    @SerialName(value = "savings")
    savings("savings"),

    @SerialName(value = "family")
    family("family");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InvestorProfileFundingSource) "$data" else null

        /**
         * Returns a valid [InvestorProfileFundingSource] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InvestorProfileFundingSource? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

