/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: affiliated_with_us_broker,senior_executive,senior_political_figure,family_of_political_figure
 */
@Serializable
enum class InvestorProfileDeclaration(val value: kotlin.String) {

    @SerialName(value = "affiliated_with_us_broker")
    affiliated_with_us_broker("affiliated_with_us_broker"),

    @SerialName(value = "senior_executive")
    senior_executive("senior_executive"),

    @SerialName(value = "senior_political_figure")
    senior_political_figure("senior_political_figure"),

    @SerialName(value = "family_of_political_figure")
    family_of_political_figure("family_of_political_figure");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InvestorProfileDeclaration) "$data" else null

        /**
         * Returns a valid [InvestorProfileDeclaration] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InvestorProfileDeclaration? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

