/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param businessAddressLine1 
 * @param businessAddressLine2 
 * @param businessBeneficialOwnerExplanationMessage 
 * @param businessBeneficialOwnersStarIdEmail 
 * @param businessBeneficialOwnersStarIdFirstName 
 * @param businessBeneficialOwnersStarIdLastName 
 * @param businessBeneficialOwnersStarIdPhoneNumber 
 * @param businessBeneficialOwnersStarOwnershipStake 
 * @param businessCity 
 * @param businessCorporationType 
 * @param businessCountry 
 * @param businessDba 
 * @param businessFormationDate 
 * @param businessFormationState 
 * @param businessName 
 * @param businessPhoneNumber 
 * @param businessState 
 * @param businessTin 
 * @param businessWebsite 
 * @param businessZip 
 * @param customStar 
 */
@Serializable

data class ModernRawBusinessDataRequest (

    @SerialName(value = "business.address_line1") val businessAddressLine1: kotlin.String? = null,

    @SerialName(value = "business.address_line2") val businessAddressLine2: kotlin.String? = null,

    @SerialName(value = "business.beneficial_owner_explanation_message") val businessBeneficialOwnerExplanationMessage: kotlin.String? = null,

    @SerialName(value = "business.beneficial_owners.*.id.email") val businessBeneficialOwnersStarIdEmail: kotlin.String? = null,

    @SerialName(value = "business.beneficial_owners.*.id.first_name") val businessBeneficialOwnersStarIdFirstName: kotlin.String? = null,

    @SerialName(value = "business.beneficial_owners.*.id.last_name") val businessBeneficialOwnersStarIdLastName: kotlin.String? = null,

    @SerialName(value = "business.beneficial_owners.*.id.phone_number") val businessBeneficialOwnersStarIdPhoneNumber: kotlin.String? = null,

    @SerialName(value = "business.beneficial_owners.*.ownership_stake") val businessBeneficialOwnersStarOwnershipStake: kotlin.String? = null,

    @SerialName(value = "business.city") val businessCity: kotlin.String? = null,

    @SerialName(value = "business.corporation_type") val businessCorporationType: kotlin.String? = null,

    @SerialName(value = "business.country") val businessCountry: kotlin.String? = null,

    @SerialName(value = "business.dba") val businessDba: kotlin.String? = null,

    @SerialName(value = "business.formation_date") val businessFormationDate: kotlin.String? = null,

    @SerialName(value = "business.formation_state") val businessFormationState: kotlin.String? = null,

    @SerialName(value = "business.name") val businessName: kotlin.String? = null,

    @SerialName(value = "business.phone_number") val businessPhoneNumber: kotlin.String? = null,

    @SerialName(value = "business.state") val businessState: kotlin.String? = null,

    @SerialName(value = "business.tin") val businessTin: kotlin.String? = null,

    @SerialName(value = "business.website") val businessWebsite: kotlin.String? = null,

    @SerialName(value = "business.zip") val businessZip: kotlin.String? = null,

    @SerialName(value = "custom.*") val customStar: kotlin.String? = null

) {


}

