/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CollectedDataOption

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * There is missing investor profile data that must be collected
 *
 * @param kind 
 * @param missingAttributes 
 * @param missingDocument 
 * @param populatedAttributes 
 */
@Serializable

data class OnboardingRequirementCollectInvestorProfile (

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementCollectInvestorProfile.Kind,

    @SerialName(value = "missing_attributes") @Required val missingAttributes: kotlin.collections.List<CollectedDataOption>,

    @SerialName(value = "missing_document") @Required val missingDocument: kotlin.Boolean,

    @SerialName(value = "populated_attributes") @Required val populatedAttributes: kotlin.collections.List<CollectedDataOption>

): OnboardingRequirement() {

    /**
     * 
     *
     * Values: collect_investor_profile
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "collect_investor_profile") collect_investor_profile("collect_investor_profile");
    }

}

