/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The flow requires a business, and one hasn't yet been created / selected
 *
 * @param kind 
 * @param requiresBusinessSelection When true, requires either selecting an existing business, or will create a new one upon  `POST /hosted/business/onboarding`.  When false, there's already a business associated with this session, so we can  immediately call `POST /hosted/business/onboarding`.
 */
@Serializable

data class OnboardingRequirementCreateBusinessOnboarding (

    @SerialName(value = "kind") @Required val kind: OnboardingRequirementCreateBusinessOnboarding.Kind,

    /* When true, requires either selecting an existing business, or will create a new one upon  `POST /hosted/business/onboarding`.  When false, there's already a business associated with this session, so we can  immediately call `POST /hosted/business/onboarding`. */
    @SerialName(value = "requires_business_selection") @Required val requiresBusinessSelection: kotlin.Boolean

): OnboardingRequirement() {

    /**
     * 
     *
     * Values: create_business_onboarding
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "create_business_onboarding") create_business_onboarding("create_business_onboarding");
    }

}

