/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DataIdentifier

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param authToken 
 * @param id 
 * @param canCopy 
 * @param defaultHidden 
 * @param label 
 * @param showHiddenToggle 
 */
@Serializable

data class RenderV1SdkArgs (

    @SerialName(value = "auth_token") @Required val authToken: kotlin.String,

    @SerialName(value = "id") @Required val id: DataIdentifier,

    @SerialName(value = "can_copy") val canCopy: kotlin.Boolean? = null,

    @SerialName(value = "default_hidden") val defaultHidden: kotlin.Boolean? = null,

    @SerialName(value = "label") val label: kotlin.String? = null,

    @SerialName(value = "show_hidden_toggle") val showHiddenToggle: kotlin.Boolean? = null

) {


}

