/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RenderV1SdkArgs

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class SdkArgsRenderV1 (

    @SerialName(value = "data") @Required val `data`: RenderV1SdkArgs,

    @SerialName(value = "kind") @Required val kind: SdkArgsRenderV1.Kind

) {

    /**
     * 
     *
     * Values: render_v1
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "render_v1") render_v1("render_v1");
    }

}

