/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param isBootstrap 
 * @param `value` 
 */
@Serializable

data class SignupChallengeRequestEmail (

    @SerialName(value = "is_bootstrap") @Required val isBootstrap: kotlin.Boolean,

    @SerialName(value = "value") @Required val `value`: kotlin.String

) {


}

