/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChallengeKind
import org.openapitools.client.models.IdentifyScope
import org.openapitools.client.models.SignupChallengeRequestEmail

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeKind 
 * @param scope 
 * @param email 
 * @param phoneNumber 
 */
@Serializable

data class SignupChallengeRequest (

    @SerialName(value = "challenge_kind") @Required val challengeKind: ChallengeKind,

    @SerialName(value = "scope") @Required val scope: IdentifyScope,

    @SerialName(value = "email") val email: SignupChallengeRequestEmail? = null,

    @SerialName(value = "phone_number") val phoneNumber: SignupChallengeRequestEmail? = null

) {


}

