/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeToken Information saved client side and sent back with the challenge response
 * @param timeBeforeRetryS The timeout until you're allowed to initiate another challenge
 * @param biometricChallengeJson If the challenge kind is biometric, the challenge JSON for the browser
 */
@Serializable

data class UserChallengeResponse (

    /* Information saved client side and sent back with the challenge response */
    @SerialName(value = "challenge_token") @Required val challengeToken: kotlin.String,

    /* The timeout until you're allowed to initiate another challenge */
    @SerialName(value = "time_before_retry_s") @Required val timeBeforeRetryS: kotlin.Long,

    /* If the challenge kind is biometric, the challenge JSON for the browser */
    @SerialName(value = "biometric_challenge_json") val biometricChallengeJson: kotlin.String? = null

) {


}

