/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChallengeKind

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeKind 
 * @param challengeToken 
 * @param timeBeforeRetryS 
 * @param biometricChallengeJson 
 * @param token Auth token to pass to the verify call
 */
@Serializable

data class UserChallengeData (

    @SerialName(value = "challenge_kind") @Required val challengeKind: ChallengeKind,

    @SerialName(value = "challenge_token") @Required val challengeToken: kotlin.String,

    @SerialName(value = "time_before_retry_s") @Required val timeBeforeRetryS: kotlin.Long,

    @SerialName(value = "biometric_challenge_json") val biometricChallengeJson: kotlin.String? = null,

    /* Auth token to pass to the verify call */
    @SerialName(value = "token") val token: kotlin.String? = null

) {


}

