/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.VerificationCheckKybData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class VerificationCheckKyb (

    @SerialName(value = "data") @Required val `data`: VerificationCheckKybData,

    @SerialName(value = "kind") @Required val kind: VerificationCheckKyb.Kind

) {

    /**
     * 
     *
     * Values: kyb
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "kyb") kyb("kyb");
    }

}

