/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AdverseMediaListKind
import org.openapitools.client.models.AmlMatchKind

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param adverseMedia 
 * @param continuousMonitoring 
 * @param matchKind 
 * @param ofac 
 * @param pep 
 * @param adverseMediaLists 
 */
@Serializable

data class VerificationCheckAmlData (

    @SerialName(value = "adverse_media") @Required val adverseMedia: kotlin.Boolean,

    @SerialName(value = "continuous_monitoring") @Required val continuousMonitoring: kotlin.Boolean,

    @SerialName(value = "match_kind") @Required val matchKind: AmlMatchKind,

    @SerialName(value = "ofac") @Required val ofac: kotlin.Boolean,

    @SerialName(value = "pep") @Required val pep: kotlin.Boolean,

    @SerialName(value = "adverse_media_lists") val adverseMediaLists: kotlin.collections.List<AdverseMediaListKind>? = null

) {


}

