/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.VerificationCheckAml
import org.openapitools.client.models.VerificationCheckBusinessAml
import org.openapitools.client.models.VerificationCheckCurpValidation
import org.openapitools.client.models.VerificationCheckIdentityDocument
import org.openapitools.client.models.VerificationCheckKyb
import org.openapitools.client.models.VerificationCheckKyc
import org.openapitools.client.models.VerificationCheckNeuroId
import org.openapitools.client.models.VerificationCheckPhone
import org.openapitools.client.models.VerificationCheckSentilink
import org.openapitools.client.models.VerificationCheckStytchDevice

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class VerificationCheck (

    @SerialName(value = "data") @Required val `data`: kotlin.String,

    @SerialName(value = "kind") @Required val kind: VerificationCheck.Kind

) {

    /**
     * 
     *
     * Values: sentilink
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "sentilink") sentilink("sentilink");
    }

}

