/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind 
 */
@Serializable

data class VerificationCheckBusinessAml (

    @SerialName(value = "data") @Required val `data`: kotlin.String,

    @SerialName(value = "kind") @Required val kind: VerificationCheckBusinessAml.Kind

) {

    /**
     * 
     *
     * Values: business_aml
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "business_aml") business_aml("business_aml");
    }

}

