/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.VerificationCheck

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param verificationChecks 
 */
@Serializable

data class WfrAdhocVendorCallConfig (

    @SerialName(value = "verification_checks") @Required val verificationChecks: kotlin.collections.List<VerificationCheck>

) {


}

