/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WfrOnboardConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind Allow onboarding onto the specific playbook.  This allows editing data, re-verifies data, and then re-triggers decision engine
 */
@Serializable

data class WorkflowRequestConfigOnboard (

    @SerialName(value = "data") @Required val `data`: WfrOnboardConfig,

    /* Allow onboarding onto the specific playbook.  This allows editing data, re-verifies data, and then re-triggers decision engine */
    @SerialName(value = "kind") @Required val kind: WorkflowRequestConfigOnboard.Kind

) {

    /**
     * Allow onboarding onto the specific playbook.  This allows editing data, re-verifies data, and then re-triggers decision engine
     *
     * Values: onboard
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "onboard") onboard("onboard");
    }

}

