/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WfrAdhocVendorCallConfig
import org.openapitools.client.models.WorkflowRequestConfigAdhocVendorCall
import org.openapitools.client.models.WorkflowRequestConfigDocument
import org.openapitools.client.models.WorkflowRequestConfigOnboard

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param kind Adhoc vendor call
 */
@Serializable

data class WorkflowRequestConfig (

    @SerialName(value = "data") @Required val `data`: WfrAdhocVendorCallConfig,

    /* Adhoc vendor call */
    @SerialName(value = "kind") @Required val kind: WorkflowRequestConfig.Kind

) {

    /**
     * Adhoc vendor call
     *
     * Values: adhoc_vendor_call
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "adhoc_vendor_call") adhoc_vendor_call("adhoc_vendor_call");
    }

}

