// This file is auto-generated by @hey-api/openapi-ts

import { type Options, createClient, createConfig } from '@hey-api/client-fetch';
import request from './request';
import { keysToCamelCase } from './transform-data';

import type {
  GetHostedBusinessError,
  GetHostedBusinessOwnersError,
  GetHostedBusinessOwnersResponse,
  GetHostedBusinessResponse,
  GetHostedBusinessesError,
  GetHostedBusinessesResponse,
  GetHostedCheckSessionError,
  GetHostedCheckSessionResponse,
  GetHostedOnboardingConfigError,
  GetHostedOnboardingConfigResponse,
  GetHostedOnboardingNidError,
  GetHostedOnboardingNidResponse,
  GetHostedOnboardingSessionError,
  GetHostedOnboardingSessionResponse,
  GetHostedOnboardingStatusError,
  GetHostedOnboardingStatusResponse,
  GetHostedUserAuthMethodsError,
  GetHostedUserAuthMethodsResponse,
  GetHostedUserAuthRequirementsError,
  GetHostedUserAuthRequirementsResponse,
  GetHostedUserAuthorizedOrgsError,
  GetHostedUserAuthorizedOrgsResponse,
  GetHostedUserTokenError,
  GetHostedUserTokenResponse,
  GetOrgSdkArgsError,
  GetOrgSdkArgsResponse,
  HostedOnboardingD2pGenerateData,
  HostedOnboardingD2pGenerateError,
  HostedOnboardingD2pGenerateResponse,
  HostedOnboardingD2pSmsData,
  HostedOnboardingD2pSmsError,
  HostedOnboardingD2pSmsResponse,
  HostedOnboardingD2pStatusError,
  HostedOnboardingD2pStatusPostData,
  HostedOnboardingD2pStatusPostError,
  HostedOnboardingD2pStatusPostResponse,
  HostedOnboardingD2pStatusResponse,
  PatchHostedBusinessOwnersData,
  PatchHostedBusinessOwnersError,
  PatchHostedBusinessOwnersResponse,
  PatchHostedBusinessVaultData,
  PatchHostedBusinessVaultError,
  PatchHostedBusinessVaultResponse,
  PatchHostedUserVaultData,
  PatchHostedUserVaultError,
  PatchHostedUserVaultResponse,
  PostHostedBusinessOnboardingData,
  PostHostedBusinessOnboardingError,
  PostHostedBusinessOnboardingResponse,
  PostHostedBusinessVaultDecryptData,
  PostHostedBusinessVaultDecryptError,
  PostHostedBusinessVaultDecryptResponse,
  PostHostedBusinessVaultValidateData,
  PostHostedBusinessVaultValidateError,
  PostHostedBusinessVaultValidateResponse,
  PostHostedDocumentsByIdProcessData,
  PostHostedDocumentsByIdProcessError,
  PostHostedDocumentsByIdProcessResponse,
  PostHostedDocumentsByIdUploadBySideData,
  PostHostedDocumentsByIdUploadBySideError,
  PostHostedDocumentsByIdUploadBySideResponse,
  PostHostedDocumentsData,
  PostHostedDocumentsError,
  PostHostedDocumentsResponse,
  PostHostedIdentifyData,
  PostHostedIdentifyError,
  PostHostedIdentifyKbaData,
  PostHostedIdentifyKbaError,
  PostHostedIdentifyKbaResponse,
  PostHostedIdentifyLiteData,
  PostHostedIdentifyLiteError,
  PostHostedIdentifyLiteResponse,
  PostHostedIdentifyLoginChallengeData,
  PostHostedIdentifyLoginChallengeError,
  PostHostedIdentifyLoginChallengeResponse,
  PostHostedIdentifyResponse,
  PostHostedIdentifySignupChallengeData,
  PostHostedIdentifySignupChallengeError,
  PostHostedIdentifySignupChallengeResponse,
  PostHostedIdentifyValidationTokenError,
  PostHostedIdentifyValidationTokenResponse,
  PostHostedIdentifyVerifyData,
  PostHostedIdentifyVerifyError,
  PostHostedIdentifyVerifyResponse,
  PostHostedOnboardingAuthorizeError,
  PostHostedOnboardingAuthorizeResponse,
  PostHostedOnboardingData,
  PostHostedOnboardingError,
  PostHostedOnboardingFpData,
  PostHostedOnboardingFpError,
  PostHostedOnboardingFpResponse,
  PostHostedOnboardingProcessData,
  PostHostedOnboardingProcessError,
  PostHostedOnboardingProcessResponse,
  PostHostedOnboardingResponse,
  PostHostedOnboardingSdsData,
  PostHostedOnboardingSdsError,
  PostHostedOnboardingSdsResponse,
  PostHostedOnboardingSkipPasskeyRegisterData,
  PostHostedOnboardingSkipPasskeyRegisterError,
  PostHostedOnboardingSkipPasskeyRegisterResponse,
  PostHostedOnboardingTelData,
  PostHostedOnboardingTelError,
  PostHostedOnboardingTelResponse,
  PostHostedOnboardingTimelineData,
  PostHostedOnboardingTimelineError,
  PostHostedOnboardingTimelineResponse,
  PostHostedOnboardingValidateError,
  PostHostedOnboardingValidateResponse,
  PostHostedUserAttestDeviceChallengeData,
  PostHostedUserAttestDeviceChallengeError,
  PostHostedUserAttestDeviceChallengeResponse,
  PostHostedUserAttestDeviceData,
  PostHostedUserAttestDeviceError,
  PostHostedUserAttestDeviceResponse,
  PostHostedUserChallengeData,
  PostHostedUserChallengeError,
  PostHostedUserChallengeResponse,
  PostHostedUserChallengeVerifyData,
  PostHostedUserChallengeVerifyError,
  PostHostedUserChallengeVerifyResponse,
  PostHostedUserConsentData,
  PostHostedUserConsentError,
  PostHostedUserConsentResponse,
  PostHostedUserDocumentsByIdProcessData,
  PostHostedUserDocumentsByIdProcessError,
  PostHostedUserDocumentsByIdProcessResponse,
  PostHostedUserDocumentsByIdUploadBySideData,
  PostHostedUserDocumentsByIdUploadBySideError,
  PostHostedUserDocumentsByIdUploadBySideResponse,
  PostHostedUserDocumentsData,
  PostHostedUserDocumentsError,
  PostHostedUserDocumentsResponse,
  PostHostedUserEmailVerifyData,
  PostHostedUserEmailVerifyError,
  PostHostedUserEmailVerifyResponse,
  PostHostedUserPrivateBoLinksError,
  PostHostedUserPrivateBoLinksResponse,
  PostHostedUserTokensData,
  PostHostedUserTokensError,
  PostHostedUserTokensResponse,
  PostHostedUserUploadByDocumentIdentifierData,
  PostHostedUserUploadByDocumentIdentifierError,
  PostHostedUserUploadByDocumentIdentifierResponse,
  PostHostedUserVaultDecryptData,
  PostHostedUserVaultDecryptError,
  PostHostedUserVaultDecryptResponse,
  PostHostedUserVaultValidateData,
  PostHostedUserVaultValidateError,
  PostHostedUserVaultValidateResponse,
  PostOrgSdkArgsData,
  PostOrgSdkArgsError,
  PostOrgSdkArgsResponse,
  PostOrgSdkTelemetryData,
  PostOrgSdkTelemetryError,
  PostOrgSdkTelemetryResponse,
} from '@onefootprint/request-types';

export const client = createClient(
  createConfig({
    responseTransformer: data => Promise.resolve(keysToCamelCase(data)),
    fetch: request,
  }),
);

/**
 * Get information about the business for which we started a KYC of a beneficial owner
 */
export const getHostedBusiness = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetHostedBusinessResponse, GetHostedBusinessError, ThrowOnError>({
    ...options,
    url: '/hosted/business',
  });
};

/**
 * Gets or creates the business Onboarding, optionally accepting an existing business. You can select an existing business from the results of `GET /hosted/businesses`.
 */
export const postHostedBusinessOnboarding = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedBusinessOnboardingData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedBusinessOnboardingResponse,
    PostHostedBusinessOnboardingError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/business/onboarding',
  });
};

/**
 * Get information about the beneficial owners of this business
 */
export const getHostedBusinessOwners = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetHostedBusinessOwnersResponse, GetHostedBusinessOwnersError, ThrowOnError>({
    ...options,
    url: '/hosted/business/owners',
  });
};

/**
 * Applies multiple operations in batch to update or create business owners. NOTE: the open API documentation for the request is extremely incorrect for this API.
 */
export const patchHostedBusinessOwners = <ThrowOnError extends boolean = false>(
  options: Options<PatchHostedBusinessOwnersData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    PatchHostedBusinessOwnersResponse,
    PatchHostedBusinessOwnersError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/business/owners',
  });
};

/**
 * Updates data in a business vault. Can be used to update `business.` data
 */
export const patchHostedBusinessVault = <ThrowOnError extends boolean = false>(
  options: Options<PatchHostedBusinessVaultData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    PatchHostedBusinessVaultResponse,
    PatchHostedBusinessVaultError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/business/vault',
  });
};

/**
 * Decrypts the specified list of fields from the provided vault.
 */
export const postHostedBusinessVaultDecrypt = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedBusinessVaultDecryptData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedBusinessVaultDecryptResponse,
    PostHostedBusinessVaultDecryptError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/business/vault/decrypt',
  });
};

/**
 * Checks if provided vault data is valid before adding it to the business vault
 */
export const postHostedBusinessVaultValidate = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedBusinessVaultValidateData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedBusinessVaultValidateResponse,
    PostHostedBusinessVaultValidateError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/business/vault/validate',
  });
};

/**
 * Get information about the businesses owned by the authenticated user
 */
export const getHostedBusinesses = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetHostedBusinessesResponse, GetHostedBusinessesError, ThrowOnError>({
    ...options,
    url: '/hosted/businesses',
  });
};

/**
 * Checks a hosted session token for expiration/validity
 */
export const getHostedCheckSession = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetHostedCheckSessionResponse, GetHostedCheckSessionError, ThrowOnError>({
    ...options,
    url: '/hosted/check_session',
  });
};

/**
 * Create a new document for the outstanding document request
 */
export const postHostedDocuments = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedDocumentsResponse, PostHostedDocumentsError, ThrowOnError>({
    ...options,
    url: '/hosted/documents',
  });
};

/**
 * Process the document and run any vendor verifications.
 */
export const postHostedDocumentsByIdProcess = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedDocumentsByIdProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedDocumentsByIdProcessResponse,
    PostHostedDocumentsByIdProcessError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/documents/{id}/process',
  });
};

/**
 * Upload an image for the given side to the provided document.
 */
export const postHostedDocumentsByIdUploadBySide = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedDocumentsByIdUploadBySideData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedDocumentsByIdUploadBySideResponse,
    PostHostedDocumentsByIdUploadBySideError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/documents/{id}/upload/{side}',
  });
};

/**
 * Tries to identify an existing user by either phone number or email. If the user is found, returns available challenge kinds.
 */
export const postHostedIdentify = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedIdentifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedIdentifyResponse, PostHostedIdentifyError, ThrowOnError>({
    ...options,
    url: '/hosted/identify',
  });
};

/**
 * Respond to a KBA challenge to prove knowledge of existing data in the vault.
 */
export const postHostedIdentifyKba = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedIdentifyKbaData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedIdentifyKbaResponse, PostHostedIdentifyKbaError, ThrowOnError>({
    ...options,
    url: '/hosted/identify/kba',
  });
};

/**
 * Tries to identify an existing user by either phone number or email and returns whether a user exists. This is used exclusively in our SDK to check proactively if bootstrapped data identifies an existing user. This is very similar to the normal identify API, but it has a much simpler API will hopefully be more stable than the normal identify API since changes will break old SDK versions.
 */
export const postHostedIdentifyLite = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedIdentifyLiteData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedIdentifyLiteResponse, PostHostedIdentifyLiteError, ThrowOnError>({
    ...options,
    url: '/hosted/identify/lite',
  });
};

/**
 * Sends a challenge to the phone number and returns an HTTP 200. When the challenge is completed through the identify/verify endpoint, the client can get or create the user with this phone number.
 */
export const postHostedIdentifyLoginChallenge = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedIdentifyLoginChallengeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedIdentifyLoginChallengeResponse,
    PostHostedIdentifyLoginChallengeError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/identify/login_challenge',
  });
};

/**
 * Sends a challenge to a phone number or email and returns an HTTP 200. When the challenge is completed through the identify/verify endpoint, the client can begin onboarding the user.
 */
export const postHostedIdentifySignupChallenge = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedIdentifySignupChallengeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedIdentifySignupChallengeResponse,
    PostHostedIdentifySignupChallengeError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/identify/signup_challenge',
  });
};

/**
 * Generate a validation token after the user finishes the identify flow.
 */
export const postHostedIdentifyValidationToken = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedIdentifyValidationTokenResponse,
    PostHostedIdentifyValidationTokenError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/identify/validation_token',
  });
};

/**
 * Verifies the response to either an SMS or biometric challenge. When the challenge response is verified, we will return an auth token for the user. If no user exists (which may only happen after a phone challenge), we will create a new user with the provided phone number
 */
export const postHostedIdentifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedIdentifyVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedIdentifyVerifyResponse,
    PostHostedIdentifyVerifyError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/identify/verify',
  });
};

/**
 * Gets or creates the Onboarding for this (user, ob_config) pair.
 */
export const postHostedOnboarding = <ThrowOnError extends boolean = false>(
  options?: Options<PostHostedOnboardingData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedOnboardingResponse, PostHostedOnboardingError, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding',
  });
};

/**
 * Mark the onboarding as authorized and initiate IDV checks
 */
export const postHostedOnboardingAuthorize = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedOnboardingAuthorizeResponse,
    PostHostedOnboardingAuthorizeError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/authorize',
  });
};

/**
 * Get the details of an onboarding configuration.
 */
export const getHostedOnboardingConfig = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostedOnboardingConfigResponse,
    GetHostedOnboardingConfigError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/config',
  });
};

/**
 * Generates a new d2p session token for the currently authenticated user. The d2p session token has a limited scope, and also includes some status metadata for syncing state across the phone and desktop.
 */
export const hostedOnboardingD2pGenerate = <ThrowOnError extends boolean = false>(
  options: Options<HostedOnboardingD2pGenerateData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    HostedOnboardingD2pGenerateResponse,
    HostedOnboardingD2pGenerateError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/d2p/generate',
  });
};

/**
 * Send an SMS with a link to the phone onboarding page.
 */
export const hostedOnboardingD2pSms = <ThrowOnError extends boolean = false>(
  options: Options<HostedOnboardingD2pSmsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<HostedOnboardingD2pSmsResponse, HostedOnboardingD2pSmsError, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding/d2p/sms',
  });
};

/**
 * Gets the status of the provided d2p session. Requires the d2p session token as the auth header.
 */
export const hostedOnboardingD2pStatus = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HostedOnboardingD2pStatusResponse,
    HostedOnboardingD2pStatusError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/d2p/status',
  });
};

/**
 * Update the status of the provided d2p session. Only allows updating to certain statuses.
 */
export const hostedOnboardingD2pStatusPost = <ThrowOnError extends boolean = false>(
  options: Options<HostedOnboardingD2pStatusPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    HostedOnboardingD2pStatusPostResponse,
    HostedOnboardingD2pStatusPostError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/d2p/status',
  });
};

/**
 * Records a fingerprint visitorID for the Fingerprint SDK in the frontend
 */
export const postHostedOnboardingFp = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedOnboardingFpData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedOnboardingFpResponse, PostHostedOnboardingFpError, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding/fp',
  });
};

/**
 * Retrieve identifier used for NeuroId
 */
export const getHostedOnboardingNid = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetHostedOnboardingNidResponse, GetHostedOnboardingNidError, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding/nid',
  });
};

/**
 * initiates privacy pass protocol.
 */
export const getHostedOnboardingPrivacyPass = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<void, unknown, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding/privacy_pass',
  });
};

/**
 * Continue processing the onboarding after user this stage of user input has finished
 */
export const postHostedOnboardingProcess = <ThrowOnError extends boolean = false>(
  options?: Options<PostHostedOnboardingProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedOnboardingProcessResponse,
    PostHostedOnboardingProcessError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/process',
  });
};

/**
 * Records a deviceSessionId from the Socure Device SDK in the frontend
 */
export const postHostedOnboardingSds = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedOnboardingSdsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedOnboardingSdsResponse, PostHostedOnboardingSdsError, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding/sds',
  });
};

/**
 * Fetch information from an existing onboarding session token.
 */
export const getHostedOnboardingSession = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostedOnboardingSessionResponse,
    GetHostedOnboardingSessionError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/session',
  });
};

/**
 * Tells us that a passkey registration was skipped
 */
export const postHostedOnboardingSkipPasskeyRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedOnboardingSkipPasskeyRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedOnboardingSkipPasskeyRegisterResponse,
    PostHostedOnboardingSkipPasskeyRegisterError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/skip_passkey_register',
  });
};

/**
 * Returns the status of the onboarding.
 */
export const getHostedOnboardingStatus = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostedOnboardingStatusResponse,
    GetHostedOnboardingStatusError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/status',
  });
};

/**
 * Performs a lookup with Stytch on the passed up telemetry_id and records the response + risk signals
 */
export const postHostedOnboardingTel = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedOnboardingTelData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedOnboardingTelResponse, PostHostedOnboardingTelError, ThrowOnError>({
    ...options,
    url: '/hosted/onboarding/tel',
  });
};

/**
 * Log a timeline event for this user using a frontend-provided page identifier
 */
export const postHostedOnboardingTimeline = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedOnboardingTimelineData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedOnboardingTimelineResponse,
    PostHostedOnboardingTimelineError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/timeline',
  });
};

/**
 * Finish onboarding the user. Returns the validation token that can be exchanged for a permanent Footprint user token.
 */
export const postHostedOnboardingValidate = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedOnboardingValidateResponse,
    PostHostedOnboardingValidateError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/onboarding/validate',
  });
};

/**
 * receive the attestation
 * Parses and accepts a user's onboarding device attestation
 */
export const postHostedUserAttestDevice = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserAttestDeviceData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserAttestDeviceResponse,
    PostHostedUserAttestDeviceError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/attest_device',
  });
};

/**
 * initiate the attestation challenge
 * Generate a device attestation challenge
 */
export const postHostedUserAttestDeviceChallenge = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserAttestDeviceChallengeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserAttestDeviceChallengeResponse,
    PostHostedUserAttestDeviceChallengeError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/attest_device/challenge',
  });
};

/**
 * Returns information about the auth methods this user has registered.
 */
export const getHostedUserAuthMethods = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetHostedUserAuthMethodsResponse, GetHostedUserAuthMethodsError, ThrowOnError>(
    {
      ...options,
      url: '/hosted/user/auth_methods',
    },
  );
};

/**
 * Returns the set of auth requirements to satisfy the auth portion of the playbook in the provided session
 */
export const getHostedUserAuthRequirements = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostedUserAuthRequirementsResponse,
    GetHostedUserAuthRequirementsError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/auth_requirements',
  });
};

/**
 * Returns a list of organizations onto which the user has onboarded
 */
export const getHostedUserAuthorizedOrgs = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostedUserAuthorizedOrgsResponse,
    GetHostedUserAuthorizedOrgsError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/authorized_orgs',
  });
};

/**
 * Sends a challenge of the requested kind
 */
export const postHostedUserChallenge = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserChallengeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedUserChallengeResponse, PostHostedUserChallengeError, ThrowOnError>({
    ...options,
    url: '/hosted/user/challenge',
  });
};

/**
 * Verify the previously sent challenge and attach the new form of contact info to the vault
 */
export const postHostedUserChallengeVerify = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserChallengeVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserChallengeVerifyResponse,
    PostHostedUserChallengeVerifyError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/challenge/verify',
  });
};

/**
 * Records a user's consent to collection of their images.
 */
export const postHostedUserConsent = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserConsentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedUserConsentResponse, PostHostedUserConsentError, ThrowOnError>({
    ...options,
    url: '/hosted/user/consent',
  });
};

/**
 * Create a new document for the outstanding document request
 */
export const postHostedUserDocuments = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedUserDocumentsResponse, PostHostedUserDocumentsError, ThrowOnError>({
    ...options,
    url: '/hosted/user/documents',
  });
};

/**
 * Process the document and run any vendor verifications.
 */
export const postHostedUserDocumentsByIdProcess = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserDocumentsByIdProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserDocumentsByIdProcessResponse,
    PostHostedUserDocumentsByIdProcessError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/documents/{id}/process',
  });
};

/**
 * Upload an image for the given side to the provided document.
 */
export const postHostedUserDocumentsByIdUploadBySide = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserDocumentsByIdUploadBySideData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserDocumentsByIdUploadBySideResponse,
    PostHostedUserDocumentsByIdUploadBySideError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/documents/{id}/upload/{side}',
  });
};

/**
 * Used to asynchronously verify a user's email address. Requires the token sent to the users email.
 */
export const postHostedUserEmailVerify = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserEmailVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserEmailVerifyResponse,
    PostHostedUserEmailVerifyError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/email/verify',
  });
};

/**
 * Generate links for all secondary BOs to complete onboarding onto a KYB playbook that requires KYC of all BOs.
 */
export const postHostedUserPrivateBoLinks = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserPrivateBoLinksResponse,
    PostHostedUserPrivateBoLinksError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/private/bo_links',
  });
};

/**
 * Returns information about the auth token. Can only be used in sandbox mode for demo tenants.
 */
export const getHostedUserPrivateToken = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<void, unknown, ThrowOnError>({
    ...options,
    url: '/hosted/user/private/token',
  });
};

/**
 * Returns information about a given auth token.
 */
export const getHostedUserToken = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetHostedUserTokenResponse, GetHostedUserTokenError, ThrowOnError>({
    ...options,
    url: '/hosted/user/token',
  });
};

/**
 * Create a new token with the requested scopes using the permissions granted by the existing token. Used to create a secondary token with more limited scope. The new token's expiry time is the same as the old token's
 */
export const postHostedUserTokens = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserTokensData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostHostedUserTokensResponse, PostHostedUserTokensError, ThrowOnError>({
    ...options,
    url: '/hosted/user/tokens',
  });
};

/**
 * POSTs a document to the vault
 */
export const postHostedUserUploadByDocumentIdentifier = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserUploadByDocumentIdentifierData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserUploadByDocumentIdentifierResponse,
    PostHostedUserUploadByDocumentIdentifierError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/upload/{documentIdentifier}',
  });
};

/**
 * Updates data in a user vault
 */
export const patchHostedUserVault = <ThrowOnError extends boolean = false>(
  options: Options<PatchHostedUserVaultData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<PatchHostedUserVaultResponse, PatchHostedUserVaultError, ThrowOnError>({
    ...options,
    url: '/hosted/user/vault',
  });
};

/**
 * Decrypts the specified list of fields from the provided vault.
 */
export const postHostedUserVaultDecrypt = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserVaultDecryptData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserVaultDecryptResponse,
    PostHostedUserVaultDecryptError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/vault/decrypt',
  });
};

/**
 * Checks if provided vault data is valid before adding it to the vault
 */
export const postHostedUserVaultValidate = <ThrowOnError extends boolean = false>(
  options: Options<PostHostedUserVaultValidateData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostHostedUserVaultValidateResponse,
    PostHostedUserVaultValidateError,
    ThrowOnError
  >({
    ...options,
    url: '/hosted/user/vault/validate',
  });
};

/**
 * Fetch information from an existing SDK args session.
 */
export const getOrgSdkArgs = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
  return (options?.client ?? client).get<GetOrgSdkArgsResponse, GetOrgSdkArgsError, ThrowOnError>({
    ...options,
    url: '/org/sdk_args',
  });
};

/**
 * Create a new session containing args for the SDK.
 */
export const postOrgSdkArgs = <ThrowOnError extends boolean = false>(
  options: Options<PostOrgSdkArgsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostOrgSdkArgsResponse, PostOrgSdkArgsError, ThrowOnError>({
    ...options,
    url: '/org/sdk_args',
  });
};

/**
 * Log contents of the HTTP body.
 */
export const postOrgSdkTelemetry = <ThrowOnError extends boolean = false>(
  options: Options<PostOrgSdkTelemetryData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<PostOrgSdkTelemetryResponse, PostOrgSdkTelemetryError, ThrowOnError>({
    ...options,
    url: '/org/sdk_telemetry',
  });
};
