import footprint from '@onefootprint/footprint-js';

export type { UserData } from './@types/user-data';
export { default as FootprintAuthButton } from './components/auth-button';
export { default as FootprintButton } from './components/footprint-button';
export { default as FootprintForm } from './components/footprint-form';
export { default as FootprintRender } from './components/footprint-render';
export type { AddressCityInputProps } from './components/onboarding-components/address-city-input';
export { default as AddressCityInput } from './components/onboarding-components/address-city-input';
export type { AddressCountryInputProps } from './components/onboarding-components/address-country-input';
export { default as AddressCountryInput } from './components/onboarding-components/address-country-input';
export type { AddressInputProps } from './components/onboarding-components/address-input';
export { default as AddressInput } from './components/onboarding-components/address-input';
export type { AddressLine1InputProps } from './components/onboarding-components/address-line-1-input';
export { default as AddressLine1Input } from './components/onboarding-components/address-line-1-input';
export type { AddressLine2InputProps } from './components/onboarding-components/address-line-2-input';
export { default as AddressLine2Input } from './components/onboarding-components/address-line-2-input';
export type { AddressStateInputProps } from './components/onboarding-components/address-state-input';
export { default as AddressStateInput } from './components/onboarding-components/address-state-input';
export type { AddressZipInputProps } from './components/onboarding-components/address-zip-input';
export { default as AddressZipInput } from './components/onboarding-components/address-zip-input';
export type { CustomInputProps } from './components/onboarding-components/custom-input';
export { default as CustomInput } from './components/onboarding-components/custom-input';
export type { CustomSelectProps } from './components/onboarding-components/custom-select';
export { default as CustomSelect } from './components/onboarding-components/custom-select';
export type { DobInputProps } from './components/onboarding-components/dob-input';
export { default as DobInput } from './components/onboarding-components/dob-input';
export type { EmailInputProps } from './components/onboarding-components/email-input';
export { default as EmailInput } from './components/onboarding-components/email-input';
export type { FirstNameInputProps } from './components/onboarding-components/first-name-input';
export { default as FirstNameInput } from './components/onboarding-components/first-name-input';
export type { FormProps } from './components/onboarding-components/form';
export { default as Form } from './components/onboarding-components/form';
export type { LastNameInputProps } from './components/onboarding-components/last-name-input';
export { default as LastNameInput } from './components/onboarding-components/last-name-input';
export type { MiddleNameInputProps } from './components/onboarding-components/middle-name-input';
export { default as MiddleNameInput } from './components/onboarding-components/middle-name-input';
export type { PhoneInputProps } from './components/onboarding-components/phone-input';
export { default as PhoneInput } from './components/onboarding-components/phone-input';
export { default as Provider } from './components/onboarding-components/provider';
export type { SSN4InputProps } from './components/onboarding-components/ssn-4-input';
export { default as SSN4Input } from './components/onboarding-components/ssn-4-input';
export type { SSN9INputProps } from './components/onboarding-components/ssn-9-input';
export { default as SSN9Input } from './components/onboarding-components/ssn-9-input';
export { default as FootprintVerifyButton } from './components/verify-button';
export { useFootprint } from './hooks/use-footprint';

export default footprint;
