name: Bundle size

on: [pull_request]

jobs:
  size:
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: '**/.next/**/*.{js,mjs,cjs}'
