import type { Config } from 'tailwindcss';
import type { PluginAPI } from 'tailwindcss/types/config';

const config: Omit<Config, 'content'> = {
  theme: {
    colors: {
      gray: {
        0: 'var(--gray-0)',
        25: 'var(--gray-25)',
        50: 'var(--gray-50)',
        100: 'var(--gray-100)',
        150: 'var(--gray-150)',
        200: 'var(--gray-200)',
        300: 'var(--gray-300)',
        400: 'var(--gray-400)',
        500: 'var(--gray-500)',
        600: 'var(--gray-600)',
        700: 'var(--gray-700)',
        800: 'var(--gray-800)',
        825: 'var(--gray-825)',
        850: 'var(--gray-850)',
        875: 'var(--gray-875)',
        900: 'var(--gray-900)',
        950: 'var(--gray-950)',
        1000: 'var(--gray-1000)',
      },
      red: {
        25: 'var(--red-25)',
        50: 'var(--red-50)',
        100: 'var(--red-100)',
        200: 'var(--red-200)',
        300: 'var(--red-300)',
        400: 'var(--red-400)',
        500: 'var(--red-500)',
        600: 'var(--red-600)',
        700: 'var(--red-700)',
        800: 'var(--red-800)',
      },
      yellow: {
        25: 'var(--yellow-25)',
        50: 'var(--yellow-50)',
        100: 'var(--yellow-100)',
        200: 'var(--yellow-200)',
        300: 'var(--yellow-300)',
        400: 'var(--yellow-400)',
        500: 'var(--yellow-500)',
        600: 'var(--yellow-600)',
        700: 'var(--yellow-700)',
        800: 'var(--yellow-800)',
        900: 'var(--yellow-900)',
      },
      green: {
        25: 'var(--green-25)',
        50: 'var(--green-50)',
        100: 'var(--green-100)',
        200: 'var(--green-200)',
        300: 'var(--green-300)',
        400: 'var(--green-400)',
        500: 'var(--green-500)',
        600: 'var(--green-600)',
        700: 'var(--green-700)',
        800: 'var(--green-800)',
      },
      blue: {
        25: 'var(--blue-25)',
        50: 'var(--blue-50)',
        100: 'var(--blue-100)',
        200: 'var(--blue-200)',
        300: 'var(--blue-300)',
        400: 'var(--blue-400)',
        500: 'var(--blue-500)',
        600: 'var(--blue-600)',
        700: 'var(--blue-700)',
        800: 'var(--blue-800)',
      },
      purple: {
        25: 'var(--purple-25)',
        50: 'var(--purple-50)',
        100: 'var(--purple-100)',
        200: 'var(--purple-200)',
        300: 'var(--purple-300)',
        400: 'var(--purple-400)',
        450: 'var(--purple-450)',
        500: 'var(--purple-500)',
        600: 'var(--purple-600)',
        700: 'var(--purple-700)',
        800: 'var(--purple-800)',
      },
      darkblue: {
        50: 'var(--darkblue-50)',
        100: 'var(--darkblue-100)',
        200: 'var(--darkblue-200)',
        300: 'var(--darkblue-300)',
        400: 'var(--darkblue-400)',
        500: 'var(--darkblue-500)',
        600: 'var(--darkblue-600)',
        700: 'var(--darkblue-700)',
        800: 'var(--darkblue-800)',
        900: 'var(--darkblue-900)',
      },
      'brand-sleep': {
        100: 'var(--brand-sleep-100)',
        200: 'var(--brand-sleep-200)',
        300: 'var(--brand-sleep-300)',
        800: 'var(--brand-sleep-800)',
      },
      'brand-think': {
        500: 'var(--brand-think-500)',
        800: 'var(--brand-think-800)',
      },
      'brand-go': {
        500: 'var(--brand-go-500)',
        800: 'var(--brand-go-800)',
      },
    },
    borderRadius: {
      none: '0px',
      xs: '2px',
      sm: '4px',
      DEFAULT: '6px',
      lg: '20px',
      full: '9999px',
    },
    extend: {
      outlineColor: {
        DEFAULT: 'var(--purple-500)',
      },
      backgroundColor: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        tertiary: 'var(--bg-tertiary)',
        quaternary: 'var(--bg-quaternary)',
        quinary: 'var(--bg-quinary)',
        senary: 'var(--bg-senary)',
        accent: 'var(--bg-accent)',
        error: 'var(--bg-error)',
        info: 'var(--bg-info)',
        success: 'var(--bg-success)',
        warning: 'var(--bg-warning)',
        neutral: 'var(--bg-neutral)',
        active: 'var(--bg-active)',
        infoInverted: 'var(--bg-info-inverted)',
        successInverted: 'var(--bg-success-inverted)',
        warningInverted: 'var(--bg-warning-inverted)',
        neutralInverted: 'var(--bg-neutral-inverted)',
        errorInverted: 'var(--bg-error-inverted)',
        transparent: 'var(--text-transparent)',
      },
      textColor: {
        transparent: 'var(--text-transparent)',
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        tertiary: 'var(--text-tertiary)',
        quaternary: 'var(--text-quaternary)',
        quinary: 'var(--text-quinary)',
        senary: 'var(--text-senary)',
        septenary: 'var(--text-septenary)',
        accent: 'var(--text-accent)',
        error: 'var(--text-error)',
        info: 'var(--text-info)',
        success: 'var(--text-success)',
        warning: 'var(--text-warning)',
        neutral: 'var(--text-neutral)',
        successInverted: 'var(--text-success-inverted)',
        warningInverted: 'var(--text-warning-inverted)',
        errorInverted: 'var(--text-error-inverted)',
        infoInverted: 'var(--text-info-inverted)',
        neutralInverted: 'var(--text-neutral-inverted)',
      },
      borderColor: {
        transparent: 'var(--border-transparent)',
        primary: 'var(--border-primary)',
        secondary: 'var(--border-secondary)',
        tertiary: 'var(--border-tertiary)',
        error: 'var(--border-error)',
        info: 'var(--border-info)',
        success: 'var(--border-success)',
        warning: 'var(--border-warning)',
        accent: 'var(--border-accent)',
      },
      fontFamily: {
        sans: ['var(--font-family-default)'],
        code: ['var(--font-family-code)'],
      },
    },
  },
  plugins: [
    ({ addUtilities }: PluginAPI) => {
      addUtilities({
        '.text-display-1': {
          fontWeight: '600',
          fontSize: '3.75rem',
          lineHeight: '4.75rem',
          letterSpacing: '-0.015em',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-display-2': {
          fontWeight: '600',
          fontSize: '2.5rem',
          lineHeight: '3.25rem',
          letterSpacing: '-0.015em',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-display-3': {
          fontWeight: '600',
          fontSize: '1.75rem',
          lineHeight: '2.25rem',
          letterSpacing: '-0.015em',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-display-4': {
          fontWeight: '400',
          fontSize: '1.3125rem',
          lineHeight: '2rem',
          letterSpacing: '-0.015em',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-display-5': {
          fontWeight: '400',
          fontSize: '1.1875rem',
          lineHeight: '1.875rem',
          letterSpacing: '-0.015em',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-heading-1': {
          fontWeight: '550',
          fontSize: '1.5rem',
          lineHeight: '2rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-heading-2': {
          fontWeight: '550',
          fontSize: '1.3125rem',
          lineHeight: '2rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-heading-3': {
          fontWeight: '550',
          fontSize: '1.125rem',
          lineHeight: '1.75rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-heading-4': {
          fontWeight: '550',
          fontSize: '1.0625rem',
          lineHeight: '1.75rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-heading-5': {
          fontWeight: '550',
          fontSize: '1rem',
          lineHeight: '1.5rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-body-1': {
          fontWeight: '400',
          fontSize: '1rem',
          lineHeight: '1.5rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-body-2': {
          fontWeight: '400',
          fontSize: '0.9375rem',
          lineHeight: '1.5rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-body-3': {
          fontWeight: '400',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-label-1': {
          fontWeight: '525',
          fontSize: '1rem',
          lineHeight: '1.5rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-label-2': {
          fontWeight: '525',
          fontSize: '0.9375rem',
          lineHeight: '1.5rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-label-3': {
          fontWeight: '525',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-caption-1': {
          fontWeight: '500',
          fontSize: '0.8125rem',
          lineHeight: '1rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-caption-2': {
          fontWeight: '400',
          fontSize: '0.8125rem',
          lineHeight: '1rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-caption-3': {
          fontWeight: '500',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-caption-4': {
          fontWeight: '400',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontFamily: 'var(--font-family-default)',
        },
        '.text-snippet-1': {
          fontWeight: '400',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontFamily: 'var(--font-family-code)',
        },
        '.text-snippet-2': {
          fontWeight: '400',
          fontSize: '0.8125rem',
          lineHeight: '1rem',
          fontFamily: 'var(--font-family-code)',
        },
        '.text-snippet-3': {
          fontWeight: '400',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontFamily: 'var(--font-family-code)',
        },
      });
    },
  ],
};

export default config;
