import type { TenantRoleKindDiscriminant, TenantScope } from '@onefootprint/request-types/dashboard';

// This map shows us, for a given scope, which role kinds are supported
export const supportedTenantRoleKinds: Record<TenantScope['kind'], TenantRoleKindDiscriminant[]> = {
  read: ['dashboard_user', 'api_key'],
  admin: ['dashboard_user', 'api_key'],
  api_keys: ['dashboard_user'],
  manage_vault_proxy: ['dashboard_user'],
  manage_webhooks: ['dashboard_user'],
  manual_review: ['dashboard_user'],
  onboarding_configuration: ['dashboard_user'],
  org_settings: ['dashboard_user'],
  write_lists: ['dashboard_user'],
  label_and_tag: ['dashboard_user'],
  cip_integration: ['api_key'],
  invoke_vault_proxy: ['api_key'],
  trigger_kyc: ['api_key'],
  trigger_kyb: ['api_key'],
  auth_token: ['api_key'],
  write_entities: ['api_key', 'dashboard_user'],
  onboarding: ['api_key'],
  decrypt_all: ['dashboard_user', 'api_key'],
  decrypt_document_and_selfie: ['dashboard_user', 'api_key'],
  decrypt: ['dashboard_user', 'api_key'],
  decrypt_custom: ['dashboard_user', 'api_key'],
  decrypt_document: ['dashboard_user', 'api_key'],
  compliance_partner_read: ['compliance_partner_dashboard_user'],
  compliance_partner_admin: ['compliance_partner_dashboard_user'],
  compliance_partner_manage_templates: ['compliance_partner_dashboard_user'],
  compliance_partner_manage_reviews: ['compliance_partner_dashboard_user'],
  manage_compliance_doc_submission: ['dashboard_user'],
  decrypt_all_except_pci_data: ['dashboard_user', 'api_key'],
} as const;

// This list is the list of all possible scopes
export const possibleTenantScopes: TenantScope['kind'][] = [
  'read',
  'admin',
  'api_keys',
  'manage_vault_proxy',
  'manage_webhooks',
  'manual_review',
  'onboarding_configuration',
  'write_lists',
  'org_settings',
  'cip_integration',
  'invoke_vault_proxy',
  'trigger_kyb',
  'trigger_kyc',
  'auth_token',
  'onboarding',
  'decrypt',
  'decrypt_custom',
  'decrypt_document',
  'decrypt_document_and_selfie',
  'decrypt_all',
  'decrypt_all_except_pci_data',
  'write_entities',
  'label_and_tag',
  'manage_compliance_doc_submission',
  'compliance_partner_read',
  'compliance_partner_admin',
  'compliance_partner_manage_templates',
  'compliance_partner_manage_reviews',
];
