import { useMutation } from '@tanstack/react-query';
import { BIOMETRIC_BASE_URL } from 'global-constants';
import request, { RequestError, RequestResponse } from 'request';
import { MY1FP_AUTH_HEADER } from 'src/config/constants';

export type D2PSmsRequest = {
  authToken: string; // scoped auth token generated by d2p
};

const d2pSms = async (payload: D2PSmsRequest) => {
  const { data: response } = await request<RequestResponse<{}>>({
    method: 'POST',
    url: '/hosted/onboarding/d2p/sms',
    data: {
      baseUrl: BIOMETRIC_BASE_URL,
    },
    headers: {
      [MY1FP_AUTH_HEADER]: payload.authToken,
    },
  });
  return response.data;
};

const useD2PSms = () => useMutation<{}, RequestError, D2PSmsRequest>(d2pSms);

export default useD2PSms;
