#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -d "frontend/node_modules" ]; then
  if [[ $(command -v node) != "" ]]; then
    cd frontend
    npx lint-staged
  fi
else
  echo "​​ℹ️​  Skipping frontend pre-commit hooks"
fi