name: 'Extract Component Commit Hash'
inputs:
  commitHash:
    required: false
outputs:
  apiComponentVersion:
    value: ${{ steps.constants.outputs.apiComponentVersion }}
  enclaveComponentVersion:
    value: ${{ steps.constants.outputs.enclaveComponentVersion }}
  expectedServerVersion:
    value: ${{ steps.constants.outputs.expectedServerVersion }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      with:
        ref: ${{ inputs.commitHash }}
        # We extract all commits here to make sure we're pulling the right commit hash
        fetch-depth: 0
    - name: Extract commit hash
      id: constants
      shell: bash
      run: |
        git --version

        imageTagPrefix="${{ (github.head_ref || github.ref_name) == 'master' && 'master-' || 'pr-' }}"
        # Match the file patterns to .github/workflows/backend_ci.yml
        expectedServerVersion="$(git log -n 1 --format="%H" ./backend ./.github/workflows/backend* ./.github/actions/backend*)"

        apiVersion="${imageTagPrefix}${expectedServerVersion}"
        enclaveVersion="${imageTagPrefix}$(git log -n 1 --format="%H" ./backend/components/enclave ./backend/infra ./backend/images/enclave ./backend/images/enclave-proxy)"

        echo "api is ${apiVersion}"
        echo "enclave is ${enclaveVersion}"

        echo "apiComponentVersion=${apiVersion}" >> $GITHUB_OUTPUT
        echo "enclaveComponentVersion=${enclaveVersion}" >> $GITHUB_OUTPUT
        echo "expectedServerVersion=${expectedServerVersion}" >> $GITHUB_OUTPUT
