name: Airplane Deploy

on:
  push:
    paths:
      - 'backend/internal_tools/**'

    branches:
      - master

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-airplane

jobs:
  airplane_deploy:
    name: airplane update
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Airplane deploy
        working-directory: ./backend/internal_tools/airplane
        run: |
          curl -L https://github.com/airplanedev/cli/releases/latest/download/install.sh | sh
          /home/runner/.airplane/bin/airplane deploy --env prod .
        env:
          AP_TEAM_ID: tea20220706zs7g4auu0i6
          AP_API_KEY: ${{ secrets.AIRPLANE_API_KEY }}
          AP_SOURCE: githubAction
