name: Broken Build Alert

on:
  push:
    branches: ['master']

jobs:
  wait:
    name: 'Wait for checks'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812
        with:
          ref: ${{ github.sha }}
          running-workflow-name: 'Wait for checks'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,cancelled

  alert:
    if: failure()
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - name: Notify on slack
        id: slack
        uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302 # ratchet:slackapi/slack-github-action@v1.21.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "user": "${{ github.event.head_commit.author.username }}",
              "url": "https://github.com/onefootprint/monorepo/commit/${{ github.sha }}/checks"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
