name: Backend Deploy Dev

on:
  workflow_call:
    inputs:
      commit_sha:
        type: string
        required: true

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-deploy-dev

jobs:
  extract_commit_hash:
    # We check out the commit that was passed in the workflow_call event, or
    # the HEAD of the branch for the manual workflow_dispatch. Then we
    # backtrack to the last commits that changed each component and deploy the
    # corresponding tags.
    runs-on: ubuntu-latest
    name: Compute commit hash
    outputs:
      apiCommitHash: "${{ steps.constants.outputs.apiCommitHash }}"
      apiComponentVersion: "${{ steps.components.outputs.apiComponentVersion }}"
      enclaveComponentVersion: "${{ steps.components.outputs.enclaveComponentVersion }}"
    steps:
      - name: Hash
        shell: bash
        id: constants
        run: |
          set -euxo pipefail

          echo "commit hash from workflow_call ${{ inputs.commit_sha }}"
          echo "commit hash over branch HEAD ${{ github.sha }}"
          commit_hash="${{ inputs.commit_sha || github.sha }}"
          echo "commit hash we will deploy in this workflow: $commit_hash"

          echo "apiCommitHash=${commit_hash}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      - uses: ./.github/actions/backend_extract_commit_hash
        id: components
        with:
          commitHash: ${{ steps.constants.outputs.apiCommitHash }}

  deploy_stack_dev:
    name: Deploy stack dev
    needs: [extract_commit_hash]
    uses: ./.github/workflows/backend_deploy.yml
    with:
      environment: dev
      baseStackName: dev
      stackName: dev
      commitHash: ${{ needs.extract_commit_hash.outputs.apiCommitHash }}
      apiComponentVersion: ${{ needs.extract_commit_hash.outputs.apiComponentVersion }}
      enclaveComponentVersion: ${{ needs.extract_commit_hash.outputs.enclaveComponentVersion }}

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ALT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALT }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}
      PULUMI_CLOUD_URL: ${{ secrets.PULUMI_CLOUD_URL }}
      AWS_SECRETS_PROVIDER: ${{ secrets.AWS_SECRETS_PROVIDER }}
      AIRPLANE_API_KEY: ${{ secrets.AIRPLANE_API_KEY }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

  run_tests:
    name: "integration tests"
    needs: [deploy_stack_dev, extract_commit_hash]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: "${{ needs.deploy_stack_dev.outputs.url }}"
      isPR: false
      expectedApiCommitHash: ${{ needs.extract_commit_hash.outputs.apiCommitHash }}
      environment_name: dev
    secrets:
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}
