name: Backend Destroy Ephemeral Stack
on:
  pull_request:
    types: [closed]

  workflow_dispatch:
    inputs:
      branchName:
        description: "Name of the branch whose stack to delete. DEV ONLY"
        required: true
        type: string

concurrency:
  group: "ephem-stack-group-${{ github.event.inputs.branchName || github.head_ref || github.run_id }}"

jobs:
  destroy_ephemeral_stack:
    name: Destroy Ephemeral Stack
    runs-on: ubuntu-latest
    environment: dev
    # don't run for bot changes and PRs that don't label ephemeral
    if: (!endsWith(github.actor, '[bot]')) && ((github.event_name != 'pull_request') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'FastEphemeral')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'FullEphemeral')))

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2

      # pulumi setup
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # ratchet:actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ALT }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALT }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812

      - name: Pulumi login
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}

      - run: yarn install
        working-directory: ./backend/infra

      - name: Extract stack name
        shell: bash
        run: |
          branch_raw="${{ github.event.inputs.branchName || github.head_ref }}"
          branch="$(echo ${branch_raw} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          stack="dev-${branch}"
          echo "##[set-output name=stack;]$(echo ${stack})"
        id: get_stack_name

      # create our temp stack
      - run: pulumi stack init --secrets-provider ${{ secrets.AWS_SECRETS_PROVIDER }} --copy-config-from "dev" "${{ steps.get_stack_name.outputs.stack }}" || true
        working-directory: ./backend/infra

      # copy our stack file just in case
      - run: cp Pulumi.dev.yaml Pulumi.${{ steps.get_stack_name.outputs.stack }}.yaml
        working-directory: ./backend/infra

      # get the url for the environment
      - name: Extract env url
        shell: bash
        working-directory: ./backend/infra
        run: |
          base=$(pulumi config --stack ${{ steps.get_stack_name.outputs.stack }} get --path constants.domain.base)
          url="${{ steps.get_stack_name.outputs.stack }}.${base}"
          echo "##[set-output name=url;]$(echo ${url})"
        id: extract_env_url

      - name: cancel current running
        run: pulumi cancel "${{ steps.get_stack_name.outputs.stack }}" -y || true
        working-directory: ./backend/infra

      - uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: refresh
          work-dir: ./backend/infra
          stack-name: "${{ steps.get_stack_name.outputs.stack }}"
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

      - uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: destroy
          work-dir: ./backend/infra
          stack-name: "${{ steps.get_stack_name.outputs.stack }}"
          message: "Destroyed ephemeral environment https://${{ steps.extract_env_url.outputs.url }}"
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

      # rm our temp stack
      - run: pulumi stack --stack ${{ steps.get_stack_name.outputs.stack }} rm -y
        working-directory: ./backend/infra
