name: Backend CI (skip)

on:
  push:
    branches:
      - master

    paths-ignore:
      - 'backend/**'

  pull_request:
    paths-ignore:
      - 'backend/**'

jobs:
  check_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not required"

  integration_migration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - run: echo "Not required"

  clippy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not required"