name: Backend Release
on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  staging_pr:
    name: Create Staging PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: extract version name
        id: version_name
        run: |
          input=${{inputs.version}}
          ref=${GITHUB_REF##*/}
          version="${input:-$ref}"
          echo "##[set-output name=version;]$(echo ${version})"

      - name: create branch
        run: |
          git checkout -b "staging/release-${{ steps.version_name.outputs.version }}"
          git push --set-upstream origin "staging/release-${{ steps.version_name.outputs.version }}"

      - name: token
        id: get_token
        uses: onefootprint/action-github-app-token@v1
        with:
          app_id: ${{ secrets.RELEASE_APP_ID }}
          private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Release] ${{ steps.version_name.outputs.version }}',
              owner,
              repo,
              head: owner + ':staging/release-${{ steps.version_name.outputs.version }}',
              base: 'production',
              body: [
                'This PR is automatically generated to stage a release',
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['release']
            });
