name: Backend Remote Integration Tests

on:
  workflow_call:
    inputs:
      testUrl:
        description: 'url to test against'
        type: string
        required: true

      prNumber:
        description: 'PR number to post results to'
        type: string
        required: false

      isPR:
        description: 'is this a PR? Only used for ephemeral'
        type: boolean
        default: false
        required: false

      waitForDeploy:
        description: 'whether to wait for an in-progress deploy to finish'
        type: boolean
        default: false
        required: false

      expectedCommitHash:
        description: 'hash of commit that we expect to be deployed'
        type: string
        required: false

      environment:
        description: 'secrets environment to use'
        type: string
        required: true

    secrets:
      IT_PHONE_NUMBERS:
        required: true
      IT_TWILIO_ACCOUNT_SID:
        required: true
      IT_TWILIO_SECRET_AUTH_TOKEN:
        required: true
      SVIX_AUTH_TOKEN:
        required: true

jobs:
  run_tests:
    name: remote integration tests
    runs-on: 8core
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        python-version: ['3.11']
    env:
      PR_NUMBER: ${{ inputs.prNumber }}
      TEST_URL: ${{ inputs.testUrl }}
      IT_PHONE_NUMBERS: ${{ secrets.IT_PHONE_NUMBERS }}
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      DITTO_URL: 'https://ditto.footprint.dev'
      SVIX_AUTH_TOKEN: ${{ secrets.SVIX_AUTH_TOKEN }}
      ENVIRONMENT: ${{ inputs.isPr && 'ephemeral' || inputs.environment }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.expectedCommitHash || github.sha }}
          # We extract all commits here to make sure we're pulling the right commit hash
          fetch-depth: 0

      - uses: ./.github/actions/backend_extract_commit_hash
        id: components
        with:
          commitHash: ${{ inputs.expectedCommitHash || github.sha }}

      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./backend/ci
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Integration testing
        working-directory: ./backend/ci
        run: |
          set -o pipefail
          pytest -n 6 tests/ 2>&1 | tee integration_test_output.txt
        env:
          EXPECTED_SERVER_VERSION: ${{ steps.components.outputs.expectedServerVersion }}

      - name: Create PR comment
        if: ${{ inputs.isPR && (success() || failure()) }}
        id: test_results
        working-directory: ./backend/ci
        run: |
          SHORT_SUMMARY=$(cat integration_test_output.txt | awk '/short test summary info/,0')
          FINISH=`awk '/===/{ print NR; }' integration_test_output.txt | sed -n 2p`
          CROP=$(expr $FINISH - 1)
          BEGIN=$(expr $FINISH - 7)
          cat integration_test_output.txt
          head -n $CROP integration_test_output.txt | tail -n $BEGIN > out.txt
          sed -i 's/\[.*%\]//g' out.txt
          sed -i 's/tests/* tests/g' out.txt
          echo '### Remote integration tests' > test_out.txt
          echo "Tested on ${{ inputs.testUrl }}" >> test_out.txt
          cat out.txt >> test_out.txt
          echo -e "$SHORT_SUMMARY" >> test_out.txt
          COMMENT="$(cat test_out.txt)"
          COMMENT="${COMMENT//'%'/'%25'}"
          COMMENT="${COMMENT//$'\n'/'%0A'}"
          COMMENT="${COMMENT//$'\r'/'%0D'}"
          echo "::set-output name=body::$COMMENT"

      - name: Find local comment
        uses: peter-evans/find-comment@v2.0.0
        if: ${{ inputs.isPR && github.ref != 'refs/heads/master' && (success() || failure()) }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Remote integration tests'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        if: ${{ inputs.isPR && github.ref != 'refs/heads/master' && (success() || failure()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.test_results.outputs.body }}
          edit-mode: replace
