name: Backend Refresh Stack

on:
  workflow_dispatch:
    inputs:
      stackName:
        description: 'Name of the stack to refresh'
        required: true
        type: string
        default: 'dev'

      environment:
        description: 'Environment to run against'
        type: environment
        required: true

jobs:
  refresh_stack:
    name: Refresh Stack
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2

      # pulumi setup
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # ratchet:actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812

      - name: Pulumi login
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}

      - run: yarn install
        working-directory: ./backend/infra

      # bring up the stack
      - uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: refresh
          work-dir: ./backend/infra
          stack-name: '${{ github.event.inputs.stackName }}'
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}
