name: Backend Build Master

on:
  push:
    paths:
      - 'backend/**'

    branches:
      - master

  workflow_dispatch:

jobs:
  build_backend:
    name: build backend
    uses: ./.github/workflows/backend_build.yml
    with:
      commitHash: ${{ github.event.pull_request.head.sha || github.sha }}
      rustVersion: 1.77.0
    # don't run for dependabot changes and only run when labeled ephemeral or infra changes detected
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}
