name: Backend Instant Deploy Production

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'Long hash of commit that we will be deploying. But, ensure that there is an image built for this commit'
        type: string
        required: true

jobs:
  instant_deploy_stack:
    name: deploy stack
    runs-on: ubuntu-latest
    outputs:
      url: 'https://${{ steps.constants.outputs.url }}'
      versionLong: '${{ steps.constants.outputs.versionLong }}'
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commitHash }}
          # We extract all commits here to make sure we're pulling the right commit hash
          fetch-depth: 0

      - uses: ./.github/actions/backend_extract_commit_hash
        id: components
        with:
          commitHash: ${{ inputs.commitHash }}

      # pulumi setup
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812

      - name: Pulumi login
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}

      - run: yarn install
        working-directory: ./backend/infra

      - name: Extract Constants
        shell: bash
        id: constants
        working-directory: ./backend/infra
        run: |
          pulumi stack select prod

          sub=$(pulumi config get --path constants.domain.prefix)
          base=$(pulumi config get --path constants.domain.base)
          url="${sub}${base}"

          git --version
          versionLong=$(git rev-parse HEAD)

          echo "url is ${url}"
          echo "api is ${{ steps.components.outputs.apiComponentVersion }}"
          echo "enclave is ${{ steps.components.outputs.enclaveComponentVersion }}"

          pulumi config set --path constants.containers.apiVersion ${{ steps.components.outputs.apiComponentVersion }}
          pulumi config set --path constants.containers.enclaveVersion ${{ steps.components.outputs.enclaveComponentVersion }}

      # bring up the stack
      - uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: up
          work-dir: ./backend/infra
          stack-name: prod
          message: 'Deployed to https://${{ steps.constants.outputs.url }} with api(${{ steps.constants.outputs.componentVersion }}) and enclave(${{ steps.components.outputs.enclaveComponentVersion }})'
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

  run_tests:
    name: 'integration tests'
    needs: [instant_deploy_stack]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.instant_deploy_stack.outputs.url }}'
      expectedCommitHash: ${{ needs.instant_deploy_stack.outputs.versionLong }}
      isPR: false
      environment_name: production
    secrets:
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}
