name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

  # We prefix tags with branch hints to avoid confusion with images built on
  # PRs. Images built on PRs may have different config (e.g. debug builds).
  IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'master-' || 'pr-' }}${{ github.event.pull_request.head.sha || github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-ci-check-test
  cancel-in-progress: true

jobs:
  files-changed:
    name: Determine if relevant files changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
        id: changes
        with:
          filters: |
            src:
              # Match the file patterns to .github/actions/backend_extract_commit_hash/action.yml
              - 'backend/**'
              - '.github/workflows/backend*'
              - '.github/actions/backend*'
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  build_images:
    name: Build images
    runs-on: 16core
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    strategy:
      matrix:
        include:
          - name: api
            dockerfile: api
            args:
              BUILD_PROFILE: ${{ github.ref == 'refs/heads/master' && 'release' || 'debug' }}
              GIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
          - name: enclave_proxy_pkg
            dockerfile: enclave-proxy
            args:
              BUILD_PROFILE: release
              CARGO_FEATURES: "vsock"
              GIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
          - name: enclave-proxy-dev
            dockerfile: enclave-proxy
            args:
              BUILD_PROFILE: debug
              CARGO_FEATURES: ""
              GIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
          - name: enclave
            dockerfile: enclave
            args:
              BUILD_PROFILE: release
          - name: enclave-dev
            dockerfile: enclave-dev
            args: {}
          - name: integration-tests
            dockerfile: integration-tests
            args: {}
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89 # ratchet:docker/setup-buildx-action@v3

      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR (Image Cache)
        id: login-ecr-image-cache
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Install Rust toolchain for usage by Swatinem/rust-cache
        uses: dtolnay/rust-toolchain@8be9e387b07ce3b7674d8037a26b3c8d72b6e510 # ratchet:dtolnay/rust-toolchain@1.79.0

      # Note that the cargo environment used by Swatinem/rust-cache to
      # construct a cache key is incorrect since we're actually building inside
      # Docker. This doesn't actually affect cache performance. However we
      # should keep the Rust toolchain above in sync with the one used in the
      # Dockerfiles for consistent behavior.
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # ratchet:Swatinem/rust-cache@v2
        id: rust-cache
        with:
          shared-key: image-build-${{ matrix.name }}-${{ matrix.args.BUILD_PROFILE || 'default' }}
          cache-all-crates: true
          workspaces: |
            backend

      - name: Inject Rust cache into Docker
        # Forked to use public.ecr.aws instead of Docker hub.
        uses: onefootprint/buildkit-cache-dance@0b57ad680b6cd71e30faf021b1f6eae15638062e
        with:
          cache-map: |
            {
              "./backend/target": "/build/target",
              "/home/runner/.cargo/registry": "/root/.cargo/registry"
            }
          skip-extraction: ${{ steps.rust-cache.outputs.cache-hit }}

      - name: Expose env vars to Docker for layer caching to the GHA cache
        uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3

      - name: Build image
        env:
          REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
          REPO: ${{ matrix.name }}
          TAG: ${{ env.IMAGE_TAG }}
        working-directory: ./backend
        run: |
          set -euxo pipefail

          # The image may already exist in the registry if we are retrying the
          # job after it already succeeded. Exit early in this case.
          IMG_REF=${REGISTRY}/${REPO}:${TAG}
          docker manifest inspect "${IMG_REF}" && echo "Image ${IMG_REF} has already been built. Skipping." && exit 0 || echo "Building ${IMG_REF}..."

          echo '${{toJSON(matrix.args) }}' | jq -r '. | to_entries | map("--build-arg \(.key)=\(.value | @sh)") | join(" ")' | \
            xargs docker buildx build \
              --platform linux/amd64 \
              --file ./images/${{ matrix.dockerfile }}/Dockerfile \
              --tag ${IMG_REF} \
              --push \
              --cache-to type=gha,scope=images-buildx,mode=max,compression=zstd,timeout=4m,ignore-error=true \
              --cache-from type=gha,scope=images-buildx,timeout=2m \
              .

  test:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core
    environment: backend_ci
    services:
      postgres:
        image: postgres:16.3@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libpq-dev

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@8be9e387b07ce3b7674d8037a26b3c8d72b6e510 # ratchet:dtolnay/rust-toolchain@1.79.0

      - uses: rui314/setup-mold@7f56dbde35ee02a3fe0287e7ddd310922eb5f553
        with:
          mold-version: 2.0.0
          make-default: false

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          shared-key: backend-test
          cache-all-crates: true
          workspaces: |
            backend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@43c891271eabca0b34d95f2453e2fe354928b16d #4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set dot env
        working-directory: ./backend
        run: make set-dot-env

      - name: Unset AWS Credentials
        uses: aws-actions/configure-aws-credentials@43c891271eabca0b34d95f2453e2fe354928b16d #4.0.1
        with:
          unset-current-credentials: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        working-directory: ./backend
        run: cargo test --all --no-default-features --features simulate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres

  clippy:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@8be9e387b07ce3b7674d8037a26b3c8d72b6e510 # ratchet:dtolnay/rust-toolchain@1.79.0
        with:
          components: clippy

      - uses: rui314/setup-mold@7f56dbde35ee02a3fe0287e7ddd310922eb5f553
        with:
          mold-version: 2.0.0
          make-default: false

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          save-if: false
          shared-key: backend-test
          workspaces: |
            backend

      - name: Clippy
        working-directory: ./backend
        run: cargo clippy --all --no-default-features --features simulate -- -D warnings

      - name: Clippy (vsock enabled)
        working-directory: ./backend
        run: cargo clippy -p enclave_proxy -p api_core --features vsock

  integration_tests:
    needs: [build_images]
    runs-on: 16core
    environment: backend_ci
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: ./.github/actions/backend_run_local
        with:
          commit_hash: ${{ github.event.pull_request.head.sha || github.sha }}
          image_tag: ${{ needs.build_images.outputs.image_tag }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          img_cache_aws_access_key_id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          img_cache_aws_secret_access_key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Run local integration tests
        working-directory: ./backend/ci
        env:
          # Make sure you configure backend/compose.yaml to forward these env
          # vars to the integration_test container or else they won't take effect.
          EXPECTED_SERVER_VERSION: ${{ github.event.pull_request.head.sha || github.sha }}
          TEST_URL: "http://localhost:8000"
          IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
          IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
          DITTO_URL: "https://ditto.footprint.dev"
          IT_SVIX_API_KEY: ${{ secrets.IT_SVIX_API_KEY }}
          ENVIRONMENT: ci
          FLAGS: ${{ github.ref == 'refs/heads/master' && '-v' || '' }}
        # Run pytest with -v verbose flag when running CI on master
        run: |
          set -euxo pipefail
          docker compose --env-file /dev/null run --quiet-pull integration_tests \
            pytest -n 6 ${{ env.FLAGS }} ci/tests/ 2>&1 | tee integration_test_output.txt

      - name: Extract Docker logs if tests failed
        if: ${{ failure() }}
        working-directory: ./backend
        run: |
          docker compose --env-file /dev/null logs > docker_logs.txt

      - name: Upload Docker logs if tests failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # ratchet:actions/upload-artifact@v4
        with:
          name: docker_logs.txt
          path: ./backend/docker_logs.txt

      - name: Create results for PR
        id: test_results
        if: ${{ github.ref != 'refs/heads/master' && (success() || failure()) }}
        working-directory: ./backend/ci
        run: |
          SHORT_SUMMARY=$(cat integration_test_output.txt | awk '/short test summary info/,0')
          FINISH=`awk '/===/{ print NR; }' integration_test_output.txt | sed -n 2p`
          CROP=$(expr $FINISH - 1)
          BEGIN=$(expr $FINISH - 7)
          cat integration_test_output.txt
          head -n $CROP integration_test_output.txt | tail -n $BEGIN > out.txt
          sed -i 's/\[.*%\]//g' out.txt
          sed -i 's/tests/* tests/g' out.txt
          echo '### Local integration tests' > test_out.txt
          cat out.txt >> test_out.txt
          if [ ! -z "$SHORT_SUMMARY" ]; then
            echo '```' >> test_out.txt
            echo -e "$SHORT_SUMMARY" >> test_out.txt
            echo '```' >> test_out.txt
          fi
          COMMENT="$(cat test_out.txt)"
          COMMENT="${COMMENT//'%'/'%25'}"
          COMMENT="${COMMENT//$'\n'/'%0A'}"
          COMMENT="${COMMENT//$'\r'/'%0D'}"
          echo "::set-output name=body::$COMMENT"

      - name: Find local comment
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d # ratchet:peter-evans/find-comment@v2.0.0
        if: ${{ github.ref != 'refs/heads/master' && (success() || failure()) }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Local integration tests"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # ratchet:peter-evans/create-or-update-comment@v2.0.0
        if: ${{ github.ref != 'refs/heads/master' && (success() || failure()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.test_results.outputs.body }}
          edit-mode: replace

      - name: Check valid db migrations
        working-directory: ./backend/ci/scripts
        run: |
          docker compose \
          --env-file /dev/null \
          run --quiet-pull integration_tests ./ci/scripts/check_db_migrations.sh

  openapi_check:
    needs: [build_images]
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/backend_open_api.yml
    secrets: inherit
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      pull_request_head_sha: ${{ github.event.pull_request.head.sha }}
      pull_request_base_sha: ${{ github.event.pull_request.base.sha }}

  rustfmt:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@64dec968ae28eba8cb36254ca81ecc9d3249ffd4 # ratchet:dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run rustfmt
        id: rustfmt
        run: cargo +nightly fmt --manifest-path ./backend/Cargo.toml --all --check > rustfmt_output.txt

      - name: Compose failure comment.txt
        if: failure()
        run: |
          set -x
          echo '### Rustfmt output:' > comment.txt
          echo 'Rustfmt failed. Please run `cargo +nightly fmt --all` to fix.' >> comment.txt
          echo '```diff' >> comment.txt
          cat rustfmt_output.txt >> comment.txt
          echo '```' >> comment.txt
          cat comment.txt

      - name: Compose success comment.txt
        if: success()
        run: |
          set -x
          echo '### Rustfmt output:' > comment.txt
          echo 'Rustfmt succeeded' >> comment.txt
          cat comment.txt

      - name: Find local rustfmt comment
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d
        if: ${{ github.ref != 'refs/heads/master' && (failure() || success()) }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Rustfmt output"

      - name: Create or update rustfmt comment
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        if: ${{ github.ref != 'refs/heads/master' && (failure() || success()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.txt
          edit-mode: replace

  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
  # Add all jobs in this workflow to this job's `needs`
  backend-ci:
    runs-on: ubuntu-latest
    needs: [build_images, test, clippy, integration_tests, rustfmt]
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  # This workflow may decide to not actually deploy the ephemeral stack.
  deploy-and-test-ephemeral:
    name: Ephemeral stack deploy and test
    needs: [build_images]
    if: ${{ github.ref != 'refs/heads/master' }}
    uses: ./.github/workflows/backend_deploy_ephemeral.yml
    secrets: inherit
    with:
      pull_request_head_sha: ${{ github.event.pull_request.head.sha || github.sha }}
      pull_request_number: ${{ github.event.pull_request.number }}
      image_tag: ${{ needs.build_images.outputs.image_tag }}

  deploy-and-test-dev:
    name: Dev deploy and test
    needs: [backend-ci]

    if: ${{ github.ref == 'refs/heads/master' }}

    uses: ./.github/workflows/backend_deploy_dev.yml
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}

  deploy-and-test-prod:
    name: Prod deploy and test

    # CRITICAL: ONLY DEPLOY TO PROD AFTER DEV TESTS SUCCEED
    needs: [backend-ci, deploy-and-test-dev]

    # CRITICAL: ONLY DEPLOY TO PROD ON MASTER
    if: ${{ github.ref == 'refs/heads/master' }}

    uses: ./.github/workflows/backend_deploy_prod.yml
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}
