name: Backend Deploy Dev

on:
  push:
    paths:
      - 'backend/infra/**'
      - 'backend/components/**'
      - 'backend/*.dockerfile'
      - '.github/workflows/backend_*.yml'

    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-deploy-dev

jobs:
  deploy_stack_dev:
    name: Deploy stack dev
    uses: ./.github/workflows/backend_build_and_deploy.yml
    with:
      environment: dev
      baseStackName: dev
      stackName: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}
      PULUMI_CLOUD_URL: ${{ secrets.PULUMI_CLOUD_URL }}
      AWS_SECRETS_PROVIDER: ${{ secrets.AWS_SECRETS_PROVIDER }}
      AIRPLANE_API_KEY: ${{ secrets.AIRPLANE_API_KEY }}

  sentry_release:
    name: 'Sentry Release Integration'
    runs-on: ubuntu-latest
    needs: [deploy_stack_dev]
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: onefootprint
          SENTRY_PROJECT: backend
        with:
          environment: dev

  run_tests:
    name: 'integration tests'
    needs: [deploy_stack_dev]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.deploy_stack_dev.outputs.url }}'
      isPR: false
      waitForDeploy: true
      environment: dev
    secrets:
      IT_PHONE_NUMBERS: ${{ secrets.IT_PHONE_NUMBERS }}
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      SVIX_AUTH_TOKEN: ${{ secrets.SVIX_AUTH_TOKEN }}
