name: Backend Open API

on:
  workflow_call:
    inputs:
      pull_request_number:
        type: string
        required: true
      pull_request_head_sha:
        type: string
        required: true
      pull_request_base_sha:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-ci-open-api
  cancel-in-progress: true

jobs:
  compute_open_api_head:
    runs-on: 16core
    environment: backend_ci
    outputs:
      commit: '${{ steps.commit.outputs.commit }}'
    steps:
      - uses: actions/checkout@v4
        # Default behavior of actions/checkout is horribly to check out a merge commit of the PR
        # merged into master...
        # This checks out the _actual_ commit in the PR
        # https://github.com/actions/checkout/issues/504
        with:
          ref: ${{ inputs.pull_request_head_sha }}

      - uses: ./.github/actions/backend_run_local
        with:
          commit_hash: ${{ inputs.pull_request_head_sha }}
          image_tag: ${{ inputs.pull_request_head_sha }}
          run_api_only: true
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          img_cache_aws_access_key_id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          img_cache_aws_secret_access_key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch open API schema
        working-directory: ./backend
        run: |
          set -euxo pipefail
          git log HEAD -n 1
          curl --fail http://172.17.0.1:8000/docs-spec-v3 | jq > ../head_open_api.json

      - uses: actions/upload-artifact@v3
        with:
          name: head-open-api
          path: head_open_api.json

      - id: commit
        run: |
          set -x
          echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"


  compute_open_api_base:
    runs-on: 16core
    environment: backend_ci
    outputs:
      commit: '${{ steps.commit.outputs.commit }}'
    steps:
      - uses: actions/checkout@v4
        # Default behavior of actions/checkout is horribly to check out a merge commit of the PR
        # merged into master...
        # This checks out the _actual_ commit in the PR
        # https://github.com/actions/checkout/issues/504
        with:
          ref: ${{ inputs.pull_request_head_sha }}
          fetch-depth: 0

      # Don't compare the current open API against current master, compare it against the base of this PR.
      # Otherwise, we'll see fake backwards incompatibilities with commits that have landed on master
      # since this PR was created
      # TODO: the pull_request.base.sha seems to be fixed in time when the PR is opened, because GH is dumb :(
      # This could be fixed with some horrible logic to parse the commit message of the merge commit made by the actions/checkout. More info below
      # https://github.com/orgs/community/discussions/59677
      # https://onefootprint.slack.com/archives/C044HVC8UM8/p1699653697437509
      - id: get_merge_base
        name: Compute merge base
        run: |
          set -x
          git log HEAD -n 1
          MERGE_BASE=$(git merge-base ${{ inputs.pull_request_head_sha }} ${{ inputs.pull_request_base_sha }})
          echo "Note: GHA is dumb - this merge base may be incorrect"
          echo "Merge base $MERGE_BASE"
          git log $MERGE_BASE -n 1
          echo "merge_base=$MERGE_BASE" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_merge_base.outputs.merge_base }}

      - uses: ./.github/actions/backend_run_local
        with:
          commit_hash: ${{ steps.get_merge_base.outputs.merge_base }}
          image_tag: ${{ steps.get_merge_base.outputs.merge_base }}
          run_api_only: true
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          img_cache_aws_access_key_id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          img_cache_aws_secret_access_key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch open API schema
        working-directory: ./backend
        run: |
          set -euxo pipefail
          git log HEAD -n 1
          curl --fail http://172.17.0.1:8000/docs-spec-v3 | jq > ../base_open_api.json

      - uses: actions/upload-artifact@v3
        with:
          name: base-open-api
          path: base_open_api.json

      - id: commit
        run: |
          set -x
          echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"


  compare_open_api:
    runs-on: 16core
    needs: [compute_open_api_head, compute_open_api_base]
    steps:
      - run: |
          set -x
          [[ ! -z "${{ needs.compute_open_api_head.outputs.commit }}" ]]
          [[ ! -z "${{ needs.compute_open_api_base.outputs.commit }}" ]]
          if test "${{ needs.compute_open_api_head.outputs.commit }}" = "${{ needs.compute_open_api_base.outputs.commit }}"
          then
            echo "Commits being compared are not different..."
            exit 1
          fi

      - name: Download head
        uses: actions/download-artifact@v3
        with:
          name: head-open-api

      - name: Download base
        uses: actions/download-artifact@v3
        with:
          name: base-open-api

      - name: Compare OpenAPI files
        id: compare_openapi
        uses: docker://openapitools/openapi-diff:2.0.1
        with:
          args: --fail-on-incompatible base_open_api.json head_open_api.json --text incompat_raw.txt

      - name: Print incompat.txt
        if: ${{ success() || failure() }}
        run: |
          set -x
          echo '### Open API Backcompat Report' >> incompat.txt
          echo '```' >> incompat.txt
          cat incompat_raw.txt >> incompat.txt
          echo '```' >> incompat.txt
          cat incompat.txt

      - name: Find local comment
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d
        id: fc
        if: ${{ success() || failure() }}
        with:
          issue-number: ${{ inputs.pull_request_number }}
          comment-author: 'github-actions[bot]'
          body-includes: "Open API Backcompat Report"

      - name: Create or update comment with incompat
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        if: ${{ steps.compare_openapi.outcome == 'failure' && (success() || failure()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ inputs.pull_request_number }}
          body-path: incompat.txt
          edit-mode: replace

      - name: Create or update comment with success
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        if: ${{ steps.compare_openapi.outcome == 'success' && (success() || failure()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ inputs.pull_request_number }}
          body: "### Open API Backcompat Report\nNo Open API backwards incompatibilities detected 👍"
          edit-mode: replace
