name: Backend Ephemeral Stack
on:
  pull_request:
    types: [labeled, reopened, opened, synchronize, edited]

  workflow_run:
    workflows: ['Tag Ephemeral']
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

jobs:
  wait_triage:
    name: Wait for triage labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for triage
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'triage'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped

  ephemeral_stack_name:
    name: Stack name
    runs-on: ubuntu-latest
    outputs:
      stackName: ${{ steps.constants.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract Constants
        id: constants
        shell: bash
        run: |
          branch_raw="${{ github.head_ref }}"
          branch="$(echo ${branch_raw} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          echo "friendly branch name is ${branch}"
          echo "::set-output name=branch::$(echo ${branch})"

  deploy_ephemeral_stack:
    name: deploy ephemeral
    needs: [ephemeral_stack_name, wait_triage]
    uses: ./.github/workflows/backend_build_and_deploy.yml
    # don't run for dependabot changes and only run when labeled ephemeral
    if: github.actor != 'dependabot[bot]' && contains( github.event.pull_request.labels.*.name, 'ephemeral')
    permissions:
      contents: write
      pull-requests: write
    with:
      environment: dev
      baseStackName: dev
      createStack: true
      stackName: 'dev-${{ needs.ephemeral_stack_name.outputs.stackName }}'
      prefixDomain: 'api-${{ needs.ephemeral_stack_name.outputs.stackName }}.'

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_SECRETS_PROVIDER: ${{ secrets.AWS_SECRETS_PROVIDER }}

  run_tests:
    name: 'ephemeral integration tests'
    needs: [deploy_ephemeral_stack]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.deploy_ephemeral_stack.outputs.url }}'
      prNumber: ${{ github.event.number }}
      waitForDeploy: true
      isPR: true
    secrets:
      INTEGRATION_TEST_PHONE_NUMBER: ${{ secrets.INTEGRATION_TEST_PHONE_NUMBER }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_KEY_SECRET: ${{ secrets.TWILIO_API_KEY_SECRET }}
