name: Backend Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "secrets environment to use"
        type: string
        required: true

      baseStackName:
        description: "base stack we're building, i.e. dev"
        type: string
        required: true

      stackName:
        description: "stack or possibly ephemeral stack name, i.e. dev"
        type: string
        required: true

      createStack:
        description: "create a new stack"
        type: boolean
        default: false
        required: false

      baseDomain:
        description: "override the base domain for the stack"
        type: string
        required: false

      prefixDomain:
        description: "override the prefix domain for the stack"
        type: string
        required: false

      useEphemeralHoneycombApiKey:
        description: "override the honeycomb API key for the stack with the ephemeral API key"
        type: boolean
        required: false
        default: false

      commitHash:
        description: "hash of commit that we will be deploying"
        type: string
        required: false

      useNeonDB:
        description: "uses NeonDB for faster ephemeral env"
        type: boolean
        required: false
        default: false

      apiComponentVersion:
        description: api container version
        required: true
        type: string

      enclaveComponentVersion:
        description: api container version
        required: true
        type: string

    outputs:
      url:
        description: "stack url"
        value: ${{ jobs.deploy_stack.outputs.url }}

    secrets:
      ENCLAVE_SIGNING_KEY:
        required: true
      ENCLAVE_SIGNING_CERT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SECRETS_PROVIDER:
        required: true
      PULUMI_CLOUD_URL:
        required: true
      IMG_CACHE_AWS_ACCESS_KEY_ID:
        required: true
      IMG_CACHE_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  copy_images:
    name: Copy container images to the target environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR (Image Cache)
        id: login-ecr-image-cache
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Configure AWS Credentials (Target Account)
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR (Target Account)
        id: login-ecr-target
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Install crane for copying images
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3

      - name: Copy API image to target ECR
        env:
          SRC_REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
          DST_REGISTRY: ${{ steps.login-ecr-target.outputs.registry }}
          REPO: api
          TAG: ${{ inputs.apiComponentVersion }}
        run: |
          crane cp ${SRC_REGISTRY}/${REPO}:${TAG} ${DST_REGISTRY}/${REPO}:${TAG}

      - name: Copy Enclave Proxy Package to target ECR
        env:
          SRC_REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
          DST_REGISTRY: ${{ steps.login-ecr-target.outputs.registry }}
          REPO: enclave_proxy_pkg
          TAG: ${{ inputs.enclaveComponentVersion }}
        run: |
          crane cp ${SRC_REGISTRY}/${REPO}:${TAG} ${DST_REGISTRY}/${REPO}:${TAG}

  sign_push_enclave:
    name: Sign and push enclave
    runs-on: eif-builder
    environment: ${{ inputs.environment }}
    steps:
      - name: Log in to Amazon ECR (Image Cache)
        id: login-ecr-image-cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          REGISTRY="$(aws sts get-caller-identity --query Account --output text).dkr.ecr.${AWS_REGION}.amazonaws.com"
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
          echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT

      - name: Log in to Amazon ECR (Target Account)
        id: login-ecr-target
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          REGISTRY="$(aws sts get-caller-identity --query Account --output text).dkr.ecr.${AWS_REGION}.amazonaws.com"
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
          echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT

      - name: Sign EIF and package if necessary
        # Run this in a temporary directory to convince ourselves this is hermetic.
        # This directory is automatically cleaned up at the end of the job.
        # On a self hosted runner, the runner.temp directory looks like this:
        #   /home/ec2-user/actions-runner/_work/_tem
        #
        # Since self-hosted runners can only run one job at at time[1], there's
        # no risk of one job run cleaning up another job's temporary directory.
        #
        # [1] https://github.com/orgs/community/discussions/26769#discussioncomment-3253321
        working-directory: ${{ runner.temp }}
        env:
          REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
          REPO: enclave
          TAG: ${{ inputs.enclaveComponentVersion }}
          # We package the EIF in a Docker image, even though it's not run as a container.
          EIF_REGISTRY: ${{ steps.login-ecr-target.outputs.registry }}
          EIF_REPO: enclave_pkg
          EIF_TAG: ${{ inputs.enclaveComponentVersion }}
        run: |
          set -euo pipefail
          # Don't set -x to avoid leaking signing key to logs.

          TMP_DIR=$(mktemp -d -p ${PWD})

          docker manifest inspect "${EIF_REGISTRY}/${EIF_REPO}:${EIF_TAG}" && echo "EIF package already exists in remote registry. Skipping sign & push." && exit 0 || echo "EIF package found in remote registry. Proceeding with sign & push."

          # Fetch the enclave image for signing
          docker pull ${REGISTRY}/${REPO}:${TAG}

          KEYS_DIR=${TMP_DIR}/keys
          mkdir ${KEYS_DIR}
          echo "${{ secrets.ENCLAVE_SIGNING_KEY }}" > ${KEYS_DIR}/enclavekey.pem
          echo "${{ secrets.ENCLAVE_SIGNING_CERT }}" > ${KEYS_DIR}/cert.pem

          EIF_DIR=${TMP_DIR}/eif
          mkdir ${EIF_DIR}

          # Build the EIF & defensively clean up the keys.
          nitro-cli build-enclave \
            --docker-uri ${REGISTRY}/${REPO}:${TAG} \
            --output-file ${EIF_DIR}/enclave.eif \
            --private-key ${KEYS_DIR}/enclavekey.pem \
            --signing-certificate ${KEYS_DIR}/cert.pem \
            && rm -rf ${KEYS_DIR} || (rm -rf ${KEYS_DIR} && exit 1)

          # Package the eif in docker image. On startup, the enclave EC2
          # instances will copy out the EIF from this image.
          #
          # Creating the package Dockerfile inline to avoid having to check out
          # the repository. As of June 7, 2024 on the stateful nitro-devbox,
          # it's unclear how the runner ever got access to the repository code.
          # It seemingly has an outdated copy of the repository, since there
          # was never a checkout action. In the future, we could add a checkout
          # action if we find a way to make it hermetic.
          PKG_DOCKERFILE=${TMP_DIR}/Dockerfile
          echo "FROM alpine:latest" >> ${PKG_DOCKERFILE}
          echo "COPY ./enclave.eif /usr/local/share/enclave.eif" >> ${PKG_DOCKERFILE}

          docker build -t "${EIF_REGISTRY}/${EIF_REPO}:${EIF_TAG}" -f ${PKG_DOCKERFILE} ${EIF_DIR}
          docker push "${EIF_REGISTRY}/${EIF_REPO}:${EIF_TAG}"

  deploy_stack:
    name: deploy stack
    runs-on: ubuntu-latest
    outputs:
      url: "${{ steps.pulumi_deploy.outputs.apiUrl }}"
    environment:
      name: ${{ inputs.environment }}
      url: "${{ steps.pulumi_deploy.outputs.apiUrl }}"
    needs: [copy_images, sign_push_enclave]
    if: success()
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ inputs.commitHash }}

      # pulumi setup
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # ratchet:actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812

      - name: Pulumi login
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}

      - run: yarn install
        working-directory: ./backend/infra

      # create our stack if needed
      - name: "create stack"
        if: ${{ inputs.createStack }}
        working-directory: ./backend/infra
        run: |
          pulumi stack init --secrets-provider ${{ secrets.AWS_SECRETS_PROVIDER }} --copy-config-from "${{ inputs.baseStackName }}" "${{ inputs.stackName  }}" || true
          cp Pulumi.${{ inputs.baseStackName }}.yaml Pulumi.${{ inputs.stackName }}.yaml

      - name: select stack
        working-directory: ./backend/infra
        run: pulumi stack select "${{ inputs.stackName }}"

      - name: "use fast ephemeral db"
        if: ${{ inputs.createStack && inputs.useNeonDB }}
        working-directory: ./backend/infra
        run: |
          pulumi config set useNeonEphemeralDbProjectId bitter-shape-200807

      - name: "override base domain"
        if: ${{ inputs.baseDomain || false }}
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.domain.base ${{ inputs.baseDomain }}

      - name: "override prefix domain"
        if: ${{ inputs.prefixDomain || false }}
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.domain.prefix ${{ inputs.prefixDomain }}

      - name: "override honeycomb API key"
        if: ${{ inputs.useEphemeralHoneycombApiKey || false }}
        working-directory: ./backend/infra
        run: |
          pulumi config set --secret --path constants.honeycomb.apiKey $(pulumi config get --path constants.honeycomb.ephemeralApiKey)

      - name: "set api/enclave image version"
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.containers.apiVersion ${{ inputs.apiComponentVersion }}
          pulumi config set --path constants.containers.enclaveVersion ${{ inputs.enclaveComponentVersion }}

      # refresh the state
      - name: "pulumi refresh"
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: refresh
          work-dir: ./backend/infra
          stack-name: "${{ inputs.stackName }}"
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}
          comment-on-pr: false

      # preview the stack
      - name: "pulumi preview"
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: preview
          work-dir: ./backend/infra
          stack-name: "${{ inputs.stackName }}"
          comment-on-pr: false
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

      # deploy the stack
      - name: "pulumi up"
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        id: pulumi_deploy
        with:
          command: up
          work-dir: ./backend/infra
          stack-name: "${{ inputs.stackName }}"
          message: "Deployed component ${{ inputs.apiComponentVersion }} and ${{ inputs.enclaveComponentVersion }}"
          comment-on-pr: true
          edit-pr-comment: true
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

      - name: Update deploy info on pull request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # ratchet:actions/github-script@v6
        with:
          script: |
            // get existing comments
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Find any comment already made by the bot.
            const botComment = comments.find(comment => comment.user.id === 41898282 && comment.body.includes('Deployed 🚀'));
            const commentBody = "**Deployed 🚀**\n\
            - URL: ${{ steps.pulumi_deploy.outputs.apiUrl }}\n\
            - Stack name: `${{ steps.pulumi_deploy.outputs.shortStackName }}`\n\
            - **api**: `${{ inputs.apiComponentVersion }}`\n\
            - **enclave**: `${{ inputs.enclaveComponentVersion }}`";

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
