name: Backend Instant Deploy Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'secrets environment to use'
        type: environment
        required: true

      stackName:
        description: 'stack or possibly ephemeral stack name, i.e. dev'
        type: string
        required: true

      shortHashVersion:
        description: 'Short SHA of API server image version (or latest)'
        type: string
        required: false
        default: 'latest'

jobs:
  instant_deploy_stack:
    name: deploy stack
    runs-on: ubuntu-latest
    outputs:
      url: 'https://${{ steps.constants.outputs.url }}'
    environment:
      name: ${{ inputs.environment }}
      url: 'https://${{ steps.constants.outputs.url }}'
    steps:
      - uses: actions/checkout@v2

      # pulumi setup
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812

      - name: Pulumi login
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}

      - run: yarn install
        working-directory: ./backend/infra

      # get environment constants
      - name: Extract Constants
        shell: bash
        working-directory: ./backend/infra
        run: |
          sub=$(pulumi config --stack ${{ inputs.stackName }} get --path constants.domain.prefix)
          base=$(pulumi config --stack ${{ inputs.stackName }} get --path constants.domain.base)
          url="${sub}${base}"
          version="${branch}-${{ inputs.shortHashVersion }}"
          echo "##[set-output name=url;]$(echo ${url})"
          echo "##[set-output name=componentVersion;]$(echo ${version})"
        id: constants

      - name: select stack
        working-directory: ./backend/infra
        run: pulumi stack select "${{ inputs.stackName }}"

      - name: 'set api/enclave image version'
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.containers.apiVersion ${{ steps.constants.outputs.componentVersion }}
          pulumi config set --path constants.containers.enclaveVersion ${{ steps.constants.outputs.componentVersion }}

      # bring up the stack
      - uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: up
          work-dir: ./backend/infra
          stack-name: '${{ inputs.stackName }}'
          message: 'Deployed to https://${{ steps.constants.outputs.url }} with component ${{ steps.constants.outputs.componentVersion }}'
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

  run_tests:
    name: 'integration tests'
    needs: [instant_deploy_stack]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.deploy_stack_dev.outputs.url }}'
      isPR: false
      waitForDeploy: true
      environment: ${{ inputs.environment }}
    secrets:
      INTEGRATION_TEST_PHONE_NUMBER: ${{ secrets.INTEGRATION_TEST_PHONE_NUMBER }}
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      SVIX_AUTH_TOKEN: ${{ secrets.SVIX_AUTH_TOKEN }}
