name: Backend Instant Deploy Production

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'Long hash of commit that we will be deploying. But, ensure that there is an image built for this commit'
        type: string
        required: true

jobs:
  instant_deploy_stack:
    name: deploy stack
    runs-on: ubuntu-latest
    outputs:
      url: 'https://${{ steps.constants.outputs.url }}'
      versionLong: '${{ steps.constants.outputs.versionLong }}'
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commitHash }}
          # We extract all commits here to make sure we're pulling the right commit hash
          fetch-depth: 0

      # pulumi setup
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812

      - name: Pulumi login
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}

      - run: yarn install
        working-directory: ./backend/infra

      - name: Extract Constants
        shell: bash
        id: constants
        working-directory: ./backend/infra
        run: |
          pulumi stack select prod

          sub=$(pulumi config get --path constants.domain.prefix)
          base=$(pulumi config get --path constants.domain.base)
          url="${sub}${base}"

          git --version
          versionLong=$(git rev-parse HEAD)
          apiVersion="master-$(git rev-parse --short HEAD)"
          enclaveVersion="master-$(git log -n 1 --format="%h" ../components/enclave)"

          echo "url is ${url}"
          echo "api is ${apiVersion}"
          echo "enclave is ${enclaveVersion}"

          pulumi config set --path constants.containers.apiVersion $apiVersion
          pulumi config set --path constants.containers.enclaveVersion $enclaveVersion

          echo "##[set-output name=url;]$(echo ${url})"
          echo "##[set-output name=componentVersion;]$(echo ${apiVersion})"
          echo "##[set-output name=versionLong;]$(echo ${versionLong})"

      # bring up the stack
      - uses: pulumi/actions@4204b4e8a7e703da96ba5dd4c3a667adeee35812
        with:
          command: up
          work-dir: ./backend/infra
          stack-name: prod
          message: 'Deployed to https://${{ steps.constants.outputs.url }} with component ${{ steps.constants.outputs.componentVersion }}'
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}

  run_tests:
    name: 'integration tests'
    needs: [instant_deploy_stack]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.instant_deploy_stack.outputs.url }}'
      expectedCommitHash: ${{ needs.instant_deploy_stack.outputs.versionLong }}
      isPR: false
      waitForDeploy: true
      environment: production
    secrets:
      IT_PHONE_NUMBERS: ${{ secrets.IT_PHONE_NUMBERS }}
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      SVIX_AUTH_TOKEN: ${{ secrets.SVIX_AUTH_TOKEN }}
