name: Backend Ephemeral Stack
on:
  workflow_call:
    inputs:
      pull_request_head_sha:
        type: string
        required: true
      pull_request_number:
        type: number
        required: true
      image_tag:
        type: string
        required: true

  # Re-run if the PR is manually labeled.
  pull_request:
    types: [labeled]

concurrency:
  group: "ephem-stack-group-${{ github.head_ref }}"

jobs:
  detect_ephemeral_stack:
    name: Detect ephemeral
    runs-on: ubuntu-latest
    outputs:
      stackName: ${{ steps.constants.outputs.branch }}
      hasInfraChanges: ${{ steps.detect.outputs.ephemeral }}
      needsFullInfra: ${{ steps.detect.outputs.full_ephemeral}}

      # The image_tag input isn't available for the pull_request trigger.
      imageTag: ${{ inputs.image_tag || format('pr-{0}', github.sha) }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          # We extract all commits here to make sure we're pulling the right commit hash
          fetch-depth: 0
          ref: ${{ inputs.pull_request_head_sha || github.sha }}

      - name: Extract Constants
        id: constants
        shell: bash
        run: |
          branch_raw="${{ github.head_ref }}"
          branch="$(echo ${branch_raw} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          echo "friendly branch name is ${branch}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT

      - name: Detect infra changes
        id: detect
        shell: bash
        run: |
          set -euxo pipefail

          git --version
          code_hash="$(git log -n 1 --format="%h" ./)"

          infra_hash="$(git log -n 1 --format="%h" ./backend/infra ':(exclude)backend/infra/Pulumi.prod.yaml' ':(exclude)backend/infra/src/alerts' ./backend/images/enclave ./backend/images/enclave-proxy ./.github/workflows/backend_deploy.yml ./.github/workflows/backend_deploy_ephemeral.yml)"
          infra_db_hash="$(git log -n 1 --format="%h" ./backend/infra/src/db.ts)"

          echo "code=${code_hash} infra=${infra_hash}"

          if [ "$code_hash" == "$infra_hash" ]; then
            echo "ephemeral=true" >> $GITHUB_OUTPUT
            if [ "$infra_db_hash" == "$infra_hash" ]; then
              echo "full_ephemeral=true" >> $GITHUB_OUTPUT
            else
              echo "full_ephemeral=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "ephemeral=false" >> $GITHUB_OUTPUT
          fi

  label_pr:
    needs: [detect_ephemeral_stack]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      # https://github.com/cli/cli/discussions/5307
      repository-projects: read
    steps:
      - name: Label FastEphemeral
        if: ${{ needs.detect_ephemeral_stack.outputs.hasInfraChanges == 'true' && needs.detect_ephemeral_stack.outputs.needsFullInfra == 'false' }}
        run: gh pr edit "$PR_NUMBER" --add-label "$LABEL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          LABEL: FastEphemeral
      - name: Label FastEphemeral
        if: ${{ needs.detect_ephemeral_stack.outputs.hasInfraChanges == 'true' && needs.detect_ephemeral_stack.outputs.needsFullInfra == 'true' }}
        run: gh pr edit "$PR_NUMBER" --add-label "$LABEL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          LABEL: FullEphemeral

  deploy_ephemeral_stack:
    name: Deploy ephemeral
    needs: [detect_ephemeral_stack]
    uses: ./.github/workflows/backend_deploy.yml
    # don't run for bot changes and only run when labeled ephemeral or infra changes detected
    if: !endsWith(github.actor, '[bot]') && (contains( github.event.pull_request.labels.*.name, 'FastEphemeral') || contains( github.event.pull_request.labels.*.name, 'FullEphemeral') || needs.detect_ephemeral_stack.outputs.hasInfraChanges == 'true')
    permissions:
      contents: write
      pull-requests: write
    with:
      environment: dev
      baseStackName: dev
      createStack: true
      stackName: "dev-${{ needs.detect_ephemeral_stack.outputs.stackName }}"
      prefixDomain: "api-${{ needs.detect_ephemeral_stack.outputs.stackName }}."
      useNeonDB: ${{ contains(github.event.pull_request.labels.*.name, 'FullEphemeral') || (needs.detect_ephemeral_stack.outputs.needsFullInfra == 'true') }}
      useEphemeralHoneycombApiKey: true
      # We deploy the images built for the PR HEAD commit to ephemeral.
      apiComponentVersion: ${{ inputs.image_tag || format('pr-{0}', github.sha) }}
      enclaveComponentVersion: ${{ inputs.image_tag || format('pr-{0}', github.sha) }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ALT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALT }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}
      PULUMI_CLOUD_URL: ${{ secrets.PULUMI_CLOUD_URL }}
      AWS_SECRETS_PROVIDER: ${{ secrets.AWS_SECRETS_PROVIDER_ALT }}
      AIRPLANE_API_KEY: ${{ secrets.AIRPLANE_API_KEY }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

  run_tests:
    name: Ephemeral integration tests
    needs: [deploy_ephemeral_stack]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: "${{ needs.deploy_ephemeral_stack.outputs.url }}"
      isPR: true
      expectedApiCommitHash: ${{ inputs.pull_request_head_sha || github.sha }}
      environment_name: ephemeral
    secrets:
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}
