name: Backend Remote Integration Tests

on:
  workflow_call:
    inputs:
      testUrl:
        description: 'url to test against'
        type: string
        required: true

      isPR:
        description: 'is this a PR? Only used for ephemeral'
        type: boolean
        required: true

      expectedApiCommitHash:
        description: 'hash of commit that we expect to be deployed'
        type: string
        required: true

      environment_name:
        description: 'name of the environment in which tests are running, passed to integration tests'
        type: string
        required: true

    secrets:
      IT_TWILIO_ACCOUNT_SID:
        required: true
      IT_TWILIO_SECRET_AUTH_TOKEN:
        required: true
      IT_SVIX_API_KEY:
        required: false
      AWS_REGION:
        required: true
      IMG_CACHE_AWS_ACCESS_KEY_ID:
        required: true
      IMG_CACHE_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  run_tests:
    name: remote integration tests
    runs-on: 8core

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ inputs.expectedApiCommitHash }}

      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR (Image Cache)
        id: login-ecr-image-cache
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Run remote integration tests
        working-directory: ./backend/ci
        env:
          REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
          TAG: ${{ inputs.isPR && 'pr-' || 'master-' }}${{ inputs.expectedApiCommitHash }}

          # Make sure you configure backend/compose.yaml to forward these env
          # vars to the integration_test container or else they won't take effect.
          EXPECTED_SERVER_VERSION: ${{ inputs.expectedApiCommitHash }}
          TEST_URL: ${{ inputs.testUrl }}
          IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
          IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
          DITTO_URL: 'https://ditto.footprint.dev'
          IT_SVIX_API_KEY: ${{ secrets.IT_SVIX_API_KEY }}
          ENVIRONMENT: ${{ inputs.environment_name }}
        run: |
          set -euxo pipefail

          # Use the pre-built image for integration tests.
          export CI_IMAGE_INTEGRATION_TESTS="${REGISTRY}/integration-tests:${TAG}"

          docker compose run --quiet-pull integration_tests \
            pytest -n 6 ci/tests/ 2>&1 | tee integration_test_output.txt

      - name: Create PR comment
        if: ${{ inputs.isPR && (success() || failure()) }}
        id: test_results
        working-directory: ./backend/ci
        run: |
          SHORT_SUMMARY=$(cat integration_test_output.txt | awk '/short test summary info/,0')
          FINISH=`awk '/===/{ print NR; }' integration_test_output.txt | sed -n 2p`
          CROP=$(expr $FINISH - 1)
          BEGIN=$(expr $FINISH - 7)
          cat integration_test_output.txt
          head -n $CROP integration_test_output.txt | tail -n $BEGIN > out.txt
          sed -i 's/\[.*%\]//g' out.txt
          sed -i 's/tests/* tests/g' out.txt
          echo '### Remote integration tests' > test_out.txt
          echo "Tested on ${{ inputs.testUrl }}" >> test_out.txt
          cat out.txt >> test_out.txt
          echo -e "$SHORT_SUMMARY" >> test_out.txt
          COMMENT="$(cat test_out.txt)"
          COMMENT="${COMMENT//'%'/'%25'}"
          COMMENT="${COMMENT//$'\n'/'%0A'}"
          COMMENT="${COMMENT//$'\r'/'%0D'}"
          echo "::set-output name=body::$COMMENT"

      - name: Find local comment
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d # ratchet:peter-evans/find-comment@v2.0.0
        if: ${{ inputs.isPR && github.ref != 'refs/heads/master' && (success() || failure()) }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Remote integration tests'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # ratchet:peter-evans/create-or-update-comment@v2.0.0
        if: ${{ inputs.isPR && github.ref != 'refs/heads/master' && (success() || failure()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.test_results.outputs.body }}
          edit-mode: replace
