name: Backend Build and Deploy Stack

on:
  workflow_call:
    inputs:
      environment:
        description: 'secrets environment to use'
        type: string
        required: true

      baseStackName:
        description: "base stack we're building, i.e. dev"
        type: string
        required: true

      stackName:
        description: 'stack or possibly ephemeral stack name, i.e. dev'
        type: string
        required: true

      createStack:
        description: 'create a new stack'
        type: boolean
        default: false
        required: false

      baseDomain:
        description: 'override the base domain for the stack'
        type: string
        required: false

      prefixDomain:
        description: 'override the prefix domain for the stack'
        type: string
        required: false

      useEphemeralHoneycombApiKey:
        description: 'override the honeycomb API key for the stack with the ephemeral API key'
        type: boolean
        required: false
        default: false

      commitHash:
        description: 'hash of commit that we will be deploying'
        type: string
        required: false

      useNeonDB:
        description: 'uses NeonDB for faster ephemeral env'
        type: boolean
        required: false
        default: false

    outputs:
      url:
        description: 'stack url'
        value: ${{ jobs.deploy_stack.outputs.url }}

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SECRETS_PROVIDER:
        required: true
      ENCLAVE_SIGNING_KEY:
        required: true
      ENCLAVE_SIGNING_CERT:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true
      AIRPLANE_API_KEY:
        required: true
jobs:
  extract_commit:
    name: Extract commit hash
    runs-on: ubuntu-latest
    outputs:
      apiComponentVersion: '${{ steps.constants.outputs.apiComponentVersion }}'
      enclaveComponentVersion: '${{ steps.constants.outputs.enclaveComponentVersion }}'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
          # We extract all commits here to make sure we're pulling the right commit hash
          fetch-depth: 0
      - name: Extract commit hash
        id: constants
        shell: bash
        run: |
          git --version
          branch="$(echo ${{ github.head_ref || github.ref_name }} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          apiVersion="${branch}-$(git rev-parse --short HEAD)"
          enclaveVersion="${branch}-$(git log -n 1 --format="%h" ./backend/components/enclave)"

          echo "api is ${apiVersion}"
          echo "enclave is ${enclaveVersion}"

          echo "apiComponentVersion=${apiVersion}" >> $GITHUB_OUTPUT
          echo "enclaveComponentVersion=${enclaveVersion}" >> $GITHUB_OUTPUT

  # build the main api image
  build_api:
    name: Build API container
    runs-on: 32core
    environment: ${{ inputs.environment }}
    needs: [extract_commit]
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commitHash }}

      - name: Cache docker cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/docker-cache
            ./backend/target
          key: ${{ runner.os }}-cargo-cache-docker-1-68-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-cache-docker-1-68

      - name: Restore docker cache
        run: |
          mkdir -p ~/docker-cache
          sudo mv ~/docker-cache /var/lib/docker/volumes/cargo-cache

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # package and push the api image
      - name: build api container
        working-directory: ./backend
        run: |
          make api-release
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          componentVersion="${{ needs.extract_commit.outputs.apiComponentVersion }}"
          echo "using account ${account}"
          echo "create image tagged as ${componentVersion}"
          docker build -t "api:${componentVersion}" -f api.dockerfile .
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag api:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${componentVersion}
          docker tag api:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/api:latest
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${componentVersion}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/api:latest

      # workaround: move the cargo cache to somewhere it can be cached
      # make api-release uses a docker image to build the binary (rust on musl linux)
      - name: cache permissions
        run: |
          rm -rf ~/docker-cache
          sudo mv /var/lib/docker/volumes/cargo-cache ~/docker-cache
          sudo chown -R $(whoami):$(whoami) ~/docker-cache

  # builds the enclave proxy image as needed
  build_enclave_proxy:
    name: Build Enclave Proxy
    runs-on: 32core
    environment: ${{ inputs.environment }}
    needs: [extract_commit]
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commitHash }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: build enclave proxy
        working-directory: ./backend
        run: |
          git --version
          make build-enclave-proxy-release
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          componentVersion="${{ needs.extract_commit.outputs.enclaveComponentVersion }}"
          echo "using account ${account}"
          echo "create image tagged as ${componentVersion}"
          docker build -t "enclave_proxy_pkg:${componentVersion}" -f enclave_proxy_package.dockerfile .
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag enclave_proxy_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:${componentVersion}
          docker tag enclave_proxy_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:latest
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:${componentVersion}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:latest

  # builds the eif enclave image if needed
  build_eif:
    name: Build Signed EIF
    runs-on: eif-builder
    environment: ${{ inputs.environment }}
    needs: [extract_commit]
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commitHash }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # install our signing credentials
      # build, sign, package and push the eif image
      - name: build, sign and package
        working-directory: ./backend
        run: |
          echo "${{ secrets.ENCLAVE_SIGNING_KEY }}" > ../enclavekey.pem
          echo "${{ secrets.ENCLAVE_SIGNING_CERT }}" > ../cert.pem
          git --version
          make build-eif
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          componentVersion="${{ needs.extract_commit.outputs.enclaveComponentVersion }}"
          echo "using account ${account}"
          echo "create image tagged as ${componentVersion}"
          docker build -t "enclave_pkg:${componentVersion}" -f enclave_eif_package.dockerfile .
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag enclave_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${componentVersion}
          docker tag enclave_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:latest
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${componentVersion}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:latest

      # cleanup: remove keys
      - name: cleanup
        working-directory: ./backend
        if: always()
        run: rm -f ../enclavekey.pem

  deploy_stack:
    name: deploy stack
    runs-on: ubuntu-latest
    outputs:
      url: '${{ steps.pulumi_deploy.outputs.apiUrl }}'
    environment:
      name: ${{ inputs.environment }}
      url: '${{ steps.pulumi_deploy.outputs.apiUrl }}'
    needs: [build_api, build_eif, build_enclave_proxy, extract_commit]
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commitHash }}

      # pulumi setup
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
        with:
          pulumi-version: 3.48.0

      - run: yarn install
        working-directory: ./backend/infra

      # create our stack if needed
      - name: 'create stack'
        if: ${{ inputs.createStack }}
        working-directory: ./backend/infra
        run: |
          pulumi stack init --secrets-provider ${{ secrets.AWS_SECRETS_PROVIDER }} --copy-config-from "footprint/${{ inputs.baseStackName }}" "footprint/${{ inputs.stackName  }}" || true
          cp Pulumi.${{ inputs.baseStackName }}.yaml Pulumi.${{ inputs.stackName }}.yaml
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: select stack
        working-directory: ./backend/infra
        run: pulumi stack select "footprint/${{ inputs.stackName }}"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: 'use fast ephemeral db'
        if: ${{ inputs.createStack && inputs.useNeonDB }}
        working-directory: ./backend/infra
        run: |
          pulumi config set useNeonEphemeralDbProjectId bitter-shape-200807

      - name: 'override base domain'
        if: ${{ inputs.baseDomain || false }}
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.domain.base ${{ inputs.baseDomain }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: 'override prefix domain'
        if: ${{ inputs.prefixDomain || false }}
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.domain.prefix ${{ inputs.prefixDomain }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: 'override honeycomb API key'
        if: ${{ inputs.useEphemeralHoneycombApiKey || false }}
        working-directory: ./backend/infra
        run: |
          pulumi config set --secret --path constants.honeycomb.apiKey $(pulumi config get --path constants.honeycomb.ephemeralApiKey)
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: 'set api/enclave image version'
        working-directory: ./backend/infra
        run: |
          pulumi config set --path constants.containers.apiVersion ${{ needs.extract_commit.outputs.apiComponentVersion }}
          pulumi config set --path constants.containers.enclaveVersion ${{ needs.extract_commit.outputs.enclaveComponentVersion }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # refresh the state
      - uses: pulumi/actions@v3.20.0
        with:
          command: refresh
          work-dir: ./backend/infra
          stack-name: 'footprint/${{ inputs.stackName }}'
          comment-on-pr: false
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # preview the stack
      - uses: pulumi/actions@v3.20.0
        with:
          command: preview
          work-dir: ./backend/infra
          stack-name: 'footprint/${{ inputs.stackName }}'
          comment-on-pr: false
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # deploy the stack
      - uses: pulumi/actions@v3.20.0
        id: pulumi_deploy
        with:
          command: up
          work-dir: ./backend/infra
          stack-name: 'footprint/${{ inputs.stackName }}'
          message: 'Deployed component ${{ needs.extract_commit.outputs.apiComponentVersion }} and ${{ needs.extract_commit.outputs.enclaveComponentVersion }}'
          comment-on-pr: true
          edit-pr-comment: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update deploy info on pull request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            // get existing comments
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Find any comment already made by the bot.                                                                                                    
            const botComment = comments.find(comment => comment.user.id === 41898282 && comment.body.includes('Deployed 🚀'));
            const commentBody = "**Deployed 🚀**\n\
            - URL: ${{ steps.pulumi_deploy.outputs.apiUrl }}\n\
            - Stack name: `${{ steps.pulumi_deploy.outputs.shortStackName }}`\n\
            - **api**: `${{ needs.extract_commit.outputs.apiComponentVersion }}`\n\
            - **enclave**: `${{ needs.extract_commit.outputs.enclaveComponentVersion }}`";
                                                                  
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
