name: Backend Deploy Production

on:
  #
  # NOTE: for now we are auto-deploying to prod if tests pass!
  #
  workflow_run:
    workflows: ['Backend Deploy Dev']
    types:
      - completed

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-deploy-prod

jobs:
  extract_commit_hash:
    # Since the prod deploy job can be triggered by either a successful prod deploy or a manual trigger,
    # we have to extract out the commit hash that is meant to be deployed by each job run.
    # The special case is when the prod deploy is triggered by a successful dev deploy: we look at
    # the commit that was used to run the successful dev deploy.
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch'
    name: Compute commit hash
    outputs:
      commitHashToDeploy: '${{ steps.constants.outputs.commitHashToDeploy }}'
      apiComponentVersion: '${{ steps.components.outputs.apiComponentVersion }}'
      enclaveComponentVersion: '${{ steps.components.outputs.enclaveComponentVersion }}'
    steps:
      - name: Hash
        shell: bash
        id: constants
        run: |
          echo "commit hash from workflow_run ${{ github.event.workflow_run.head_commit.id }}"
          echo "commit hash over branch HEAD ${{ github.sha }}"
          commit_hash="${{ github.event.workflow_run.head_commit.id || github.sha }}"
          echo "commit hash we will deploy in this workflow: $commit_hash"
          echo "##[set-output name=commitHashToDeploy;]$(echo ${commit_hash})"
      - uses: actions/checkout@v4
      - uses: ./.github/actions/backend_extract_commit_hash
        id: components
        with:
          commitHash: ${{ steps.constants.outputs.commitHashToDeploy }}

  deploy_stack_prod:
    name: Deploy stack
    needs: [extract_commit_hash]
    if: success()
    uses: ./.github/workflows/backend_deploy.yml
    with:
      environment: production
      baseStackName: prod
      stackName: prod
      commitHash: ${{ needs.extract_commit_hash.outputs.commitHashToDeploy }}
      apiComponentVersion: ${{ needs.extract_commit_hash.outputs.apiComponentVersion }}
      enclaveComponentVersion: ${{ needs.extract_commit_hash.outputs.enclaveComponentVersion }}

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}
      PULUMI_CLOUD_URL: ${{ secrets.PULUMI_CLOUD_URL }}
      AWS_SECRETS_PROVIDER: ${{ secrets.AWS_SECRETS_PROVIDER }}
      AIRPLANE_API_KEY: ${{ secrets.AIRPLANE_API_KEY }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

  run_tests:
    name: 'integration tests'
    needs: [deploy_stack_prod, extract_commit_hash]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.deploy_stack_prod.outputs.url }}'
      isPR: false
      waitForDeploy: true
      expectedCommitHash: ${{ needs.extract_commit_hash.outputs.commitHashToDeploy }}
      environment_name: production
    secrets:
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      # None
      IT_SVIX_API_KEY:

  notify_slack:
    needs: [deploy_stack_prod]
    runs-on: ubuntu-latest
    steps:
      - name: Notify on slack
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          payload: |
            {
              "user": "${{ github.event.workflow_run.head_commit.author.username }}, ${{ github.triggering_actor }}, ${{ github.event.workflow_run.head_commit.author.email }}",
              "environment": "[Backend PROD]",
              "url": "${{ needs.deploy_stack_prod.outputs.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_BOT_SLACK_WEBHOOK_URL }}
