name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-ci-check-test
  cancel-in-progress: true

jobs:
  files-changed:
    name: Determine if relevant files changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
        id: changes
        with:
          filters: |
            src:
              - 'backend/**'
              - '.github/**'
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  build_images:
    name: Build images
    runs-on: 16core24
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    strategy:
      matrix:
        include:
          - name: api
            dockerfile: api
            args:
              BUILD_PROFILE: release
              GIT_HASH: ${{ github.sha }}
          - name: enclave-proxy
            dockerfile: enclave-proxy
            args:
              BUILD_PROFILE: release
              CARGO_ARGS: "--features vsock"
              GIT_HASH: ${{ github.sha }}
          - name: enclave-proxy-dev
            dockerfile: enclave-proxy
            args:
              BUILD_PROFILE: debug
              CARGO_ARGS: ""
              GIT_HASH: ${{ github.sha }}
          - name: enclave
            dockerfile: enclave
            args: {}
          - name: enclave-dev
            dockerfile: enclave-dev
            args: {}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR (Image Cache)
        id: login-ecr-image-cache
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Build image
        env:
          REGISTRY: ${{ steps.login-ecr-image-cache.outputs.registry }}
          REPO: ${{ matrix.name }}
          TAG: ${{ github.sha }}
        working-directory: ./backend
        run: |
          set -euxo pipefail

          echo '${{toJSON(matrix.args) }}' | jq -r '. | to_entries | map("--build-arg \(.key)=\(.value | @sh)") | join(" ")' | \
            xargs docker buildx build \
              --platform linux/amd64 \
              --file ./images/${{ matrix.dockerfile }}/Dockerfile \
              --tag $REGISTRY/$REPO:$TAG \
              --push \
              ${{ github.ref == 'refs/heads/master' && '--cache-to type=registry,ref=${REGISTRY}/build-cache:${REPO}-master,compression=zstd,mode=max' || '' }} \
              --cache-from type=registry,ref=${REGISTRY}/build-cache:${REPO}-master \
              .

  test:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core24
    environment: backend_ci
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: install deps
        run: |
          # https://github.com/actions/runner-images/issues/9937
          sudo apt remove needrestart

          sudo apt-get update
          sudo apt-get install -y libssl-dev libpq-dev

      - uses: actions/checkout@v4

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@1.77.0

      - uses: rui314/setup-mold@7f56dbde35ee02a3fe0287e7ddd310922eb5f553
        with:
          mold-version: 2.0.0
          make-default: false

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          shared-key: backend-test
          cache-all-crates: true
          workspaces: |
            backend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@43c891271eabca0b34d95f2453e2fe354928b16d #4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set dot env
        working-directory: ./backend
        run: make set-dot-env

      - name: Unset AWS Credentials
        uses: aws-actions/configure-aws-credentials@43c891271eabca0b34d95f2453e2fe354928b16d #4.0.1
        with:
          unset-current-credentials: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        working-directory: ./backend
        run: cargo test --all --no-default-features --features simulate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres

  clippy:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core24
    steps:
      - uses: actions/checkout@v4

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@1.77.0
        with:
          components: clippy

      - uses: rui314/setup-mold@7f56dbde35ee02a3fe0287e7ddd310922eb5f553
        with:
          mold-version: 2.0.0
          make-default: false

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
        with:
          save-if: false
          shared-key: backend-test
          workspaces: |
            backend

      - name: Clippy
        working-directory: ./backend
        run: cargo clippy --all --no-default-features --features simulate

      - name: Clippy (vsock enabled)
        working-directory: ./backend
        run: cargo clippy -p enclave_proxy -p api_core --features vsock

  integration_tests:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core24
    environment: backend_ci
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_USER: 'runner'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/backend_run_local
        id: backend_run_local
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Run local integration tests
        working-directory: ./backend/ci
        run: |
          set -euxo pipefail
          pip install -r requirements.txt
          pytest -n 6 tests/ 2>&1 | tee integration_test_output.txt
          kill ${{ steps.backend_run_local.outputs.server_pid }}
        env:
          EXPECTED_SERVER_VERSION: ${{ github.sha }}
          TEST_URL: 'http://localhost:8000'
          IT_SVIX_API_KEY: ${{ secrets.IT_SVIX_API_KEY }}
          ENVIRONMENT: ci

      - name: Create results for PR
        id: test_results
        if: ${{ github.ref != 'refs/heads/master' && (success() || failure()) }}
        working-directory: ./backend/ci
        run: |
          SHORT_SUMMARY=$(cat integration_test_output.txt | awk '/short test summary info/,0')
          FINISH=`awk '/===/{ print NR; }' integration_test_output.txt | sed -n 2p`
          CROP=$(expr $FINISH - 1)
          BEGIN=$(expr $FINISH - 7)
          cat integration_test_output.txt
          head -n $CROP integration_test_output.txt | tail -n $BEGIN > out.txt
          sed -i 's/\[.*%\]//g' out.txt
          sed -i 's/tests/* tests/g' out.txt
          echo '### Local integration tests' > test_out.txt
          cat out.txt >> test_out.txt
          if [ ! -z "$SHORT_SUMMARY" ]; then
            echo '```' >> test_out.txt
            echo -e "$SHORT_SUMMARY" >> test_out.txt
            echo '```' >> test_out.txt
          fi
          COMMENT="$(cat test_out.txt)"
          COMMENT="${COMMENT//'%'/'%25'}"
          COMMENT="${COMMENT//$'\n'/'%0A'}"
          COMMENT="${COMMENT//$'\r'/'%0D'}"
          echo "::set-output name=body::$COMMENT"

      - name: Find local comment
        uses: peter-evans/find-comment@v2.0.0
        if: ${{ github.ref != 'refs/heads/master' && (success() || failure()) }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Local integration tests'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        if: ${{ github.ref != 'refs/heads/master' && (success() || failure()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.test_results.outputs.body }}
          edit-mode: replace

      - name: Check valid db migrations
        working-directory: ./backend/ci/scripts
        run: ./check_db_migrations.sh

  rustfmt:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: 16core24

    steps:
      - uses: actions/checkout@v3

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run rustfmt
        id: rustfmt
        run: cargo +nightly fmt --manifest-path ./backend/Cargo.toml --all --check > rustfmt_output.txt

      - name: Compose failure comment.txt
        if: failure()
        run: |
          set -x
          echo '### Rustfmt output:' > comment.txt
          echo 'Rustfmt failed. Please run `cargo +nightly fmt --all` to fix.' >> comment.txt
          echo '```diff' >> comment.txt
          cat rustfmt_output.txt >> comment.txt
          echo '```' >> comment.txt
          cat comment.txt

      - name: Compose success comment.txt
        if: success()
        run: |
          set -x
          echo '### Rustfmt output:' > comment.txt
          echo 'Rustfmt succeeded' >> comment.txt
          cat comment.txt

      - name: Find local rustfmt comment
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d
        if: ${{ github.ref != 'refs/heads/master' && (failure() || success()) }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Rustfmt output'

      - name: Create or update rustfmt comment
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        if: ${{ github.ref != 'refs/heads/master' && (failure() || success()) }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.txt
          edit-mode: replace

  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
  # Add all jobs in this workflow to this job's `needs`
  backend-ci:
    runs-on: ubuntu-latest
    needs: [build_images, test, clippy, integration_tests, rustfmt]
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
