name: Backend Build

on:
  workflow_call:
    inputs:
      commitHash:
        type: string
        required: true
      rustVersion:
        type: string
        required: true

    secrets:
      AWS_REGION:
        required: true
      IMG_CACHE_AWS_ACCESS_KEY_ID:
        required: true
      IMG_CACHE_AWS_SECRET_ACCESS_KEY:
        required: true

    outputs:
      expectedServerVersion:
        description: 'api container version'
        value: ${{ jobs.extract_commit.outputs.expectedServerVersion }}
      apiComponentVersion:
        description: 'api container version'
        value: ${{ jobs.extract_commit.outputs.apiComponentVersion }}
      enclaveComponentVersion:
        description: 'enclave/proxy container version'
        value: ${{ jobs.extract_commit.outputs.enclaveComponentVersion }}

jobs:
  extract_commit:
    name: Extract commit hash
    runs-on: ubuntu-latest
    outputs:
      expectedServerVersion: '${{ steps.constants.outputs.expectedServerVersion }}'
      apiComponentVersion: '${{ steps.constants.outputs.apiComponentVersion }}'
      enclaveComponentVersion: '${{ steps.constants.outputs.enclaveComponentVersion }}'
    steps:
      # Need to checkout before running the referenced sub-action
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
      - uses: ./.github/actions/backend_extract_commit_hash
        id: constants
        with:
          commitHash: ${{ inputs.commitHash }}

  build_api:
    name: Build API server container
    runs-on: 16core
    needs: [extract_commit]
    if: success()
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}

      - name: Cache docker cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/docker-cache
            ./backend/target
          key: ${{ runner.os }}-cargo-cache-docker-1-77-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-cache-docker-1-74

      - name: Restore docker cache
        run: |
          mkdir -p ~/docker-cache
          sudo mv ~/docker-cache /var/lib/docker/volumes/cargo-cache

      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #4.0.1
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch cached containers
        run: |
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker pull ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${{ needs.extract_commit.outputs.apiComponentVersion }} && docker tag ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${{ needs.extract_commit.outputs.apiComponentVersion }} api:${{ needs.extract_commit.outputs.apiComponentVersion }} || echo "Image not found"

      # package and push the api image
      - name: build api container
        working-directory: ./backend
        run: |
          rm .cargo/config.toml
          componentVersion="${{ needs.extract_commit.outputs.apiComponentVersion }}"
          serverGitHash="${{ needs.extract_commit.outputs.expectedServerVersion }}"
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          echo "using account ${account}"
          echo "create image tagged as ${componentVersion}"

          function build_api {
            echo "building release mode"
            docker run --env GIT_HASH="${serverGitHash}" -v "cargo-cache:/root/.cargo/registry" -v "${PWD}:/volume" --rm -t "clux/muslrust:${RUST_VERSION}-stable" cargo build -p api_server --release
            cp ./target/x86_64-unknown-linux-musl/release/api_server ./out/api_server
            docker build -t "api:${componentVersion}" -f api.dockerfile .
          }

          # check cache or build
          docker inspect api:${componentVersion} && echo "Fetched from package cache"|| (echo "Cache miss, building..." && build_api)

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag api:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${componentVersion}          
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${componentVersion}
        env:
          RUST_VERSION: ${{ inputs.rustVersion }}

      - name: cache permissions # workaround: move the cargo cache to somewhere it can be cached
        run: |
          rm -rf ~/docker-cache
          sudo mv /var/lib/docker/volumes/cargo-cache ~/docker-cache
          sudo chown -R $(whoami):$(whoami) ~/docker-cache

  build_enclave_proxy:
    name: Build Enclave Proxy
    runs-on: 16core
    needs: [extract_commit]
    if: success()
    steps:
      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a #4.0.1
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch cached containers
        run: |
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker pull ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:${{ needs.extract_commit.outputs.enclaveComponentVersion }} && docker tag ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:${{ needs.extract_commit.outputs.enclaveComponentVersion }} enclave_proxy_pkg:${{ needs.extract_commit.outputs.enclaveComponentVersion }} || echo "Image not found"

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}

      - name: build enclave proxy
        working-directory: ./backend
        run: |
          git --version
          rm .cargo/config.toml
          componentVersion="${{ needs.extract_commit.outputs.enclaveComponentVersion }}"
          serverGitHash="${{ needs.extract_commit.outputs.expectedServerVersion }}"
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          echo "using account ${account}"
          echo "create image tagged as ${componentVersion}"

          function build_enclave_proxy {
            echo "[release] building enclave-proxy"
            docker run --env GIT_HASH="${serverGitHash}" -v "cargo-cache:/home/ec2-user/.cargo/registry" -v "${PWD}:/volume" --rm -t "clux/muslrust:${RUST_VERSION}-stable" cargo build -p enclave_proxy --features vsock --release
            cp ./target/x86_64-unknown-linux-musl/release/enclave_proxy ./out/enclave_proxy
            docker build -t "enclave_proxy_pkg:${componentVersion}" -f enclave_proxy_package.dockerfile .
          }

          # check cache or build
          docker inspect enclave_proxy_pkg:${componentVersion} && echo "Fetched from package cache"|| (echo "Cache miss, building..." && build_enclave_proxy)

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag enclave_proxy_pkg:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:${componentVersion}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_proxy_pkg:${componentVersion}
        env:
          RUST_VERSION: ${{ inputs.rustVersion }}

  build_enclave:
    name: Build Enclave
    runs-on: eif-builder
    needs: [extract_commit]
    if: success()
    steps:
      - name: Configure AWS Credentials (Image Cache)
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 #1
        with:
          aws-access-key-id: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch cached containers
        run: |
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker pull ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${{ needs.extract_commit.outputs.enclaveComponentVersion }} && docker tag ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${{ needs.extract_commit.outputs.enclaveComponentVersion }} enclave:${{ needs.extract_commit.outputs.enclaveComponentVersion }} || echo "Image not found"

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}

      # install our signing credentials
      # build, sign, package and push the eif image
      - name: build enclave
        working-directory: ./backend
        run: |
          git --version
          componentVersion="${{ needs.extract_commit.outputs.enclaveComponentVersion }}"
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          echo "using account ${account}"
          echo "create image tagged as ${componentVersion}"

          function build_enclave_docker {
            rm -f ./out/enclave

            echo "building enclave"
            docker run -v "cargo-cache:/home/ec2-user/.cargo/registry" -v "${PWD}:/build" --rm -t "ne_builder2:${RUST_VERSION}" cargo build --target=x86_64-unknown-linux-musl -p enclave --no-default-features --features nitro --release

            cp ./target/x86_64-unknown-linux-musl/release/enclave ./out/enclave

            docker build -f enclave.dockerfile -t enclave:${componentVersion} .
          }

          # check cache or build
          docker inspect enclave:${componentVersion} && echo "Fetched from package cache"|| (echo "Cache miss, building..." && build_enclave_docker)

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag enclave:${componentVersion} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${componentVersion}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave:${componentVersion}
        env:
          RUST_VERSION: ${{ inputs.rustVersion }}
