name: Backend Ephemeral Stack
on:
  pull_request:
    types: [labeled, opened, synchronize]

concurrency:
  group: 'ephem-stack-group-${{ github.head_ref }}'
  # We want a new push on a branch
  cancel-in-progress: true

jobs:
  ephemeral_stack:
    name: Detect ephemeral
    runs-on: ubuntu-latest
    outputs:
      stackName: ${{ steps.constants.outputs.branch }}
      hasInfraChanges: ${{ steps.detect.outputs.ephemeral }}
      needsFullInfra: ${{ steps.detect.outputs.full_ephemeral}}
    steps:
      - uses: actions/checkout@v4
        with:
          # We extract all commits here to make sure we're pulling the right commit hash
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Extract Constants
        id: constants
        shell: bash
        run: |
          branch_raw="${{ github.head_ref }}"
          branch="$(echo ${branch_raw} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          echo "friendly branch name is ${branch}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT

      - name: Detect infra changes
        id: detect
        shell: bash
        run: |
          git --version
          code_hash="$(git log -n 1 --format="%h" ./)"
          infra_hash="$(git log -n 1 --format="%h" ./backend/infra)"
          infra_db_hash="$(git log -n 1 --format="%h" ./backend/infra/src/db.ts)"
          echo "code=${code_hash} infra=${infra_hash}"

          if [ "$code_hash" == "$infra_hash" ]; then
            echo "ephemeral=true" >> $GITHUB_OUTPUT
            if [ "$infra_db_hash" == "$infra_hash" ]; then
              echo "full_ephemeral=true" >> $GITHUB_OUTPUT
            else
              echo "full_ephemeral=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "ephemeral=false" >> $GITHUB_OUTPUT
          fi

  build_backend:
    name: build backend
    needs: [ephemeral_stack]
    uses: ./.github/workflows/backend_build.yml
    with:
      commitHash: ${{ github.event.pull_request.head.sha }}
      rustVersion: 1.77.0

    # don't run for dependabot changes and only run when labeled ephemeral or infra changes detected
    if: github.actor != 'dependabot[bot]' && (contains( github.event.pull_request.labels.*.name, 'FastEphemeral') || contains( github.event.pull_request.labels.*.name, 'FullEphemeral') || needs.ephemeral_stack.outputs.hasInfraChanges == 'true')
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

  deploy_ephemeral_stack:
    name: deploy ephemeral
    needs: [build_backend, ephemeral_stack]
    uses: ./.github/workflows/backend_deploy.yml
    # don't run for dependabot changes and only run when labeled ephemeral or infra changes detected
    if: github.actor != 'dependabot[bot]' && (contains( github.event.pull_request.labels.*.name, 'FastEphemeral') || contains( github.event.pull_request.labels.*.name, 'FullEphemeral') || needs.ephemeral_stack.outputs.hasInfraChanges == 'true')
    permissions:
      contents: write
      pull-requests: write
    with:
      environment: dev
      baseStackName: dev
      createStack: true
      stackName: 'dev-${{ needs.ephemeral_stack.outputs.stackName }}'
      prefixDomain: 'api-${{ needs.ephemeral_stack.outputs.stackName }}.'
      useNeonDB: ${{ !contains(github.event.pull_request.labels.*.name, 'FullEphemeral') && !(needs.ephemeral_stack.outputs.needsFullInfra == 'true') }}
      useEphemeralHoneycombApiKey: true
      apiComponentVersion: ${{ needs.build_backend.outputs.apiComponentVersion}}
      enclaveComponentVersion: ${{ needs.build_backend.outputs.enclaveComponentVersion}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}
      PULUMI_CLOUD_URL: ${{ secrets.PULUMI_CLOUD_URL }}
      AWS_SECRETS_PROVIDER: ${{ secrets.AWS_SECRETS_PROVIDER }}
      AIRPLANE_API_KEY: ${{ secrets.AIRPLANE_API_KEY }}
      IMG_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.IMG_CACHE_AWS_ACCESS_KEY_ID }}
      IMG_CACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.IMG_CACHE_AWS_SECRET_ACCESS_KEY }}

  run_tests:
    name: 'ephemeral integration tests'
    needs: [build_backend, deploy_ephemeral_stack]
    if: success()
    uses: ./.github/workflows/backend_remote_integration_tests.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      testUrl: '${{ needs.deploy_ephemeral_stack.outputs.url }}'
      waitForDeploy: true
      isPR: true
      environment: dev
      expectedCommitHash: ${{ needs.build_backend.outputs.expectedServerVersion }}
    secrets:
      IT_PHONE_NUMBERS: ${{ secrets.IT_PHONE_NUMBERS }}
      IT_TWILIO_ACCOUNT_SID: ${{ secrets.IT_TWILIO_ACCOUNT_SID }}
      IT_TWILIO_SECRET_AUTH_TOKEN: ${{ secrets.IT_TWILIO_SECRET_AUTH_TOKEN }}
      SVIX_AUTH_TOKEN: ${{ secrets.SVIX_AUTH_TOKEN }}
