name: Build and Deploy Stack

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      stackName:
        type: string
        required: true
      ephemeral:
        type: boolean
        default: false
        required: false        
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ENCLAVE_SIGNING_KEY:
        required: true
      ENCLAVE_SIGNING_CERT:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true
      STACK_NAME:
        required: true

jobs:  
  # build the main api image
  build_api:
    name: Build API container
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}                        
      
      # package and push the api image
      - run: make package-api

  # builds the eif enclave image if needed
  build_eif:
    name: Build Signed EIF
    runs-on: eif-builder
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}              
                  
      # install our signing credentials
      # build, sign, package and push the eif image      
      - name: build, sign and package        
        run: |
          echo "${{ secrets.ENCLAVE_SIGNING_KEY }}" > ../enclavekey.pem
          echo "${{ secrets.ENCLAVE_SIGNING_CERT }}" > ../cert.pem
          make build-eif
          make package-enclave          
      
      # cleanup: remove keys
      - run: rm -f ../enclavekey.pem

  deploy_stack:    
    name: deploy stack
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [build_api, build_eif]
    if: success()
    steps:
      - uses: actions/checkout@v2
          
      # pulumi setup
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0       

      - run: yarn install
        working-directory: infra
                  
      # get environment constants
      - name: Extract Constants
        shell: bash
        working-directory: infra
        run: |
          sub=$(pulumi config --stack footprint/${{ inputs.stackName }} get --path constants.cdnAppSubdomain)
          root=$(pulumi config --stack footprint/${{ inputs.stackName }} get --path constants.rootDomain)
          url="${sub}.${root}"
          vers="$(make get-named-commit)"
          echo "##[set-output name=url;]$(echo ${url})"
          echo "##[set-output name=componentVersion;]$(echo ${vers})"
        id: constants
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}     

      # create our temp stack if needed
      - name: create emphemeral stack
        if: ${{ inputs.ephemeral }}
        working-directory: infra
        run: |
          pulumi stack init --secrets-provider ${{ secrets.AWS_SECRETS_PROVIDER }} --copy-config-from "footprint/${{secrets.STACK_NAME}}" "footprint/${{ inputs.stackName  }}" || true
          cp Pulumi.${{secrets.STACK_NAME}}.yaml Pulumi.${{ inputs.stackName }}.yaml
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
                    
      - name: select stack
        working-directory: infra
        run: pulumi stack select "footprint/${{ inputs.stackName }}"

      - name: "set api image version"
        run: make set-api-version

      - name: "set enclave image version"
        run: make set-enclave-version

      # bring up the stack
      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: infra
          stack-name: "footprint/${{ inputs.stackName }}"
          message: "Deployed to https://${{ steps.constants.outputs.url }} with component ${{ steps.constants.outputs.componentVersion }}"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}