name: Build and Deploy Stack

on:
  workflow_call:
    inputs:
      environment:
        description: "secrets environment to use"
        type: string
        required: true

      baseStackName:
        description: "base stack we're building, i.e. dev"
        type: string
        required: true

      stackName:
        description: "stack or possibly ephemeral stack name, i.e. dev or dev-feature-x"
        type: string
        required: true

      ephemeral:
        description: "whether or not this stack is ephemeral"
        type: boolean
        default: false
        required: false

    outputs:
      url:
        description: "stack url"
        value: ${{ jobs.deploy_stack.outputs.url }}

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SECRETS_PROVIDER:
        required: true
      ENCLAVE_SIGNING_KEY:
        required: true
      ENCLAVE_SIGNING_CERT:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true
jobs:
  # build the main api image
  build_api:
    name: Build API container
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache docker cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/docker-cache
            ./target
          key: ${{ runner.os }}-cargo-cache-docker

      - name: Restore docker cache
        run: |
          mkdir -p ~/docker-cache
          sudo mv ~/docker-cache /var/lib/docker/volumes/cargo-cache

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # package and push the api image
      - run: |
          make api-release
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          branch="$(echo ${{ github.head_ref || github.ref_name }} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          commit="${branch}-$(git rev-parse --short HEAD)"
          echo "using account ${account}"
          echo "create image tagged as ${commit}"
          docker build -t "api:${commit}" -f api.dockerfile .
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag api:${commit} ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${commit}
          docker tag api:${commit} ${account}.dkr.ecr.us-east-1.amazonaws.com/api:latest
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/api:${commit}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/api:latest

      # workaround: move the cargo cache to somewhere it can be cached
      # make api-release uses a docker image to build the binary (musl linux)
      - name: cache permissions
        run: |
          rm -rf ~/docker-cache
          sudo mv /var/lib/docker/volumes/cargo-cache ~/docker-cache
          sudo chown -R 1001:1001 ~/docker-cache

  # builds the eif enclave image if needed
  build_eif:
    name: Build Signed EIF
    runs-on: eif-builder
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # install our signing credentials
      # build, sign, package and push the eif image
      - name: build, sign and package
        run: |
          echo "${{ secrets.ENCLAVE_SIGNING_KEY }}" > ../enclavekey.pem
          echo "${{ secrets.ENCLAVE_SIGNING_CERT }}" > ../cert.pem
          make build-eif
          account="$(aws sts get-caller-identity --query "Account" --output text)"
          branch="$(echo ${{ github.head_ref || github.ref_name }} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          commit="${branch}-$(git rev-parse --short HEAD)"
          echo "using account ${account}"
          echo "create image tagged as ${commit}"
          docker build -t "enclave_pkg:${commit}" -f enclave_package.dockerfile .
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com
          docker tag enclave_pkg:${commit} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${commit}
          docker tag enclave_pkg:${commit} ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:latest
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:${commit}
          docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/enclave_pkg:latest

      # cleanup: remove keys
      - run: rm -f ../enclavekey.pem

  deploy_stack:
    name: deploy stack
    runs-on: ubuntu-latest
    outputs:
      url: "https://${{ steps.constants.outputs.url }}"
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ steps.constants.outputs.url }}"
    needs: [build_api, build_eif]
    if: success()
    steps:
      - uses: actions/checkout@v2

      # pulumi setup
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
        with:
          pulumi-version: 3.30.0

      - run: yarn install
        working-directory: infra

      # create our temp stack if needed
      - name: create emphemeral stack
        if: ${{ inputs.ephemeral }}
        working-directory: infra
        run: |
          pulumi stack init --secrets-provider ${{ secrets.AWS_SECRETS_PROVIDER }} --copy-config-from "footprint/${{ inputs.baseStackName }}" "footprint/${{ inputs.stackName  }}" || true
          cp Pulumi.${{ inputs.baseStackName }}.yaml Pulumi.${{ inputs.stackName }}.yaml
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # get environment constants
      - name: Extract Constants
        shell: bash
        run: |
          sub=$(pulumi --cwd infra config --stack footprint/${{ inputs.stackName }} get --path constants.cdnAppSubdomain)
          root=$(pulumi --cwd infra config --stack footprint/${{ inputs.stackName }} get --path constants.rootDomain)
          url="${sub}.${{ inputs.stackName }}.${root}"
          branch="$(echo ${{ github.head_ref || github.ref_name }} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"
          version="${branch}-$(git rev-parse --short HEAD)"
          echo "##[set-output name=url;]$(echo ${url})"
          echo "##[set-output name=componentVersion;]$(echo ${version})"
        id: constants
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: select stack
        working-directory: infra
        run: pulumi stack select "footprint/${{ inputs.stackName }}"

      - name: "set api/enclave image version"
        run: |
          pulumi --cwd infra config set --path constants.containers.apiVersion ${{ steps.constants.outputs.componentVersion }}
          pulumi --cwd infra config set --path constants.containers.enclaveVersion ${{ steps.constants.outputs.componentVersion }}

      - name: Set Ephemeral DB Restore Snapshot
        if: ${{ inputs.ephemeral }}
        working-directory: infra
        run: |
          pulumi config set restoreSnapshotFromClusterNamed "db-${{ inputs.baseStackName }}"

      # bring up the stack
      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: infra
          stack-name: "footprint/${{ inputs.stackName }}"
          message: "Deployed to https://${{ steps.constants.outputs.url }} with component ${{ steps.constants.outputs.componentVersion }}"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update deploy info on pull request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed to https://${{ steps.constants.outputs.url }} with component tag `${{ steps.constants.outputs.componentVersion }}`'
            })
