name: Build Components

on:
  push:
    paths:
      - 'infra/**'
      - 'components/**'
      - '.github/workflows/**'

    branches:
      - master

jobs:  
  deploy_stack_dev:    
    name: Deploy stack dev
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment: dev
      stackName: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENCLAVE_SIGNING_KEY: ${{ secrets.ENCLAVE_SIGNING_KEY }}      
      ENCLAVE_SIGNING_CERT: ${{ secrets.ENCLAVE_SIGNING_CERT }}        
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      STACK_NAME: ${{ secrets.STACK_NAME }}


