name: Destroy Ephemeral Stack
on:
  pull_request:
    types: [closed]
    
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the branch whose stack to delete'
        required: true
        type: string        
jobs:
  destroy_ephemeral_stack:
    name: Destroy Ephemeral Stack
    runs-on: ubuntu-latest
    environment: dev
    if: github.actor != 'dependabot[bot]' # don't run for dependabot changes
    steps:

      # pulumi setup
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
        with:
          pulumi-version: 3.30.0
          
      - name: Extract branch name
        shell: bash
        run: |
          branch_raw="${{ github.event.inputs.branchName  || github.head_ref }}"
          branch="$(echo ${branch_raw} | sed -r 's/\//-/g' | sed -r 's/_/-/g')"          
          echo "##[set-output name=branch;]$(echo ${branch})"
        id: extract_branch          

      # bring up the ephemeral stack
      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: "footprint/dev-${{ steps.extract_branch.outputs.branch }}"
          message: "Destroyed ephemeral environment"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # rm our temp stack
      - run: pulumi stack --stack footprint/dev-${{ steps.extract_branch.outputs.branch }} rm -y
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
