name: 'Tag Ephemeral'

on:
  pull_request:
    paths:
      - 'backend/infra/**/*'
      - 'backend/infra/*'

jobs:
  tag-ephemeral:
    name: Ephemeral
    runs-on: ubuntu-latest

    steps:
      - name: tag ephemeral environment
        uses: andymckay/labeler@master
        with:
          add-labels: 'ephemeral'
