name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

# The names of these jobs are important since they're used in Github branch protections
jobs:
  files-changed:
    name: Determine if relevant files changed
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
        id: changes
        with:
          filters: |
            src:
              - 'frontend/**'
              - '.github/**'
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  lint:
    runs-on: frontend_runner
    steps:
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache turbo build setup
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # ratchet:actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install node_modules
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Lint
        working-directory: ./frontend
        run: yarn lint:ci

  test:
    runs-on: frontend_runner
    steps:
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache turbo build setup
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # ratchet:actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install node_modules
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Unit tests
        working-directory: ./frontend
        run: yarn test:ci

  typecheck:
    runs-on: frontend_runner
    steps:
      - name: Check out code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache turbo build setup
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # ratchet:actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install node_modules
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Typecheck
        working-directory: ./frontend
        run: yarn typecheck

  bun-unit-tests:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    name: 'bun-unit-tests'
    runs-on: frontend_runner
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # ratchet:oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", 1.0.23 ,<sha>

      - name: Bun install
        working-directory: ./frontend
        run: bun install

      - name: Bun tests
        working-directory: ./frontend
        run: bun run test:ci:bun

  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
  # Add all jobs in this workflow to the `needs` here
  frontend-ci:
    runs-on: frontend_runner
    needs: [files-changed, lint, typecheck, test, bun-unit-tests]
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1







