name: E2E

on:
  deployment_status:

permissions:
  actions: write # Necessary to cancel workflow executions
  checks: write # Necessary to write reports
  contents: read
  packages: write
  pull-requests: write # Necessary to comment on PRs

env:
  CI_SKIP: false
  CI: true
  E2E_AUTH_BASE_URL: ''
  E2E_AUTH_KEY: 'ob_test_2TwubGlrWdKaJnWsQQKQYl'
  E2E_BIFROST_BASE_URL: http://localhost:3000
  E2E_DEMOS_BASE_URL: 'https://demo.preview.onefootprint.com'
  E2E_HANDOFF_BASE_URL: http://localhost:3005
  E2E_OB_INVESTOR: 'ob_test_3xYoHcfrkxuOGNy8vILxh4'
  E2E_OB_KYB: 'ob_test_5zu2usM1ilTzDnqQpaZ6Sg'
  E2E_OB_KYC_DOC_FIRST: 'pb_test_ZeSUWIlEteLWZByDjLITUL'
  E2E_OB_KYC_DOC: 'ob_test_0DNRM31nSBCSqHLJQTeWi9'
  E2E_OB_KYC_ES: 'ob_test_yHlPBcaJ6lnxwkkD1YLStx'
  E2E_OB_KYC_LEGAL_STATUS: 'pb_test_jaZzYsm4aSPSY4YfH0qe7T'
  E2E_OB_KYC_NO_PHONE: 'ob_test_h9Qp2W3Trk1pfIoI7dTD5q'
  E2E_OB_KYC: 'ob_test_Gw8TsnS2xWOYazI0pugdxu'
  E2E_UPDATE_UTOKEN: ''
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  VERCEL_AWAIT_POLL_INTERVAL_SEC: 7
  VERCEL_AWAIT_TIMEOUT_SEC: 360
  VERCEL_PROJECT_ID_HANDOFF: 'prj_UWCk5C2ed14AnfXDfkF9H5YQHRic'
  VERCEL_TEAM_ID: 'footprint'
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: debug github.event.deployment
  #       run: echo "${{ toJson(github.event.deployment) }}"
  #     - name: debug github.event.deployment_status
  #       run: echo "${{ toJson(github.event.deployment_status) }}"

  e2e-auth:
    name: 'On auth success'
    if: >
      github.event.deployment_status.state == 'success' &&
      startsWith(github.event.deployment_status.target_url, 'https://auth-') &&
      startsWith(github.event.deployment_status.environment, 'Preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Cache error: The event type deployment_status is not supported because it's not tied to a branch or tag ref.
      - name: Bun install node_modules
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Install playwright dependencies
        working-directory: ./frontend
        run: npx playwright install --with-deps chromium webkit

      - name: Exit on failure
        if: ${{ failure() }}
        run: exit 1

      - name: Get update auth methods token
        run: |
          E2E_UPDATE_UTOKEN=$(curl -s https://api.dev.onefootprint.com/users/fp_id_test_rJBzCaVzkYQgWIfr0qtFDC/token -X POST -d '{"kind": "update_auth_methods"}' -u ${{ secrets.E2E_ACME_SECRET_API_KEY_DEV }}: | jq -r '.token')
          if [[ -z "$E2E_UPDATE_UTOKEN" ]]; then
            echo "Token is not valid"
            echo "CI_SKIP=true" >> $GITHUB_ENV
          else
            echo "E2E_UPDATE_UTOKEN=${E2E_UPDATE_UTOKEN}" >> $GITHUB_ENV
          fi

      - name: Run playwright tests
        if: ${{ env.CI_SKIP != 'true' }}
        working-directory: ./frontend
        env:
          E2E_AUTH_BASE_URL: ${{ github.event.deployment_status.target_url }}
          E2E_AUTH_KEY: ${{ env.E2E_AUTH_KEY }}
          E2E_DEMOS_BASE_URL: ${{ env.E2E_DEMOS_BASE_URL }}
          E2E_UPDATE_UTOKEN: ${{ env.E2E_UPDATE_UTOKEN }}
        run: yarn workspace @onefootprint/e2e test:e2e:auth-ci --reporter=html

      - name: Upload test results (for 3 days)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./frontend/packages/e2e/test-results/
          retention-days: 3

      - name: Upload HTML report to azure (for 7 days)
        if: ${{ failure() }}
        id: upload-report
        shell: bash
        run: |
          REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
          azcopy cp --recursive "./frontend/packages/e2e/playwright-report/*" "https://pwe2e.blob.core.windows.net/\$web/$REPORT_DIR"
          echo "::set-output name=report-dir::$REPORT_DIR"
          echo "::notice title=HTML report url::https://pwe2e.z13.web.core.windows.net/$REPORT_DIR/index.html"
        env:
          AZCOPY_AUTO_LOGIN_TYPE: SPN
          AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
          AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
          AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'

      - name: Add failure comment to PR
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            const prNumber = context.issue.number || issues.data.find(i => i.head.sha === context.sha)?.number || null
            if (prNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: "E2E auth run failed for ${{ github.sha }}:\n\n- Report URL: [report](https://pwe2e.z13.web.core.windows.net/${{ steps.upload-report.outputs.report-dir }}/index.html)\n- Manual check: [demo](${{ env.E2E_DEMOS_BASE_URL }}/components/auth?ob_key=${{ env.E2E_AUTH_KEY }}&app_url=${{ env.E2E_AUTH_BASE_URL }})"
              })
            }

  e2e-verify:
    name: 'On bifrost success'
    if: >
      github.event.deployment_status.state == 'success' &&
      startsWith(github.event.deployment_status.target_url, 'https://bifrost-') &&
      startsWith(github.event.deployment_status.environment, 'Preview')
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Cache error: The event type deployment_status is not supported because it's not tied to a branch or tag ref.
      - name: Bun install node_modules
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Install playwright dependencies
        working-directory: ./frontend
        run: npx playwright install --with-deps chromium webkit

      - name: Exit on failure
        if: ${{ failure() }}
        run: exit 1

      - name: Get Vercel handoff preview_url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_handoff
        continue-on-error: true
        with:
          vercel_team_id: ${{ env.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ env.VERCEL_PROJECT_ID_HANDOFF }}

      - name: Wait for handoff preview_url to be ready
        uses: UnlyEd/github-action-await-vercel@v1
        id: await-vercel-handoff
        if: >
          steps.vercel_handoff.outputs.deployment_state != 'CANCELED' &&
          steps.vercel_handoff.outputs.deployment_state != 'ERROR'
        continue-on-error: true
        with:
          deployment-url: ${{ steps.vercel_handoff.outputs.preview_url }}
          poll-interval: ${{ env.VERCEL_AWAIT_POLL_INTERVAL_SEC }}
          timeout: ${{ env.VERCEL_AWAIT_TIMEOUT_SEC }}

      - name: Run Playwright tests
        working-directory: ./frontend
        env:
          E2E_DEMOS_BASE_URL: ${{ env.E2E_DEMOS_BASE_URL }}
          E2E_BIFROST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          E2E_HANDOFF_BASE_URL: ${{ env.E2E_HANDOFF_BASE_URL }}
        run: yarn workspace @onefootprint/e2e test:e2e:verify-ci --reporter=html

      - name: Upload test results (for 3 days)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./frontend/packages/e2e/test-results/
          retention-days: 3

      - name: Upload HTML report to azure (for 7 days)
        if: ${{ failure() }}
        id: upload-report
        shell: bash
        run: |
          REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
          azcopy cp --recursive "./frontend/packages/e2e/playwright-report/*" "https://pwe2e.blob.core.windows.net/\$web/$REPORT_DIR"
          echo "::set-output name=report-dir::$REPORT_DIR"
          echo "::notice title=HTML report url::https://pwe2e.z13.web.core.windows.net/$REPORT_DIR/index.html"
        env:
          AZCOPY_AUTO_LOGIN_TYPE: SPN
          AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
          AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
          AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'

      - name: Add failure comment to PR
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            const prNumber = context.issue.number || issues.data.find(i => i.head.sha === context.sha)?.number || null
            if (prNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: "E2E verify run failed for ${{ github.sha }}:\n\n- Report URL: [report](https://pwe2e.z13.web.core.windows.net/${{ steps.upload-report.outputs.report-dir }}/index.html)"
              })
            }
