name: UI Chromatic

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  files-changed:
    name: Determine if files changed
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
        id: changes
        with:
          filters: |
            src:
              - 'frontend/packages/**'
              - '.github/workflows/frontend_chromatic_ui.yml'
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  chromatic-ui:
    name: Check UI
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: frontend_runner
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: ⎔ Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # ratchet:actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install node_modules
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: 🏗️ Build Storybook
        working-directory: ./frontend
        run: yarn build:storybook --filter=@onefootprint/ui

      - name: ⚡ Run Chromatic on UI
        uses: chromaui/action@b984808b772126a9f44b2b7737b131b68a2ede32 # ratchet:chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_UI_TOKEN }}
          workingDir: frontend/packages/ui
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: "dependabot/**"
          storybookBuildDir: storybook-static

  chromatic-idv:
    name: Check IDV
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: frontend_runner
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: ⎔ Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # ratchet:actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install node_modules
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: 🏗️ Build Storybook
        working-directory: ./frontend
        run: yarn build:storybook --filter=@onefootprint/idv

      - name: ⚡ Run Chromatic on IDV
        uses: chromaui/action@b984808b772126a9f44b2b7737b131b68a2ede32 # ratchet:chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_IDV_TOKEN }}
          workingDir: frontend/packages/idv
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: "dependabot/**"
          storybookBuildDir: storybook-static
