name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/.changeset/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: ./frontend
        run: yarn build:packages

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          cwd: ./frontend
          publish: yarn release
          title: Bump frontend public packages
          commit: Bump frontend public packages
