name: Frontend CI (skip)

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend_ci_ignore.yml'

# The names of these jobs are important since they're used in Github branch protections

jobs:
  install-dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  typecheck:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    needs: install-dependencies
    steps:
      - run: echo "Not required"
