name: Frontend CI Audit (skip)

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend_audit_ignore.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  audit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"
