name: Frontend CI

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

# The names of these jobs are important since they're used in Github branch protections

jobs:
  install-dependencies:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Restore node modules cache
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules if not cached
        working-directory: ./frontend
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  lint:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Lint
        working-directory: ./frontend
        run: yarn lint:ci

  format:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Prettier
        working-directory: ./frontend
        run: yarn format

  test:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Tests
        working-directory: ./frontend
        run: yarn test:ci

  typecheck:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Typecheck
        working-directory: ./frontend
        run: yarn typecheck
