name: Frontend CI Audit

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_audit.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

# The names of these jobs are important since they're used in Github branch protections

jobs:
  audit:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    name: 'Audit'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Audit for vulnerabilities
        working-directory: ./frontend
        run: npx audit-ci@^6 --config ./audit-ci.jsonc
