name: Frontend E2E

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  E2E_UPDATE_UTOKEN: ''
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  files-changed:
    name: Determine if relevant files changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
        id: changes
        with:
          filters: |
            src:
              - '.github/workflows/frontend_e2e.yml'
              - 'frontend/apps/auth/**'
              - 'frontend/apps/components/**'
              - 'frontend/apps/handoff/**'
              - 'frontend/packages/**'
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  test:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: frontend_runner
    steps:
      - name: Get update auth methods token
        run: |
          E2E_UPDATE_UTOKEN=$(curl -s https://api.dev.onefootprint.com/users/fp_id_test_rJBzCaVzkYQgWIfr0qtFDC/token -X POST -d '{"kind": "update_auth_methods"}' -u ${{ secrets.E2E_ACME_SECRET_API_KEY_DEV }}: | jq -r '.token')
          if [[ -z "$E2E_UPDATE_UTOKEN" ]]; then
            echo "Token is not valid"
          else
            echo "E2E_UPDATE_UTOKEN=${E2E_UPDATE_UTOKEN}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      - name: Build relevant apps and run tests
        working-directory: ./frontend
        run: |
          docker compose -f compose.yml build \
            --build-arg TURBO_TEAM=${{ vars.TURBO_TEAM }} \
            --build-arg TURBO_TOKEN=${{ secrets.TURBO_TOKEN }} \
            --build-arg E2E_ACME_SECRET_API_KEY_DEV=${{ secrets.E2E_ACME_SECRET_API_KEY_DEV }} \
            --build-arg E2E_ACME_SECRET_API_KEY_PROD=${{ secrets.E2E_ACME_SECRET_API_KEY_PROD }} \
            --build-arg E2E_SECRET_API_KEY_DEV=${{ secrets.E2E_SECRET_API_KEY_DEV }} \
            --build-arg E2E_UPDATE_UTOKEN=${{ env.E2E_UPDATE_UTOKEN }} \
          && docker compose up --abort-on-container-exit --attach-dependencies --exit-code-from tester

      - name: Upload test results (for 3 days)
        if: ${{ failure() }}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # ratchet:actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./frontend/packages/e2e/test-results/
          retention-days: 3

      - name: Upload HTML report to azure (for 7 days)
        if: ${{ failure() }}
        id: upload-report
        shell: bash
        run: |
          REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
          azcopy cp --recursive "./frontend/packages/e2e/playwright-report/*" "https://pwe2e.blob.core.windows.net/\$web/$REPORT_DIR"
          echo "::set-output name=report-dir::$REPORT_DIR"
          echo "::notice title=HTML report url::https://pwe2e.z13.web.core.windows.net/$REPORT_DIR/index.html"
        env:
          AZCOPY_AUTO_LOGIN_TYPE: SPN
          AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
          AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
          AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'

      - name: Add failure comment to PR
        if: ${{ failure() }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # ratchet:actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            const prNumber = context.issue.number || issues.data.find(i => i.head.sha === context.sha)?.number || null
            if (prNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: "E2E HTML report: [report](https://pwe2e.z13.web.core.windows.net/${{ steps.upload-report.outputs.report-dir }}/index.html)"
              })
            }

  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
  # Add all jobs in this workflow to the `needs` here
  frontend-e2e:
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
