name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

# The names of these jobs are important since they're used in Github branch protections

jobs:
  files-changed:
    name: Determine if relevant files changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@affb29871ab1f927ecad0ee68c0989584101408f
        id: changes
        with:
          filters: |
            src:
              - 'frontend/**'
              - '.github/**'
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  install-dependencies:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Restore node modules cache
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules if not cached
        working-directory: ./frontend
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  lint:
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Lint
        working-directory: ./frontend
        run: yarn lint:ci

  format:
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Prettier
        working-directory: ./frontend
        run: yarn format

  test:
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Tests
        working-directory: ./frontend
        run: yarn test:ci

  typecheck:
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: frontend_runner
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Restore yarn dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Typecheck
        working-directory: ./frontend
        run: yarn typecheck

  audit:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    name: 'Audit'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit for vulnerabilities
        working-directory: ./frontend
        run: npx audit-ci@^6 --config ./audit-ci.jsonc

  bun-unit-tests:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    name: 'bun-unit-tests'
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3 # or "latest", "canary", 1.0.23 ,<sha>

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bun install
        working-directory: ./frontend
        run: bun install

      - name: Bun tests
        working-directory: ./frontend
        run: bun run test:ci:bun

  # Branch protections require this job to pass. If any of the `needs` fail, then this job will fail.
  # Add all jobs in this workflow to the `needs` here
  frontend-ci:
    runs-on: ubuntu-latest
    needs:
      [
        files-changed,
        install-dependencies,
        lint,
        format,
        test,
        typecheck,
        audit,
        bun-unit-tests,
      ]
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
