name: Frontend E2E Form Chromium

on:
  pull_request:
    paths:
      - 'frontend/apps/demos/**'
      - 'frontend/apps/components/**'
      - 'frontend/packages/**'
      - '.github/workflows/frontend_e2e_form_chromium.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  CI: true
  SKIP_PLAYWRIGHT_RUN: false
  E2E_DEMOS_BASE_URL: http://localhost:3002
  E2E_COMPONENTS_BASE_URL: http://localhost:3000
  API_BASE_URL_DEV: https://api.dev.onefootprint.com
  API_BASE_URL_PROD: https://api.onefootprint.com
  E2E_ACME_SECRET_API_KEY_DEV: ${{ secrets.E2E_ACME_SECRET_API_KEY_DEV }}
  E2E_ACME_SECRET_API_KEY_PROD: ${{ secrets.E2E_ACME_SECRET_API_KEY_PROD }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM_ID: 'footprint'
  VERCEL_PROJECT_ID_DEMOS: 'prj_LBgEpZnmdIAi10IeHtVD0RKTbQmW'
  VERCEL_PROJECT_ID_COMPONENTS: 'prj_JmEU6AM71Y8skXfZ8jJCFUD1d6pd'
  VERCEL_AWAIT_TIMEOUT_SEC: 240
  VERCEL_AWAIT_POLL_INTERVAL_SEC: 5

jobs:
  e2e:
    # if: ${{ contains(github.event.pull_request.labels.*.name, 'e2e-on') }}
    strategy:
      matrix:
        shard: [1/2, 2/2]
        node-version: [18.x]
        os: [ubuntu-latest]
    name: 'End-to-End test'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Restore node modules cache
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules if not cached
        working-directory: ./frontend
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Install Playwright dependencies [chromium]
        working-directory: ./frontend
        run: npx playwright install --with-deps chromium

      - name: Get Vercel components preview_url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_components_url
        with:
          vercel_team_id: ${{ env.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ env.VERCEL_PROJECT_ID_COMPONENTS }}

      - name: Get Vercel demos preview_url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_demos_url
        with:
          vercel_team_id: ${{ env.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ env.VERCEL_PROJECT_ID_DEMOS }}

      - name: Wait for components preview_url to be ready
        uses: UnlyEd/github-action-await-vercel@v1
        id: await-vercel-components
        if: steps.vercel_components_url.outputs.deployment_state != 'CANCELED'
        continue-on-error: true
        with:
          deployment-url: ${{ steps.vercel_components_url.outputs.preview_url }}
          timeout: ${{ env.VERCEL_AWAIT_TIMEOUT_SEC }}
          poll-interval: ${{ env.VERCEL_AWAIT_POLL_INTERVAL_SEC }}

      - name: Wait for demos preview_url to be ready
        uses: UnlyEd/github-action-await-vercel@v1
        id: await-vercel-demos
        if: steps.vercel_demos_url.outputs.deployment_state != 'CANCELED'
        continue-on-error: true
        with:
          deployment-url: ${{ steps.vercel_demos_url.outputs.preview_url }}
          timeout: ${{ env.VERCEL_AWAIT_TIMEOUT_SEC }}
          poll-interval: ${{ env.VERCEL_AWAIT_POLL_INTERVAL_SEC }}

      - name: Set E2E_DEMOS_BASE_URL
        run: |
          if [[ "${{ steps.vercel_demos_url.outputs.deployment_state }}" == "CANCELED" ]]; then
            echo "Workflow canceled due to demos_url preview cancellation."
            echo "SKIP_PLAYWRIGHT_RUN=true" >> $GITHUB_ENV
          fi
          export E2E_DEMOS_BASE_URL="https://${{ steps.vercel_demos_url.outputs.preview_url }}"
          echo "E2E_DEMOS_BASE_URL=${E2E_DEMOS_BASE_URL}" >> $GITHUB_ENV

      - name: Set E2E_COMPONENTS_BASE_URL
        if: ${{ env.SKIP_PLAYWRIGHT_RUN != 'true' }}
        run: |
          if [[ "${{ steps.vercel_components_url.outputs.deployment_state }}" == "CANCELED" ]]; then
            echo "Workflow canceled due to components_url preview cancellation."
            echo "SKIP_PLAYWRIGHT_RUN=true" >> $GITHUB_ENV
          fi
          export E2E_COMPONENTS_BASE_URL="https://${{ steps.vercel_components_url.outputs.preview_url }}"
          echo "E2E_COMPONENTS_BASE_URL=${E2E_COMPONENTS_BASE_URL}" >> $GITHUB_ENV

      - name: Sleep for 10 seconds
        if: ${{ env.SKIP_PLAYWRIGHT_RUN != 'true' }}
        run: sleep 10

      - name: Run Playwright tests
        if: ${{ env.SKIP_PLAYWRIGHT_RUN != 'true' }}
        working-directory: ./frontend
        env:
          E2E_DEMOS_BASE_URL: ${{ env.E2E_DEMOS_BASE_URL }}
          E2E_COMPONENTS_BASE_URL: ${{ env.E2E_DEMOS_BASE_URL }}
          E2E_ACME_SECRET_API_KEY_DEV: ${{ secrets.E2E_ACME_SECRET_API_KEY_DEV }}
          E2E_ACME_SECRET_API_KEY_PROD: ${{ secrets.E2E_ACME_SECRET_API_KEY_PROD }}
          API_BASE_URL_DEV: ${{ env.API_BASE_URL_DEV }}
          API_BASE_URL_PROD: ${{ env.API_BASE_URL_PROD }}
        run: yarn workspace @onefootprint/e2e test:e2e:form-ci --project chromium --shard ${{ matrix.shard }}

      - name: Upload artifacts
        if: ${{ env.SKIP_PLAYWRIGHT_RUN != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./frontend/packages/e2e/test-results/
          retention-days: 3
        # with:
        #   name: all-blob-reports
        #   path: ./frontend/packages/e2e/blob-report/
        #   retention-days: 3

  # merge-reports:
  #   if: always()
  #   needs: [e2e]

  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: 18
  #   - name: Install dependencies
  #     run: npm ci

  #   - name: Download blob reports from GitHub Actions Artifacts
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: all-blob-reports
  #       path: all-blob-reports

  #   - name: Merge into HTML Report
  #     run: npx playwright merge-reports --reporter html ./all-blob-reports 

  #   - name: Upload HTML report
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: html-report--attempt-${{ github.run_attempt }}
  #       path: playwright-report
  #       retention-days: 14