name: Mobile CI (skip)

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'mobile/**'
  pull_request:
    paths-ignore:
      - 'mobile/**'
      - '.github/workflows/*.yml'

# The names of these jobs are important since they're used in Github branch protections

jobs:
  install-dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  lint-mobile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  typecheck-mobile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  format-mobile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"

  test-mobile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    needs: install-dependencies
    steps:
      - run: echo "Not required"

  audit-mobile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - run: echo "Not required"