name: Mobile CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  API_BASE_URL: https://api.dev.onefootprint.com

jobs:
  install-dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        working-directory: ./mobile
        run: yarn install --frozen-lockfile

  lint:
    needs: install-dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        working-directory: ./mobile
        run: yarn install --frozen-lockfile

      - name: Lint
        working-directory: ./mobile
        run: yarn lint:ci

  test:
    needs: install-dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        working-directory: ./mobile
        run: yarn install --frozen-lockfile

      - name: Tests
        working-directory: ./mobile
        run: yarn test:ci

  typecheck:
    needs: install-dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        working-directory: ./mobile
        run: yarn install --frozen-lockfile

      - name: Typecheck
        working-directory: ./mobile
        run: yarn typecheck

  audit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    name: 'Audit'
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        working-directory: ./mobile
        run: yarn install --frozen-lockfile

      - name: Audit for vulnerabilities
        working-directory: ./mobile
        run: npx audit-ci@^6 --config ./audit-ci.jsonc

  mobile-ci:
    runs-on: ubuntu-latest
    needs: [install-dependencies, lint, format, test, typecheck, audit]
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Fail
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1