name: Publish to CocoaPods

on:
  push:
    tags:
      - '*' # Matches any tag

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4      

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Validate Podspec
        run: pod lib lint FootprintOnboardingComponents.podspec --allow-warnings --verbose

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push FootprintOnboardingComponents.podspec --allow-warnings --verbose