name: Remote Integration Tests

on:
  workflow_call:
    inputs:
      testUrl:
        description: "url to test against"
        type: string
        required: true

      prNumber:
        description: "PR number to post results to"
        type: string
        required: false

      isPR:
        description: "is this a PR?"
        type: boolean
        default: false
        required: false

    secrets:
      INTEGRATION_TEST_PHONE_NUMBER:
        required: true
      TWILIO_ACCOUNT_SID:
        required: true
      TWILIO_API_KEY:
        required: true
      TWILIO_API_KEY_SECRET:
        required: true

jobs:
  run_tests:
    name: run integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    env:
      PR_NUMBER: ${{ inputs.prNumber }}
      TEST_URL: ${{ inputs.testUrl }}
      INTEGRATION_TEST_PHONE_NUMBER: ${{ secrets.INTEGRATION_TEST_PHONE_NUMBER }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_KEY_SECRET: ${{ secrets.TWILIO_API_KEY_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ci
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Integration testing
        working-directory: ci
        run: pytest tests/ --emoji 2>&1 tee integration_test_output.txt

      - name: Comment markdown on PR
        if: ${{ inputs.isPR && (success() || failure()) }}
        working-directory: ci
        run: |
          FINISH=`awk '/===/{ print NR; }' integration_test_output.txt | sed -n 2p`
          CROP=$(expr $FINISH - 1)
          BEGIN=$(expr $FINISH - 7)
          cat integration_test_output.txt
          head -n $CROP integration_test_output.txt | tail -n $BEGIN > out.txt
          sed -i 's/\[.*%\]//g' out.txt
          sed -i 's/tests/* tests/g' out.txt
          echo '# :globe_with_meridians: :footprints: ${{ inputs.testUrl }} Integration Report' > tmp.txt
          cat out.txt >> tmp.txt
          COMMENT="$(awk '{printf "%s\\n", $0}' tmp.txt)"
          comments_url=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/onefootprint/footprint-core/pulls/$PR_NUMBER" | jq '._links.comments.href' | sed 's/\"//g')
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$comments_url" -d "{\"body\": \"$COMMENT\" }"
