name: Svix Webhook Event Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'secrets environment to use'
        type: environment
        required: true

  #
  # NOTE: for now we are auto-deploying once prod deploys!
  #
  workflow_run:
    workflows: ['Backend Deploy Production']
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  svix_event_sync:
    runs-on: 16core24
    # by default deploy to production as triggered
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v4

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - uses: rui314/setup-mold@7f56dbde35ee02a3fe0287e7ddd310922eb5f553
        with:
          mold-version: 2.0.0
          make-default: false

      - name: Generate Schemas
        working-directory: ./backend
        run: cargo test --package webhooks --lib -- tests::sync_webhook_event_types --exact --nocapture --ignored
        env:
          SVIX_AUTH_TOKEN: ${{ secrets.SVIX_AUTH_TOKEN }}
