name: Publish and Sync Swift OBC with external repo

on:
  push:
    paths:
      - 'mobile/packages/NativeOnboardingComponents/SwiftOnboardingComponents/changelog.md'
    branches:
      - kmm-ci

env:
  ZIP_FILE: "SwiftOnboardingComponentsShared.xcframework.zip"
  KMM_DIR: "mobile/packages/NativeOnboardingComponents"
  VERSION: ""
  CHECKSUM: ""

jobs:
  publish:
    if: ${{ contains(github.event.head_commit.message, '[kmm-swift-obc-publish]') }}
    runs-on: macos-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract latest version from changelog.md
        working-directory: ${{ env.KMM_DIR }}/SwiftOnboardingComponents
        id: extract_version
        run: |
          # Extract the first version number listed in the changelog, without the leading 'v'
          VERSION=$(sed -nE 's/^# v([0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?)/\1/p' changelog.md | head -n 1)
          echo "Latest version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version in IOSPackage
        working-directory: ${{ env.KMM_DIR }}
        run: |
          # Define the file to update and the placeholder
          FILE="shared/src/iosMain/kotlin/com/onefootprint/native_onboarding_components/Package.ios.kt"
          VERSION_PATTERN='override val version: String = ".*"'
          NEW_VERSION_LINE="override val version: String = \"$VERSION\""

          # Use an alternate delimiter (e.g., @) to avoid conflicts with slashes or quotes
          sed -i '' "s@${VERSION_PATTERN}@${NEW_VERSION_LINE}@" "$FILE"

          # Verify the change
          echo "Updated version in $FILE to $VERSION"

      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # ratchet:actions/setup-java@v3
        with:
          java-version: "22"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Gradle
        uses: actions/cache@f4b3439a656ba812b8cb417d2d49f9c810103092 # ratchet:actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('${{ env.KMM_DIR }}/**/*.gradle*', '${{ env.KMM_DIR }}/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Assemble the Swift XCFramework using Gradle
      - name: Assemble SwiftOnboardingComponentsShared XCFramework
        working-directory: ${{ env.KMM_DIR }}
        run: ./gradlew :shared:assembleSwiftOnboardingComponentsSharedReleaseXCFramework

      # Create a ZIP file from the generated XCFramework
      - name: Zip XCFramework
        working-directory: ${{ env.KMM_DIR }}
        run: |
          echo "Zipping the generated XCFramework to the root path..."
          zip -r ./${{ env.ZIP_FILE }} ./shared/build/XCFrameworks/release/SwiftOnboardingComponentsShared.xcframework

      # Compute the checksum for the ZIP file
      - name: Compute Checksum
        working-directory: ${{ env.KMM_DIR }}
        id: checksum
        run: |
          echo "Computing checksum for the binary..."
          CHECKSUM=$(swift package compute-checksum ./${{ env.ZIP_FILE }})
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV

      # Create a release in the target repository
      - name: Create Release in Target Repo
        working-directory: ${{ env.KMM_DIR }}
        run: |
          RELEASE_NAME="Release ${{ env.VERSION }}"
          ASSET_PATH="${{ env.ZIP_FILE }}"

          # Create the release
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.SWIFT_OBC_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"tag_name\": \"${{ env.VERSION }}\", \"name\": \"$RELEASE_NAME\"}" \
            https://api.github.com/repos/onefootprint/Swift-Onboarding-Components/releases)

          # Extract upload URL
          UPLOAD_URL=$(echo $RELEASE_RESPONSE | jq -r '.upload_url' | sed 's/{.*}//')

          # Log release response for debugging
          echo "Release Response: $RELEASE_RESPONSE"

          # Upload the XCFramework asset
          curl -X POST \
            -H "Authorization: token ${{ secrets.SWIFT_OBC_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @"$ASSET_PATH" \
            "$UPLOAD_URL?name=$(basename $ASSET_PATH)"

      # Install git-filter-repo
      - name: Install git-filter-repo
        run: |
          brew update
          brew install python3 git-filter-repo
      # Run git-filter-repo to isolate subdirectory
      - name: Filter Subdirectory
        run: |
          git filter-repo --force --subdirectory-filter ${{ env.KMM_DIR }}/SwiftOnboardingComponents

      # Ensure branch state and reset if needed
      - name: Ensure Branch State
        run: |
          git reset --hard

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SWIFT_OBC_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@github.com || true

      # Modify Package.swift
      - name: Set new version in Package.swift
        run: |
          PACKAGE_SWIFT_PATH="./Package.swift"
          echo "Updating checksum and version in $PACKAGE_SWIFT_PATH..."
          sed -i.bak -E "/\.binaryTarget\(/,/\)/c\\
              .binaryTarget(\\
                  name: \"SwiftOnboardingComponentsShared\",\\
                  url: \"https://github.com/onefootprint/Swift-Onboarding-Components/releases/download/${{ env.VERSION }}/SwiftOnboardingComponentsShared.xcframework.zip\",\\
                  checksum: \"${{ env.CHECKSUM }}\"\\
              )," "$PACKAGE_SWIFT_PATH"
          echo "Updated $PACKAGE_SWIFT_PATH"    

      # Modify Footprint.podspec
      - name: Set new version in podspec
        id: update_version
        run: |
          PODSPEC_FILE="./FootprintOnboardingComponents.podspec"
  
          # Check if VERSION_PLACEHOLDER exists in the file
          if ! grep -q "VERSION_PLACEHOLDER" "$PODSPEC_FILE"; then
              echo "Error: VERSION_PLACEHOLDER not found in $PODSPEC_FILE"
              exit 1
          fi

          # Replace VERSION_PLACEHOLDER with the provided version
          sed -i '' "s/VERSION_PLACEHOLDER/${{ env.VERSION }}/g" "$PODSPEC_FILE"

          # Confirm the replacement
          echo "Replaced VERSION_PLACEHOLDER with ${{ env.VERSION }} in $PODSPEC_FILE"      
        
      # Commit the changes
      - name: Commit Changes and Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./Package.swift
          git add ./FootprintOnboardingComponents.podspec
          git commit -m "Update Package and podspec with version ${{ env.VERSION }} and checksum ${{ env.CHECKSUM }}"
          git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
          echo "Last commits:\n$(git log --oneline -5)"

      - name: Push to Target Repository
        run: |
          git remote add swift-obc git@github.com:onefootprint/Swift-Onboarding-Components.git
          git push --force --follow-tags swift-obc ${{ github.ref_name }}:master
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4 # ratchet:ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Validate podspec
        run: pod lib lint FootprintOnboardingComponents.podspec --allow-warnings

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.SWIFT_OBC_COCOAPODS_TOKEN }}
        run: pod trunk push FootprintOnboardingComponents.podspec --allow-warnings