DROP TRIGGER refresh_updated_at_uv ON user_vaults;
DROP TRIGGER refresh_updated_at_tenant ON tenants;
DROP TRIGGER refresh_updated_at_api_keys ON tenant_api_keys;
DROP TRIGGER refresh_updated_at_ob  ON onboardings;
DROP TABLE onboarding_session_tokens;
DROP INDEX onboardings_fp_id;
DROP INDEX onboardings_tenant_id;
DROP TABLE onboardings;
DROP FUNCTION token_expiry;
DROP TABLE tenants;
DROP INDEX user_vaults_sh_ssn;
DROP INDEX user_vaults_sh_phone_number;
DROP INDEX user_vaults_sh_email;
DROP TABLE user_vaults;
DROP TABLE tenant_api_keys;
DROP TYPE User_Status;
DROP FUNCTION prefixed_uid;
